### ISSUE TITLE
same material conflict

### ISSUE THREAD

**Issue by crazymad-tools** [CesiumGS/cesium#8545] opened 2020-01-16 10:05 UTC
if I have a polygon with Color '#1890ff', and hide it. then I create anthor polygon use same material color '#1890ff', the hidden one will show at the same time。
I used Cesium version1.50

**Comment by OmarShehata** [comment] 2020-02-25 15:21
Can you please provide a Sandcastle example reproducing this issue @crazymad-tools ? 

I'm closing because there's not enough information to determine that this is a bug. My guess is you need to create a separate material for the other polygon, since materials with the same properties are cached for performance.

**Closed by OmarShehata** 2020-02-25 15:21 UTC
