### ISSUE TITLE
Applying Clip Planes to Globe Error when enable webgl2

### ISSUE THREAD

**Issue by JiaoJianing** [CesiumGS/cesium#7712] opened 2019-04-04 06:47 UTC
Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVZRb9s4DP4rQoHDHNRTJEu27DYtDpcdsAEDNmDD9tDsQbHVRDhH9slyttzQ/3607DhJmw1tXmJR5Pd9ZEg6W2lRVTtdmQbdoIX5uTAIPtNpXhmnfrgP/d0V+mnVv61q3Fe1XJXRFXK2VQ8L83C9MFvA2Gr1XVmAMOo7mqtGtxv8xduCV7k/zgFQaqPsq3DPOIHghblvTd4dUV7qui6lUU1Q6NXHShvXTAZBHUftLcAx3vr40+v3yqzcGpz6Iy79eXScTtHcKukUyhUkOILeVxYpma97EdqskFdyQN/bP3qBgH/37bq/7UKDzkWDlVzD1+xEyzW6vNQTNCSyxzNQ3HemUD8gKNDoEtEJ+uM07jRgowt/C/5DfefSOniShmFZFEEfe6e/hQPM3cgBpqPf5RAXTCZHLL9l2LSl03W5+2v3KZeltMHeO0QEx+EYPHkku63PwpnKbmSp/1NHOM+Q2CFavVqf19i0S2dl7oIz+b+I5tcUB93eJ+xdH0vsvc4C5LZqmn1wWz9Lzm/gDnr6p3BwPg7ver7a1C00faEbJ02u0HKHaqucMkXX626t+n5HukHS+XMFGrU5zau3zf3kqMKPwunIe9MohWDyuDKjgJuTELxSzo/0m+E+OEN1vslOBxPXbbMOjmt6fD0q28sYy/wwTLpfWbiB5QCaymqp8JPB/xX4vCpL5TdZcDTr/UJDV490hgcPVay62MpejbDdCX99++7z34PfQ6fzoVtifRGH/bdfQ6PhafqHlnodpSxmcYx5lkSpYCwLEc+yKIkpZhmJMpZEIkSRSNKIc8xEGsdpyiJfo2czJDRLMBEUvlLCWU/BGcVZLFKRRXHsKYRII0wjKoiIGHshBaMMc8ily0J4BpqxDHMeE5rFhPVJxJBEximHBxbxl1HEaZxABURGMkHTniIlCaaEEk7j1DNAXikWnKUJB9qXMjDCMOOCRpzEtC9TRDOcQFok5XygIIJgEUESgpOspzj7mvQvuKF7c7lRVuL7cve52rdiAa9ubWTXnVfnVw6+t9XmjVpZBcC0UwJ6INUsg+oJEUYxzggRUPE44TyKkiQUcI1pGqdgJgn8LhNo0sn1RXgxa9yuVLc99596U1fWodaWAcZTpzYgH1inyzb/RzmcN17/bLoPmhV6i3Rxs7h49NdhcQFjJJsGbu7bsvwEe29xcTubgv9JWFnJbq992Cpbyl3nsqa373sjxng2hePTKFdV5VLaI8T/AQ

Browser: Chrome 73.0.3683.86 x64

Operating System: Windows 7 SP1 x64

**Comment by JiaoJianing** [comment] 2019-04-04 06:48
I want to apply clip planes to the globe.When i use webgl1 as default, it seems well.
But when i enable webgl2 by setting requestWebgl2 to true, The Globe disappear!

**Comment by JiaoJianing** [comment] 2019-04-04 06:52
I tried Cesium version 1.48, when enable webgl2, the globe will not disappera.But my clip hole will be saw only very close to the ground.when disable webgl2, everything is well.

**Comment by JiaoJianing** [comment] 2019-04-04 06:53
var options = 
{
    contextOptions: {requestWebgl2: true}
};
var viewer = new Cesium.Viewer('cesiumContainer', options);

Using up code.
I tried some cesium versions. When come to version 1.52 and later, globe will disappear.

**Comment by OmarShehata** [comment] 2019-04-04 11:51
Looks like there's a bug that prevents it from rendering with WebGL 2. https://github.com/AnalyticalGraphicsInc/cesium/issues/7647

Can you try `viewer.scene.highDynamicRange = false;` to see if that fixes your issue? If so, we can close this because it's the same issue.

**Comment by JiaoJianing** [comment] 2019-04-06 02:06
> Looks like there's a bug that prevents it from rendering with WebGL 2. #7647
> 
> Can you try `viewer.scene.highDynamicRange = false;` to see if that fixes your issue? If so, we can close this because it's the same issue.

Thanks! I tried that and the globe render correctly. But my clip planes applying to globe still not work(the clip hole on the ground still not visible).Does my usage of the globe.clippingPlanes wrong?

**Comment by JiaoJianing** [comment] 2019-04-08 12:52
> Looks like there's a bug that prevents it from rendering with WebGL 2. #7647
> 
> Can you try `viewer.scene.highDynamicRange = false;` to see if that fixes your issue? If so, we can close this because it's the same issue.

I tested on Cesium Code Example: Terrain Clipping Planes.Adding `contextOptions: {requestWebgl2: true}` and `viewer.scene.highDynamicRange = false`. The result was not correct. Is this a clip plane's bug with webgl2?

**Comment by OmarShehata** [comment] 2019-04-08 13:15
@JiaoJianing I think you're right. This looks like it's indeed a WebGL 2 bug. Here's a screenshot from the [terrain clipping planes Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Terrain%20Clipping%20Planes.html):

![clipping_webgl1](https://user-images.githubusercontent.com/1711126/55726807-aa858680-59de-11e9-8d0b-3228367adcd4.png)

And if you enable WebGL 2:

![clipping_webgl2](https://user-images.githubusercontent.com/1711126/55726823-b07b6780-59de-11e9-95bf-4b427c32d70f.png)

I initially thought it was the "fill tiles" refactor for terrain made in 1.55 but confirmed it still happens in 1.54. 

@hpinkos can we label as a bug?

**Comment by OmarShehata** [comment] 2020-04-21 13:46
I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap, so we can consolidate known bugs and discussion in this issue: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407.

**Closed by OmarShehata** 2020-04-21 13:46 UTC
Labels: category - graphics, type - bug
