### ISSUE TITLE
Loading CustomDataSource crashes Chromium/Opera/Chrome/Firefox etc..

### ISSUE THREAD

**Issue by mdhsl** [CesiumGS/cesium#6188] opened 2018-02-06 16:11 UTC
Browser crashes after loading CustomDataSource. Can be reproduced after loading Sandcastle example https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Custom%20DataSource.html&label=Showcases.

Making my own example reproduces the problem. I've got a "Aw Snap" message from chrome. The console does not show any errors. This has been reproduced on several chrome (stable/unstable/beta) AND chromium versions as well as Opera or firefox.

Only the last firefox (57) and epiphany, both with WebGL disabled, seem to work. I presume it is a WebGL error.

Creating the datasource seems to have no effect, the crash occurs if we add an entity and it  does not crash after adding the entity but after, probably in the rendering part or something like that. Debugging that problem is quite complicated since we have absolutly no info about the error, only the "Aw Snap" from chrome.

This is my Graphic Card config and drivers:

- Tested on Linux with nvidia last (and older) NVIDIA drivers : 387.34-1
- Tested on different distros such as Ubuntu/Arch/Gentoo => same problem
- NVIDIA MSI 1060 GTX (in legacy or/and UEFI mode)

WebGL functionnalities are running fine (Run a lot of WebGL test without any problem)

**Comment by hpinkos** [comment] 2018-02-06 18:17
Thanks for including all the details @mdhsl 
Can you also please paste the result from http://webglreport.com/?

**Comment by mdhsl** [comment] 2018-02-06 19:26
Sure

For WebGL1:

Platform:	Linux x86_64
Browser User Agent:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	NVIDIA Corporation
Unmasked Renderer:	GeForce GTX 1060 6GB/PCIe/SSE2
Antialiasing:	Available
ANGLE:	No
Major Performance Caveat:	No

![webgl1](https://user-images.githubusercontent.com/6577027/35879576-da40cdb0-0b7b-11e8-968e-1f51a1258c4d.png)

Supported Extensions:
--
  | ANGLE_instanced_arrays
  | EXT_blend_minmax
  | EXT_color_buffer_half_float
  | EXT_disjoint_timer_query
  | EXT_frag_depth
  | EXT_shader_texture_lod
  | EXT_texture_filter_anisotropic
  | WEBKIT_EXT_texture_filter_anisotropic
  | EXT_sRGB
  | OES_element_index_uint
  | OES_standard_derivatives
  | OES_texture_float
  | OES_texture_float_linear
  | OES_texture_half_float
  | OES_texture_half_float_linear
  | OES_vertex_array_object
  | WEBGL_color_buffer_float
  | WEBGL_compressed_texture_s3tc
  | WEBKIT_WEBGL_compressed_texture_s3tc
  | WEBGL_compressed_texture_s3tc_srgb
  | WEBGL_debug_renderer_info
  | WEBGL_debug_shaders
  | WEBGL_depth_texture
  | WEBKIT_WEBGL_depth_texture
  | WEBGL_draw_buffers
  | WEBGL_lose_context
  | WEBKIT_WEBGL_lose_context

From WebGL 2 tab:


Platform: | Linux x86_64
-- | --
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
webgl2
WebGL 2.0 (OpenGL ES 3.0 Chromium)
WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
WebKit
WebKit WebGL
NVIDIA Corporation
GeForce GTX 1060 6GB/PCIe/SSE2
Available
No
No

Supported Extensions:
EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context

![webgl2](https://user-images.githubusercontent.com/6577027/35879577-da632ee6-0b7b-11e8-94b5-c8c22a8303fe.png)

To see draft extensions in Chrome, browse to about:flags, enable the "Enable WebGL Draft Extensions" option, and relaunch.

WebGL 2 Functions Implementation Status:
88 of 88 new functions implemented.

copyBufferSubData
getBufferSubData
blitFramebuffer
framebufferTextureLayer
getInternalformatParameter
invalidateFramebuffer
invalidateSubFramebuffer
readBuffer
renderbufferStorageMultisample
texStorage2D
texStorage3D
texImage3D
texSubImage3D
copyTexSubImage3D
compressedTexImage3D
compressedTexSubImage3D
getFragDataLocation
uniform1ui
uniform2ui
uniform3ui
uniform4ui
uniform1uiv
uniform2uiv
uniform3uiv
uniform4uiv
uniformMatrix2x3fv
uniformMatrix3x2fv
uniformMatrix2x4fv
uniformMatrix4x2fv
uniformMatrix3x4fv
uniformMatrix4x3fv
vertexAttribI4i
vertexAttribI4iv
vertexAttribI4ui
vertexAttribI4uiv
vertexAttribIPointer
vertexAttribDivisor
drawArraysInstanced
drawElementsInstanced
drawRangeElements
drawBuffers
clearBufferiv
clearBufferuiv
clearBufferfv
clearBufferfi
createQuery
deleteQuery
isQuery
beginQuery
endQuery
getQuery
getQueryParameter
createSampler
deleteSampler
isSampler
bindSampler
samplerParameteri
samplerParameterf
getSamplerParameter
fenceSync
isSync
deleteSync
clientWaitSync
waitSync
getSyncParameter
createTransformFeedback
deleteTransformFeedback
isTransformFeedback
bindTransformFeedback
beginTransformFeedback
endTransformFeedback
transformFeedbackVaryings
getTransformFeedbackVarying
pauseTransformFeedback
resumeTransformFeedback
bindBufferBase
bindBufferRange
getIndexedParameter
getUniformIndices
getActiveUniforms
getUniformBlockIndex
getActiveUniformBlockParameter
getActiveUniformBlockName
uniformBlockBinding
createVertexArray
deleteVertexArray
isVertexArray
bindVertexArray

**Comment by OmarShehata** [comment] 2020-04-21 13:43
Closing since we are unable to reproduce. @mdhsl if the issue still happens or if you've been able to reproduce this on more devices please let us know.

**Closed by OmarShehata** 2020-04-21 13:43 UTC
