### ISSUE TITLE
create a box and plane manually Cause an error

### ISSUE THREAD

**Issue by wzwxwc** [CesiumGS/cesium#9811] opened 2021-09-15 08:33 UTC
i create a box and plane by click two button.
the button code is below:
addPlane
addBox
the addPlane()、addBox() codes all is from cesium sandcastle.
when i first click addBox button,and then click addPlane button
attention:click addBox first
then cause a error below
![image](https://user-images.githubusercontent.com/11436176/133387947-5aea90d2-1205-497e-8320-1f2e4e1b3de6.png)

Sandcastle example:
https://sandcastle.cesium.com/#c=zVRda9swFP0rFz854Mnu2jLwnLAm3cNY2UbbDQqGIds3tagsBX3YS0f++2TZIWkS6F4G04Pse33OuffqGLVUQcuwQwVTENjBAjWzDfnhc2EelD5eSGEoE6jyYPI+F7mI47W00FhtYMmU20vOyiegVTWXv6CwxkgRmRoBlZIKOsY56Fp2ubijoiqpNhyJQ99LyQuq5p7gyg0CeRDB0orSMCkgnMDvXEDrOlXo5adjywSFYYah7pXCHuSWoA2mkAe3WEHhwB0zNRScuu6kNdwN4dQH6Epq1pdIt1MvqDLujYpzslSyucZHhajDN2fJO5JEcJH0+3nSL5JMRhVXJIWxOEDFGhTaiep0/zx3yuHFyN8pRXB5oAnQUIOKUb7rTXKpyO3Ha9JPdMVXNQ0TcrljjNOlYJTFw6xnH2jNb64Wn0fgxj83vbmbweFXffrGqT/LI6e2VnnA35u18vB/bpcvs2fYGO955fsOj2t8//Lp/udDBC98es3vtyf8/k9cDqIg02bNcbaV+cCalVQGrOIhIbHBxp2OmyMubPmEhpRa99wemsX71KxiLbBqeuK+cDcD1dp9WVrO79iz83OWxQ5/ROWSVkw8fm1RcbruYfXZ7GZIEkKy2IWnmWb4Ow+U/wA

Browser:
![image](https://user-images.githubusercontent.com/11436176/133388010-487076f6-5efc-45f9-a25c-8d4f30bfdc7d.png)

Operating System:
win10

**Comment by mramato** [comment] 2021-09-15 19:24
@ebogo1 @lilleyse given it's worker related, this may be a regression we should look at before the next release.

**Comment by lilleyse** [comment] 2021-09-15 19:48
It looks like this bug goes at last as far back as CesiumJS 1.75 (I didn't try going further back than that)

And it seems to be related to the fact that both entities have an outline. If you comment out the plane's outline it works.

**Comment by mramato** [comment] 2021-09-15 19:53
Hmm. that's still a pretty bad error we should fix (and hopefully we can do it before the next release) but I changed the label since this isn't a regression.

**Comment by ebogo1** [comment] 2022-02-07 21:44
@wzwxwc We were unable to reproduce this on macOS, Windows, or Linux and think we may have fixed this issue in a prior release. I'll close the issue for now but if you are still running into this please post steps to reproduce and feel free to reopen it. Thanks!

**Closed by ebogo1** 2022-02-07 21:44 UTC
Labels: priority - high, category - entity
