### ISSUE TITLE
Wrong triangulation on large polygons with holes

### ISSUE THREAD

**Issue by AliFlux** [CesiumGS/cesium#10012] opened 2022-01-16 15:55 UTC
This geoJSON polygon is displayed incorrectly (weird triangle connecting the polygon and hole). I have checked various other similar issues (#3044, #2788) but so far couldn't find a solution. This issue only appears in 3D globe (not 2D). I guess it's an issue with triangulation over curved surface. The geoJSON works perfectly fine on geojson.io

![circle](https://user-images.githubusercontent.com/8333794/149667185-86b8e5bc-3047-4e8c-9667-fba6fdb4a73d.PNG)

Sandcastle example:

[Sandcastle link](https://sandcastle.cesium.com/#c=hZpbb1vXEYX/CqE+1AWYo32/uE5QIEmLFk1TwEVfIj+wEu2wpUWBoh04gf97vzX7bDltA1QGbOtwnX2ZPbNmzWy+35037w/7H/bnzeeb+/0Pmy/3j4d3b5e/27NnN1e39vuXp/vL7nC/P99cbTc/3dxvNtfXm8fb/f3+m9Pd/vl86+V8srz88uu/fB2+2gp6ObzdH3n5+eb17vi4t2e7+8Pb3eVwuv/5Qx692Z8//PV8en+425+f/3xB3z7s719ezvv95Zvdwx//E/jMVrTZvDsfN883v/7+cnl4fH59vVsuh+N+OfHmo735dvewnM5vrn8t+Mff3Nx//M1vb+715z1meLM//fPxdI8dfrq5unx42N9cPb+5+v1+d3l33n95Oh73t1owFri5ej2ePgL57hfQhnk4M/P5cjAUoNeH49FAv6q5xP0A6eFnp4fd7eHygQ/dEnnIak//2n/2w+Hu8j0P/Ueesbq3+8v5wxjracK/no4f3qyLuj2dzneH+91lrOu773Jcgo8px1aiT873bXBLS6V151LLobr4amsoF1twLaYeUowDlXNurdXIR0kov/iWAr+GGEIvApUasg819OxyqXWgnHcxxpJrCM0mLNml6krxvaZUJsqFEFstpbeeSzJc6rX36LJ3PWXDuaX35H1gF55HE9ai47cSQs4rqhUXYqqh5lrbOilG1h5TCzkAS21h/uZDjjlMWM++tdhZbu99omLuTNhiiQMSBSrBZ3aeVwy7ZowcfXehDFhx/ATsMQYqTNerb6W7MkB+KaHUVjVcYFtlwnxzKVRfXI9pwHprrlaf2GuIKywmNsKZOR4Fg2HmWnovPrc89piWXkuKvT7BwoLhe3AcuWu92SkJVlp2nB9Wyj4aLHD6bItF514myrOhxOZlIENFdhNLaTFwdgaLC2cm+9fYfY+ZnabFNRys++T1WY4DF3rHhpUFcTzBYN3ViGFd9bxaJyxx5NgpOl/qgFUvUycMtMICjsZrrvnGrNlvQ15qTVl7DZxg8ysKO3jmDFgqFUM1h21baI6DH0sTjF3Whhe0EAYq8z9edbhgVgQkt9Te2E3Glrkpmtpi/2F+fJu1TFTG/AE7eTt3UCX50uXwkdgvExbl21jA+Zqz4YhIjBuxD7Ovw3FwvRG8sjyREt2CGzTHoQTnvNc+YydQtAw5DbYqA4Wp8FjPXrNFisGaU7jGqqUJFQtbx0W0KXMiQ9VC8MMURJofc+KhTbEZXHFmD+EwasS/a6nE/DaGhT3BF6l4eV95guFWjRPIbK8bjJ3HlFJtCTOUCWuBTaTEttJA1RYJFowUUhjWSDo+hy1ZdK3bmBfG9T7VFBzrrSuqee8S9scRWjBUw5fZBCZm+0L5JTORyAD3aK7kbawLBMLKI+bhSU8Th1cXkVf1wVCF+YqigBhfHQ2OxYCsVwtLeauTwzU5+pY9FJjyxGGMoHVFotJgRAWG4DV5zYi83JOIt+EySSfAi+zG43/ACh9MWM/QiXOx4GB5wAqWj5iitTwmrRB8ygED4FoJjuFNTpZpm4KdCEwThuexp8TrPq84PISskESL2VbXF9wp18i0gfeBlUXWgUl8ZRMtTBSegHdA1dqoQAXL+BxZtZktB4K96VRwGxi3buHWrLiEN0k9FlGAcH2FIb6BOfMANbgF40fmFCgvjdVA90EG4Vi35AU4I8jYAfMQHSsO3oAh8XtPEBkMXxUfaBPNUH3hP3gVPspKXWM0zwQyLXbEmSeqO+zNr/gg6cJAbIW1st7qhSpxsRQUQyq4VA1bEi6OpwNgE+LrCYMKoKoA2UJHA5Z41BPDVWMqQykYiJCaQ1pRuTJu4WV42AaTi3oLf/LUCiMX4desxedqB2koIjWRcEXJZUXBZZFAVCwKVrE/CQrrB3zMYGmJ7LJyGhHKSWmi8BqvACV1hoHSx5FEyXlZ7hSsy4gEWSNAVxSbEgD3k+/UuuD9sCLePkEZ4k1EfBev9hVEjEOrcDL0PlFFh5E8tOcnqpKIIH/gNa+oRLR6bTzMsYLSDZTFIfc2UFm5OuAnwXileYsjUgucN1EYE+Oz+sixlBXlCymtsFastqIsQZLASrQU3CLRUOXqxeMMzmwPn8CPVUmT48wrLCNAul5HZw2Uh6hhA3JynqBCKEN2nB7RZCh4FSlCVgjDEkKJYKrECPplzIgDNOXWFJILczDonIAjANAcfsBQSJxXqLWa8YUiYqATZVvt0UYn9lBikXMbYxFszFQJP+SeF0z8pKDFddAdTyDEVjFtQ0IZICiRRbFQb/JTKKzDLnES4tUPFCyvjMShWXgYCs+HS6Mcb0yI9sxaEfarE9VZDZTDhK2UgYJcSUbaTQgTRSoil6EL+HtrbFUlTSATHNMEXCsLpG/GymYBEUqTEiFZZHKZ0ZOhiIXiOBafygDhMPh+lPZpE0TkoLKr4m8Mhe05BkxBko5PKGQPOyUVoGMNFbRwoqH4T8sqomkcDmbzhsoiZ+2dNdQVJuUp00Tpab8VbxeIlYGJNjh1ovAwD39AKEpHxu7YAe0CNTjL9AbD9FLFlmwGjBBAV0GL2U8Q3kdAJtF8MxDz4TfKMXwwjC+NT97J3ay7JTtFlC0R42FkPCBPmFfah6NVURgMfUayl8RJw3dgtYQfETGwFv8qr/WM4GMFRFeZ8YFvw46mhXTehiIHIBsYkn2O6Ea7QyCWUeHIkXKVOKt4v1vyM1SQy2E2VS6GwnHlRyLTYNKiKfej39HFYmaEJ2qA8ilJdENObcSaUCgBfJMYhJSHZoDJiQVyktSSOKxRBjm8opunIO54EEnBRVUH1Ur8hCpiCZbac1thOCJmRD5m48O8UL+R2VREkDu7KSjoTJmVJ8TriipmRLlyCm3oLAkcToiIKGNKCgQcrgnbtL5tjOyS45CSFhvEiYKmpWJZCUFpKFKhMmUgNAVSQYiabEopnLGEKeqcYPBUI8E0hWGyqqmqf3scILR8wi2QsKYkS1+koKUFIyUUqjT0BU2J1XUSVLllolBDyvJZWxoo6XDWSaIcIVmKKAyiRZiRRUBV7JelV8h81C1lgtDPMBPzFnzVUDg3J4vWiOZfhWKnKOV8QmU0L8wIUWNmInnCGF85hpAg5gbME8QsgjxnhFL8In/jR8WpInMbIrbgLTIRZlTxuOLwAAaEFSInP2AJ2yAXSQVuFPeNvcNDSICiLIhGoSLEaJiIKFFpa6WvcFA1eZ/t4QR5wJLqGpW4sGIYUoy0AGnpLJmpqqbFegCQRNg8+YFCC/NOlLTu2qlQZBV8B3pbRZ3IjmXGtvY5hEF+Q2yiT8q4tdHx/9ohwCRd2TfDyzdVFKsELfJ7Tg8nIxpXhUvOVFGDF1XTFoazyqxYHRbWbkeVnsVsGGTixLhJxlE5NqQpuCSFoNIvtxUFSwYNWVR6TlSH+AlgJ/qdMFAUoywkxRWmUsZzNBwzlD3mVNUlD0+trnOiHAkwlRQqVw0XgwoIp1qf7JOH6Yhn4xtIOah5AgyygObIj8iFGicM0xVnCTKVASvG9ASNvGyFqXsAmWvdtQ4Yw6FxYOhoKlAoOJU1QQrg1zml8Ylk1fTNDFLwLUiQNcACci7FAgSONm8qrgm/icuIFYECZCi3FK4r/JPJxuG7SfzsVcdiKGGUR1mFOhq++AmihFGzQYLHpQGDTpEAcqfWVhgOK7qlFmvR+gpsCa+3dhLuVUf0YT40DLUpZ0WpJGIg9LtclaQ2VJ7BJOkzihdHhCENR+Cg6qh9RG+jRAAgMaoqjnQmziJ8eIjGxUDNqnzBrHqlTMZoLRosq1MhLkLuDaIhXRMFtUuh10TBrRIHSzM+Akp5dqKaujaeD7r6D8C8CAAVhGqDjAVTcy0oQ0nF88k24pQKWbWmiAwT44biDwEkJux9oFClailhcztOaL5IPRWV3U3UHMuCUMtU1cRMUW9xwhiqieU58wGTi7KFhvv5NWfoBIIYhpUFgahuOXevPuIsg7y4FrUmMkrkFeq/ogIH5kDx9TxRqL9oEisQ60IR9QTAKGufxuLc9HYgDsJAIcTUp6oqzFcUdWRQmMMgysLdagT4R0/J/euUKA2JNqI2UuxIbKBbqHrUHSA8w0QVU8tEANRvKGwFo3XUhLztaTCyCpoLR0VBp/Ei3sWmWKJfq7iiU42QCQk5SyuxSoZJavdRvM1iT91HjKimcPUDZs0JWIc1tolyavXgX1WyVygW2VRGj4JcmCz9r6IWSw5IUakKLSJlZgmK4pXIoFRdFyU9AV9RbSBQbCiPDRW3ig2PMkOzULxjCShR3a00QTgye2wqmQcKfzSZTPU4R6p4I5EmH4GghMLDixpWcG3wExVVk5qOp3w2FHnHC0G1kYYHZrUaIeGwogqnTwXKAbUkebmiEJViMCyMzQaK7atEVEnQ52DwLYtAYeFm2WDZGsikH066TxQGVdaEiXwcKNKPOlMQ4xAkfVEXLf0HCt5AUeBNqL/RJZNSkniWD1PS+GAwtR4yOyCV2pSGcuIIfF49zoHi7JW5lQcnSs0wPJfwZx8DRf4MRhVxii5mU1KS6Eqyfl2CZSTShapAtxIYntS8tVD4KxlMRTeJT8RhPigUpmoqVbPS0IqCbyTHai15okSPupJAqPiJqhLTiCRngreEBeknbYJbkRSseGHPmJBKAiVpvWmhnBripCg2pRMXCkrDwZFefXRyhCLnutF3KnGgKLBYEjSPgUYnSuSLZnITRf0nnWp8SIXTVpSzrrbpKZ/ygFGiUXp5pd44YGrQNbV4knrpK0yqX5wsx8trQpVnMziHOnASYsQRzKDacOh/S7xqfFfrYqcVhhkjeyoiqJHtEVLwTtKdhqEkRGJU7W1/23FmNcAUKY1AUxwOGCm+ZLUtoxWZuqwKqr103zBQcZEXN+tJYtGpfrz6OE6iU6JqwEiBKjJJI8E9wbAidqLQhCvW4aRVo3rRfrTXUxMfBF2+iHQSROwX1Uy68kjqHFkhYDCpZuqkKC2aDWcJqigWmvGGYJC9kosqnKy2rWBe7VncljBq680QXE8CzOoU6ILASjyClgmVEKw9Jxj6IKvTHVQnGEwNhKS2qZrBBlMBZzddGArnt0xY1MQmKnDyUQgYgXVVbxwxoWsgZWG0HAl1KCkD6W4L1oZE8cYBU6pEhqqTktdmt9IqBVop6usXpXs4T94tz8cuK0pUr3ItcvR1oNS0K7rFYTF5wqip1MrQj2kHL74k/qoW/TQYsoBMRaGMXQYKjZdMl+L8AxWCtflVAsO4EjVIeHXfMlYL4ROK7CJyVNfRUKiLqPsBBNxwNYNhCnwQwuDQB8zL1M5IbLWFkkxUArPuhRWc0jNJvVc9myhiTrdtMqcbKAzFEiQEcKSJA4boU8GKTDEY7AgfV4VnrnNSVUFqwOnCwQ+YriO7tWSH10q6SsJrzVkJdRsKSlPFoWh0vRRK1qdLWf10dSKCodAASU2gYOJlwnT5I97XHdsYDSur5y7DhXF1oSYcx6bLkab+rMGQ12QneD5JnU2YbrmCro51rWIwWEP300ldhzpuODgBpsMGVLDjnk+Kzun+u+veekWhFZxuL5sabFYo6KKa1KhqQcGx4vAyu1kQE4cBS+ruSKBT3bRRJsYaFEDVrTAMrtoaI8pKJo0NZZ0NPFBXWWsxqXY8c1jzcoWRpLxdNwQplgGD04hX1Y6lrHc0/7+EffXq48dXH9dvQMxvQdztLruXp3fn2/3m8/ndiz/sT396PN1/9fTRcjzt7p6tX5h4+g6FfWVk+TTA47K7u3v26XcBV9CPp9Pbv53+67Or7dWLx8uH4/6L8XWOzeZ3h7cPp/NFX+x4tizXl/3bh6O+3nD9j3e3/9pfltvHR70o6Ivrn7/64u7wfnO4+/wXvr+yuT3uHh/55PW74/Hl4cf9zdUXL67B/8+r2uTh/s237/fn4+6DYN/7L/48Hi7L8uKaX3/5zcvpdPzH7vxfI/8b)

Browser:

Tested on latest Firefox and Chrome.

Operating System:

Windows 10

**Comment by ggetz** [comment] 2022-01-19 14:24
Thanks @AliFlux. I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/8042. I'll close this report to keep the discussion in one place. If you have any further input on this, please post it there instead. There's a workaround in that thread that you can try.

**Closed by ggetz** 2022-01-19 14:24 UTC

**Comment by AliFlux** [comment] 2022-01-22 10:11
Thanks, the workaround worked!
