### ISSUE TITLE
When the camera is underground, zoom can cause an exception，v1.66

### ISSUE THREAD

**Issue by ElevenIjusee** [CesiumGS/cesium#8628] opened 2020-02-24 03:57 UTC
When the camera is underground, scaling can cause an exception

https://sandcastle.cesium.com/#c=bZFRa8IwEMe/SuiLLWhqkbGhVQaVPW0M5thTX67pqcE0KUlaceJ339VOcM5Awt3lf7+7XFqwrJW4R8vmTOOeZehkU/GvcywciLObGe1BarSDaJbrXs+dQI10WkS9qkFgBhVa6LTWKEUK1FAozMiRThq9RI/Ck0Gl1qAcEuuGtlGmIObW7Fc7ab27Ut7RFSB2L13hhirozT2sOPfE1+rwacIjyzWjVaLzUkPXyvTy4AysJwv0hK+tqZa4oXe5cJQkj0M2oT1KHsbjaNgTjJVII+kJxz7WrVp6sZ3+It/Ab7k3H1AS1oXJ05iPo157yvUpmgXDIHX+oHDRR59lVRvrWWNVyHnssaoVUFdx0Ygdei6c6+afxpektJQtk+U8D27+KQ+YUOAc3axpOCv5jXmwSGPS/0lThprTm/cWrYJDJ9kmi9c+yDlPY3L/Z3ljVAH2ivgD

**Comment by lilleyse** [comment] 2020-02-24 23:42
I don't see a crash right away from loading the sandcastle but I've noticed similar crashes before.

Could you try the [camera-underground](https://github.com/CesiumGS/cesium/tree/camera-underground) branch  with this [sandcastle](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/globe-alpha/Build/Apps/Sandcastle/index.html#c=ZVDLasMwEPwV4UtsSGWbUFoSJxScY0uhKT35spHXiagsGUl2SEP+veuoKX0sSOyOZkbDDmDZIPGAli2ZxgMr0cm+5W8XLJ6Iy1ga7UFqtJNkUenA506gRrotot50ILCEFi2MXGuUIgZq2CosaZBOGr1Gj8JTQ181oByS17ebuIh5o46vJj6xSjOqGp2XGkbN/JqsBOupAz3jjTXtGncUwMU3eX43ZTM6N/ltliXT4GCsRMoeHE4BG6uTXuznX5ZP4PfcmxeoydbF+X3GsyRwz5U+J4toGhXOHxWuAvog285Yz3qrYs5Tj22ngFKl2168o+fCuXFRRXoVFbUcmKyXVfRnoVXEhALn6KXpldrID6yiVZES/5dMGQqnd88DWgXHkbLPV48B5JwXKY3/Vd4YtQX7w/ET)?

**Comment by hpinkos** [comment] 2020-06-12 19:04
I'm closing this issue since I'm also unable to reproduce this. @ElevenIjusee feel free to re-open this issue if you're still seeing the crash in the latest version of Cesium.  Thanks!

**Closed by hpinkos** 2020-06-12 19:04 UTC
