### ISSUE TITLE
requestWebgl2 CloudCollection bug

### ISSUE THREAD

**Issue by Lemonjay** [CesiumGS/cesium#10739] opened 2022-08-31 08:16 UTC
![image](https://user-images.githubusercontent.com/9245295/187627343-e4bc09dc-e7c6-47ab-b0ea-5597b6e84d80.png)

**Comment by ggetz** [comment] 2022-09-02 13:39
Thanks for the report @Lemonjay. I'm adding the [`webgl 2` label](https://github.com/CesiumGS/cesium/labels/webgl%202) to track a few needed shader fixes.

**Comment by sanjeetsuhag** [comment] 2022-11-17 20:40
Closing as duplicate of https://github.com/CesiumGS/cesium/issues/10064.

**Closed by sanjeetsuhag** 2022-11-17 20:40 UTC
Labels: type - bug, webgl 2
