### ISSUE TITLE
valid glTF fails to load in CesiumJS

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#11961] opened 2024-04-27 13:37 UTC
[house.glb.txt](https://github.com/CesiumGS/cesium/files/15138348/house.glb.txt) is a draco encoded glTF model that loads fine in all viewers I tried except for CesiumJS. It validates cleanly with no errors.

When loaded into CesiumJS, it reports:

```
RuntimeError: Failed to load model: ../../SampleData/models/house.glb
Failed to load glTF
One of options.bufferViewId and options.draco must be defined.
```

**Comment by javagl** [comment] 2024-04-27 21:07
Probably a duplicate of https://github.com/CesiumGS/cesium/issues/10284 : Sparse accessors are simply not supported.

(This is also indicated by the ❌ in the "Cesium.js 116" column of the "Simple Sparse Accessor" row of the table in  https://github.com/cx20/gltf-test : This is currently rendered _without_ the sparse substitution...)
 
The example here adds Draco compression, and the crash is caused by the `_BATCHIID` attribute, which is sparse and not covered by draco, because it only contains `0`s anyhow. So there are a few things coming together that cause the lack of sparse accessor support to wreak havoc in this case. Maybe the crash could easily be avoided even _without_ full sparse accessor support (and only cause a warning of so...)...

**Comment by mramato** [comment] 2024-04-29 01:15
@javagl I agree that the way CesiumJS is failing here is not very useful and a clear error message or warning about lack of sparse accessors would be the least we could do. But it definitely bugs me that there is part of the glTF standard we seem to not support, especially since tools like gltf-transform's optimize function produces sparse accessors where applicable.

@ggetz @lilleyse What is the level of effort to support them?

**Comment by ggetz** [comment] 2024-04-29 14:00
Closing in favor of #10284 to keep discussion in one place...

**Closed by ggetz** 2024-04-29 14:00 UTC
Labels: type - bug
