### ISSUE TITLE
Incorrect shape fill when line segments intersect when drawing 2D polygons.

### ISSUE THREAD

**Issue by 0naka** [CesiumGS/cesium#11502] opened 2023-09-04 05:26 UTC
Thanks for the great product.
	It seems that when line segments intersect within a single 2D polygon, as in the sample code below, the unexpected areas are filled in as shown in the screenshot.
![1](https://github.com/CesiumGS/cesium/assets/143977196/eae6c4df-5185-4968-823a-ca966e703dd3)

Execution results assumed to be correct
![2](https://github.com/CesiumGS/cesium/assets/143977196/2890690b-3fe5-4bfd-badd-4d661b3df9b9)

Sandcastle example:
(https://sandcastle.cesium.com/#c=bZL/btMwEMdf5ZS/Uqk4bccPLWQVo5tUJBATTOwPwh9ecm0sHF9kO+2yaQ/BG2zAk/EkOE6D0lFHsn13n/v6dLmMlLGwEbhFDSegcAsLNKIu2RfvC9Mg8/aClOVCoU6DMdyBUCt6SzcxrLg0CPej16nKvBYqK6xA49Q6WdZ7HNJ+vcl4nod3qQKoSDZrUjF4C6AQqLnOiiYeFnTRUcs+GHYw9PEF19bduDpiK03lGa41ojnVmjfh155t17Pp5BWbjGHmd7eiCP78eDiETGdD5BH2mOMOORoiPw8Qs5dD4teAcM8ce43nQ+J3T3wbdbfRuDupttL9ghisrnHftyBJOv7XitZin87P9qErkdsidq/t3CW3qAWXe232uR92kQtNFWrbhHvCV8t3l+dsK2xxKquChxP2YtTXiDeuuBzzJYp1YWOYeP+92/2MpGo3FLdE5SWFT0akRYJxkBjbSJz3fXgjyoq0hVrLkLHIYllJV6CJruvsO1qWGZ/Yokk0TE1ysQGRnxwYYsgkN8ZFVrWUn8UtpsE8iRz/X6okngu1/rhBLXnTYsV0/r5zMsaSyJmHMy2RvOb6ifJf)
Browser:Chrome 116.0.5845.14

Operating System:System: Windows10

**Comment by ggetz** [comment] 2023-09-05 13:11
Hi @0naka. This is a duplicate of https://github.com/CesiumGS/cesium/issues/1209. I'm going to close this issue to keep discussion in one place. Thanks!

**Closed by ggetz** 2023-09-05 13:11 UTC
