### ISSUE TITLE
polygon set ImageMaterialProperty , img auto rotated

### ISSUE THREAD

**Issue by chaijinsong** [CesiumGS/cesium#9257] opened 2020-11-30 02:04 UTC
https://codesandbox.io/s/romantic-shockley-39dyp?file=/index.html
this is my demo. 
when load test.geojson ，img is rotated
when load normal.geojson, img is normal

**Comment by dzungpng** [comment] 2020-12-14 17:15
Closing this issue as it is a duplicate of https://github.com/CesiumGS/cesium/issues/9185.

**Closed by dzungpng** 2020-12-14 17:15 UTC
