### ISSUE TITLE
Some 3D Tiles below WGS84 Ellipsoid are not colored by Classification

### ISSUE THREAD

**Issue by anne-gropler** [CesiumGS/cesium#11570] opened 2023-10-18 13:20 UTC
In my local app, I have the problem that the classification coloring is not applied to point cloud parts that are underground. So I tried reproducing this issue in the sandcastle, and funnily, it's reproducible only for some point clouds. From what I tried, the Church and the St. Helens Mountain have that bug, but the point cube from the Point Cloud Styling example does not have this bug. Below you find images and GIFs from those 3 point clouds.

Basically, I draw a green polygon on the ground which should classify a part of the point cloud.

Expected Behaviour in all cases: All point cloud points within that polygon should colored green.

Current Behaviour in case for Church and Mountain: The point cloud points inside the WGS84 Ellipsoid (= "underground") are not colored green. **Even when I selected the world terrain (default in provided Sandcastle example), that WGS84 threshold still applies.**

Sandcastle example: [link](https://sandcastle.cesium.com/#c=vVd7b9s2EP8qrDegciDLduJ0hfPAGjdoAiwPJM7yxzSglERLXChSICknburvvqNIydLitOiALYBt3vEePx7vjpdYcKXRkpJHItER4uQRzYiiZR78XvG8sBdX9ExwjSknMuz56DnkCGkiJXCmtcLc0sFCivxeSJY4htf30XCIDgeDAZIkF0uCdEYVYmANaYHijMQPwCLo/tPt+wmsJFGZYEnI1/2DkIecEY00ZUQRDbSWKwsAjM7O7m5mZ1MUlanjODk4C37EVNfg7M/ex7ndrkCeC/5BAXGeeON3k92xcYaQs3NxdXc5/3B+2dj+d4b3fxnvdezO7k5Op+hRyAf1pmLt/KDxO8k8owIWe0EwvMV5wchHrPGwIz28FpTrGRNl0lreU51dE1kxrqUoiNQUZJ374C8leNgz1i3m4XBnWGOvP7Ws0itGuinTBnBrtr1ni7Qw/m7pFzJF+75hra19m3eBigknQSFpTjVdEhXgJPGcny2CKRMRCRJS6GxOlP6QQpIp7bINEC0wU6St9kWIfC5c1Jxd31It9GcEJ5Sn11TH2Q3mKXEKCI2CkV+vB6NgvyHqWESi5Eb3tsiIJIEEQ6VCO2g3GFnR/iamqAWMcE3NBVQHNvwWnFOzt9pEkK1SAcX2XPuOGVaKLmiMNRV8vipIU4mzF1vBydX8DGCH2qhmlEgs42w17dweZizC8YPLi5Xn9dHRsXEYaqMXV61iwYSw+aMg1H+8EgG4J2gPfx5YXaPdtVIlxBgMNL6lhhXmey4UVvjVCFv7/kauc47aljfy0d4Ivkb974q2JPrfhr37n8O2mH8Qtm2Vdt26pKAoVebZePvuAPUBEfRjXUretn1tE+2sThGvZcvqGTBr31ZZv8mpHMPJKGabJBRMyKpjNXAn3rZDTDxTX2hsvkb2611/Y7gw7UpRk8lnhKaZnlrXTmDtinHd9+saWyNI/DhDHnQEIfu2ZMwFCkYCJlLv86nZQExUBV9f1hT9/FxprD9bK1U8edy8kBciIQwuv7KXOSymM6yr0LtzPXARP4hSB1pCMXmNor0fa00LAaVmHtxExGUOWRGkRJ8yYpYnK3g3wp6TCXtG8Z+2cVGw1QmtckttfPi15S06BrTxchUpIpc4gu7c0gt79kDgrhJUZaRiSSPiLUoem+Ajz0r06xZkSTjDZZlHMCm4bdvkEF0gj6pLfNmoff2K3jhMCVnA47/p8f1NW7MZ6YysTciqZleFLYaUEanERUbjbhHW3G6+ed/p07YcXYc+aHtSpVzgmGytdOPiBjIHc9U4aCODFOMp1WVC/O3b0JU7u6PmlehgEIuFHQn+Bwju8reggCzmilUPyVYokCgm0XWDw8JuLLtINvQrbazrur6v3CTnBdaSPm2cW3pSBWG+Qee1kFo7bnrs+b3Dalg5rjH8SvNCSI1KGKVghNIERihoX2oYlfEDuI2VqpEg9FNdrE2KImSeyVSaZJoimUbYm+z6qP6Mgvcbbehf8DJAyk3RpHhqsSMhEyIHdlTobq5fuKa8KHUbwNIMbjFmA8xoClNBTpOEkZdeB1oUU7Tb8VxvRUJrkXd3nevDYTtghwldIpocbflXwE4hsLMoGTMDXtg7PhyC/AtV12yvADnDKyOWjY9/s8wgCA6HQG7XbBphc39m79g+Bm0V2LCB0jDxgKI0QxxgzCkHajAewR+UGjDwEzDGjlKaFIaEZQJj9CCCtgr0ErMSRipbGT6qyLsCJID5tvLztg2p41mTJ20sQ0CA2v+W5cZG+yR/Aw). Move around the mountain until you see the green triangle. Then use the slider in the upper left corner and move it to approx. `-1777`.

Browser: Chrome, Firefox
Operating System: Windows

# This works

Load this tileset using:

```js
// CUBE: works!
tileset = await Cesium.Cesium3DTileset.fromUrl(
    "../SampleData/Cesium3DTiles/PointCloud/PointCloudWithPerPointProperties/tileset.json"
);
```

![grafik](https://github.com/CesiumGS/cesium/assets/5690856/36d14b2d-5123-4ded-819b-84d35598ea03)

![grafik](https://github.com/CesiumGS/cesium/assets/5690856/8b09c184-67ae-42f4-a1dc-b844121d1bf0)

# This does not work

## Church -- Note the `-430` height translation in both GIFs

Load this tileset using:

```js
// CHURCH: bug
tileset = await Cesium.Cesium3DTileset.fromIonAssetId(16421);
```

No Terrain:
![classChurchNoTerrain](https://github.com/CesiumGS/cesium/assets/5690856/5935037d-bebb-42bc-8575-cb289499cd9d)

World Terrain:
![classChurchWorldTerrain](https://github.com/CesiumGS/cesium/assets/5690856/fe066d8f-2273-4058-88cf-74dd39673459)

## Mountain -- Note the height translation values around `-1777` in both GIFs

```js
// MOUNTAIN: bug
tileset = await Cesium.Cesium3DTileset.fromIonAssetId(5713);
```

No Terrain:

![classMountNoTerrain](https://github.com/CesiumGS/cesium/assets/5690856/89a4b101-2cb0-402f-a253-1f6c53e0fb3a)

World Terrain: 

![classMountWorldTerrain](https://github.com/CesiumGS/cesium/assets/5690856/6cf25a78-99d5-48f3-86bb-c730d9efec09)

**Comment by ggetz** [comment] 2023-10-19 14:44
@lilleyse or @ptrgags I'm at a loss for why this may be happening. Is this in any way related to different 3D Tiles versions?

**Comment by lilleyse** [comment] 2023-10-19 15:08
This problem is caused by `GroundPrimitive`'s usage of `ApproximateTerrainHeights`. If the tileset falls outside that range it won't be colored. You can see the bounding volume by setting `debugShowBoundingVolume` to true.

![image](https://github.com/CesiumGS/cesium/assets/915398/38a96f08-7a50-407a-8327-702f3c3f3837)

The reason `GroundPrimitive` uses `ApproximateTerrainHeights` instead of rendering an infinitely tall volume is for performance reasons since rendering large shadow volumes can be expensive.

One way to work around this is to build your own `ClassificationPrimitive` and provide the exact geometry for the classification volume. Though it's not the simplest workaround to implement.

Some ideas for fixing this in CesiumJS:

* Allow the user to override the min and max height of a ground primitive
* Add an option to render infinitely tall shadow volumes.

**Comment by ggetz** [comment] 2023-10-19 16:49
Thanks @lilleyse. So this is the same as https://github.com/CesiumGS/cesium/issues/8480 I believe. I'll close this issue as a duplicate to keep discussion in one place.

**Closed by ggetz** 2023-10-19 16:49 UTC
Labels: type - bug, category - 3d tiles, needs feedback
