### ISSUE TITLE
Browser freeze when scene.drillPick is invoked on a ParticleSystem

### ISSUE THREAD

**Issue by 3DGISKing** [CesiumGS/cesium#10837] opened 2022-10-05 07:13 UTC
Sandcastle example: https://sandcastle.cesium.com/#c=vVZZb+M2EP4rhJ9kwKVkZ5PmRlPX2aR1DsRu+1AVC0Yax0QoUiApJ94i/71DHRYVu2nRAiVykHN8M5xLTJQ0lqw4vIAmZ0TCCxmD4UVGfylpQdxLyvNYScu4BB33+iexjGUYzsASuwSimUxVRmSRPSKIAUjJQmmSIDQ3FqQlGkwhrKGxrMFvmF1SA/ahVL0tNWeoGOz54I+qkKkhakFUgcA8KwSzXElieQaxTErfjWXaous18o+F4Ez+wCzQhVaZ2wTuVuVmFA33B2SEP/hveNB3xhoUle8EYWk6A5RJTVBaQr1RNPAD1QoH/cb7G/YMxBQamtByQ1gVrRS1NIbI3QEDUvFpIlTyTEsLc2SgK+Xe0SXinmwJqnwjp/K/EksKrTH+/wSx/IvpeII2DOMNjU7v7u6/zOZ39yckDKcKg1VfB2T6DgmzZHkueFlQwy3Pl6oQ6YXkGQYMBawuwK8ndFVgmRGr/IRXlbCBaqToV6WyuWoy40JRZSDZlPWNSkGgnT9iSXBBxo1BxAe0fkz2aTSo6E+arbhdH5NoQ8o4Ollk9wjNEwFTvkCNIR01bPb6IbvSnuVY1Y4eddVq+qcNvbzCLGECfGmMbk1rXc1rizP+FekjZMTyzbt1rgwvg9bmETVwx+Re1RPwpAFM8M3RHj06OPwU7WFDHNHDwygaDav4NSljGWhGF2KNQa4jiPVruSzTcvxvDOA2ivrosp+pzGUJh4Lmr63bcxwsBidJZigwY2+Vtsuf87m65K+QXmr0LWju6mOZBKSrrPoO5XHT55vgrXEyZa4pHJvmmmcItALjGj6obur1+H1HrQmFW1jHT5iGuEdpOGNZLgAnAQtNpp4RVj7FvUEr7F3z2D94ImUdjJVQuo2uO9Hp9eer+Wxy8flhMrmlL9wuL0S+ZEFEv+17+lgxu7R/vbqeTzpakdN6Z7eutU3f0JbaNbEl2NA6mDs7qNXZwfZjtau/POVt9i7bdZ9tGS3p29a2xT16B7/Me9WCXp1sGmEUtBh+ww7Ibno3Gd0p5UXZo3cUHgttrDkmv7Ukt8LQzWgDFZ+8cCGIShLmMJgQa2LWMnGjNtHgxjEj5fBOXMngJwoWC0hsF3JHU3zvwP2eaJYb0/7k8ledBxx2O7lV2B036nLf+oP/6tAw+tij/f/fo7+JEU7Mj1za23apPf/eKRSBfVLbPChtdorOWtDdeuYavZ9UnGBEoxrYGeh8KQxWEMhZzhKYrPDJcYUPO+HoYK9lXtiLxI3pIMjUCjLk98nZefNNrkZwqrE673nyvJGh/nR/GzQ+zd6Zmq9zfJ9MLudfxtPr8U9OuDfoxb0Th978EnJq7FrAeXPf73iW4weFFFoEOLpxquf41gATPhbJM+AzyZj+Sa0Z+qqnKV8Rnp7teBiTRDBjkLMohHBdHffOT0OU31IViqVcPt2tQAu2dmLL4fm0IlJKT0M87ta0SolHpt8h/wk

Browser:  Google Chrome Version 105.0.5195.127 (Official Build) (64-bit)

Operating System: Windows 10

**Comment by ggetz** [comment] 2022-10-05 12:44
Hi @3DGISKing, I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/7254. I'll close this issue so discussion can continue there. Thanks!

**Closed by ggetz** 2022-10-05 12:44 UTC
