### ISSUE TITLE
Camera moves uncontrollably fast when close to the ground.

### ISSUE THREAD

**Issue by DrMerfy** [CesiumGS/cesium#9381] opened 2021-02-16 14:45 UTC
## Description
When the user is close to the ground and tilted to the point the horizon is shown, moving the camera for longer than a few seconds will translate to uncontrolled and fast movement.

## Reproduction

1. Zoom close to the ground.
2. Tilt to the point the horizon is shown.
3. (Or go to the sandcastle example)
3. Start moving the camera for longer than a couple of seconds.

## Example

https://user-images.githubusercontent.com/21154979/108077950-c72c8400-7075-11eb-939e-765ed89ea6e9.mov

## Sandcastle example

[Standcastle](https://sandcastle.cesium.com/#c=bVLBjtsgFPyVJ5+ykoXt2A6J1xu1TVX1sNJWqtSTLwS/XaPFYAH2yq3678U4qjZt4ALDzMCbx8QMTALf0MADKHyDE1ox9uRHwDZNxMP+pJVjQqFpohh+NQr8ODOLj2xG803wVzQVPDNpMV4PJ/NpdE6ra7TTPd7CnehRevtrVLFJvDAntPqKcrilsxwV5p+flJwrcGb8i3d6lO1HJXrmrkx/3903aplcK+uAsx4N85WvEZDgR1Y0EJMEvsgZnAbXITTRYPRZoncVvIlg0FYsz/N2QUIsuiW4TUioReuECu+v3kd7Ysb5FVP5Jk+LQ75Lya6kNN0WWbqLIcsPeVZSQouySLOCHvYx+BWl+4yk5XZP6aHI70I12gj0fVlvuHSlQ9YK9VJBSbaXNAbheFdBSlJ6QYyWsoId2e5DKI3yuURxVFs3SzyuHIAPoh+0cTAauSEkcdgP0udpk/PoG+4It3aJc6HWyXtp3YoJRPtw4/cAl8xaf/I8Svld/MQmOtaJ5/8nlToU8jShkWxeaF12fFxBQkid+O1tpdNanpn5x/kP
)

**Comment by DrMerfy** [comment] 2021-02-19 12:12
The situation is a bit more obvious when complex terrain is available and globe translucency is enabled.


https://user-images.githubusercontent.com/21154979/108503010-5d51eb80-72bc-11eb-9b65-2554be58fa68.mov

Related [sandcastle](https://sandcastle.cesium.com/#c=dVJNT+MwEP0rVk6tVDkpq0WIphVfizggQGLFXnKZONPWYmJ3x04gu+K/r/MBtN3iSzxv3pu8mXENLGqNL8hiLgy+iEt0uirlU4eNskh18aU1HrRBzqKJ+JsZEU4ODm+hQX7Q6hn5VCyBHE76ZM0XlffW7KJrW+Ih3OsSKZTfRQ3UegVeW3ODtDmkcwoNfru6N9ScCs/VB762FRXnRpfg94p6ZA6dPLCtddG6HhpWjIH7yzIVP3vKaOhTCMbfFTr/hOzx9c5yGept/a+nvY3b79t4lpnMxLH4YSAnFCuyOQYuGEdVsKuaNq+scX7IzYcFyK4b2YFdke4mt6VyyWER16DwnDZruGiutPNgFO4u7w6Br4EfFRCEHQ5dCHGcJDKZfMZH30Uspsk2dLJHmcrkPRh/ZSoH9fzhKThJviJiN5IiUNrZzT4HoaBEhv1J9OgsmkSp8w3h4t3JmS43lr2omEZSxh7LDYXluTivwkv0UjnXmm2pabwtTQtdC13MDzxroQicC5llRfSo/2AWLdI48P+TkoVCm9V9jUzQtLT1dHHbg1LKNA7hYaW3lnLgvcr/AA)

**Comment by dzungpng** [comment] 2021-04-19 20:54
@DrMerfy Thank you for sharing the videos. This looks like it is the intended behavior, since the [`defaultMoveAmount`](https://cesium.com/docs/cesiumjs-ref-doc/Camera.html#defaultMoveAmount) of the camera is relatively large since the camera starts out in outer space looking at the earth. You can dynamically change the camera move amount with a [callback property](https://cesium.com/docs/cesiumjs-ref-doc/CallbackProperty.html?classFilter=callback) so that it decreases as the camera gets closer to the ground.

**Comment by dzungpng** [comment] 2021-04-23 18:06
@DrMerfy Closing this issue because of the comment above, but please feel free to re-open it if the `defaultMoveAmount` is not a good solution for your use case.

**Closed by dzungpng** 2021-04-23 18:06 UTC
