### ISSUE TITLE
Master right now (Cesium 1.66) crashes Chrome with an 'Aw, snap' error

### ISSUE THREAD

**Issue by tinco** [CesiumGS/cesium#8585] opened 2020-02-03 13:51 UTC
This is a super vague report, but hopefully we can build up a root case analysis from here. I upgraded our app to the Cesium master to get the fix for the polyline issue (#8546), and now our users experience a full browser tab crash every now and then (about 1 or 2 times every 8 hour day spent working in cesium).

As far as I can tell upgrading Cesium was the only relevant thing we changed, so that's what I'm focusing on right now. My first step is going to be to downgrade to 1.65 and then backport #8546 and the powerPreference thing, since those directly affect us. If the issue persists then we'll rollback to 1.65 clean as a control step, and drill down to the issue from there.

Since the crash only happens every few hours of Cesium use, I can't really come up with a sandcastle. If someone has tips for debugging these kinds of issues I'm open to suggestions. We have one user that works in Cesium fulltime that I can ask to do experiments like run a debug Chrome version if necessary.

Other details: This is on Windows 10, in Chrome, reproduced on at least 2 separate systems.

**Comment by OmarShehata** [comment] 2020-05-28 15:36
I'm closing this for now since we don't have a way to reproduce. There have been similar reports which may or may not be the same issue. I'm keeping my eye out and we can revisit once anyone has a consistent way to reproduce.

**Closed by OmarShehata** 2020-05-28 15:36 UTC
