### ISSUE TITLE
Polyline disappears on map drag on SCENE2D

### ISSUE THREAD

**Issue by Nikitak211** [CesiumGS/cesium#11374] opened 2023-06-27 10:55 UTC
Hello.

Added sandcastle and video with super simple scenario.
Polyline with ```callbackPropery``` and without blinking and disappearing

![image](https://github.com/CesiumGS/cesium/assets/86636988/f396f1b5-1f42-47cc-885f-8be4384796e7)

[video](https://www.youtube.com/watch?v=oOlPRG-zzQc&ab_channel=NikitaKogan)
[sandcastle](https://sandcastle.cesium.com/#c=lZNva9swEMa/yuFXNhiZLv0DmRPaOGIdc+oQtxujLkW1L52oLAVJSclKv3tlpy7pVkiD3uhOz3N3+gmVShoLK46PqGEAEh8hQcOXNfnZ5vzCK9s4UdIyLlEXXvhUSABTosSJqrD/asi7BMkTekG/jMNCPgdfC9msFdMwOhvfTrP0d/r9gr7vRaXldu23dWGhxFq4Tn3YxG3KcMvdqH247jwJ09btmOyRuVb1GO81ovF7x2HvOAg7J+ySn+wtPwlu3vQ1s6g5Ex2DRAmlyYyOW8HzG4BXwgSbi3I0hFWVv81jm9O3LPsUqB2ktmwJE+KOlQ9TrRaoXQE/GAyvP33pw7B3uAejo73lR0GnvgnnTBgMdhAepVd0o9jB+B3LDnIhowguz7OcwuTsB3VbCtNZNkrpBCZXyTn8ymY59UIvNnYtcNjNcsrrhdIWllr4hEQW64Vw45noblk+oCWlMU2LRhpH29a44ivg1eCDzwSlYMa4k/lSiJz/xcIbxpHT/2cVilVc3mcr1IKtG9mfg2G6SRJC4siFHzutUu759T+VXwA)

**Comment by ggetz** [comment] 2023-06-28 17:49
Hi @Nikitak211, Thanks for bringing up this issue!  I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/11370. 

I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2023-06-28 17:49 UTC
