### ISSUE TITLE
Improve GEE test coverage

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#5348] opened 2017-05-22 18:23 UTC
These files have some of the lowest coverage in Cesium:

![image](https://cloud.githubusercontent.com/assets/782098/26322699/1cb02690-3efa-11e7-84e5-6344be5383f5.png)

Perhaps it is possible to create stubs to cover more of the code.

**Comment by pjcozzi** [comment] 2017-05-22 18:24
And these:

![image](https://cloud.githubusercontent.com/assets/782098/26322767/6a79969a-3efa-11e7-8e9d-a603d9f37069.png)

**Comment by mramato** [comment] 2017-05-22 18:26
Part of the issue is that there is a large amount of generated code from the protocol buffer stuff, it would make sense to add whatever special comments we need to instruct coverage to ignore those junks of code.

**Comment by pjcozzi** [comment] 2017-05-22 18:27
Sounds good.  Related: if it is not a huge amount of work, I am also into looking at other coverage tools that we can run as part of CI.

**Comment by mramato** [comment] 2017-05-22 18:35
Switching to `istanbul` has been the plan for a while and is what we use in all of our other projects..  The problem is `karma` is lagging behind istanbul versions and we need the newer versions to actually be able to test Cesium (because of it's size).  It might be easy to just use istanbul directly, but I need to look more into it.

**Comment by ggetz** [comment] 2023-04-13 18:25
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!

**Closed by ggetz** 2023-04-13 18:25 UTC
Labels: cleanup, good first issue, category - terrain and imagery
