### ISSUE TITLE
Rendering error for certain GeoJSON at south pole

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#12251] opened 2024-10-13 13:43 UTC
### What happened?

CesiumJS bails out with a
```
RangeError: Invalid array length
    at PolygonGeometryLibrary.subdivideRhumbLine (http://localhost:8080/Build/CesiumUnminified/Workers/chunk-L63KAE7U.js:338:20)
    at createGeometryFromPositions (http://localhost:8080/Build/CesiumUnminified/Workers/createPolygonOutlineGeometry.js:142:56)
    at PolygonOutlineGeometry.createGeometry (http://localhost:8080/Build/CesiumUnminified/Workers/createPolygonOutlineGeometry.js:482:26)
    at createPolygonOutlineGeometry (http://localhost:8080/Build/CesiumUnminified/Workers/createPolygonOutlineGeometry.js:528:41)
    at http://localhost:8080/Build/CesiumUnminified/Workers/createGeometry.js:152:29
    at async Promise.all (index 0)
    at async onMessageHandler (http://localhost:8080/Build/CesiumUnminified/Workers/chunk-5ODQSF26.js:60:22)
```
for certain GeoJSON data near the south pole. 

Specifically, for a GeoJSON polygon with the coordinates
```
              [-160.0, -90.0],
              [-180.0, -90.0],
              [-180.0, -80.0],
              [-160.0, -80.0]
```
(inlined in the sandcastle below).

The problem is that [here, `numVertices` will be `NaN`](https://github.com/CesiumGS/cesium/blob/7aefae928b1bc57d5c076b6bbd9696348ffdb2d1/packages/engine/Source/Core/PolygonGeometryLibrary.js#L336), because the `rhumb.surfaceDistance` above is `NaN`, because ... (several debugging steps deeper) ... the [`sigma1` and `sigma2` here](https://github.com/CesiumGS/cesium/blob/7aefae928b1bc57d5c076b6bbd9696348ffdb2d1/packages/engine/Source/Core/EllipsoidRhumbLine.js#L181) are both `-Infinity`. 

(I think that whenever `Math.log` is called, one has to make very, _very_ **very** sure that either the argument is not 0, or the downstream computation anticipates the possible `-Infinity`. This did not happen [here](https://github.com/CesiumGS/cesium/blob/7aefae928b1bc57d5c076b6bbd9696348ffdb2d1/packages/engine/Source/Core/EllipsoidRhumbLine.js#L169)...)

### Reproduction steps

Open this sandcastle:

https://sandcastle.cesium.com/index.html#c=jVNdb5swFP0rFk9EoqbRqiojNKrE1ErTpk5LtZd5D665Sa0aX2SbVHTiv89AYJBm0nix7z0fvoaDQG0dOUh4BUNuiIZXkoGVVUF/dL2QBaKrM9SOSw2GBYs100yLTunAuk/cca/9zTQhLHB1CSxI/O4OuKsMZKgUCCdRsyDqOZoXR06rH9vC2LbbGc2tekE0AKXBEoyT0PNnjpXRCe5FksMu8YbJw32WLOmHJPu+XV2xgDStSXM8cdeP2Nn87N2Pp5+9yjhCi+4BC3Cmnox8KvtaKSe/oar34+UHkkA0udTczQ7vn1nxrvSNi+X1Jb2MyMVHv/yKzuCr/8NX/8KvJ/gcnpWTYtw2/aZbfLPp0nIM1T3gZ4u6TcwWKyOAKuR5OKRoQd0z6HBX6S4vJMxH4mJ4x31W6V/EUp7nU+Z6RnxDLB7xBG8W6yAKUutqBZth8FtZlGgcqYwKKY0dFKVqv0/8VIkXcFRYO3in8VSa5vJAZH5z5l8hQnFrPbKrlNrKNx+MTRp7/jtp+yKk3j8cwChet7Tn5eZL36SUprEvzysdonri5sT5Dw

### Sandcastle example

(See above)

### Environment

Browser: All
CesiumJS Version: 1.122
Operating System: All

---

This was originally brought up, with real-world data (quite literally "real-world data"...), at https://community.cesium.com/t/25mb-geojson-file-related-rangeerror-invalid-array-length/35754

**Comment by ggetz** [comment] 2024-10-14 12:50
I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/4801.

As a workaround, you can set `scene3DOnly` to `true` when creating the viewer to avoid this error.

**Comment by ggetz** [comment] 2024-10-14 12:50
I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2024-10-14 12:50 UTC
Labels: type - bug, needs triage

**Comment by javagl** [comment] 2024-10-14 13:36
I don't want to argue about what to close for which reason, but will mention a few points, at least for completeness:

- the error here is "RangeError: Invalid array length" (and not "DeveloperError: normalized result is not a number" as in the other issue)
- the stack traces do not seem to have anything in common
- This sandcastle sets `scene3DOnly: true`, and still causes the error:
https://sandcastle.cesium.com/index.html#c=jVNdb5swFP0rFk9EoqZRpyqjNJpEtUrTpkxLtZexB9fcpNaML/JHKjrx32cgMEhTqbzY955zz702xxyVseQg4Bk0uSUKnkkGRriS/uxyYR7wLs5QWSYU6DyIyN9cEWI4KLi62yhZJ8RqB7lqFje5yhXvRC0Ye8cs87IdPw9sXUEeJH73GZh1GjKUErgVqLxqz1GsPHLa+jHNtWmzndBcqi+IBqDSWIG2Anr+TNFpleCeJwXsEi+YbO6zZEmvkuzHdvUhD0jTijTHjrt+xE7mV69+7H72KOMILboHLMHqejLyadk3J634jrLej4cfSBxRF0IxO2vef7PgVegTF8vrS3oZkYuPfvkdncFX78NXb+HXE3wOz8JJMG6bftMtPtl0bjn67R7wi0HVOmaLTnOgElkRDi5aUPsEKtw51fmFhMVIXAx33NuY/kcMZUUxZd7MiC+I5QOe4N7DQRSkxtYS1sPgn0RZobbEaRlSGlsoK9n+n/jR8T9gKTdm0E7jaWlaiAMRxe2ZZ0S4ZMZ4ZOek3IoXb4x1Gnv+q9L2IoTabw6gJatb2tNy/bVPUkrT2IfnKy2ifGT6RPkf

- I just tried out the data from https://github.com/CesiumGS/cesium/issues/4801 , and this does not cause an error for me. I.e. even _without_ `scene3DOnly:true`, it does _not_ cause a "normalized result is not a number" error. It just renders properly.
