### ISSUE TITLE
extrudedHeight setting 0.2 or 1, expression is the same

### ISSUE THREAD

**Issue by chaijinsong** [CesiumGS/cesium#9263] opened 2020-12-04 02:12 UTC
https://codesandbox.io/s/laughing-leavitt-8iiv0?file=/index.html:1979-1993
setting extrudedHeight = 1；
![image](https://user-images.githubusercontent.com/25416773/101112718-ebe99180-3618-11eb-9a86-9b3106f36ee9.png)
setting extrudedHeight = 0.2
![image](https://user-images.githubusercontent.com/25416773/101112811-19363f80-3619-11eb-9a00-93d19d4496f1.png)

**Comment by OmarShehata** [comment] 2020-12-04 05:37
I'm not able to reproduce. I can see a change between 0.2 and 1 in [this Sandcastle](https://sandcastle.cesium.com/index.html#c=lVLBToNAEP2VCSea1KVVD4Zio9amHowabbyIhxWm7cZlp5ldUDT9d5dCY6NeXJLNvHnvDY8JlWSoFL4hwykYfIMJWlUW4nHbC9Mg2+IJGSeVQU6D3ig1zVN555IRzR3peknG+9tBAo1TTqEVMs/Dz9QAGFlgDGkwa/SA747LHHNYt8406DeiDsWwtQCsFLLkbFXHu1ATyc5X0hyJBVNxic377TmzrMOn1gRwMByciEF/B48P90DL+TP8F/+Nn3tdsfuGK1TLlYthIA47ppAOWUn9nZo0sZjdT6c3nSTTZHFO6xgWUlvc716Qc1TsExt/b9qld/v9ICrmFP7Ydm8EQT9IrKs1jnfpz1SxJnZQsg6FiBwWa+3z2eilzF7RiczaZnQjTaJ9a5KrClR++scP4INKaz2zKLV+UB+YBuMk8vpfVk0yV2Z5WyFrWTey1XB83TaFEEnk4d9OR6RfJP+Y/AU).

I wasn't able to edit your code sandbox (I forked it but was unable to run the fork). I'm closing since this appears to work as expected. Please use the Cesium community forum for your question: https://community.cesium.com/. You can include the GeoJSON file and/or a Sandcastle to get help determining if it's an issue in your application.

**Closed by OmarShehata** 2020-12-04 05:37 UTC
