### ISSUE TITLE
Unable to render a multipolygon correctly

### ISSUE THREAD

**Issue by shubhamMtree** [CesiumGS/cesium#9189] opened 2020-10-06 09:28 UTC
I am trying to render a multipolygon in Cesium, but it seems that it is not rendering up properly.
Here is the code link: https://sandcastle.cesium.com/#c=rV1tjxw3cv4rg8UBJwEuqvnSbNKWjSRycEFySQ5xkC/ZILe3Oz4vbrUjzMzK5xj676nueWk2Ww6ch48/3Emr3VoO+bCqWC9Pfbzbbz4+bn/c7jdfb563P27ebQ+PL+/Nf0xfe3V7cz/9/d3u+Xj3+Lzd3968/ur2+Wl73Nzrl3Yv44/9fPu82dzeHH/6sL29+VL/9M8vT8fHP+yefvrz7vn25ovTP3+8e3qZ/l2si+ev3e92+4fH57vj9jD+y3+OX91c/q/4w+KPm40dTgIu/6Xe9J1LubODD7YL87/91xe/VkRQESkOXe86561ziAxvehvCRQ4iwZnz77c+DS71iAyrMmJnbR+7mH30iIzO9N4O2eZumD4SIGPIKmPoB+f64L0uCZGRzPmHT59nQGQMKiNb73IY8hBTRmRE0xdCoGUoRk8HEmy0KUDLUJDGGAafUwo+Iyc7KEbnI9FdRWQoSofU+RCT61KHrUNRmnyyl3uL3NlBUZpyny8wQ25cVJTmAqfI0cZkivsWLHJb4mAW6EBuS4wmWjfYOETfdXpEiIzeTL9/sF1OLvYITGMw0QU3DGFCK3K00ZvzZzjBDDpapzJKkCEyrLmcyLQj0GfpTHFnO0gh99nEZo3cK07LC4NgrFeclp8GuS+94vRqaNXQITjtFadDARFoHYrTkwZzIal+h063V6SmIV0vHiJCgTrf/AHSyb0CNefgbD7hBLkwfWfKY4EubsjmojompCHrCMkUSqzzCE7DYBZmDrkvIaqM5J2/7Cwiozcnn7QLk05EsB6CKdUHpJODN2d1PEmCjtaZofRvoaO1ptElDArS0jQgF84rSFsvrVeQtu6oV5AWfpSDZChIU2H2IRkK0tmydAlRpl5BmstdRWR4s9gO5LJ4Z64KfXTYIRnWzJ6p3l5EIfvOlLYlIzJcNldFOpls5MK4ZEod1jtEFbrBlN66h2REc1VhkzBERm8K5zTliCghF0wqn3MRWolitfS2E3Q2CtbSFUI0u1OwFmZKRSFCFK1t+tAqVsvjhWQoVK9BHDWYkAxFavEmDJACsNGU64AUs+3NrFH1kCEZwRSRCz0g6MN4Uyr3iAlxplCqOSREn1lriuvfYUfTmYWv3CFCsilc5XFvkBiZmY9F742DIikmL2JkyOvSlGj3kM1UpC5el8h2KFJLxz9CNtMsPAhIo5q8MJlQQEdhutBlA3IwitPyPdZBIOuAn5Hlb7YZekAJZROkOo8I2VohAEMqgPaIPhbGTZHqyjpICEF1SKXCLLQllS6F3DqhaHVZ2RdoZymmTmqrO2D7wnAAZOWKYFIITpHU7pnHtoXgKErtsWKYa/echeLBC+MtIfWrBsMb5YElq7ceJITw6JT69euwXake4hhWGCEBqYMTEOAYURKpwzUQahlxI6kDWJgQQiRN6pAe5jIRYovCCHIKI9oqddjXYj5gc/hZ6ig4hPo6Gg8FB4SRFxBGgkIYmRJhpGykzh1hQqokFoTYOpuGCanTetirhZBgFEKiUygZV6lzvxDuGUloqbPhEO4ZaXmhFAgIo1RB6poJyLlgFG9IXUWCCWmvZhFGVY0wynuEUWckjIInYVReSV0CBp0OoxZNGEVxwqjOE0KVoDCqFYVQNSmM6k1hlJEKo55VGIW1wqjwlbrUGBOyrHjGAheM0muBSsDHn7EK8OC7PofsK5G/7oTH1Qenb+hshxTiAAnRfeyGTi1U77IaGmwleqJdzvb8mVyChCi21MiEIQ2974MNkBBFue371A0+6mXJkJDRPqjmsfquGQbvI/Rx1FLpE82FGNRMOP1AkBDVQS50Q/ZOL52HDkeNt97ZrLctWd9520NCFLATPs6Ag2QoXr3rhyF3uqduwBaieB3R0Q0xqPLAZChcfXLBR9VlUc8GEqJwnZfhLCSjG61DVpOt75FgoV1V97vXuz8Gb3NUBQ/JGK1U7oeLJoBkKFRLrEZIyGi3CymQDIXqrAC6jO3I6Ml0uYtnbQLJUKhGr86QH+KgNgYT4kaXarT9fsix8w4SoliNOXQXJY2tpDPzMnzO0EqConUoDA4mROF61SI295B+DorXAiXYxoY4+u/z3mIrUcCmGDp9f0eXEuYMhGBOduZkQrGFKGCz6+Kg7nuMCfMFggJWPZquU9c99Qkye0HxOpneMR8bEuYKhE6fit18eSAhPpsT2tXxnl7ikJDx0ap2xulTIqrvhwkZn8+zQvKYkPEhb1NOnTo5ecA0vR9DCvrI69KQbIJ0iQ9m3IirdsTW4U10nc/xdMyQwfHOFAcTMVfAW3P2JCZBkCbxitbx8l8cT+jTOEWrugAudWHytDAhilYfZuuHCVG0FqYP8waconVWiz20r07Ben5kTSoJgqtTuIZZvSbIL3EK17OvOL0KsJUoXosHTsBWongt/U5sJQrY0h+AhFgF7EJJQ0IUsOXdgWyfHePp8+eBtKtVvKrZvDiwmDdgxxTDmBWwnc0JMsFW4To/CBy4qwrX6eqeH0rYShSuF29Ct8VjK7Hm7Oid3jnYShSu89FAqqRTsKbk0+U1DclQrM5PcX1EQkIUq4U3D2G1U6zm4uNgO9KbyY04AxYSEczQufn1CRngzpsCqR1kbDpnijCYGlBIiDVnl/Xk0WNb0plCAah2BITkbK7HMopBFpLHhHaegwsIRPKUWb++GQNyd/OY4i9iadA6ejO7Rfp0RO5MHoseTk7vdHWgdShSr8+aESOIDEWqLww4tKfWFN6ZaldEhuJ0tjKpQ9aRspmDinaA7F1SnF6jxt0AWaqkOC3j4Mi5JMVpa2wyKU7LoBG0DsVp+Y5H1GFSnJaPK2gditPS40WMf1Kclm4ItKeK09I8IOsYFKflxUXWMYwlbcWmQjIUp0XkKyBOyDAW+Z112GT+ERmK0xRmyw3tqeI0FTcGWofitNiOCK1DcXpJsNgQArQOxWmeI0WIChoUprOrHKCYc8zmEtqZjD8kI5nCUHoorRgHU8ZWAyQjmqsL5BKU+4q9uTraU8AKkRHMxZsbAxEZ8aSiN4sLB63DmcI7dT20DmuKtJdzkBqLYwX37BhaKIjYK1BP5+rSFJGEhExl7WmOaCIyxgL7IjmCiIimeBVaB0Wa+7Hl4JJxVjODOJe9QnVMI7pz/A4RoUgt1PqA3LremVPs/7yviAgFapm0hpbRmVQmE6GFBMVpmeFBRCSTFkF3xL4EhWkZC0Vuf1CcLuJTiAyFaRk3gIIPIZhUvuigt3ZQpC7cbUSGM6l0haB1KFRLOwWtQ6FaqhBkHX7sKSuOF3LrvGJ1zkEM0PX3Y5/dNRE5QFlEH81iGZAMhWouvSFERjDXTOaoBKD8kPemdFEHyPH3zhTJvwjlEL01c62JGgnEK/OdWcQvA4J3l821WGzKzSCfxiUz1b1drBXkt7vBlBlv7EHlolkAHjlf15ur3Z7OGZGhaHXlniCQd4rW4jE0QErRKVpnnKmOh85m7KkuX/+IDIVrESnHSqzGPvNT+v/0eocSEGPHe5nzhuLLitZQKiQo6TaSABSqFSsGMrm56kzR2l4LpGhtL9BQtLbnzRWtRS4zgFkIk1tzTNnkMvQPKQEFa3NYVrHaHDJTqDbHMxSqy6cm4qCZvHgGIK6zN7ndQVOktltOa3K7QhupXmacjQ8TRAjwM7L8zTZBWWWhbIJQzkMo0JAKpJiJkeV1cVBWRxj3VhgKRBiaTCqVChVnCUO3S2VlPIZaisETiu0VihsgDIdEas8IAwvFSROKvygU11VqJxoq1xSGOy/1wyJgH4jxxhHKc0sYDz9hvEClfgtDBR9CeZYLJUIglGCF1GETDC2MAI7UoSTs8zCCWsIIrwkjzieMgKPUkU/seBgxWKmjwQ5aCyMuLXWA3GNLIYTqpU4aQDKq7AX2aQhpFGHkc4SSWZI6xQVdH0qyTeq0HySjPfsodRYUAwohHSuMtLBUCWqsBVgImXKpMvaQZ0wpHZBVFQMkhFFPIVVlB5SCEEaJidS1LpAMQs2NEGp/pKpBwo6GUAsljKIsYVSHCaFKTRjVclKX7WFCCPWDwihkFEZFpTBKO6WuMcWEEIpdpa66xYQQyn+lrkOGrg6jIFrqymxMSFUiDh0xo1ZdGEXzwqjel7qNALqAjH4GqRsrMCGEDg+pW00wIYSeF6mbbzAhhC4gqduRMCGEvihhNGjJqlUMi8AzutZk1UAHSmlv5ZNVUyEWx2/vbpRVmyUmpL3fUyidp8LogRVCL66smoJBKYT+ZKG0SkvdtQ1ubXP3uFDa2KVuqPeglGVvfwSPmUAzICvGA1AKgXxBVjwQmJCKkQI7IgY5hqx4OsC1tDOGCIW7RCg0KlIzumC7wuCWkZrlBgsAUgh3pKb+QfeFwEIkFR1SBJHLYGYSCkmUUPiqhEKdJSsWL0xdMgjFpKY2AxUDg2VNar43sIKHQT0nKxY8DLsMQj5ZcQOCayHQFAqFMVFW5I3YJ2LwSMqK0hK7RwRyTVnRfIJLaScclRX1KXaLCCSswmCDFQYtrTD4cWXF1IvtLIEzWFbsxdgFIvAoy4rRGVxKO7e0rFiuMSEEvm1ZUX9jQioSckwIgQ5dVszsmBACR7ys6OoxIe28+UJh8BfKMAGhzDUQyogFoUx7EMrgCaHMwBDKOA5hDAYRyogSYQxLEcrYFqFMkBHKMBuhzNURyogfoUwbEsrgI6HMYBLKOChhDKYSyogsoUzrEsrgMKHMMBPOPDWhzHYTypg5oUy8E8rwPeEMAhTGTEKhTEcUzqRGoUyNFMoAS6HM0hTKWE+hTBgVyrBTocxdFc4MWKHMoxXCYFzhjOgVyrhgoUwuFsoQZaHMcxbKaGmhTLkWysBtocz+FsoYcqFMRBfOdHahTIoXztT6z4iJ5qrpJnmYlLGFIs9GCdyYYFL5cozgYrxZ3EfwFjjFb+lRYfh11qTCtKFxD9eZZqVpx8654qw7bF+swvcaUFJLCy5mbCgsn4/YWY/t5MVaQBU+drZ3hZ0FNd7YZj8HT/S4QDHelJYgDuDWOFNq35Aw1TmyIczaQbUNZplGZobSCwfBN/baX51wm0F1Nfb9l3YSjKKYvIjcYe9Zs7gFDttdxe/iPYtJCSYv3hWgP2TywsPD9J3JpamNoCmwJi9U3oAd0siGU8LOQx+qg35o8atdh0V2OftQHcqARfwY+KiQGiHVRrk01f3FLAdDk1Q6DXspVuoVBBtF1a/sDiSEYgNrg4zZdY53sHJVICEMr6n24MATYniTtWcLCSG42Bxnn/LwqB9BWAKZ8yJbvQ6xbWG8VOtXMyakesA7TAolmlBHNiAFRwmy1PEeSB1QQk91FAxzUxgBuTo2CClaSpiSEjGlBG/rQDImpD2iXYfWIaVUh/khGYyEAyX3QUnDUDJCdXIKW0mVJ4NOuE7ZQUe8Sh9CQhiZTEZOlZPerVPNkIKlZL3rBDy2EkYtAKcugVIjUZdrQGdMqRypi1igy8Mop6EU9lBqjCjlTpTKK0oRWF2PBp0wpTSOUqVHKRhklC5SiigZ5ZyUwlJKjSul3JZS+UspQq7robGVLEuzIRGMGnGsWv3/qpunVPAzegkoXQ2M/gpGowel5YTR/MLowqH0AzE6kyg9UoxuLUrfGKODjdFKx+jpYzQXUtocGQ2XlNZPRhMqpR2W0plLaRKm9CtTWqcpXdyUhnJKbzulzZ7S8U8hH6DwIFAoGSjsEBSiCgpnBoW+g8IkQiE1ofCrUKheKKwzFAIcChcPgxWIwk9EoUpikDZR6KMoTFYUUi0GvReFaIzCeUahX6MwwVFI6Sj8eASiPgZhIIW6kMKiSCF0JDBLMhguKVybDNZPBv0ogQaVwsfKYIalcNRS6HIpzL0MDmEGmTGDVZlB78zgmWYQXjOYtxkU4AwucgYpOoOdnUETz+CrZxDnMxj8GaMEGDMNGMMVGFMeGOMmGHMvGAM4GJNAGCNJGLNRGENaGNNiGGNrCONzGGN8GPOEGIONCAOWCHOeGPOmCHOvGPO3GIPAKCPJGMPRKGPaCPPiCGPrKPPzGJP8CBMFKaMNCTMWCaMeKTMnGdMvKXM4GRNBGaNJGTNSCbNaGTNjKdNrGXN0KRN9KcOFGWOOGfOWGYOfGROoKbOwGVO5GePBKYPKKTPTKePbKZPkKUPtf6WQaBaAR/bV9eZqt6eDRmQoWl25JwjknaK1eAgNEEqcwnUGWuihx5Ab26jLlz8iQ+FaBMktlmQee8tPyf/T0x0KUI9d7mW+G6uyNGVlRY+Ve46N/4VuxeLtitfmsjPFa3sxkOK1vT5D8VqmzLHqGcVrmcjEYKKAbU0wZZPLwD9URKBoXQRloWiGyc0BM8VqczRDoVq8NR30mlColg8B7Pp6k9t9NIVqu/G0JrertJHgpQBaQjK7HfAji187voj+/zIYn59xEAxEVNDMwLNueUMs8iQjXFSCviCorUp7Ik4UQYlXxiQgCW2GVWOYV4adJ/gbtd+DiCD4XwxHkOGR1q4xcOcJHnr9UkAyQIwnC+PtRHjDEZ6S9ZMWyRMw3taMRz4j2lCHPYArS4i+1EEg5NYzolGEqBghOEeIEdahSkQEIWRax26BIyGEkOtQNrKK9oh6HddHGknr/AKSYCDkOQjpFkbap04/AZ49IQtWJ+OAq9aeEqwzk8gimvOjhCxtlS12SHtie9K6ypxHZC8IGfxVJQEig1DSUJVWINedUOFR15kgq2gvd2kvuqkqf5CiP0IBEqEOilCO1V4URihNqyvkgNtOKNQj1AsSyhYJ1ZN1ESegcAi1pHVJK7CdhMrausAXWUV7nXFd7gzgoq66RlbRXvxNqEEnlMLXFflIFLW9MaDuTwC0L6FNou7WAE6E0DRS964gq2hvoak7eZDtbG8oIvQ1rfqrkBgsodFr1XEGraO5823VgQcto7URcNWOiKQJ2tsiGe2ZhDbR9mbVVc8skskiNO8yuojrbuYBWkdrUzWjt7tuMkcQWjW799Ay2rvuV+3/SDaMwEOw4kNAbmxNzACto50hYkVVAa2jmTKDQd3B4BCpuUywFHY7qUrN7oJsKYFlpqa7gT5JO+1Oxf+DQJRAQ8TgQ2IQMzEYolZUVZCMds6smrwLEtFOIlazmSEGjsCqtqJ3g9bRzjO3IryD1tHOvMegAFxxESLag0CKuGJnhNbRzBK5YquEZDSzZq7YOxHL0s4iSiAzJXCqEqhdVxSzyGa0U92uKHchGc3UvysKYmgZzVTIK0ZmxLoRqKFXFNXIOmqqbEhGO2f3ijscORcCifmKTB1ax68mdb/88fyH6f/0fz59dft8+3y/ez4cNw93x7vvdi/7++2/3L3f/mG//f7xr5uvN7/Vfz3ql387fevmzZun7XFzvz08vrx/t3va7fVb3k1/M9Nfzff73ft3h8P0l++O+8fnP7+6P/3Dbv/+7vgP27++ev1aZZ1/6Hfb3T8eds/fXn+5edrdPbw6/9IvNj+XH3D+7/7p7v2Hf9/9br97eX74cnPcv2y/+Px3Ho773V+2Xy4X+Xe//9t3//QLP/D949NT9e3/9vffrr/302tz/GH7/OrhsPn6m19a58PBPOtu6iZt/vibnz+3xZ/++zc/nz+t+Xj39LL99MevPi/r4+P2x+3ezEIO5u7hQX//61/4geMPjwdzlv1t8VMfXg4//MKPfRq/ePPFzdvD8aen7TeXb/ibx/cfdvvj5mX/9MqYN8ft+w9Pd8ft4c2fXu7/sj2a+8NV2ts35Y++fXj8uHl8+Pr25gKZ5+Pd4/N2f3sznuHhoP/y/cvT03eP/7O9vfnm7Rv9/tWPjohQHP3rx+3+6e6n8dt+sN/8/vRFY8zbN/rXz//kcbd7+tPdvpL8vw

Why is it being rendered like this and how to rectify it?

**Comment by GatorScott** [comment] 2020-10-06 11:53
This is likely a duplicate of [#4871](https://github.com/CesiumGS/cesium/issues/4871).

**Comment by dzungpng** [comment] 2020-10-30 15:47
Closing as a duplicate of https://github.com/CesiumGS/cesium/issues/4871

**Closed by dzungpng** 2020-10-30 15:47 UTC
