### ISSUE TITLE
cesium 1.105.1 版本下，设置 viewer.trackedEntity = entity; 之后，不能进行地图缩放操作！

### ISSUE THREAD

**Issue by Southjor** [CesiumGS/cesium#11317] opened 2023-05-30 06:26 UTC
Cesium 1.105.1 版本下，设置 viewer.trackedEntity = entity; 之后，可以鼠标左边拖动改变视角，但是不能通过鼠标滚轮进行地图缩放操作！

Sandcastle example: [视角跟随示例](https://sandcastle.cesium.com/#c=dVV/b9s2EP0qhLE/ZMCjf0i2pMQN1jrBGiDtilroMEwDypB0zIUiDZKy6xb+7juKku3GGWIgJo989/ju3ZlqZR3aCr7jBr1Biu/QgltRV/hLsxeVPdqsF1o5IhQ3ZW+AfpQKIceNgZ2r7kIR1nhldPWnNpK1G1F/UKpD/7pUtElmKVcccoWkuFkeg1Rq+nwKNksIlkpyh7hywu2vw2KjrXBCq09Gb7hptgMEI44sdW0oh1AlrM/VUlx8r+TtMYylJizyTyl7GA+XpNpI7sPDhYTvhf7d6FoxTOFW2SuVf0LL65TDYsJYdJGzj92aq2hVK+pJorMT/SBfeAxwO0VwsycA84m7d/t7INcLzD8I+VyYmj6XPc8CXbwecAIg7iLXrehHzpRU3BBsufOljRoSjFsnFPHnr86LvyDGwTei4kYfhMaT8SwZxTjLkuk0m02y6SAEfk3SeBZPU5zkcTwdx3kXSEbZeJLnOB1PZ3mWJ7nf7jdBbQSQvcz6nhMm1NMn4ej6s5ayzZ3gSZZPJuMUELNRlo1mXe4RTtI8H6WjcZJORxP4tJEZnqR5muXjNM2SOB7Hp+RcscIQZVfaVEfvfiDOiG8Jvr+9+1jcF38NjuI5sw/1CuZyQnJQEOQmOyLcUa/mX3xbhHDTA/davbWwgDKCFrNZKNy56/HGiAqKtW1d1IKHxAiJFYrCORr8+J6Lp7Vb1puNhvKw1kioI4WFAjAiGxIP4G3OPOzdFsR+ENYBkomsg9IGKgfEJXRHC7ITiukdJhLsBL4r1sKiR6N3FgYD09wipaF3Q270EyHcmfIAqiFKoHoogt7Xpn+STkvfb0/R1zsfQL71oNQd9Sv0y4/mxuGrhzp4AY6901COOiw/EbBd61qyt0pUxPn+dqbm16cq6cd/OXW20HffqKyZP/F3aI9/mlOt+tq6z2AHKMeFTKfGPaocoLv2AsiXPei79guRNY8CSVobA5iFqHjQB73sUQB5pcBRFx5cPKTVudEIeZHO+tsZQp85u+vmynFalmpJFKPEOqgBvLTQWj4S8652Tis/4KUGG/x03Q/5Cwn+Jw+MSL6CXwZ2mjj+rzfoza3bS34Tno7Qb6JqzFMbGcG8dRzmLZTPDh9hsIF9qbWdTvPh+dU5E1sk2JtXfou8E62FyKqWcim+87J3Mx/C+YurreP+2HIjyd4fW49vHsImxng+hOXrN13Q6wXyfw)

Browser: 谷歌浏览器 112.0.5615.87（正式版本）

Operating System: win10

**Comment by ggetz** [comment] 2023-05-30 13:30
Thank @Southjor! This is a duplicate of https://github.com/CesiumGS/cesium/issues/11286. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2023-05-30 13:30 UTC
