### ISSUE TITLE
Z-aligned billboards rotate if camera pitch changes while camera is rotated

### ISSUE THREAD

**Issue by iatkin** [CesiumGS/cesium#10101] opened 2022-02-14 16:22 UTC
I have some map markers that I have set to follow the globe rotation by setting alignedAxis to Cesium.Cartesian3.UNIT_Z. However, I modified the camera position with lookAt along with a custom HeadingPitchRange, and the markers rotate depending on the exact camera heading and pitch. The greater the heading, the greater the rotation caused by a change in pitch. The example below will do a complete 180 degree rotation if the camera is dragged to be upright again.

Sandcastle example: [https://sandcastle.cesium.com/#c=jVFdaxsxEPwr4p7OcJHOtIXiXEyN+1BDP0La9KEclLW0Pi/RSUa7dpqW/Pfq7hoIrR/6phnNjGZXNgYWdSK8x6SuVMB7tUamY6+/jlzZFnbE6xgEKGBqi9llG06QFGbD5NQYhISQNThX/mqDUofImYlh8ZS3hiT5BOGF3qXYv8UuIXJ58bquXtZVPasG15a830ZIbqHGFKWohw4Xqi32IgdeGMMQnAUWj3pqpm3szfTIbegp0I7QmRUzCpvNYGeTi1zYhI5EH0LXFtUUDp66gG71g/hcz9uPmy/fv/3RpigwDVQPxGMbHsdFTAuw0GMC7WO8W0n5vyM/3/c7BEehuyax+xsIHZYfQPb6elM9KUYs8SbrIOSY+aucMK/reja7LKqiYXnwuJzaKvWG+kNMoo7Jl1obwf7gIdcx26O9Q9GWeeg/SBvz3No4OilyV2d+XlkPzPlmd/T+M/3Etlg2Juv/sfo4TvPphMnDwyDbz5fvJ1Jr3ZgMzzslRr+F9Ffybw](https://sandcastle.cesium.com/#c=jVFdaxsxEPwr4p7OcJHOtIXiXEyN+1BDP0La9KEclLW0Pi/RSUa7dpqW/Pfq7hoIrR/6phnNjGZXNgYWdSK8x6SuVMB7tUamY6+/jlzZFnbE6xgEKGBqi9llG06QFGbD5NQYhISQNThX/mqDUofImYlh8ZS3hiT5BOGF3qXYv8UuIXJ58bquXtZVPasG15a830ZIbqHGFKWohw4Xqi32IgdeGMMQnAUWj3pqpm3szfTIbegp0I7QmRUzCpvNYGeTi1zYhI5EH0LXFtUUDp66gG71g/hcz9uPmy/fv/3RpigwDVQPxGMbHsdFTAuw0GMC7WO8W0n5vyM/3/c7BEehuyax+xsIHZYfQPb6elM9KUYs8SbrIOSY+aucMK/reja7LKqiYXnwuJzaKvWG+kNMoo7Jl1obwf7gIdcx26O9Q9GWeeg/SBvz3No4OilyV2d+XlkPzPlmd/T+M/3Etlg2Juv/sfo4TvPphMnDwyDbz5fvJ1Jr3ZgMzzslRr+F9Ffybw)

Browser: Safari, Firefox, Chrome

Operating System: macOS 11.6.3

**Comment by ggetz** [comment] 2022-02-15 14:49
Hi @iatkin, what effect are you trying to achieve? [This forum thread](https://community.cesium.com/t/how-to-use-alignedaxis-for-a-billboard/1586/2) explains the intended behavior of `alignedAxis` for billboards.

**Comment by iatkin** [comment] 2022-02-15 19:07
Thanks for the reply. I'm displaying currents with arrow heads showing the direction of the stream. The first image is the initial downward facing camera with the top of the screen being north. The second image has the same camera heading with some pitch applied. The arrows are still facing the correct direction. The third image is same area with about 180 degrees of rotation and the camera pointing straight down; the arrows are still facing the correct direction. The fourth image shows the camera pitched around 45 degrees with the same 180 degree rotation. In the case, the arrows have rotated from their initial position.  

<img width="300" src="https://user-images.githubusercontent.com/2798032/154129588-2217fb47-5126-4818-8076-d6e52d97467a.png">
<img width="300" src="https://user-images.githubusercontent.com/2798032/154130248-939667b3-39b6-4ccc-afa5-3b04033d6886.png">

<img width="300" src="https://user-images.githubusercontent.com/2798032/154129597-d95273bc-d0f5-4c2c-b753-54a0b042c0f8.png">
<img width="300" src="https://user-images.githubusercontent.com/2798032/154129607-a3714881-1269-414b-90b9-1701951041f2.png">

**Comment by ggetz** [comment] 2022-02-15 20:04
I see. I believe this is a duplicate issue with https://github.com/CesiumGS/cesium/issues/6165. Basically, the alignedAxis property is working as expected, but you would need a different property which lets you specify the heading of the billboard. I'm going to close this issue as a duplicate, but let me know if you think otherwise. Thanks!

**Closed by ggetz** 2022-02-15 20:04 UTC

**Comment by abigstupidbear** [comment] 2022-03-27 01:53
> I see. I believe this is a duplicate issue with https://github.com/CesiumGS/cesium/issues/6165. Basically, the alignedAxis property is working as expected, but you would need a different property which lets you specify the heading of the billboard. I'm going to close this issue as a duplicate, but let me know if you think otherwise. Thanks!now do you have any good solutions to solve it？ if you Draw a arrow With direction，it will rotate when you change the camera.

**Comment by ggetz** [comment] 2022-03-28 12:55
Ultimately, this is a fairly common use case and we should probably support it directly in the API, as tracked in #6165. In the meantime, you could update the alignment to match that of the camera, but you would need to update this overtime the camera moves. You could also try keeping the arrow image on the globe surface with a rectangle primitive.
