### ISSUE TITLE
Some materials not working in iOS/Safari 15

### ISSUE THREAD

**Issue by alexrobin** [CesiumGS/cesium#9827] opened 2021-09-24 09:00 UTC
Some materials don't render correctly in the latest release of iOS 15 that now uses Metal backend of WebGL (Webkit). I noticed in particular translucent materials are not working on some geometries and dashed polylines are not working but there might be others.

Sandcastle example:
https://sandcastle.cesium.com/gallery/Partial%20Ellipsoids.html
https://sandcastle.cesium.com/gallery/Polygon.html
https://sandcastle.cesium.com/gallery/Plane.html
https://sandcastle.cesium.com/gallery/Polyline%20Dash.html
https://sandcastle.cesium.com/gallery/Wall.html
https://sandcastle.cesium.com/gallery/Spheres%20and%20Ellipsoids.html

Browser:
Safari 15

Operating System:
iPadOS 15

**Comment by mramato** [comment] 2021-09-24 13:28
I can reproduce this on my own iPad Pro (10.5 inch MQDT2LL/A), but oddly enough not my iPhone Xs.

So there's a chance this is iPadOS only and not on desktop or iPhone.  Can anyone else confirm?

**Comment by mramato** [comment] 2021-09-24 13:28
Also, thanks for the bug reports, @alexrobin!

**Comment by sanjeetsuhag** [comment] 2021-09-24 13:42
I can confirm that all these Sandcastles work fine on my iPhone XR running iOS 15.0

**Comment by ebogo1** [comment] 2021-09-24 14:32
+1 for Sandcastles running fine on my macOS laptop (11.6, Safari 15)

**Comment by alexrobin** [comment] 2021-09-24 15:21
Yes, I forgot to mention this but our application that experienced these issues also seems to work OK on the latest iPad Pro 11" but not on iPad Pro 10.5".

**Comment by alexrobin** [comment] 2021-09-25 20:21
FYI, setting `orderIndependentTranslucency` to false in the viewer options seems to be a workaround for this issue.

**Comment by alexrobin** [comment] 2021-11-09 13:50
Did you make any progress on this?
Let me know if you think it's a problem on Apple's side. We're in touch with them on this.
Thanks

**Comment by ebogo1** [comment] 2021-11-10 14:42
@alexrobin No progress at this time, but we're hoping to look into it more when we get a chance. Please keep us posted if you find anything new!

**Comment by hayderGo** [comment] 2022-03-21 05:31
I can reproduce this on my iPhone 12 Pro Max (IOS 15.4)

**Comment by mramato** [comment] 2022-03-21 12:29
FYI, iOS 15.4 actually introduced at least one major WebGL regression regarding offscreen renders that is causing problems for Cesium/Babylon/Three/etc..  See https://bugs.webkit.org/show_bug.cgi?id=237906 (which also links out to a bunch of other related issues).

So anything that requires rendering to a texture in Cesium is most likely going to have problems or be totally broken on iOS 15.4.  Hopefully Apple addresses the issue soon.

**Comment by mramato** [comment] 2022-03-21 12:33
Actually, looking close this is a Safari issue that was pushed out with iOS/iPadOS updates. Since you can't really use another browser on iOS/iPadOS (thanks Apple) that means it affects Chrome/Firefox too.

On Desktop M1 Macs, it _may_ only affect Safari and Chrome/Firefox should be fine; but it depends on the details of the exact backend being used for WebGL rendering.

**Comment by arelenglish** [comment] 2022-04-22 02:56
I can reproduce this issue on all browsers on iOS. Setting orderIndependentTranslucency to false resolved the issue for me as well.

**Comment by mramato** [comment] 2022-04-29 14:30
@ggetz Assuming this bug only applies to iPad/iOS and not desktop Safari, that sounds like a sub-par solution.  Are we sure we can't use [navigator.platform](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform) to detect iPad/iOS specifically?

**Comment by ggetz** [comment] 2022-04-29 14:59
It looks like `navigator.platform` will allow us to distinguish iPad/iOS. Thanks!

**Comment by mramato** [comment] 2022-05-17 15:05
FYI, Apple has released Safari 15.5 and updates to all devices to use it. It fixes a lot of the WebGL issues and regressions that have been plaguing Cesium users and WebGL apps in general

It's probably worth doing a review of all ios/ipad/safari specific issues and seeing how many we can close (might also want to introduce some Safari/iOS specific labels if we have a lot still open.

If this is as good a WebGL update as everyone is claiming, it may even be worth a forum post to encourage the community to update to 15.5 before reporting issues.

**Comment by ggetz** [comment] 2022-05-18 15:10
Just testing this out on an iPad Pro on 15.5 after the update. No luck. 

However, if I turn off "WebGL via Metal" in Safari preferences under **Advanced** > **Experimental Features**, the materials appear to be working.

![IMG_0591](https://user-images.githubusercontent.com/4439461/169075207-31b93daf-d232-41db-9bc5-7826e18db6da.jpeg)

**Comment by ggetz** [comment] 2022-06-01 13:07
Looks like there's some limitations of `EXT_Color_buffer_float` we'll need to account for: https://bugs.webkit.org/show_bug.cgi?id=240919.

**Comment by ggetz** [comment] 2022-06-01 15:01
Adressed in https://github.com/CesiumGS/cesium/pull/10417

**Closed by ggetz** 2022-06-01 15:01 UTC
Labels: priority - high, MacOS/iOS
