### ISSUE TITLE
OSM buildings error when switching SceneMode from 3D to 2D 

### ISSUE THREAD

**Issue by wisdomware** [CesiumGS/cesium#9493] opened 2021-04-18 01:26 UTC
[Please click here to see the code and the error at SandCastle](https://sandcastle.cesium.com/#c=hVLBctMwEP2VHZ/kGVeO00ApcTNA2hulDMnAxRfV2jQaZCmzkt1Jmfw7kp10EgiDTtbTe2/f7roTBJ3CZyS4AYPPMEen2oZ/7zFWJXV/n1vjhTJIVZLBr8oAeCQKyFeynZJI7w/CmlB4/GFJy+VAYWlWmV06rUxlhlLc1WiQb0g1yqsOHRdSshODB9d8apWWyjw5lp4R16JBEnylt0vL+kQSnVdGeGXNa5q5IB++hLnkK7LNLT4RomMXVxM+Kq4zmIz42+tinMHVm1GMCWBJYeh1cOl9AdYoYpBX13vh19zbbwEVxrHxXgqwUb5e/4t2ceDthnlA7GnVmjrWgr6Rj6RerBEsHSqfNNxYiWFHe+9FxO4DxBfzuy9349vpkWA/lBBoiBXPyXT+N56imPCiyOByzN9lUBSjcNI+etzELgZ36JeqQdt6dhw9TDJy+30lWVI6v9U4O8T4oJqNJQ8tacZ57rHZ6LBslz+29U/0vHYunQ7kMj+WllJ1oOTNmf8Rai2cCy+rVuuFesEqmZV54P8l1bZf40OHpMU20tbF7PMAcs7LPFzPK721+lHQH86/AQ). 

I followed the SandCastle example and added a line of code to change the scene from 3D to 2D mode and got this error:

**An error occurred while rendering. Rendering has stopped.**

TypeError: Cannot read property 'longitude' of undefined
    at GeographicProjection.project https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:4137:26
    at Object.Transforms.wgs84To2DModelMatrix https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:28435:40
    at updateNodeHierarchyModelMatrix https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:150557:31

Below is the complete code:

```js
var viewer = new Cesium.Viewer("cesiumContainer", {
  terrainProvider: Cesium.createWorldTerrain(),
});

viewer.scene.primitives.add(Cesium.createOsmBuildings());

viewer.scene.camera.flyTo({
  destination: Cesium.Cartesian3.fromDegrees(-74.019, 40.6912, 750),
  orientation: {
    heading: Cesium.Math.toRadians(20),
    pitch: Cesium.Math.toRadians(-20),
  },
}); 

function flyToArizona() {
  viewer.scene.mode = Cesium.SceneMode.SCENE2D;
  viewer.flyTo({   
        destination:  Cesium.Cartesian3.fromDegrees(-114.11, 32.8, 110000)
  });
}

setTimeout(flyToArizona, 7000);
```

**Comment by ebogo1** [comment] 2021-04-22 22:28
Duplicate of #8933.

Thanks for posting this issue! This appears to be a variation of the behavior caused by toggling view modes when OSM buildings are in the scene (see the above issue I linked). Please post any additional feedback about this there.

**Closed by ebogo1** 2021-04-22 22:28 UTC
