### ISSUE TITLE
An error occurs in ModelOutlineLoader.js, about  triangleIndices in gltf of b3dm

### ISSUE THREAD

**Issue by Fivedogs** [CesiumGS/cesium#10280] opened 2022-04-08 07:33 UTC
![image](https://user-images.githubusercontent.com/65214298/162384354-828355a4-38b3-4b5a-b23a-f1526415ea9b.png)
An error just occured here:
![image](https://user-images.githubusercontent.com/65214298/162384530-c21fdc9f-5c86-4d46-b5ec-68690e9d52c1.png)
This is why it come in to the error point,when the count of triangleIndices and the max value of triangleIndices are both lower than 65534 (MAX_GLTF_UINT16_INDEX)
![image](https://user-images.githubusercontent.com/65214298/162385279-e341aac4-f1eb-41fc-8387-e3a58b3753ac.png)
![image](https://user-images.githubusercontent.com/65214298/162385612-cd785dae-be29-406a-ac3f-bf096df5fb0a.png)
I just want to know what is the function(matchAndStoreCoordinates) doing?And why tranverse loadResources.indexBuffersToCreate._array ,when transform the original triangleIndices to Uint32Array from Uint16Array?
![image](https://user-images.githubusercontent.com/65214298/162385974-0df1eb28-3784-41d1-9aa7-ca0c071841b5.png)
As far as i am concerned, this array was just erased by gltf loading code before，maybe it is a mistake?Because i tried to delete this part, and it is running well.

**Comment by ggetz** [comment] 2022-04-08 13:20
@ptrgags or @lilleyse Any insight here?

**Comment by kring** [comment] 2022-04-08 13:31
This code is my fault, so let me know if you need me to take a look. @Fivedogs it might be helpful if you could provide us with the model you're using, since the problem is probably triggered by something semi-unusual about the particular model.

**Comment by Fivedogs** [comment] 2022-04-11 01:40
Thanks for your reply,this is the model which triggered the problem. If you solve this problem or find the semi-unusual thing in this model,please tell me. Have a nice day!
[3dtileAndGltf.zip](https://github.com/CesiumGS/cesium/files/8460424/3dtileAndGltf.zip)

**Comment by j9liu** [comment] 2022-07-22 14:09
Hi @Fivedogs,

I downloaded your data and tried to load the tileset with `enableModelExperimental: true`, and it seems to load now. Can you verify that it works for you?

**Comment by j9liu** [comment] 2022-08-19 14:59
@Fivedogs I'm closing this issue, since I believe it has been solved with the latest `Model` changes. Feel free to reopen if you're still experiencing issues.

**Closed by j9liu** 2022-08-19 14:59 UTC
Labels: category - 3d tiles, category - gltf
