### ISSUE TITLE
Race condition in unit tests in headless mode

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#11733] opened 2024-01-03 21:57 UTC
in #11718, one commit (and only one commit) had an error that seems to be a race condition in `afterAll()`, See [this CI build](https://github.com/CesiumGS/cesium/actions/runs/7389450070/job/20102319658)

Locally I can reproduce this by running the same command. It seems to happen much more consistently on my laptop.

```
npm run test -- --browsers ChromeHeadless --failTaskOnError --webgl-stub --release --suppressPassed
```

My output (different than in CI):

```
Chrome Headless 119.0.6045.159 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: undefined thrown
Chrome Headless 119.0.6045.159 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: undefined thrown
1.217 secs: DataSources/PolygonGeometryUpdater Computes dynamic geometry bounding sphere for fill.
1.036 secs: DataSources/KmlDataSource NetworkLink: onInterval
0.764 secs: DataSources/ModelVisualizer computes bounding sphere with height reference clamp to ground
0.468 secs: DataSources/SampledProperty mergeNewSamples works with huge data sets.
0.332 secs: Core/sampleTerrain with terrain providers should handle the RequestScheduler throttling the requestTileGeometry requests with a retry
0.29 secs: Core/sampleTerrainMostDetailed queries heights
0.245 secs: Core/CesiumTerrainProvider requestTileGeometry Uses query parameter extensions for ion resource
0.193 secs: DataSources/RectangleGeometryUpdater Computes dynamic geometry bounding sphere for fill.
0.162 secs: Core/sampleTerrain requires terrainProvider, level, and positions
0.156 secs: DataSources/ModelVisualizer fails bounding sphere when sampleTerrainMostDetailed fails

Chrome Headless 119.0.6045.159 (Linux x86_64): Executed 7693 of 14044 (skipped 2) ERROR (13.319 secs / 11.735 secs)

[16:49:53] 'test' errored after 19 s
[16:49:53] Error: 1
    at formatError (/home/ptrgags/git/cesium/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/ptrgags/git/cesium/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:529:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/home/ptrgags/git/cesium/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/ptrgags/git/cesium/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/ptrgags/git/cesium/node_modules/once/once.js:25:25)
    at f (/home/ptrgags/git/cesium/node_modules/once/once.js:25:25)
    at tryCatch (/home/ptrgags/git/cesium/node_modules/async-done/index.js:24:15)
    at done (/home/ptrgags/git/cesium/node_modules/async-done/index.js:40:12)
```

**Comment by ggetz** [comment] 2024-01-04 14:11
I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/11231.

**Closed by ggetz** 2024-01-04 14:11 UTC
