### ISSUE TITLE
There seems to be a problem with the geojson data rendered using the GeoJsonDataSource

### ISSUE THREAD

**Issue by WebHero0544** [CesiumGS/cesium#8790] opened 2020-04-23 09:59 UTC
Hello, there seems to be a problem with the geojson data rendered by using the GeoJsonDataSource, but I don't know why this happens to me? With the same data, I rendered the data normally on the fine print with the l.g.json class.  Here is the screenshot:
![QQ截图20200423175833](https://user-images.githubusercontent.com/17270753/80086401-3a678580-858c-11ea-9825-3022be08d4fa.png)
![QQ截图20200423175930](https://user-images.githubusercontent.com/17270753/80088616-56205b00-858f-11ea-9561-4051d3d9f2d4.png)

**Comment by WebHero0544** [comment] 2020-04-23 10:04
The first image is rendered with Leaflet

**Comment by WebHero0544** [comment] 2020-04-23 10:06
Also, I have the same problem with polygon in Entity. Here is my code:


geojson.features.forEach((feature, i) => {
                const { properties: { value, color }, geometry: { type, coordinates: mulPolygon } } = feature
                mulPolygon.forEach((polygons, i) => {
                    const places = polygons[0].flat()
                    const holes = polygons.slice(1).map(polygon => {
                        const places = polygon.flat()
                        return {
                            positions: Cesium.Cartesian3.fromDegreesArray(places)
                        }
                    })

                    this.viewer.entities.add({
                        name: 'Blue polygon with holes',
                        polygon: {
                            hierarchy: {
                                positions: Cesium.Cartesian3.fromDegreesArray(places),
                                holes
                            },
                            material: Cesium.Color.fromCssColorString(color).withAlpha(0.6),
                            height: 0,
                            // outline: true // height is required for outline to display
                        }
                    })
                })
            })

**Comment by OmarShehata** [comment] 2020-04-23 12:38
I believe this is the same issue as https://github.com/CesiumGS/cesium/issues/8042.  Try setting the arcType to geodesic. 

I'm closing because we can't reproduce without the data source, but feel free to follow up here or on the community forum (https://community.cesium.com/).

**Closed by OmarShehata** 2020-04-23 12:38 UTC
