### ISSUE TITLE
PolygonGeometry UV error

### ISSUE THREAD

**Issue by dslming** [CesiumGS/cesium#11870] opened 2024-03-04 10:08 UTC
### What happened?

Problem with PolygonGeometry UV

error:
![image](https://github.com/CesiumGS/cesium/assets/23415941/fb100239-6bb8-4e42-a73e-5117c875e0c6)

What I am looking forward to:
![image](https://github.com/CesiumGS/cesium/assets/23415941/1639c2b6-8f32-4f31-a907-605ef9d9ace3)

### Reproduction steps

```js
     czm_material czm_getMaterial(czm_materialInput materialInput)
          {
              czm_material material = czm_getDefaultMaterial(materialInput);
              material.diffuse = vec3(materialInput.st, 0.);
              return material;
          }
```

### Sandcastle example

https://sandcastle.cesium.com/#c=fVRRb5swEP4rVp5AYk5YkmWhabUqnbpKnVqp015KtTrmSKwZG9kmFa3y32cCpkCq5YH47rv77nx3PiqFNmjP4AUUOkcCXtAaNCsy/Puo8+IRPcprKQxhAlQ88s9iUXtgTUEA3nK5Aax38sVSpIRrsBaxoEfuXPJyK8VdbpiVrcFbLJDT/mCgiKK7MuqGvh+AXuWBHLomytgTEVOcKpldwVYB6EulSOk9LsMAfQrtJ5xOu6fZPEAVNps/+UFF58ficMwS1WluQWZgVNkvQpPJdQN6/cv4NcGA4cYKRFDoM10PUO+tvpTzitpTUAMsiZAt/o4JIikQEY8agBij2KawNYhQQ1KlwKXqFXFdaYZRL52vN8ETW5r2M8Fzv+Y6VH+H/tUyYkAxwvtX+tlo3VVSslGMdpLSslAUIvTsFMdMX7M/LV8lbMG0TF3wRuTFe+ij5HeJ3rrCCXMn5SbIFaSk4O+x+sxnQzYH44SlaaGrdu6BTvtuWJuqdqfeCkyhREvSww9OeG46emj+jSJC88K+KRNZoYCg7kVQ9yJXLGOG7QeTde/Urg8KOBANw97bcTm+TTdGuhR0p6SQxQDZnjo+DnVPjiXPgahK0xu+75yzXEuWPBQqJXbuWjOvbZurTdSemmr4QW8Ee6umrYHGJEm8VnTGCHEwiIlUVpvm0NS9kjGXwurC8AueLhfh9OvnZTibLxZhz4YYazNd4mW4nIWLSWUZLsOWvMmFksyuJpzy8pd8v1AC2tjXWq2G6P/LynMJBW1Y+w4n9Q9P/KClLFTDN3Gz4p+NgtFKm5LDhTP7xrJcKoMKxT2Mxway3FKCHm8K+hcMplq7EV2Nu66rhO3tpjn/YMsjyonWFkkLzh/YK8Sji9XY2p+4ckkSJrZ3e1CclJXZLry4rZUY49XYih97Gin5hqgB8z8

### Environment

Browser: chorme
CesiumJS Version: 1.115
Operating System: windows 10

**Comment by engineerhe** [comment] 2024-03-05 05:33
@dslming 
Cesium is a large project, and for some fundamental issues, it's advisable to seek help from the community[https://community.cesium.com/], where many advanced experts are willing to assist you in resolving problems.

**Comment by ggetz** [comment] 2024-03-05 14:16
Hi @dslming, I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/11767. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

There's a workaround linked in that thread which you could use for the time being.

**Closed by ggetz** 2024-03-05 14:16 UTC
Labels: type - bug, needs triage
