### ISSUE TITLE
GeoJSON renders incorrectly

### ISSUE THREAD

**Issue by WebHero0544** [CesiumGS/cesium#8789] opened 2020-04-23 09:38 UTC
Hello, I threw an exception when using the GeoJsonDataSource to load a geojson file. The geojson file I loaded did not have any errors in format, but it reported an error. The error screenshot is as follows:
![QQ截图20200423172103](https://user-images.githubusercontent.com/17270753/80082437-f8881080-8586-11ea-9d5e-c33dfd86d91a.png)
![QQ截图20200423172115](https://user-images.githubusercontent.com/17270753/80082444-fb830100-8586-11ea-9f60-c692f06a51df.png)

This is the geojson file address that I used:
[cs.zip](https://github.com/CesiumGS/cesium/files/4522502/cs.zip)

**Comment by OmarShehata** [comment] 2020-04-23 12:53
The lines work if you render using rhumb line as shown here: https://github.com/CesiumGS/cesium/issues/8042#issuecomment-519591381.

It then crashes after a few seconds though. I've attached a simplified version of the GeoJSON with only one MultiPolygon which does not crash but does not seem to render correct:

[cs.zip](https://github.com/CesiumGS/cesium/files/4522576/cs.zip)

On first load it seems correct:

![image](https://user-images.githubusercontent.com/1711126/80101724-cc956c80-853f-11ea-9fce-0c9f76349696.png)

but after a few seconds you get this:

![image](https://user-images.githubusercontent.com/1711126/80101774-dd45e280-853f-11ea-905f-1bd94787e126.png)

I'm not sure why.

**Comment by mramato** [comment] 2020-04-23 13:54
@OmarShehata the polyline and polygons render as two different batches, so the reason it takes a few seconds is most likely because the polygon simply takes longer to triangulate. (still wrong in either case, but that's why there is a delay)

**Comment by WebHero0544** [comment] 2020-04-24 00:43
Yesterday, I loaded each feature data in the geojson file separately with the GeoJsonDataSource, some of which could be rendered out, but some of which reported an error.By the way, the geojson file is of the MultiPlygon type.This is the same geojson file as before:[https://github.com/CesiumGS/cesium/files/4522576/cs.zip](url)


Another problem was that I used the geojson data above to render it with entity.polygon and set the arcType equal to Cesium.ArcType.GEODESIC.The result is the same problem with the GeoJsonDataSource.But there is no error here, the program can run normally, the following is the code and screenshot:

`geojson.features.forEach((feature, i) => {
                const { properties: { value, color }, geometry: { type, coordinates: mulPolygon } } = feature
                mulPolygon.forEach((polygons, i) => {
                    const places = polygons[0].flat()
                    const holes = polygons.slice(1).map(polygon => {
                        const places = polygon.flat()
                        return {
                            positions: Cesium.Cartesian3.fromDegreesArray(places)
                        }
                    })

                    this.viewer.entities.add({
                        name: 'Blue polygon with holes',
                        polygon: {
                            arcType: Cesium.ArcType.GEODESIC,
                            hierarchy: {
                                positions: Cesium.Cartesian3.fromDegreesArray(places),
                                holes
                            },
                            material: Cesium.Color.fromCssColorString(color).withAlpha(0.6),
                            height: 0,
                            // outline: true // height is required for outline to display
                        }
                    })
                })
            })`

The geojson object above is the data in the geojson file.


![QQ截图20200424084221](https://user-images.githubusercontent.com/17270753/80163080-97545180-8607-11ea-8d1a-92440c6e5aa3.png)

**Comment by hpinkos** [comment] 2020-06-12 17:32
Because this is a rhumbline error, I'm going to close this as a duplicate of https://github.com/CesiumGS/cesium/issues/8042

@WebHero0544 I'll add a comment to that issue so we can check the file you posted when we fix that issue.  Thanks!

**Closed by hpinkos** 2020-06-12 17:32 UTC
Labels: category - data sources, category - polygons/geometry, type - bug
