### ISSUE TITLE
Incorrect polygon triangulation

### ISSUE THREAD

**Issue by bagnell** [CesiumGS/cesium#4003] opened 2016-06-06 18:35 UTC
Triangulation is incorrect when vertices or edges or holes are shared with the outer ring.

[sample.kml.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/301075/sample.kml.txt)

**Comment by hpinkos** [comment] 2016-07-06 13:07
Incorrect triangulation when two holes are touching
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/eVnwMOC670w
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var whitePolygon = viewer.entities.add({
    name : 'White polygon with holes',
    polygon : {
        hierarchy : {
            positions : Cesium.Cartesian3.fromDegreesArray([-95.0, 30.0,
                                                            -85.0, 30.0,
                                                            -85.0, 40.0,
                                                            -95.0, 40.0]),
            holes: [
                {positions : Cesium.Cartesian3.fromDegreesArray([-87.0, 32.0,
                                                            -86.0, 32.0,
                                                            -86.0, 33.0,
                                                            -87.0, 33.0])},
                {positions : Cesium.Cartesian3.fromDegreesArray([-88.0, 32.5,
                                                            -87.0, 32.5,
                                                            -87.0, 33.5,
                                                            -88.0, 33.5])}
                ]
        },
        extrudedHeight: 0,
        material : Cesium.Color.WHITE.withAlpha(0.5),
    }
});

viewer.zoomTo(viewer.entities);
```

**Comment by pjcozzi** [comment] 2016-07-06 13:17
Did this work in 1.22 before earcut?

**Comment by mramato** [comment] 2016-07-06 13:27
To my surprise, yes: http://cesiumjs.org/releases/1.22.1/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=48aa32a4ea19b9cb7197c98f1c39590b

**Comment by mramato** [comment] 2016-07-14 14:13
@bagnell can you create an issue for earcut with the sample @hpinkos posted.  My hope is this gets fits "for free" next time we update earcut.

**Comment by dzungpng** [comment] 2021-03-22 21:12
It looks like this issue is no longer present in Cesium 1.79: [Sandcastle ](https://sandcastle.cesium.com/#c=rZTfS8MwEMf/ldCXdTDT6ZzOWYcyBQVBQdEHu4fYnmswTcYl7azi/266tjo3X4TkoTR39/3cj5YrGJKCwxKQnBAJSzIFzfOMPqxsfideXadKGsYlYKd7HMlIFla1TLmBWyXKuZJWW0MoSMMNB01ZkvgfkST2SJYBGZPOY6Ugi0ay5CYlqRKgO706rvWMSSOsTsoBGcZp+dtcx2ubS0ltXU3ZU4bGvjE5oC+osnOYI4A+Q2Sl/7RzNKT9Hhn07fM36b9nZ+SYtO+AdPRNmnU3WKsxj8nTdoaPfw9xdLhqfc9B6weOSQMHpMOWNOt+9pzMa9R0OXRUmzvSwAFp1JLsvLZZsx/T+jThzWCeQHIJfJ6aMVn/bBkzgJyJtfkqoZA+Xl7dX9Bqa5yJRcr8Ph22v7lN/NkspnoLvSuV3St/Yyd1j72eF2pTCpi0+U55tlBoSI7CpzQwkC2ELUAHz3n8CobGWlfkKjQM1qVhwgvCk5PI21iRkUdiwbS2npdciDv+DpE3CQMbvyUViiVczm8KQMHKKizdnVzXRkppGNjr30qjlHhmuEH+Ag)with Hannah's code snippet from above.

**Comment by mramato** [comment] 2021-03-22 22:00
Thanks @dzungpng. I confirmed that original sample.kml is also loading correctly.

**Comment by cesium-concierge** [comment] 2021-03-22 22:00
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/eVnwMOC670w

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/4003 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed** 2021-03-22 22:00 UTC
Labels: category - polygons/geometry, type - bug
