### ISSUE TITLE
Clouds don't work with WebGL2

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#10911] opened 2022-11-17 20:16 UTC
As demonstrated in this [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=zVltb9s2EP4rnL/UBlTZzkuLuW62JS26AVszJGsbu+4HSjrHRCRSI6kk7pD/viP1YlqxncRx4haoId47n7ujjkoouNLkksEVSPKWcLgiR6BYlvifLa05aoR2fSS4poyDHDU88t+Ih7iGa32caoYmeoZE8J+EfzNQ+gsE5/FOj2iZgWc4N/h703pj9dChCoED+ssd+3ZZMVOhmLGK/CKWIyo1PlG+64+lSN7BuQRQTWP4ZXdn1++83tt71f3Zetrb8zv7nd3XnVd2ud8ZceN3xMcZD63Zc9BHIhayGZrfjzSBVh6+BJ1JXjk13K+VjK/FpzQFeUQVNFvf0OTNiLfb5J8JKCBcMPxNqURJDVIRKoEo0EQLEsGYZrH2SJBpElJOAiDhhPJziKwFFEmliLIQSMTGY5DAUS4WWYQRKdRUPvldXMElSI/oSemMKVSDUCRppiHyrCklUAAZ6IUL7Tgi0ZTThIU0jqd+CbT1oRBmi7+fSpYg8JegfBpFFl2nHo6MMGISg0WxWSTcxvIOsDbiHum+8jueQz8ejxGD3oI0Dt+fHOeF0Srz48T09wzHt3lqFEYOX5ie/EWvWZIlp+w7OOVl2Wc9srM/Ww4wnh27TGY6MxmHuFByiMRcEvMRgTyNWVi6JAg1G5MxjRUucr6yqcHUMZP5TI4p5lOMc2ocs1QJFtngckMdfzev0ECy84nmoLCLugV+tup6ZNT4MmEasOUqIgp9nZFR4gSryD58wJ7g+eNhnBXcAboWV6UAnY4a30wn1gFHmPNisJm3iJdd2KueZtD25gqjzOpOM099LYV+nhxvBXNgeK16BhZ72V3ixU2yd6fI4G6R4SyoIh2zg6OmZfm5aJHduoRTQ+SX2yBYeg8PsyL/bk3UhWe88kwd8QKkCy7CC5FpX0saXtTDnB2/Wog4oObAj0SYJVi0Pu7tfQzm8XD6BzZ/o5AZNYxa3T5N03h6yHjE+Lmq+/FK+wtjM9sz3o4DBfKSBjHc1h81FvU7hmKVVRaoULIAmtWR3sRK+Uyx6lvliwjbs3mIYQDlM2bFXVakZR8sqas3K7UHq7UHhfZNfuw9EpuzB6GRp/3S0DDIj1kS4Ku9knrj9EK+lflRwOlwa8JzRf1prv/oHQ22syN3K9debvHxO3Kr5qn25fhYsrvyrCS5QW+ufF19f7qC9z1nlc5NZy2s/1q71ptt7craQMu4bfgjpOM2yNfefVP1POlY3habTcfwR0/Hql6xgbjpeAwozoiw+TddMWJUmC2cQKr84sCKF4wlFsyQsrFX2YN3u3A38xXwmIDsJLdGQFYPA6pGxM2FNJv31ohrpnwHWsVNPETHkvqxEBe/6WY1+S/pn92OR8z/l91OKzfT8Bp9pacxHJTF8ytLUiE1yWTc9P22hiSNKRpoB1l4AdoPlSrrrt92VfsRuyQservgCwRujiqFnHEWx/loeNBvo/wt1VhQM6Me4905Nrefg/6ke/BnTvR9v9/G5WLNav6tdtLXJkXV0hACEU0dgiHJubWhRAen9qi9wgOZ4IlMTMT9NtJvS85TkMY4Xu+JnqZggJhAeBGIa0Qgopq+DHACL8kQ9cjiqbnupu4ZCfLemzhbK3BpPkJg1AnjuNr3O+aZXpvnjl0oDSmuunbh7s0escXOzor30KcUJZD4wvp44eGt22SmR366FwD14Mx3LBMCypoQVgfwMFePw3qwRawH28Z68FxYFzZtV26rvOc+XiwEfjPIzl9LngLAwdYBHDwTgIOnAXC4dQCHzwTgcGMAntjRmdjZ+UlerHOz+abO+LWjnU92x0l21801MpYdsMb1XQf8qj2vd6znXu9jf11M7ey9BNO+AvO3i7nIRPnnq/zbegFJsbRDZa50sG5Ah9X8vZ1MOx+Ln7Cp3SvKAzOJy7khGtfOlO2O5v8D), `CloudCollection` does not work when WebGL 2 is enabled due to a shader compilation error:

```
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:5: '=' : global variable initializers must be constant expressions
ERROR: 0:6: '=' : global variable initializers must be constant expressions
```

**Comment by ggetz** [comment] 2022-11-17 20:36
@sanjeetsuhag Is this a duplicate of https://github.com/CesiumGS/cesium/issues/10739?

**Closed** 2022-11-17 20:39 UTC
Labels: type - bug, category - graphics, webgl 2
