### ISSUE TITLE
FlyTo final position depends on duration in 2D mode

### ISSUE THREAD

**Issue by a-milenin** [CesiumGS/cesium#12325] opened 2024-11-22 07:35 UTC
### What happened?

camera.flyTo goes to different position depends on fly duration zero or not.

### Reproduction steps

1. Rotate map
3. Click FlyTo (0)
4. Check the final camera position
5. Rotate map
6. Click FlyTo (1)
7. See that final camera position with fly duration 0 and 1 are different

### Sandcastle example

https://sandcastle.cesium.com/#c=jZFBT8IwGIb/ypdd6JKlQxIuOBZ16klCIotcdinthzZ27dJ2ECT+d7fCEoMc7O17+zx925Qb7TzsJO7Rwhw07qFAJ9uavoWMVBEPc2G0Z1KjraIEjjVrFkbg5HE24Ishoa/L8r58SsBx1NhnM5h8x7eVrjQPbVt1KE1XRkRrmZdGxzDPz3egnNVoGQ0MOYJA56UO1OwCaYyTfb4uEhhOgnPRimnBmfMKKROiNEZtmH1ovTeajJ5DPxnHowRI6D61jeNe/oc6ptNLlU6DHCVR5vxBYV5pCOtO1o2xHlqrCKWpx7pRzKNLNy3/RE+5c73Yo1n6W82E3IEU8ysfAFwx57qdbavUSn5hFeVZ2vF/VGWYkPp9uUOr2KHHPm7yl1NIKc3Sbrxu+tPDL07+AQ

### Environment

Browser: Chrome
CesiumJS Version: 1.123
Operating System: Windows

**Comment by ggetz** [comment] 2024-12-10 19:43
Thanks for the report @a-milenin! I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/2469. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2024-12-10 19:43 UTC
Labels: type - bug, needs triage

**Comment by andrewda** [comment] 2025-03-13 01:50
The divergent behavior between `duration === 0` and `duration > 0` appears to be occurring because of this line in `setView2D`:

https://github.com/CesiumGS/cesium/blob/5eaa2280f495d8f300d9e1f0497118c97aec54c8/packages/engine/Source/Scene/Camera.js#L1344

Removing this condition causes the same unintuitive "drifting" behavior with any `duration` value (and also creates a whole host of other issues while interacting with the map).

The root of this issue is the puzzling 2D coordinate system. Camera height is not represented in `camera.position` or `camera.positionWC`. Instead, the "height" axis (z in `camera.position` and x in `camera.positionWC`) is always 12756274, with the frustum being used to define the zoom/height of the camera. However, this z value _is_ used by `setView` to set the new camera frustum (zoom):

https://github.com/CesiumGS/cesium/blob/5eaa2280f495d8f300d9e1f0497118c97aec54c8/packages/engine/Source/Scene/Camera.js#L1354-L1366

And herein lies the primary problem with `camera.setView({ destination: camera.positionWC })` (and `flyTo`, by proxy): The camera destination is not really being set to the camera's current position, because `position` and `positionWC` are missing height information needed to place the camera correctly.

This can be seen with the following code -- here the (x, y) coordinate of the camera stays the same, but it jumps up to a height of 12756274:

```js
viewer.camera.flyTo({ destination: viewer.camera.position, duration, convert: false });
```

For the time being, I believe this would be the minimal change to the provided Sandcastle that works as expected (i.e., camera stays stationary with `duration === 0` and `duration > 0`):

```js
const viewer = new Cesium.Viewer("cesiumContainer", {sceneMode: 2});

const flyTo = (duration) => {
  const destination = Cesium.Cartographic.toCartesian(viewer.camera.positionCartographic);
  viewer.camera.flyTo({ destination, duration });
};

Sandcastle.addToolbarButton('FlyTo (0)', () => flyTo(0));
Sandcastle.addToolbarButton('FlyTo 0.5', () => flyTo(0.5));
```
