### ISSUE TITLE
After the upgrade version is later than 1.107.0, setting two ImageryProviders when setting imageryProviderViewModels will cause an error 

### ISSUE THREAD

**Issue by iamsee** [CesiumGS/cesium#12079] opened 2024-07-12 07:13 UTC
### What happened?

After the upgrade version is later than 1.107.0, setting two ImageryProviders when setting imageryProviderViewModels will cause an error 
![image](https://github.com/user-attachments/assets/fa0a115d-0f4e-449d-b26a-9f190930a0af)
![image](https://github.com/user-attachments/assets/36cd6c89-7f1e-45ed-b315-339aa28a7cad)

I would like to know how to set up multiple at the same time after version 107
![image](https://github.com/user-attachments/assets/6a69ec58-569c-4525-a9f6-4e96a519039a)

### Reproduction steps

1. upgrade to 1.107.0
2. set ImageryProviders 

### Environment

Browser: Chrome
CesiumJS Version: 1.107.0
Operating System: Windows x64

**Comment by ggetz** [comment] 2024-07-16 12:47
Thanks fro the report @iamsee. This is a regression and should be fixed before the next release.

**Comment by ggetz** [comment] 2024-07-30 15:31
@iamsee I'm actually having trouble reproducing this particular issue. Would you be able to provide a [Sandcastle code example](https://sandcastle.cesium.com/) that raises the error?

**Comment by ggetz** [comment] 2024-08-15 14:30
I'm closing this issue due to inactivity. If you believe this is still an issue, please feel free to re-open. Thanks!

**Closed by ggetz** 2024-08-15 14:30 UTC
Labels: type - bug, category - widgets, type - regression, needs feedback
