### ISSUE TITLE
GeoJSON Point types don't map correctly in 2D if clampToGround is true

### ISSUE THREAD

**Issue by mfarmer-ara** [CesiumGS/cesium#11997] opened 2024-05-21 15:27 UTC
### What happened?

When using clampToGround, points in GeoJSON files do not appear in the expected location when using 2D.

The focus ring appears in the correct location, but the actual point does not.

### Reproduction steps

1. Added a GeoJSON file to a map, either via programmatically loading (external or local source) or drag and drop.
2. Viewed points in 3D, noted they were in the expected locations
3. Clicked on a point in the US
4. Switched map to 2D, noted that the point moved to the middle of the atlantic, but the focus ring stayed put in central US.

Points close to 0,0 don't appear to change position. Points further away from 0,0 show significant position changes for the points.

### Sandcastle example

https://sandcastle.cesium.com/#c=1VRNT9wwEP0rVnpZpMVJBJdCWCECRaoqtdICF8zBmwxg4XiisbMoRf3vtckGstmVQCqHkkvm473x09NolpLYUsEjEDtiBh5ZDlY1Fb96rk1EVDznORonlQES0c6hMMJ0HF5KJ+fYkEdxWZYTYVg/4Rzwu0Vz+oLgGmWHYOyJici1NYjowEffQLqGIEetoXAKjYimHY757m3XtQF73Zef+oBtmzTgh/4dYAWO2oAZENepv1AZt0YM/QKRSmWkG73ffQlPp+NKMizcvCZ/1iTVhDWQU93YsSjl9EpVsqGokvQAtGvbaoH6DVCBGqnDfDlN9/K9XEQDRX34Ku3/sJWx3TRJpuPi/sdam4NxJDW7nL/HvpOvZyfp/iexz7u3sZne1A82MH3Pbqb/upsrmb3EFzmFllV9geeEjSkPmKMGVsjw2xEmHKpoGmXWtRpmPe1YVTWSYw3pCeexg6rWwcd40RQP4HhhbSAGaBYPqVmplkyVR1tOYtBire/cNlrP1W/vzyyLPX6DGk6gMnc/l0BatgF2n85+dEXOeRb7dDvTIeqFpNHkvw

### Environment

Browser: Edge/Chrome
CesiumJS Version: Tested in 115, 116, 117
Operating System: Windows 10/Ubuntu 20

**Comment by ggetz** [comment] 2024-05-31 13:45
Thanks for the report @mfarmer-ara. I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/8307. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2024-05-31 13:45 UTC
Labels: type - bug, needs triage
