### ISSUE TITLE
when I run getElevationContourMaterial, I got an error

### ISSUE THREAD

**Issue by libofei2004** [CesiumGS/cesium#10893] opened 2022-11-07 17:13 UTC
when I visit https://sandcastle.cesium.com/?src=Globe%20Materials.html, I got an error:
![捕获](https://user-images.githubusercontent.com/10001548/200371794-57a747da-69d8-4db7-a5f4-b9e4ff20f292.PNG)

machine:intel i5

 gpu : gtx 650

Browser:chrome 107

Operating System: win7 64bit

An error occurred while rendering.  Rendering has stopped.
RuntimeError: Program failed to link.  Link log: Could not pack varying v_depthFromNearPlusOne
Note: Additional non-conformant packing restrictions are enforced on D3D9.

Error
    at new RuntimeError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:12642:13)
    at createAndLinkProgram (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:67392:11)
    at reinitialize (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:67545:21)
    at initialize2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:67540:5)
    at ShaderProgram._bind (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:67599:5)
    at beginDraw (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:164028:19)
    at Context.draw (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:164114:5)
    at DrawCommand.execute (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:65392:13)
    at executeCommand (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:200919:15)
    at executeCommands2 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:201106:11)

**Comment by ggetz** [comment] 2022-11-09 13:47
Thanks @libofei2004! I'm not able to reproduce. Would you mind going to https://webglreport.com/ and taking a screenshot of what you see?

**Comment by libofei2004** [comment] 2022-11-22 10:47
@ggetz No, the driver has installed failed.

**Comment by libofei2004** [comment] 2023-03-08 14:42
> Thanks @libofei2004. Do you have the latest drivers for your video card installed?

**Comment by ggetz** [comment] 2023-04-12 18:37
Closing this as this appears to be a driver issue.

**Closed by ggetz** 2023-04-12 18:37 UTC

**Comment by qiuuuy** [comment] 2023-12-07 11:14
I also encountered the same problem. How did you ultimately solve it?
