### ISSUE TITLE
Documentation modification for better readability/searching

### ISSUE THREAD

**Issue by hanbollar** [CesiumGS/cesium#6417] opened 2018-04-03 14:27 UTC
Javadocs have a listing of all methods and parameters with short info about them (just like we have for constructors) at the beginning of all docs about any class. Adding this feature to Cesium docs would streamline searching for particular methods / features, since when scrolling through longer items like the camera, it can become incredibly easy to miss certain methods and much harder to search for specific methods to use if you dont know their name.

Example: [boolean](https://docs.oracle.com/javase/7/docs/api/)

**Comment by hpinkos** [comment] 2018-04-03 14:32
@hanbollar just to clarify, this would be similar to a table of contents at the top of the page?

**Comment by hanbollar** [comment] 2018-04-03 14:53
@hpinkos yes :)

also this is the proper link for the boolean example i tried to link before:
[boolean](https://docs.oracle.com/javase/7/docs/api/index.html?java/lang/Boolean.html)

**Comment by ggetz** [comment] 2024-08-19 15:19
I think this is duplicate of https://github.com/CesiumGS/cesium/issues/3507.

**Closed by ggetz** 2024-08-19 15:19 UTC
Labels: category - doc
