### ISSUE TITLE
implement smooth zoom with mouse wheel

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#11061] opened 2023-02-01 02:08 UTC
I found inertiaZoom in `ScreenSpaceCameraController` is not working.
Then I found this issue is still open in #4537 
so I implement it. by define aggregator
this pull request is in #11062

**Comment by ggetz** [comment] 2023-02-03 15:43
Thanks @jiangheng90! We're taking a look at your PR now. In the meantime, I'm going to close this issue since it's a duplicate of https://github.com/CesiumGS/cesium/issues/4537.

**Closed by ggetz** 2023-02-03 15:43 UTC
