### ISSUE TITLE
Imagery test timeouts

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8817] opened 2020-05-01 14:19 UTC
I'm seeing a bunch of imagery tests time out when running locally and the problem doesn't fix itself if I go back as late as CesiumJS 1.60. I'm on Windows, testing with Chrome and Firefox. I don't think it needs to hold up the release, but I marked the issue as `priority - high`.

```
Core/Resource fetchJsonp returns a promise that rejects when the request errors
Core/VRTheWorldTerrainProvider conforms to TerrainProvider interface
Scene/ArcGisMapServerImageryProvider rejects readyPromise on error
Scene/ArcGisMapServerImageryProvider raises error on invalid URL
Scene/BingMapsImageryProvider rejects readyPromise on error
Scene/BingMapsImageryProvider raises error on invalid url
```

![Capture](https://user-images.githubusercontent.com/915398/80811500-0562c080-8b94-11ea-8d7f-d40617bb6785.JPG)

**Comment by likangning93** [comment] 2021-01-04 19:40
I'm seeing these in the release process for 1.77 as well, on Windows in Chrome, Firefox, and Edge (Chromium). @sanjeetsuhag wasn't able to reproduce, though, which is interesting?

**Comment by ebogo1** [comment] 2022-02-21 22:07
I don't think these have been an issue for the past few releases and I was unable to reproduce on Windows or macOS in Chrome, Firefox, or Edge. I'll close the issue for now but we can revisit this if someone notices the errors again.

**Closed by ebogo1** 2022-02-21 22:07 UTC
Labels: test failure, priority - high, category - terrain and imagery
