### ISSUE TITLE
GPU memory is freed but CPU memory is not. Basically once a tile is created it is never destroyed, only its contents are destroyed

### ISSUE THREAD

**Issue by anastasiya-liapko** [CesiumGS/cesium#12049] opened 2024-06-26 16:25 UTC
### What happened?

Hi!

We encountered an issue using a large tileset. The fact is that the tileset contains many tiles and the CPU memory occupied by the tiles is never freed and continues to grow until the limit is exceeded (in chrome jsHeapSizeLimit=4GB) and the application crashes.

We use external tilesets, so the memory will not fill up immediately, but after using the tileset for some time. 

A possible solution is to delete tiles that are loaded but not currently in use in order to free up CPU memory. The same way that tile content is being deleted to free up GPU memory.

Relevant issues:
- https://github.com/CesiumGS/cesium/issues/3453
- https://groups.google.com/g/cesium-dev/c/2ORBapD2kBg/m/bTjY4EPdCQAJ

### Reproduction steps

1. Add tileset to viewer (screenshot 1)
2. Move around the map
3. You can see that the CPU memory grows and is never freed (screenshot 2)
4. After using the map for a longer time and viewing several more cities in more detail, the memory occupied by tiles grew even more and continues to grow (screenshot 3)

Screenshot 1:
<img width="862" alt="image" src="https://github.com/CesiumGS/cesium/assets/27208149/6764b02e-062b-42c4-b76a-015774a6c6ee">

Screenshot 2:
<img width="862" alt="image" src="https://github.com/CesiumGS/cesium/assets/27208149/a9e64821-8e89-4785-92a3-5c0ccfa8a8a9">

Screenshot 3:
<img width="863" alt="image" src="https://github.com/CesiumGS/cesium/assets/27208149/7f04feab-649b-45bd-b701-850e6f0e1901">

The issue can be reproduced on any tileset. Since I can't attach a company's tileset, I made a sandcastle example using GooglePhotorealistic3DTileset

### Sandcastle example

https://sandcastle.cesium.com/#c=bZDBSsNAEIZfZQgeUpAN4k3TIlT0IigonnLodjOmg5OdsjtJqaXv7iZtUbR7m9n///gYJz4q9IQbDDAFjxuYY6SuNe/jLq8yN85z8WrJY6iyyW3lK69hC7vKA7gRocQYURPDbizpieICWsVHkYbxZSUqaWaKSu76/u1QyQceHB1MdOjRrAO1pNRjNLau8yN8CO7BWXUryDEECZMfBWE0LE2+eLApXYMKsNj6JHYDF7uxsl+MmOwyK6NuGWcDYHh31K4lKHSBc2MKxXbNyT0Wy859ohoX48EUoCx+V8uaeqB6euZU4NjGmH4+OuZX+sIqm5VFyv+rDq7km+ceA9vtEFtdzZ4OS2NMWaTxfFNFeGnDH/I3

### Environment

Browser: All
CesiumJS Version: 1.118
Operating System: All

**Comment by ggetz** [comment] 2024-07-01 13:26
Thanks for the report @anastasiya-liapko! I would think this is a duplicate of https://github.com/CesiumGS/cesium/issues/3453, and that this additional context should go there. 

I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2024-07-01 13:26 UTC
Labels: type - bug, needs triage
