### ISSUE TITLE
clampToGround works poorly with Google Photorealistic 3D Tiles

### ISSUE THREAD

**Issue by TheFullUpload** [CesiumGS/cesium#11775] opened 2024-01-19 15:01 UTC
### What happened?

When I use Google Photorealistic 3D Tiles, I need to set `globe: false` (recommended by the official doc).

I want to show a route (gpx file), so I import the file with GpxDataSource :
```
viewer.dataSources.add(Cesium.GpxDataSource.load('track.gpx',
{
    clampToGround: true,
    trackColor: Cesium.Color.YELLOW,
})).then(function (dataSource) {
    viewer.zoomTo(dataSource.entities);
});
```

I encounter two bugs:
- the `zoomTo()` function don't work (nothing is happening)
- the markers are below the terrain (the route is well placed however)

![CleanShot2024-01-19at15 44 58-ezgif com-optimize](https://github.com/CesiumGS/cesium/assets/133334778/5ed7d473-1e68-42fe-b64e-05a68967b1b8)

### Reproduction steps

1. Add a Cesium.Viewer with globe: false option
2. Add a Cesium.createGooglePhotorealistic3DTileset()
3. Add a dataSources with clampToGround: true option

### Environment

Browser: Chrome 120.0.6099.234
CesiumJS Version: 1.113
Operating System: macOS 14

**Comment by ggetz** [comment] 2024-01-19 19:03
Hi @TheFullUpload, I belive this is a duplicate of https://github.com/CesiumGS/cesium/issues/7044, and is being addressed with https://github.com/CesiumGS/cesium/pull/11604.

**Closed by ggetz** 2024-01-19 19:03 UTC
Labels: type - bug, needs triage
