### ISSUE TITLE
The earth not came out when initialized sometimes.

### ISSUE THREAD

**Issue by AnodoubleA** [CesiumGS/cesium#8449] opened 2019-12-09 09:28 UTC
When we open the web site, we just get background, but earth not come out, whatever how long we wait.

But if we refresh the web site, the erath may came out, but not always.

Not just us, I browsed some other web site by Cesium developed, same issue.

**Comment by OmarShehata** [comment] 2019-12-09 14:59
@AnodoubleA what browsers and operating system were you testing with? Do you see any errors in the console when this happens? What about network errors? Does this issue happen for you in [Sandcastle](https://Sandcastle.cesium.com/index.html?) ?

**Comment by AnodoubleA** [comment] 2019-12-26 06:42
Chrome 78 / Windows 10 / No any error (include net) happend / Just happend in Sandcastle(https://sandcastle.cesium.com/index.html?src=Billboards.html) /

I saw billboard , but no earth. Sometime, a empty black earth cover the billboard.
I guess earth rendered, but no color.

**Comment by OmarShehata** [comment] 2020-05-28 15:46
This sounds like a network issue - if you check your network tab, I would expect to see failed requests for the imagery tiles. 

Closing since we are not able to reproduce.

**Closed by OmarShehata** 2020-05-28 15:46 UTC
