### ISSUE TITLE
Globe appearing underneath large polygons

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#10383] opened 2022-05-16 12:49 UTC
This issue may be a subset of https://github.com/CesiumGS/cesium/issues/4871, however, since there are multiple issues affecting large polygons - it may be helpful to break them up into smaller parts.

| `🟡 178Lon-Rhumb` in this [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=xVrrbtvIFX6VqXcB0YhM8S7Skd0mjrsO4FxgO1sUUYClyLHENUUK5MiJkvVTtP+D9l//98H2EXrmRg5JKZYduysgiWbm3Oabc+acM0qUZyVB1wn+iAt0gDL8ER3hMlnO9Z/ZnDbeidj4KM9ImGS4GO/sPh1nEeMrI5xhYOP8OhtWi1E4x0VYr/IxLEsCOv8qj3EKNF/GGULATnBxmmfThCxjvI+MvjIdksZsKsnOF2G2jxyXzwqqxmRYRBerBXCOd85O3r16Pt5h0zOcTGdEysOfSAGM8UljdlHgEhPK+TrPMGO8YVsYDNDJxatThFM8B/tKdJkXiMyw4CjRxyRN0QSjKWBShATHKCSoWGYkmWMdSQwktUBgvPP716//Brv3fsKATJlE4519voQYXvtomcX4Eg4i7vPZfEESEFVRbYRRWWpBST/r4WQr6yClHwXWn47fvDg+f3kkkKWfJrr0sx5hhG7oPzd9uf9//heZvgHm753NlvPJHwQAmHAnBFTHeojth+QP3f7G81dxeYztf/0XMof+5tOvdgnRQZIspJtH++rFdRQWBL6Fma25jhsYge6YfmBYgev3ke94lm0NdWfoepbnB24fma7nBYbuukPD9izHNt3dyui8SACxNUpOcBgn2fRtQqLZWZ6mmqm79tDwTdexXMv1hqbVR3umbli+45qg1TDcoRP0kaEbhmHbw8CEv3zDGfqB7dcKcRZfFGFWwm0yB41C26uQFMknR3/54vj1xcuLvwvkHjkAgg0uYD+6B1gGP/29t3kaFt/nA3Aqw8AKdA/O2TUNA5zAM01j6Ou241uGZcI8+IXv2p5j6YZvGEPPMbz7+ACcrecMLSfwDMcxAuppzAlMzw4Ce8h8yzVM6gTmMHCByHSswHBc3/0DPcB3N7mAtekKtB7LA3huvVxmEYM7KjBkzjdsd8c80WoEhOyKeoGlUL55yKBxHi0pic7ZJMN4h1PwwkWCpV+H6ZLWLlSeOk/HtNgBVnW1wGRZZIIIZm6aGfwc6oCIqEZMMREWPF+9jMEKTrhXMkpujMqrh4sFnP3RLEljbd3GZQmySzlptaFxA95f4VUfse18QPklejP5lYoDFnDcUhMVxq7A7E4qQTLTdkNPZZwJX7zK8ugqXxKdFGF0pVVlHKVsk4CGdPU8yWiglDVp/xs4kTxPJzTq77jR2g6x1eQS0R2gPx0cIAk/SJVB0jYVDHkzKXFxHU5SrJpKUdDL5aSMimSCteUiBqDgZlpN84y71A2DqCWQLmwWqhjECGv5lfdrcNf8THdbmUx3JCfFtoRP1JHPEH/LZMuzfy95PnBzZcDtPuXnWmns8grBd3U3XdxIu7vqzc22Tvk/QKA0CdmsxBLygDg+AamoeKRwKqspuWovdFinnUuDlMuFUr3ELabPeT6/yDUxgj0kBDahHuo4a5y3xpqfpiomcptUZBm27xmWo3uWO/TNwLUhPfhQLRhQkPiG7xh+4AxhLrAM07R1D4oEF/4EIhttn4k83fJpZvGGUAFBncHzkOv6tuG5tmsHpg/5EBIRF7xtzhEeU/lLCxrRw8Af6I7O8Dy/xqwlytMYLTgRXWyhrReM8hmYzYGvr/ZmvqBOExYl/muah6SOJb1JxWVw/tk3+WYK/Tq7wjjWhLsI65UEO0vABYpotmoddgp3V3T1tsgXuCArJZhp39eHNFIuUx5VUpI0tpWyN1ndIpMR3ZEjEvYtYgRVV0qjFDgJ08tNghqEu2iArK4spXj4piiFTkqqZYkMrKAtHO9EHoVWE6Nu+OmXRT5/gacFxuWzoghX2nuVnjntRb5Ap/iSIO3133abq+3j2etC1G9j/6Sz9X5H5fOckHwutJ4/hNa97bWesfjQzo9vUfvkgdRSfIXO1w+h8xaAPygqahe/6SO4MHBdcs/hEiuSMK1uvqM8zQv97PhFt8y9Z7C3nLj2eSEYHbBsXr+joD9LNc84hS7X6gtarrDCe/P2ZB0ubsND2oOCeDHsvih06/TWPSwltKYVSe0qA1U15EeoBfOPunwV48UGXAgSO5lFxNVREvos+csXeT9XN/A2+fbHLyJTL/IyYcX9JwCnO7taO/v5RkK4fd6tpMz4SkMwpVInCuCodGzf9vGmr93ydRq+H79szBmybWx3gmtYxJrkaDWIKkNjqaJvtI0NcmVFUldBphKKSUkjnVkl4XOSou28KmVzjXPQOu+XqmjIUwxbmWrgeKzzkY+91FFLiFAamrSpIDmC2l4+clMNeoPubU1XhlAHQXGPcVbOcgJ0VfMDJcbxNXw5TUpCI0LrAQ/ER9bro/o2wUpDg3Uqld4WvaiHfvsNsYmjPOZXiDesrptbXuHZ8WAZYT31CV/vFLjjrCdYKPkToN8uAntwQ3diEOZge+uWVpuXPtMlCJZ1lmwfn4pkEaFdjZS4M0tj9RsWbBm9XVZ6O9azaxywalxah79Yc/i+0Tr8Db/PqATSK5UrGGmMsFGkSmfKrkP6Y4V0Ezp82qS5TFL8GkBDNJ/V8sc7Lbo0ya42P9r0wl6dsCmpTqMC6sWYGipVwIHoi2zaq0Uzi3SSP0/zSZWPtQmMGmlYyJwVmBaj785OhXrezMKYszztcERpEl1pSi3RspL3MgoBRwrcmJyBk8AhcIpm1NcwVQ269JM2e+fGaPPeiDZtp78zKskqxYfSlL8k80VeELQsUk3XBwTPF3AL43IwWUZX0CtHZVnb/YN4hlFRo8XOtMghy+9FtELaRz/Yhm3bnoLTJC/AzL0CgmsJ2cldfFIWF2A9xFx7eh4W0yRjs40V2MpoIPcwipNrlMQHa36QRFEaliWsXC7T9Dz5jMc7h6MB0DfYqPOA8jfXuEjDFSWZmYenfFLX9dEAhl2u6jWKwTgi9B1HIDoi9A6p4B2R4rDeEyyCo6clpLcD61D1I9G1IP7UViosAzKrpQ0qcXS+VjQikzxebdQaHx6xzI2qbA/scYtENWeUZIslQQRyLGwXLrEpwIfmSQajPdM36CD8BAP+HbxuQQfwFXr/cG8C9RyM2XvQfrsKEe9E79gzwT7qMVU9geV6A+iDK1UDpwgjdys1DYGN7SoofgsqUYt8D1JBDVSwNU5C7yPDJLTcG6W6JaPF2neAVENke7dj1CgoHwuihpL7IyT70QcDaJtgU0voR8NH0XFveKBPRbSGvyMycZKDUcyQg0ZrrNoZzTAkr3hfNg/tLafhBKeH8n9TjAZ8vL1a8aPWPXSyXzC7Cu8CnGisn03oS+pxmiaLMk/ih3Ew7CoOhu31x887q8dyLi793m51LJo5xGH6P8LSbCMfC56mlnvDxJ9Yytvg4b9L8qKn9VPlOuM4SXvreRbNKLKd3Q+4rObkZEkIFELARKtqkN18FdJ2QcrvX//xn9GAU24BAHytyiP4Lqo1WdZxmv8B) |
| - |
| ![Screen Shot 2022-05-11 at 10 11 18 AM](https://user-images.githubusercontent.com/5172619/167870392-392dda82-3f46-4442-9643-65a1d8b27098.png) |

This band that appears is showing the near side of the globe

![poly](https://user-images.githubusercontent.com/5172619/168599735-175b915a-8f58-458f-aa6a-02946f8c5810.gif)

**Comment by sanjeetsuhag** [comment] 2022-05-17 16:25
Another thing I noticed is the difference in the appearance of this "band" based on the longitudinal extent. In the examples below, there are two polygons: one of extent `179°` and `181°`. When the extent is >180°, the polygon wraps around the other side.

| `179°` | `181°` |
| - | - |
| ![same](https://user-images.githubusercontent.com/5172619/168861187-b78bad1c-07b7-4817-b0bb-d5afb7757862.png) | ![opp](https://user-images.githubusercontent.com/5172619/168861212-eaea9ce5-0eee-4c98-980c-88d66d5a6796.png) |

**Comment by sanjeetsuhag** [comment] 2022-05-17 20:11
I forced the use of  planar extent by editing the snippet below:

https://github.com/CesiumGS/cesium/blob/d6aa763eeb656674ca088117ae9302a8541bdc86/Source/Scene/GroundPrimitive.js#L804-L812

and achieved this result:

![poly](https://user-images.githubusercontent.com/5172619/168901441-a4a07f20-9d0d-4bc1-9ae5-ba6939578328.gif)

**Comment by sanjeetsuhag** [comment] 2022-05-18 13:29
A couple more findings using the presets in this [local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=7Vpbb9vIFf4rU+8CkhGJ4v3iyG4Tx10HcC6wnS2KKMBS5NhiTZECOXKiZP0r2vegfet7f9j+hJ65kUNSimUn3rysgSSemXObb86Zc84wUZ6VBF0n+D0u0D7K8Ht0iMtkOdd+ZnP9yU7Exod5RsIkw8VkZ/fxJIsYXxnhDAMb59fYsFqMwjkuwnqVj2FZEtD5F3mMU6D5NMkQAnaCi5M8u0zIMsZ7SB8o0yFpzKaS7GwRZnvIdvisoGpMhkV0vloA52Tn9PjNi6eTHTY9w8nljEh5+AMpgDE+bswuClxiQjlf5hlmjDdsC6MROj5/cYJwiudgX4ku8gKRGRYcJXqfpCmaYnQJmBQhwTEKCSqWGUnmWEMSA0ktEJjs/Pb583/A7uFPGJApk2iys8eXEMNrDy2zGF/AQcQDPpsvSAKiKqqNMCpLLSjpz3o42co6SOmPAutPR6+eHZ09PxTI0p8muvRnPcII3dB/bgZy///6HzJ8Hcwfns6W8+l3AgBMuBMCqmN9i+2H5Ltuf+P5q7g8xPY//xsZnr/59KtdQnSQJAvp5tGeenEdhgWB38LM6ju2E+iBZht+oJuB4w+Qb7umZXqa7Tmu6fqBM0CG47qBrjmOp1uuaVuGs1sZnRcJILZGyTEO4yS7fJ2QaHaap2nf0BzL033DsU3HdFzPMAdoaGi66duOAVp13fHsYIB0Tdd1y/ICA/7yddvzA8uvFeIsPi/CrITbZA4ahbYXISmSD7b2/NnRy/Pn538XyD1wAAQbXMD6XT1geBRf4q9zg6Htuabpa4FpB75v+47nDpBrOJbt2hocu2novkM9wbUty4SpILAdJ3A8636e4LuOH7i6GxgeCPHAEXTQHVgB+FvgGLrhmOAdrmb6phvYlu3pge2pyv7wgo4XvC5wlJSww691Bd+yfQhC29QN1zR8g3oCBH1gaY4PkWkHtsE8QTd0UzMNOErT9UzzPp5gQawb4AE+uJURGK5uMVewDF0HRzTNwLUC3Xe5K1iG71i6awdu4P1xIbRcwdSlG+RpWHydC8A17UE0anABuBCMuk89wNA9XwPPMOEygHlIFHAarm1qOjiFB97g3scBwM9c24Nbx9VtWw9o6mFZwYCDDyyPJRtHN2hWoFcFEBm2Gei24zvf0QN8Z5MLmJtqIvOhPIAX2xfLLGJwRwWGUvoV290Rr7z7BITsigaC1dR881BSx3m0pCQaZ5MMkx1OwTsZCZZ2HaZL2sxQeeo8HdPuB1jV1QKTZZEJIpi5aZb0Z9AYREQ14hITYcHT1fMYrOCEw5JRcmNUXi1cLODsD2dJGvfXbVz2JLuUk7YffW7A2yu8GiC2nXcov0Cvpv+g4oAFHLfsi5ZjV2B2J5UgmWm7oacyyYQvXmV5dJUviUaKMLrqV30dpWyTgIZ09TTJaKCUNengCziRPE+nNOrvuNHaDrHV5ALRHaA/7e8jCT9IlUHSNhUMeTUtcXEdTlOsmkpR0MrltIyKZIr7y0UMQMHNtLrMM+5SNwyilkC6sFmoYhAjrOVX3t+Hu+ZnutvKZLojOSm2JXyijnyG+GsmW579W8nzjpsrA273MT/XSmOXVwi+q7tp4kba3VVvbrZ1yv8OAqVJyGYllpAHxPEJSEULJIVTWU3J1XuDBuv0KaNByuVC717iFtPHPJ+f530xgj0kBDahHuoka5x3n72GNFUxkdukIlO3fFeHitM1oUqAUoEWCD60Dzp0KL7u27oPlSHMBVCtGJYGFaXlwJ9AZKPtMxErNiGzuB60RNB48DzkOD6UHI7lWIHhQz6ERMQFb5tzhMdU/tKCRjxqwJ/RCJ3ieX6N2RtJnsZowYnoYgttrWCUT8BsDnx9tTfzBXWasCjxX9M8JHUsaU0qLoPzz77IN1Po19kVxnFfuIuwXkmwswRcoIhmq9Zhp3B3RVevi3yBC7JSgpk+BA0gjZTLlEeVlCSNbaXsTVa3yGREd+SIhH2LGEHVldIoBY7D9GKToAbhLhohsytLKR6+KEqhk5JqWSIDK2gLxzuWR9GviVE3/LSLIp8/w5cFxuWToghX/bcqPXPa83yBTvAFQf2Xf9ttrraPZ9iFaNDG/lFn64OOyqc5IflcaD37FlqH22s9ZfHRPzu6Re2jb6SW4it0vvwWOm8B+J2ionbxmwGCCwPXJfccLrEiCdPq5jvM07zQTo+edcvcewZ7y4lrnxeC0T7L5vXDKvqzVPOEU2hyrb6g5QorvDdvT9bh4jY8oI9SIF4Mu0+M3Tq9dQ9LCa1pRVK7ykBVDfkeasH8vSafyXmxAReCxE5mEXF1lIR+p/jlk7yfqxt4m3z74yeRqRd5mbDi/gOA051drZ39eCMh3D7vVlJmfKUhmFKpEwVwVDq2b/t409du+ToN34+fNuYM2Ta2O8E1LGJNcrQaRJWhsVTRN9rGBrmyIqmrIFMJxaSkkc6skvA5SdF2XpWyucY5aJ33S1U05CmGrVz2wfFY5yO//lBHLSFCaWjSpoLkCGp7+dWLatAadK9rujKEOgiKe4yzcpYToKuaHygxjq7hl5OkJDQi+j3ggfjIegNU3yZYaWiwRqXS26IX9dCvvyI2cZjH/Apxveq6ueWzHDseLCOsp37T0zoF7iTrCRZK/gjot4vAHtzQnRiEOdjeuqXV5qWPdAmCZZ0l28enIllEaFcjJe7M0lj9ggVbRm+Xld6O9ewaB6wal9bhL9Ycvq+3Dn/DB1uVQHqlcgWjPiNsFKnSmbLrkH69lG5Ch4+bNBdJil8CaIjms1r+ZKdFlybZ1eZHm17YqxM2JdVoVEC9GFNDpQo4EG2RXfZq0cwijeRP03xa5eP+FEaNNCxkzgpMi9E3pydCPW9mYcxZHnc4ojSJrvpKLdGykvcyCgFHCtyYnIKTwCFwimbU1zBVDbr0kzZ758Zo895UbdrOYGdcklWKD6Qxf0nmi7wgaFmkfU0bETxfwD2My9F0GV1BtxyVZW35D+IhRsWNljuXRQ55fhjRGmkP/WDplmW5ClLTvABDhwWE1xLyk7P4oCwuwH6Iuvb0PCwuk4zNNlZgM+OR3MM4Tq5REu+v+T8KKErDsoSVi2WaniUf8WTnYDwC+gYbdR9Q/uoaF2m4oiQz4+CET2qaNh7BsMtVvUcxGMeEvuQIRMeE3iIVvGNSHNR7gkVw9bSEBLdvHqieJPoWxB/bSoVlRGa1tFEljs7XisZkmserjVrjg0OWu1GV74E9bpGo5oyTbLEkiECWhe3CNUY/wKF5ksFoaPg6HYQfYMB/B79b0AH8Ct1/OJxCRQdj9iK0165DxEvRG/ZQsId6TFVPYLneAPrkStXAKcLI2UpNQ2BjuwqKX4JKVCNfg1RQAxVsjZPQ+8AwCS33Rqluymi59hUg1RBZ7u0YNUrKh4KooeT+CMmO9JsBtE2wqUX0g+Gj6Lg3PNCpIlrF3xGZOMnBKGbIfqM5Vu2MZhiSV7wn24f2ltNwitMD+R+sxiM+3l6t+Kx1D53sG2ZX4V2AE631kyl9Sz1K02RR5kn8bRwMO4qDYWv98fPe6qGci0u/t1sdiXYOcZh+R1iajeRDwdPUcm+Y+CNLeRs8/MskL3paHyvXGcdJ2lvPs2hGke3sfsRlNSenS0KgEAImWleD7Oa7UH8XpPz2+Z//HY845RYAwK9VeQS/i2pNlnWc5v8):

| `🟡 178Lon-Rhumb-Edge` |
| - |
| ![bleed](https://user-images.githubusercontent.com/5172619/169050090-e1863f39-35ca-4747-b7a8-219cb8183915.png) |

| `🟡 178Lon-Rhumb-Precision` |
| - |
| ![edge](https://user-images.githubusercontent.com/5172619/169050150-3a8de08e-353b-49aa-a90d-8de85fe3a30a.png) |

Both of these seem to be influenced by the padding done in `ShadowVolumeAppearance`:

https://github.com/CesiumGS/cesium/blob/7cabc7ad9f838f92aef746a28e9833196ce23e8f/Source/Scene/ShadowVolumeAppearance.js#L846-L850

**Comment by ggetz** [comment] 2023-06-06 20:24
I think the bounding volume issue is documented in https://github.com/CesiumGS/cesium/issues/7116.

**Comment by ggetz** [comment] 2023-09-22 14:09
And I think the rest of the issue is covered by https://github.com/CesiumGS/cesium/issues/4746. Closing this as a duplcaite.

**Closed by ggetz** 2023-09-22 14:09 UTC
Labels: type - bug, category - graphics, category - polygons/geometry
