### ISSUE TITLE
Incorrect topology of data loaded by GeoJsonDataSource

### ISSUE THREAD

**Issue by zouyaoji** [CesiumGS/cesium#10242] opened 2022-03-29 01:58 UTC
I use GeoJsonDataSource to try to add a GeoJSON format data of Multipolygon type.

But I found the results presented in scene to be less accurate.

In cesium it will be split into 4 polygons.

But actually it should be considered a polygon, as rendered in QGIS.

Sandcastle example:

[link](https://sandcastle.cesium.com/#c=vVltTxw3EP4rFl9KpOue7fErJagqSapUealE2i+9fljuDKyytz7t7kFIxX/v47sQIGBa1UlPCLA99jMznhnPzE2nr2K9YDX7OcRfjt6+YSdNG9g8dmPddE13yoZmuWrDMF5iuulOYr+sxyZ21aybTt9F1oa679gy9oHVx3E93qafsCEEdjaOq2FvOj1txrP1cTWPy+myXh3HD9NbpN8PqzCfdenQlx0bz5qBrep+bObrtu5Z+FAnygkWAuvqZWDxhIV6fsZCNzbjJQP5EEY2RtaMA1vW7xvWQAbWLBLBSRP6Db+HbTN/n4TC0mb7cdO2x7HuF+wC/7HhLF7ghO+GWxsh9Ab2JWT/KX6oEpM4ehjZeRMusP6UdeGCHYahWS+r3zdzu7Od+WZ8uNVj6Gc7E/bXrGNsmIcuvI6LsHe95eh6pjo6fP7muXw2SXRjswwtdu6xk7odwmau7pqt8m8mr578cMPQoh7ro7ju5wFMfTo9XesQu2efl6oW972bjtvwM9sZL1dhtrOH/16Eelz34TC2bZgnHHC9pTnZrgyJ7o809Wl3+sx2TkNchrG/TKufp9PCPMZ+0XT1eGfn9nNncG/4wARjgsvKOEHkFLfCEk3u00hTaUFOOuOJFJfqS5I/J/8aiWulpPLcks4ieWm9IdBbKkGCVMZrbYXLISnpwAvAHPECJCGdwG/tlcwjGSGldtaQK0FSWjjtSHqdR+JKcy69tboEyVlLnCe5skiGO2M5V8rJAiQpSTjSnFQeyXkJgTzZkmuCVXnuudNa5UUymrw2ABNfBSl/TUZKhz9KO1OERFpapa2zWST4GwnhpSBbguQVRFIO951FImMhDilcVhkS9KeVf8T0yHCFe1LaFFkEjJw7p6U2WSShrLXKwndLZEI0I9gEgmxeJm7gs5Zr7YpkMtZBd4gAWSRSVgntlKOiYCQJZsXTKVntEWRBxPKKeJE/ScQaYZTRPi8TJ6mF5t4X2Z7Ay+OScvLPE3zWwvY8OV2EpMmRVZzntUcwGidgfVoUPRrcEwwZF5a/J0kIr2QUlWivNI24O3FneJeL/5zokDDgD5bEfd4PldOILnD5Io+Hf6XwIXg+tAhJUkiEH1EEpBEFEZhtPohJgexEcAGpCpAQocCxRm5BjyA52IEVQCxBElAMMhkuss8aWTIJzyv/ba+JNPIpo5WxpuSlJkQvA8vTOu8b5JAYcyFBWYLEhXD4QXL7CJJAPpW0V/bWeI9AljLBf3prgFUkU6Hf/g+RBSrn3qGWyOpC4moRzBUstqSwUfAOVDeS8kUANI73X/lEWOSGCBuQCREqiyRTQeJJC150vynh0xYKzAYx8KJSTWI1FYVLvNuWhBaPaO8rIaXM3ArEZcrfE1mUUFZ6X1JUkzEe1QSXlLU9FHJGQyCL9KUICQmSxkMi8tpDicARwogbWxSYy/zp23s8UpgURh0KiCyHJKwBh1B6kR9KFMnaK7wMWSSU/bgaaa2RXwNJqTwSnB45HDRfUj2g8EVyi3BtsnWKsNoqxDk8vUUyaa49fJ4/gvTZO765TDpxgkwAGU4REilkYtybfLzUqVeE/FKZsvQSiYuWCM6U90ODkp24BFtF6WWZPz3m8TeD2wzdbtS+Xrdj82tsL09Tj/aa5mpy05Jd9XEV+rHZNl7vNGVfvHyW5njF75z+2xD6TysPHXivS3yNe5X+gOer1IdO3ehtW7y6aUYPVb1Y7N6MbxF9jHH5Ln6xdjOqxrPQ7S4G9vQgfSUxxDa1r08xU20a/xCvOq/bdRiePJl1O5Od/c2XCQfXbP/YLFexH9m6b3erajqG5apNzejp8Xr+PozVfBgSYCLdn97eur9ozlmzePpAH5/N23oYsHKybtuj5iMUcbA/Bf29ranR3nSnb89D39aXiexMHLzaTlZVtT/F8OGdY4ztcd1/cfLf)

This is the result rendered by QGIS:

![image](https://user-images.githubusercontent.com/24430116/160516806-224630db-89ee-492f-9866-d296f6976f9f.png)

**Comment by ggetz** [comment] 2022-03-29 14:52
Hi @zouyaoji. Am I correct that the only discrepancy you are seeing between QGIS and CesiumJS is that in Cesium the `multipolygon` is split into 4 different entities? 

If that's the case, I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/9431 which requests adding support for `multipolygon` entities.

**Comment by zouyaoji** [comment] 2022-03-29 15:01
Does that mean it's not supported yet?

**Comment by ggetz** [comment] 2022-03-29 15:02
Not as a single entity, no.

**Comment by zouyaoji** [comment] 2022-03-29 15:03
Hope to support it as soon as possible, there should be many scenarios that need this.

**Closed** 2022-03-29 15:24 UTC
