### ISSUE TITLE
Clipping planes demo "Show bounding volume" does nothing for Model

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8649] opened 2020-03-02 15:55 UTC
1. Run http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Clipping%20Planes.html&label=All
2. Select `Model` from the combo box
3. Check `Show bounding volume`

The bounding volume doesn't show up.  Looking at the code, it only handles tilesets, which is fine.  But it makes the example confusing.

Why is this checkbox even here, it doesn't really have anything to do with clipping planes, right?  Perhaps we just remove the option?

**Comment by lilleyse** [comment] 2020-03-02 16:10
Duplicate of https://github.com/CesiumGS/cesium/issues/8509

**Closed by lilleyse** 2020-03-02 16:10 UTC
Labels: cleanup
