### ISSUE TITLE
Lighting of models in 2D map view 

### ISSUE THREAD

**Issue by sofasama** [CesiumGS/cesium#9083] opened 2020-08-04 05:38 UTC
I have a problem like #8014, the polygon entity is darker when it changes to the 2D view. 

In my project, the temporary solution is set height value of this polygon entity to 'undefined', but I think maybe it has a better solution.

I set an example below, I tried this [Lighting code](https://sandcastle.cesium.com/?#c=rVdfb+I4EP8qVl8IamoK19NpD7a6LW3V3nEqEqj3gnRyk4FYdezIdmjZW777jROSOEDRnm7zsIs9Mz/P/5mumSZrDm+gyWci4Y2MwfA8pc/FXdCJiuNYScu4BN0JyT8LSfAzICCyXMlHGfOIWaXJr2TJhIGwZOByqW7Ue3W7kNvucCEXco0vmggk4IPly7Q4DktSJFT02pCKI5IKFroS6gUoSPYiYMJXieVyhbxW51Bg937UV6mpmY2Sey7jW7axPIVbZuFL21O/54Iz6QhBd/iR3J/Mav6+J1le/nRCbMy0RV4m9yTr++8Svvk/wuOTwgu5zGWRBmTZCN8rPVVc2iBThjtiSKJca5B2jtSQaDC5sN0qlcojvrP78e3bCf86AQ/MJYiEYIe4o5f/OsNQgWdMU+Wy+8ACKpVOmeBfwVP0VBAqfIecYPqBsbfKKX4xKHzhaL0euc21y0tGBlcXicrRvRlDZJsAmeWyYwjLMuYMII9YUpYzQar3SazAyI4lUcLkCkiaRwltHjW5rEVqg2Y8VbL/6dPVVDAJlunNdIdmaKTSLLeAz1Z3j/IO7UkqmHvNUgha0TmVSV3fzjnaX1h1N75vLAAWJaQwW62xqwyuioMhwXnvgvQHu9NSq7SKI3FvdH0zWZoJcNo0VjZpQFkcPziQttoX/UH4UcVWgVtiIgRF9BD4coj/jVDBITk/T+psrJSwkMJcM2lQKG30qK9q584do5oayGN1z98hLus6aKwIP+4IlWZehKtI/RU1r+5aBU0xy3kmNjebMq2DlpahnyAnAzk+8u53FUpLv7Ct7j5mrOxUqziP7FFQJAd1fYaNBj5M84svSeABXnsF2Aqd+1q12QgN21xNfI42Efdtj2lyIiH9kPdD74UKdFt1PJtruet3SNr+0NFV9nQsDG43zSQtzhyM0zbYOUywFxA4oT3/mUS97U3y6vqGRa8rrXIZI4ObuR59iRsC3nb6V9k7wX6ksOdF0PE4EqX5V7dHiCfNV1wi986TD3sUOrm7n3uSa5fQ0aHcc+uezp+mnlCGlSielksDTq9jE2wQ9H8OyWW3joy3oGD3jcX+TjSLNICcOcPu1ujOh5IpKHeTiKGkcRA7YYpPP0rsEF+KARlUkzKAOmGLhafSx1t6sCdrRjMevd4JwTOjeBwA9YeUtw1VHFWOuUqpQQ/amqOolWZZwqN2WVa31PXm2kse1F55Y82suM1jmFld7mFNs0qoVbewQn+ZwH+R1kJd5Ci6ZTA4AGb2v+PuZPZgG+CyHGofImpt2PCAq6gLWpRCvV0eZbHwjj2m3Vc6EyWxEsg5CTruiD/2XNWlRvAIgotfukjsLBb55eXNJTLuAS0WcsLsPlbLOx9AtUzHUe1mAC4kK6XiYtoStSQx2xCryoJ3UzxCoFeIcZLj6kYb8WIFp96sRZ8cW/Zqf4aHIoc9fUsAO4yfncd8X7Shpnduw49qcb7JoOgbf48nj+M/ytifhWcjYzcCrkuE33iaKW1JrkVAaQ9nZ4beBNN7ydFySyNT1O+oVwmNYr4mPP68ONv7O2hxhjYyY5CyzIWY4WhcnF2PesjfEhOKxRilJ2xhgm0cS9K/npSXlNJRD4+HUlYp8cK0h/gv) to show the result more clear, you can see the code on the left side. I am sure it has nothing to do with the setting of sunlight.

In the 3D view, it's normal.
![3D_light](https://user-images.githubusercontent.com/30249119/89252267-d9038800-d64b-11ea-98d3-f579ef020da9.png)

When changes to the 2D view, this entity changes to be darker: 

![darker](https://user-images.githubusercontent.com/30249119/89251990-10256980-d64b-11ea-8beb-2e3edef714ed.png)

Changed the sun light:
![still_darker](https://user-images.githubusercontent.com/30249119/89251992-13205a00-d64b-11ea-8b4f-57cd4dc0b888.png)

When the height value set to undefined, the result is shown below:
![light](https://user-images.githubusercontent.com/30249119/89251991-1287c380-d64b-11ea-8c0e-e2f12bf4430a.png)

**Comment by OmarShehata** [comment] 2020-08-04 17:51
I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/5730.

**Closed by OmarShehata** 2020-08-04 17:51 UTC
