### ISSUE TITLE
KMLDataSource not working with Angular/Webpack in v1.85

### ISSUE THREAD

**Issue by CodeCakePie** [CesiumGS/cesium#9809] opened 2021-09-14 07:51 UTC
Sandcastle example: n/a

Browser: Firefox 92.0

Operating System: MacOS Monterey beta 12.0

After updating to cesium v1.85 there was a problem with webpack/angular where KmlDataSource.load could not load the Datasource anymore. The following error appears in the console after invoking the load method:

```
ReferenceError: _Users_<username>_<Directory>_<Project_Folder>_node_modules_babel_runtime_helpers_esm_asyncToGenerator__WEBPACK_IMPORTED_MODULE_0__ is not defined
```

After downgrading to v1.84 everything was working as expected again.

**Comment by lilleyse** [comment] 2021-09-14 12:29
It's possible this is related to https://github.com/CesiumGS/cesium/issues/9790 since KMLDataSource uses zip.js.

CC @ebogo1

**Comment by ebogo1** [comment] 2021-10-07 05:33
@CodeCakePie Could you please share some details about what plugins and versions you are working with? In particular the webpack version would be helpful. Thanks!

**Comment by CodeCakePie** [comment] 2021-10-07 05:57
I am using Angular 12 which uses Webpack v5.

```
  "dependencies": {
    "@angular/animations": "^12.0.3",
    "@angular/cdk": "^12.0.5",
    "@angular/common": "^12.0.3",
    "@angular/compiler": "^12.0.3",
    "@angular/core": "^12.0.3",
    "@angular/forms": "^12.0.3",
    "@angular/material": "^12.0.5",
    "@angular/platform-browser": "^12.0.3",
    "@angular/platform-browser-dynamic": "^12.0.3",
    "@angular/router": "^12.0.3",
    "@turf/turf": "6.5.0",
    "cesium": "1.84",
    "file-saver": "^2.0.5",
    "papaparse": "^5.3.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.3",
    "@angular/cli": "~12.0.3",
    "@angular/compiler-cli": "~12.0.3",
    "@types/file-saver": "^2.0.2",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "@types/papaparse": "^5.2.5",
    "jasmine-core": "~3.7.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^12.0.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.2.3"
  }
  ```
  These are the working dependencies.
  
  Thank you for looking at this problem!

**Comment by ebogo1** [comment] 2021-10-07 18:17
@CodeCakePie Are you able to test with this [branch](https://github.com/CesiumGS/cesium/tree/zip-pako) of CesiumJS? I think this error is related to imports from the third party zip.js worker code and the above branch imports a worker-less version of zip.js. Thanks!

If not, are you able to provide a barebones example to reproduce the error you're seeing?

**Comment by ebogo1** [comment] 2021-10-15 15:05
@CodeCakePie we recently pushed some changes to `main` to fix and close related issues so I'll close this one since I was unable to reproduce it. Feel free to re-open if you're still having issues, thanks!

**Closed by ebogo1** 2021-10-15 15:05 UTC
Labels: priority - next release
