### ISSUE TITLE
VRTheWorldTerrainProvider example can't load in hosted Sandcastle

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8935] opened 2020-06-08 18:07 UTC
Initially reported on the forum: https://community.cesium.com/t/free-terrain-service-vr-theworld-online-is-down/9802/2. 

Go to the terrain Sandcastle: https://sandcastle.cesium.com/index.html?src=Terrain.html. Click on the top dropdown and select VRTheWorldTerrainProvider. The terrain fails to load because it's loading over http, and the browser rejects it because the page is loading over https. This will work locally but not on the hosted Sandcastle.

Sandcastle has been on https for a while, but I don't remember this being broken.

**Comment by mramato** [comment] 2020-06-08 18:35
Duplicate of both #6587 and #4594.  Let's use #6587 since it has the most comments.

**Closed by mramato** 2020-06-08 18:35 UTC
Labels: category - sandcastle, type - bug
