### ISSUE TITLE
Immediately destroying a tileset results in an error

### ISSUE THREAD

**Issue by ephjos** [CesiumGS/cesium#10378] opened 2022-05-13 14:03 UTC
If a `Cesium3DTileset` is constructed and the destroyed without ever being added to the viewer or having its `readyPromise` awaited, the call to `destroy` will error with:

> This object was destroyed, i.e., destroy() was called.

To see an example of this:

1. Open the following sandcastle
2. Run it
3. Open the browser devtools
4. The above error should be logged

[Sandcastle example](https://sandcastle.cesium.com/#c=bY/BSsQwEIZfJeTUwpJSFQ9utijrZUEQVDzlkk1nNZhOlkzapYrvbtIq6LpzGWbm/74Q45EiGywcILAVQziwNZDtO/E87QrFzTSvPUZtEYLi5VKhQjOR0TogiH/RuZ3fPs3H4kMhY31wVz+BjccHIN8HA2IXfHdDKbZpi/ry4qwuFwo/8xvfbtECxeDHolzyBZcURwdNNua6tt3eh5jthRBVhG7vdASqtr15S6whyqocldVvVLZ2YLZdnfgfM04Tpcuud+7RvoPijaxS/h/qvG4tvtwPEJwec+y1bu7mpRBCVmk8TUbv3VaHI/MX)

I would expect that the behavior here would be that destroying a tileset should succeed regardless of the `ready` state.

Browser: Chromium 101.0.4951.54 Arch Linux

Operating System: Linux cesium 5.17.5-arch1-1 x86_64 GNU/Linux

**Comment by ggetz** [comment] 2022-05-13 15:05
Thanks @ephjos, I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/10363 and is being addressed in https://github.com/CesiumGS/cesium/pull/10361. I'm going to close this to track it in one place. If you think it's a distinct issue please let me know!

**Closed by ggetz** 2022-05-13 15:05 UTC
Labels: type - bug
