### ISSUE TITLE
Ambient Occlusion doesn't work！

### ISSUE THREAD

**Issue by happyfeet1996** [CesiumGS/cesium#10106] opened 2022-02-15 08:08 UTC
Sandcastle example:Ambient Occlusion

Browser:Chrome

Operating System: macos

![image](https://user-images.githubusercontent.com/40989006/154019019-fa9ef130-74d1-46a9-a918-f1b2391057c2.png)
![image](https://user-images.githubusercontent.com/40989006/154019065-1ad59321-ea79-44ed-b69e-8844276177b1.png)
when i check ambient occlusion,full screen change to black and can not look anything!

**Comment by happyfeet1996** [comment] 2022-02-18 04:29
> @happyfeet1996 I'm unable to reproduce on MacOS in Chrome. Can you provide some more details about your system by visiting [this page](https://webglreport.com/?v=1) and taking a screenshot?
![image](https://user-images.githubusercontent.com/40989006/154617573-377b8043-6a10-4b4a-a5d2-02af1cae0612.png)
![image](https://user-images.githubusercontent.com/40989006/154617694-7118c725-ade6-4681-ac37-a69a924d3abd.png)
![image](https://user-images.githubusercontent.com/40989006/154617719-3c079b05-2fc4-41b8-9f06-78bc19eb5d1a.png)
![image](https://user-images.githubusercontent.com/40989006/154617737-0e95b0ee-c574-4684-b021-7d88156bc09e.png)

**Comment by happyfeet1996** [comment] 2022-02-18 04:36
it works today,maybe my network go wrong that day

**Comment by shotamatsuda** [comment] 2023-04-14 09:55
I also reproduce the same issue on macOS Chrome with eGPU. Specifying fragment alpha in [AmbientOcclusionModulate](https://github.com/CesiumGS/cesium/blob/1.104/packages/engine/Source/Shaders/PostProcessStages/AmbientOcclusionModulate.glsl) seems to resolve it.

```glsl
- out_FragColor = ambientOcclusionOnly ? ao : ao * color;
+ out_FragColor = vec4(ambientOcclusionOnly ? ao : ao * color, 1.0);
```

**Comment by ggetz** [comment] 2023-04-17 13:05
Thanks for the info @shotamatsuda.

@jjhembd Could you please verify the potential fix in the comment above, and recommend a PR if appropriate?

**Comment by jjhembd** [comment] 2023-04-18 18:08
Hi @shotamatsuda, thanks for the tip. However, on my machine (Chrome on Windows), I get the same image even if I set the alpha to 0.0
```glsl
    out_FragColor.rgb = ambientOcclusionOnly ? ao : ao * color;
    out_FragColor.a = 0.0;
```

![image](https://user-images.githubusercontent.com/41167620/232865556-898dd786-b9a0-40f4-8958-5d284c9a97a6.png)

Does zero alpha also work on your machine, or is the `1.0` value important?

**Comment by jjhembd** [comment] 2023-04-20 20:11
Hi @shotamatsuda, thanks again for all the info. 

I think it was a mistake in `AmbientOcclusionModulate.glsl` to leave `outFragColor.a` undefined. We don't do this in any other shaders.

There are two input textures in `AmbientOcclusionModulate`:
1. `colorTexture` is the rendered scene before the ambient occlusion stage.
2. `ambientOcclusionTexture` is the shading factor computed in `AmbientOcclusionGenerate.glsl`

`ambientOcclusionTexture` has its alpha value set to a constant 1.0. I think it would make sense to preserve the alpha of the previously-rendered scene (which will usually also be 1.0, but not always). This would simplify `AmbientOcclusionModulate` to read as follows:
```glsl
    vec4 color = texture(colorTexture, v_textureCoordinates);
    vec4 ao = texture(ambientOcclusionTexture, v_textureCoordinates);
    out_FragColor = ambientOcclusionOnly ? ao : ao * color;
```

The above code gives the same result as before on my setup. Can you please verify if it works on your hardware? If so, we should be ready for a PR.

**Comment by shotamatsuda** [comment] 2023-04-21 04:07
@jjhembd Yes, I confirmed it works with my hardware, and that should solve OP's issue. Deriving alpha from `colorTexture` makes sense to me.

**Comment by ggetz** [comment] 2023-09-29 14:08
Requested on the forum: https://community.cesium.com/t/improve-ambient-occlusion/9639/4

**Comment by shotamatsuda** [comment] 2023-09-29 14:20
Major problem is in the quality of stochatic noise and the lack of denoise.
I made a library that implements Nvidia's HBAO and cross-bilateral filtering for Cesium. It's not a generic library, but you will get the concept.
https://github.com/takram-design-engineering/plateau-view/tree/main/libs/cesium-hbao
Live demo: https://plateau.takram.com

HBAO with cross-bilateral filter:
<img width="960" alt="image" src="https://github.com/CesiumGS/cesium/assets/8651513/74bc1280-2b27-435f-b1b2-ec194d123161">

HBAO without cross-bilateral filter:
<img width="960" alt="image" src="https://github.com/CesiumGS/cesium/assets/8651513/d756875d-c9a4-4b52-8d2f-91c834e89aa5">

No HBAO:
<img width="960" alt="image" src="https://github.com/CesiumGS/cesium/assets/8651513/bc53813a-f77e-4379-96d9-1f65c65b4617">

**Comment by ggetz** [comment] 2023-09-29 14:38
Awesome demo @shotamatsuda! Would you have any interest in contributing this AO algorithm implementation?

**Comment by jjhembd** [comment] 2024-08-16 14:56
One issue with our current implementation: it computes a non-zero obscurance on flat surfaces.
![image](https://github.com/user-attachments/assets/2b7e01ca-6880-4a18-a443-58f7579ba8ba)

This may be related to error in the depth buffer. We are computing obscurance based on the "horizon angle" relative to the local surface normal, as reconstructed from screen position and depth buffer. On a flat surface, the horizon angle should be 90° from the normal, and obscurance should be zero. However, the reconstructed normals don't look right. Here is a rendering of the difference between the reconstructed normals at adjacent pixels.
![image](https://github.com/user-attachments/assets/fa84960e-6161-4ba5-b1dd-5ee08516ebfd)

It shows non-zero values at the edges/curves of the model, as expected. But flat surfaces also show significant noise.

**Comment by ggetz** [comment] 2024-08-16 14:58
CC https://github.com/CesiumGS/cesium/issues/11067?

**Comment by jjhembd** [comment] 2024-08-16 15:55
The reconstructed normals are better if we don't use a log depth buffer.

Current result, with log depth buffer:
![image](https://github.com/user-attachments/assets/6b3571db-79d8-4b6c-be99-e0480031b1cf)

After forcing `Scene.defaultLogDepthBuffer = false`:
![image](https://github.com/user-attachments/assets/9fd8b511-44de-404e-81cf-73bac13d0d09)

**Comment by yoyomule** [comment] 2024-08-19 09:03
I hope AO will have better effects and performance. It is a good way to improve the effect of Cesium models. At present, it needs to be optimized in terms of performance and effects. Thank you for your efforts.

**Comment by jjhembd** [comment] 2024-08-31 14:24
As discussed offline, the depth buffer for post-processing has a precision problem. To address this, we will try the following (in order):
- Use a higher precision depth buffer during the initial rendering. We currently use the `DEPTH24_STENCIL8` format, corresponding to the `UNSIGNED_INT_24_8` data type, which is available in both WebGL2 and WebGL1 (with the [WEBGL_depth_texture extension](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_depth_texture). In a WebGL2 context, we can try the `DEPTH32F_STENCIL8` format, corresponding to the `FLOAT_32_UNSIGNED_INT_24_8_REV` data type.
- Copy the depth buffer from each render pass into a floating point texture, instead of converting it to fixed precision and packing it to an RGBA texture.
- Fix the depth buffer for multi-frustum rendering (mainly relevant for linear depth buffers). We currently copy the raw result of each frustum to the same RGBA texture, without accounting for the different near and far planes that the value is referenced to. Once we switch to a floating point texture, we can project the depth value back to eye coordinates before copying, so that all frustums will be written in the same coordinate system.
- Try the [EXT_clip_control extension](https://registry.khronos.org/webgl/extensions/EXT_clip_control/) (only working in recent versions of Chrome).

**Comment by jjhembd** [comment] 2024-08-31 14:28
Here is an [updated Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=xRmJctrI8lcmrtRapLDQLYGP92KcZEn5SGKczaaoioU0wBghsTrAOOt/f90zkhCHE3vjeptyBamn7+7p7hm1acKyidyJQtmnAzcL0teeR5OkG41pSA5Jb4cu3o/67zx2wd53ru466jnrJJ3wk+m1O1ZnPP3yuf2+KQPSX/67MSB11Is/3mjnd97d10vFODvp3J12Py7Ou2cpwO8u2mpw3r1S/7z5zC5OrmD9ip2230+/ArOzmysTn//88pFd3ACPG+/urDvWLrqfm/LeaXNofku+nF90LUpv+gNvsTe2Tmbdv+bD7M0f53O/f2OZwdnHG6O3s98Le2Gj0Ra2XXo0pIV1p9HwhE7T0XE2GNAYDBy4QUI5gReFSUpmjM75QkjnJOfwmcOk3o7H39tRmLospHFvp06+90JCUjahAUBagl0dYW7IJm7KorAKHNLIi3waV2EJ6ncG0A/MG1eX7msVvb4Tzw1nblKH3wmNXfgNIm9cF+TkHjQWqu+j6RwoC0x5EGdJCmaE1EXDVFmp8EXgh8AN6Sc6jeIU1v3IyyY0TOUhTd8EFB+PFx0fzC9xezuommAghLwVMh7BZAVfMBLaTqMk/URD8I7s+v6bGZCcsiSFpVgaZKGHviRSTXh8TW2ZhYD2e/fsFGQLdoMYBF2mbkoLB1xOA5YmSE2IPHGnUoIAcnhEzrNJH6Tw95qcRm/ZLfUlrYbKEVIEAGXWITox9/aqcwXipitWFLt++R153NfJy+/A5v56fxlkHlw5oenrNI1ZP0uptJu6fQb+uN2tk11lt7ZPGg3yIUvJAJybEPBGOqJ5WpQcotALII8ws3OfFS7LMWVOLaHYey669K3nTtMspm1uxSVNUxYOk4K6Guw2JCuak7sAlMYdInE8nyZAlyd+ZQ+13TiFJzfUpZffc0KIOENE+Za7ZB262Aq9u6/xbRPFDDJkU9Dv1PVB8Q8s9UafoiBYihuJlRWuiFUFxEDBBUBcrsvoRwGVg2goLc3n7kPvlYm+kbO7Y7rwo3kI0VumLy2CwQbwIgMKOTw8JLvebrFAHooD14bcL1MG97/sZXEMUrtQgSAkuQ/eZwF4+kTkfjTpJJFjKaqEDHo7mqJpe4qzp6hdRWnxv6+9nV4ouKJeiPciZ/UBduWHOMKeAJtpSE9ZP3bjhcyS15M+RuDC84IsAeMusylmPGwcvgFrwFGYNIckjuayG9A4lYSNvZ3uiCWkH0fzBKqtH9GEhFFKEsGDJ7Yr+JOoEECwQpCpUEZGlQkp4yDy08fajsl4OXJ9XsavMzApiickcSdT0EA7EUhdeotOBvICYRBEbkomLOQNYnPBvS0WwEshmVFPI7NvqeDTjqLYx7ynCUeYRcwHEhZK+AS+yIMreHENsIbcTb7FkJWcsVTVq76VdZ4DBRcGBctdnOTMBD3ZK02okQaRCrWr8JzLGr0XgIekKrBOFFmpY8MoSMBovaBrR0EUL+UeIHKN/IfjSCoSKvl/NdIS0CrzgmWUpd/exu6wYAeIhlQVUSoAcb7e34j0aqteT1dRlKAXDHGTiqxoracJryd5tJNWsQ8Ld7W4HTks92YLdeKw+6JRL5tYVX6CdUEq5VU7Ogee0JjNoIjN6BMy9l/PPy77FkoX0WSFvNqKCwmHaNJq9hi4id+0c9ksnNE4oeCwGyoK5CsR/9tFXSi5kn0FqfhtiF95vrIpkiCaYiXc0xSF6zaYMx+ME7h3P8w6nqOCQcH8rvaD9FsG75cScT0HHp1Rq/JXp0V3rTrzmeUBjkC4ji4X20HuB1l8mdLpJbtDvyor0yOOnDi6BrDCDQzy+bpF0jgT8y3irMPW1K+sbO66zT2XjKJ5hWRd94swWFSWWQj9GIYHgOk5gz5zExSg8reAhsN01HanXKYuROQWF0LFqJTHdhxC54UMktPY9cZS6YTlUJxGUdDn0/bDg3COI0bgdc7udBosjqFx8t5fSqgXnJEG4kOkfIqHWYFgUShVEeHAbl7C5JGbXMxDCP0UOvFCQqJaOXasaZDPIgT1vuhDk565/YBWNeHkJVqS9RMPBlcqZVMf9n8l/8Weu88bdTkLbeAVo6bIUsgkN2bpaMK81RPbMXiAumHFriLphKBHHft+xqSs2DIN0XA/P18J3DKlyW+/kRdL+Fpa729J9cfxfARLzqjcpcW2AZb5YWbJYrXvbyMuZoRtxPmaqC6bm21pi0iFFw9YVGGJ25f8/XfFyG07WGj7cF3aRlMJbN5xfiiiGCB/JKasHtucUy7+jAsWnG0MEP4z2rI8bWNQLv6MS7Is4RtMirW8y23ZmOJG5dXaWWy141VOeKiKqumGqtmypjUNW1VUy+CFdc9U8CyiypZlGYYOGBysWzr8s2XFUHXdVBXDFAeSXKLP4nxA+JHIPUU2dVVRLENvWpqqWroo8ADXFa3ZVFTdUR3FcQzVKhbspqoblqHYjuVopmqsiI3ZcJT+TKRjWI7Z1BTbNDRLsQVn6C2mbSimqsKaYVqGnYNNxW46Tc0BVAPcsCIumy6PcEs5shdHEIPlBYNQq14BlO6pi7uRbdrieWz/VUNcjW2e3BuNR53dMaoQVxncrJq6Dj6r85CCA2xZbWoQarNp1nk8jaYjAzY61jFMPFSjkEef23WIjWNapuEomm3apm7U0d0KSLNVx4F3x9I12+BHDEUHd9pW09IdRzHByULcfcW7T72mQFM1R5ENw7YsR9ebTj3PXjDVNO2mrZuWlZuq6pB6hqGAS+wn3k/osqM0LdVWbQuyt6koJrfTaNoW+NfRm6qmmpZt14kJmLYGmjRVw1It06F7dm15UZjGC9FA8ZoowltMvCHDWTVhw5BM+JwGx+cZ86Fe9xfkGBQM6IJcLqACTJLlNU/KAgrugmx05y5LS+fwH/2kK5bF3UIUvk7gBUYaDfaRZaqiEuWjZswmDPuWmFpzvrzOQO6CB4hE4ziKK5dMxV3L9RtcgIGSu6tQqUVefucU99eCy0595yBJFwE9Qgb/ZRN+f5DFgSTLDbAKjpEQ0EY/88agsVdMI6KvXnWK6acPg9wwjrLQ3/PwSNAi8bDvSnh+FX+yUZ5CwBLQCCZDb1RMNgeNQocDn80I8w+3XBbjCTtJYGWQBQHW297O0UED8FfIcoMv4GQEJ2BEGalHpwIoy/JBA143qcphkrvhIMWeXMrLbc0Xcbkf+YujYnY7SOPyGd/8o6uEEhiZCO/eBw2ArK4fsHCaQZosphQNHVFv3I9uwUJoHO4eXloWYOq3yjMBN7fCC17iHyjBz1QPabB8g/cnaVNOJaU7xL93MbgYNkTrifzWBrQVrk8x9wzGdzEtnYjLjydZHbvhEGTj8Qne9lR8dG/hUYMn7O/wCGVSXbNi5gYZnHGKCRFO/Qi44gNAi+xyEbv/3CT39t8zKZ9bn9mk/NKTlBPWL+8OnIafuDM2lCA4zT7rLtk6Lv9Tp3WKMfkX4r8Mv6os4/9A8Mu5/Jmjf8qnbQLj9i9YoiwteUwilxP+M9uCdzoEu9CzB+VhW4qDxjObcgynqP9fQPDM9gsGwGPZfeEZG7V4xl7+UMfOvykS/oUygRaVTN1QdP7KR1koIgg/OugXwsQ3JJJ/pFyhW/sOW9AKtcR4gRz+Bw) displaying the gradient of the depth buffer.

Log depth shows strong noise in the distance, as well as some spuriously large gradients on smooth surfaces nearer the camera.
![image](https://github.com/user-attachments/assets/22a40c52-577d-450a-aa38-2018c04660c6)

Linear depth reduces the noise nearer the camera. However, only the frustum nearest the camera is valid. The back frustum is washed out.
![image](https://github.com/user-attachments/assets/a4011668-ec31-4fa5-a770-0d05d14a4aa4)

**Comment by jjhembd** [comment] 2024-08-31 14:32
I updated the depth buffer to use `DEPTH32F_STENCIL8` when in a WebGL2 context. Note that this doubles the size of the depth buffer--because of alignment issues, the values are stored as 64 bits per pixel.
Unfortunately, it does not have any effect on the noise.

`DEPTH24_STENCIL8`:
![image](https://github.com/user-attachments/assets/0dcc14e1-9ab8-4c06-8c08-8e26c9d0db12)

`DEPTH32F_STENCIL8`:
![image](https://github.com/user-attachments/assets/e4e15bd1-8c5a-4bfd-8876-91ce3195b295)

See the `depth-precision` branch.

**Comment by jjhembd** [comment] 2024-09-12 14:05
@ggetz highlighted [this commit](https://github.com/CesiumGS/cesium/pull/9966/commits/cc6d525ccfeef1176ca9b0cbc652c07507d5a0a4), before which AO did not show a noisy background on flat surfaces. Here is a quick screenshot of AO from a prior commit (70fc40e258ce5592d7b00abd0d52cb10e90828c0):
![image](https://github.com/user-attachments/assets/89d753ea-b52e-405e-8b62-2d6fa637d002)
Note the absence of any occlusion on flat surfaces, even with the "Bias" set to zero.

For comparison, here is a screenshot from the current `main` branch:
![image](https://github.com/user-attachments/assets/e634b71a-0bf8-4063-8428-6c1932b680a4)

And here is the result using the `DEPTH32F_STENCIL8` format and a 1m near plane (instead of 0.1 m), both of which reduce the noise in the depth buffer: 
![image](https://github.com/user-attachments/assets/260f6ef7-d4b9-4e14-9080-9ab1c2233a77)

While some minor artifacts are reduced by the  `DEPTH32F_STENCIL8` format and a 1m near plane, the main problem is still there: a background noisiness on flat surfaces. This appears to be a problem introduced in https://github.com/CesiumGS/cesium/pull/9966.

I also captured the gradient of the depth buffer prior to #9966. It does not look significantly different from the depth buffer from the current main branch.
![image](https://github.com/user-attachments/assets/9639e6da-aa0f-4346-8a33-e36636b14309)

The background noise problem appears to be something more fundamental--perhaps a depth buffer is being overwritten somewhere?

**Comment by jjhembd** [comment] 2024-09-12 15:35
The background noise is generated when the HBAO stepping is along a direction not aligned with screen X/Y.

Here is the AO output with stepping only along X/Y. This is achieved by overriding the "randomVal" texture and using a constant rotation of 0 at every sample.
![image](https://github.com/user-attachments/assets/fbd3b6a6-baa3-4806-b31e-9b025c690fd0)

Note the significant reduction in the background on flat surfaces. The remaining background is the result of the noise in the depth buffer. It is reduced by setting the near plane to 1m (instead of 0.1m):
![image](https://github.com/user-attachments/assets/3f8cb977-30b9-43e6-b482-110582f99b1f)

This is already approaching the result before #9966. One possible explanation is that before #9966, we had 2 bugs canceling each other:
1. The random texture was not being read correctly, leading to a rotation of 0 (or nearly 0) being used at every pixel.
2. The AO was already incorrect along non-screen axes, but this bug was hidden by the random texture problem.

Then #9966 fixed the first bug, exposing the second bug. But this is speculation--actually tracing texture handling through the major refactor in #9966 would take significant time.

Here is the result using a constant rotation of `czm_piOverFour`:
![image](https://github.com/user-attachments/assets/d9a6390e-0747-401d-97e2-1601f53d9ebb)

Note the (incorrect) non-zero values on every flat surface. The current noisy result in `main` is a random mix of various non-zero values at different rotations.

**Comment by jjhembd** [comment] 2024-09-12 15:50
A remarkably similar-looking bug, which appears to be related to incorrect normals. In this case, I think world-space geometry was leaking into the normal calculation. 
https://www.reddit.com/r/GraphicsProgramming/comments/sd17k0/trying_to_implement_hbao_shader/
The similar result was what made me suspect our normals, and therefore the depth buffer from which they were computed.

**Comment by jjhembd** [comment] 2024-09-12 15:57
There were some incorrect geometry assumptions in our shader. For example,
```glsl
//Reconstruct Normal Without Edge Removation
vec3 getNormalXEdge(vec3 posInCamera, float depthU, float depthD, float depthL, float depthR, vec2 pixelSize)
{
    vec4 posInCameraUp = clipToEye(v_textureCoordinates - vec2(0.0, pixelSize.y), depthU);
    vec4 posInCameraDown = clipToEye(v_textureCoordinates + vec2(0.0, pixelSize.y), depthD);
```

Based on what the code is doing, the comment should actually read something like this:
```glsl
// Reconstruct normal with edge removal
```

But this line:
```glsl
    vec4 posInCameraUp = clipToEye(v_textureCoordinates - vec2(0.0, pixelSize.y), depthU);
```
appears to assume `v_textureCoordinates` is oriented with `y = 0` at the top of the screen, when it actually starts from the bottom of the screen.

Overall, I think our current prototype AO is pretty rough. The choice of algorithm is good, it just needs a rewrite, with careful checking of the input and output of each step.

We now know the depth buffer input is somewhat problematic, but:
- Setting near plane to 1m reduces the error
- The remaining depth buffer error is relatively small (compared to other problems in the shader)

**Comment by jjhembd** [comment] 2024-09-12 19:03
Some notes from an offline discussion:
Our HBAO is generating wrong values along any sampling axis that is not aligned with screen X/Y. This matters because each pixel rotates the sampling axes by a value that is randomized across neighboring pixels.

The error along rotated axes is much larger than the depth buffer error. It is not clear whether:
- HBAO is sensitive to depth buffer error, and magnifies the problems, or
- Our implementation has a bug affecting rotated sampling axes.

We will spend a little time reworking and testing each step of the AO implementation, under the preliminary assumption that the depth buffer is not the main problem. Initial tests/QCs will include:

- Estimate the actual angular difference between adjacent reconstructed normals. (My earlier QC was arbitrarily scaled). If this is small (< 5 deg.) on flat surfaces, then the normals themselves may not be the problem.
- Compare surface gradient (via native dFdx / dFdy) to slopes computed at sample points along rotated axes. Some other implementations snap to the texture grid, to ensure the sampled depth value and computed X/Y coordinates align at each step.
- Adjust sample distance along rotated axes, to avoid resampling the same points. For a given rotation angle, I can manually adjust step size until the noise goes away. But we would need a different step size for each angle.

**Comment by jjhembd** [comment] 2024-09-12 21:22
> One possible explanation is that before https://github.com/CesiumGS/cesium/pull/9966, we had 2 bugs canceling each other

I tried to confirm this, but can't. Before that PR, the result looks fine even with a constant rotation of `czm_piOverFour`:
![image](https://github.com/user-attachments/assets/2266e87b-6756-48b9-b58b-c30bddf44b94)

**Comment by jjhembd** [comment] 2024-09-13 14:31
Our first test was to check the angular difference between reconstructed normals at adjacent pixels.

Here are some images showing the sine of the angle between the normal at a given screen pixel, and the normal at the pixel just above it (Y + 1 pixel). The sine value is scaled by 11.47, which will make the image fully white if the angular difference exceeds 5 degrees.

From best to worst:

1. Using linear depth with near plane at 1m
![image](https://github.com/user-attachments/assets/1a3f5f60-2ad4-40e8-9836-f68592ed5e49)
Note how the image is black on flat surfaces, with white outlining the edges of the model. This is as expected.

2. Using log depth with near plane at 1m
![image](https://github.com/user-attachments/assets/bbf381a8-d157-4f76-9d69-5c87e997c5a4)
Some linear noise appears on the far-away terrain, but it represents angular differences of less than 5 degrees. There are also some strange artifacts _near_ the edges of the model. But overall, the result is close enough. The depth errors are small enough that we can move ahead with further debugging of the rest of the AO code.

3. Using log depth with near plane 0.1m (current default setting)
![image](https://github.com/user-attachments/assets/7eed99b1-7b47-41ec-83e7-6d576e554974)
The error between normals at adjacent pixels exceeds 5 degrees in many places. This will be a problem for AO.

I think we can move ahead for now and debug the rest of the AO process, using a near plane at 1m. We will need to come back later to revisit the errors with log depth and closer near planes.

**Comment by jjhembd** [comment] 2024-09-13 16:08
Some additional checks just to be sure.

Angular difference between current pixel and the pixel to the right (X + 1 pixel)
![image](https://github.com/user-attachments/assets/538c682b-eb59-41f2-afba-b696cdae01af)

Normals computed from tangents along the screen diagonal, difference along `x = -y` axis:
![image](https://github.com/user-attachments/assets/3e8f182f-18c0-461f-b5d6-c560aaff0100)

Normals computed from tangents along the screen diagonal, difference along `x = y` axis:
![image](https://github.com/user-attachments/assets/796bc15a-ccf5-43e2-ab26-c322cf08b6f1)

**Comment by jjhembd** [comment] 2024-09-13 19:36
Difference between normals computed along screen axes vs. along diagonals
![image](https://github.com/user-attachments/assets/70c40bca-947b-4fdf-800c-334e05412160)

**Comment by jjhembd** [comment] 2024-09-13 21:48
I found what changed in #9966: the depth stencil texture was changed from linear to nearest sampling.

We can recreate the old result in the current code by making 2 changes:
- Construct depth stencil texture with the default (linear) sampler
- Use a WebGL1 context (linear sampling of depth textures is not supported in WebGL2)

Current result with a WebGL2 context:
![image](https://github.com/user-attachments/assets/2f229b62-0c29-4b68-b3cf-b97b6ec32b3b)

Current main with a WebGL1 context, nearest sampling. Note how some of the artifacts are reduced.
![image](https://github.com/user-attachments/assets/a6d2a96f-789a-4efa-8bef-0ae80741ca8f)

Current main with WebGL1 context, and linear sampling of the depth texture.
![image](https://github.com/user-attachments/assets/07b67f80-9076-4f7f-81af-fdbc26c72a4f)

Just for interest: here's the linear sampling result with more angular sampling (16 instead of 4)
![image](https://github.com/user-attachments/assets/82184782-9aa8-4d08-9562-5076de751425)

**Comment by jjhembd** [comment] 2024-09-13 22:00
I don't think we want to require WebGL1 for AO. Two possible options:
- Copy the depth values to a regular floating-point texture (not a depth format) for use in post-processing. This copy step would also give us an opportunity to fix the depth buffer when using multi-frustums, which would allow us to use linear depth values when we need a more accurate depth buffer.
- Snap coordinates when sampling for AO, and make the necessary adjustments to the geometry calculations.

One thing that is not clear to me yet: why does log depth produce fewer artifacts in WebGL1 than in WebGL2?

**Comment by ggetz** [comment] 2024-09-16 13:12
> I don't think we want to require WebGL1 for AO

I agree. Is doing linear interpolation in the shader a possibility? 

@lilleyse Would you be able to weigh in on the solution here?

**Comment by jjhembd** [comment] 2024-09-16 14:05
> I'm surprised linear sampling looks that much better. Is it because coordinates aren't snapped?

Correct, the current shader does not snap coordinates to the texture grid. I am trying a snapping solution now.

> Is doing linear interpolation in the shader a possibility?

Yes, though this would add to the cost. I think the main performance hit right now is the texture access, and a manually-coded linear interpolation would make that 4x. Snapping would be faster, if we can correctly account for the snapped geometry everywhere.

**Comment by jjhembd** [comment] 2024-09-16 22:16
Here's a quick test fixing the coordinates to account for nearest sampling. This uses some WebGL2-only features like `texelFetch`.
![image](https://github.com/user-attachments/assets/1ed234a0-de88-40da-bcd5-a977ec958ec9)

The WebGL2 result still has more artifacts than WebGL1.

**Comment by jjhembd** [comment] 2024-09-17 15:09
We now have 4 actionable steps to improve AO:
1. Fix sampling of depth buffer. I have a working code in WebGL2 (`ao-debug` branch). I will spend another day to see if we can get WebGL1 working too.
2. Expose parameters (with good defaults) for the number of sample points: both the number of angles, and the number of steps along each angle. Sampling a larger disc can give significantly better results.
3. Improve scalability: the occlusion radius (`lengthCap`) is currently a fixed value in meters, which makes the AO effect disappear when zoomed out to city-wide scale. This value should scale with distance.
4. Use a smarter smoothing on the raw AO result. The cross-bilateral filtering demonstrated by @shotamatsuda looks like a good option.

Other issues arising:
1. Why do we get more artifacts in the depth buffer in WebGL2?
2. Are other post-processing steps affected by a similar bug with the depth buffer sampling?

**Comment by jjhembd** [comment] 2024-09-20 04:00
Item 1 above is addressed by #12201.
Items 2 and 3 are linked, and I think should be addressed together.

At each output pixel, we currently step rays outward along several angles to find the angle of the "horizon". The maximum distance of the ray-stepping defines the radius around the point where we allow nearby geometry to "occlude" the ambient light.

We currently have 3 factors defining this maximum occlusion radius:
1. The distance-based weighting applied to each sample. The contribution from points far away from the output point is currently weighted by `1 - (distance / lengthCap) ** 2`.
1. Truncation at the `lengthCap` uniform. As we step to pixels away from the output pixel, we compute the Cartesian distance between the stepping point and the output. If it is above "lengthCap" in meters, the contribution of that pixel is ignored _and further stepping along that angle is aborted_. Unfortunately, this truncates the occlusion if the raymarching path is interrupted by a small foreground object (such as an overhead wire).
1. The maximum number of steps along each angle (currently hard-coded to 6) along with the step size (in pixels). This may sometimes result in a hard truncation of the occlusion effect, if we reach the maximum number of steps before reaching a distance of `lengthCap`.

The main limitation of this approach is that parameters that work at one scale do not work when zooming out or in. For example, when zoomed on some details of the Power Plant model, an occlusion radius of less than 1m makes sense. But when zooming out to city scale, we might reasonably expect a skyscraper or other large building to occlude ambient light on buildings 10m or more away.

I first tried a naive approach: scale the occlusion radius based on distance from the camera. However, this makes a given feature become darker overall as it moves away from the camera, since the shadowed areas maintain their darkness, but their size grows linearly with distance.

One better approach: model the occlusion as something that _blurs_ with distance--i.e., shadowed areas become wider, but less dark. In this way the overall darkness of a given feature would remain constant.

We can achieve a blurring effect by simplifying the flow as follows:
1. Change the distance-based weighting to a normalized Gaussian distribution, with a variance proportional to distance from the camera. As the variance grows larger, the shadows become wider, but less dark, because the peak of the Gaussian becomes less pronounced.
2. Compute the step size as `scalar * gaussianVariance / maxStepCount`. This ensures that every point will sample the entire intended radius.

We do not need to abort the stepping if a given sample point is too far away from the output point, because the Gaussian weighting will already make the contribution from that point negligible.

**Comment by jjhembd** [comment] 2024-09-20 04:07
I have a preliminary version of the Gaussian-weighted AO in the `ao-sampling-disc` branch. The same parameter choices give reasonably consistent results at a wide range of scales.

Here is a quick comparison on the NYC buildings tileset. Some notes:
- The initial view is deliberately chosen at an angle and time of day where the default lighting appears washed out.
- The AO is heavily sampled: 16 angles, with 64 points along each angle.

No AO:
![image](https://github.com/user-attachments/assets/a529e04f-6059-413f-bd7d-9cd716054239)

With AO:
![image](https://github.com/user-attachments/assets/0ddfff8f-d3a3-44a3-8baa-a9e0dc980a5c)

AO term by itself:
![image](https://github.com/user-attachments/assets/6daa53ab-8aa6-485e-b357-c5b1acc56b97)

**Comment by jjhembd** [comment] 2024-09-20 04:13
A much closer view of the same scene, with the same parameters.

No AO:
![image](https://github.com/user-attachments/assets/038ee01e-fc63-4b35-b5bd-d2818b320528)

With AO:
![image](https://github.com/user-attachments/assets/81cc8c18-32e6-473b-92c6-1123043404a3)

AO term by itself:
![image](https://github.com/user-attachments/assets/17ac651e-f523-493c-8487-4ab43000d88f)

**Comment by ggetz** [comment] 2024-09-23 13:37
@jjhembd Screenshot look fantastic!

I don't see the `ao-sampling-disc` branch on GitHub. Do you need to push?

**Comment by jjhembd** [comment] 2024-09-23 13:47
https://github.com/CesiumGS/cesium/tree/ao-sampling-disc

**Closed** 2024-12-02 17:06 UTC
Labels: type - bug, category - graphics, type - regression, theme - visual quality
