### ISSUE TITLE
When setting `allowPicking: false` on a Primitive, it is still picked and returns `undefined`

### ISSUE THREAD

**Issue by easternmotors** [CesiumGS/cesium#11022] opened 2023-01-05 04:33 UTC
I did some digging around into some related issues (#6633) but I couldn't find one simple enough with a straightforward Sandcastle. I have multiple overlapping `Primitive`s in my scene, some of them "pickable" and others not. I am using [Primitive.allowPicking](https://cesium.com/learn/cesiumjs/ref-doc/Primitive.html#allowPicking) to not only improve performance as mentioned in the docs, but also to tell Cesium not to take these `Primitive`s into account when calling any "pick" calls on `Scene`.

**Expected behavior:**
When attempting to [Scene.pick](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#pick), I was under the impression that the picked objects would be ignored and the first "pickable" `Primitive` would be returned, with the "non-pickable" `Primitive`s to be ignored. In my Sandcastle (link below), I would expect `Scene.pick` to return me the blue `Primitive`.

**Actual Behavior:**
If the first Primitive found is `allowPicking: false`, it returns `undefined` instead of attempting to find the nearest "pickable" Primitive. In my Sandcastle (link below), `Scene.pick` returns undefined instead of the blue `Primitive`.

**Sandcastle Example:**
[Here](https://sandcastle.cesium.com/#c=7VZNb+IwEP0rXk5BoqbdthdKqwUKu5VKQUCrPSBVJh7Au44d2U6Arvjv6zifBXrvoRyQJzNv5o1nJhNfCm1QzGADCt0iARvUA82iAL+4Z9685ju5J4UhTICa1+o3czEXvkNqHwRYYOoBO9Gq2RJ535yAQ+b/HUvNDJNiGoWhVAZoHf2bC4Q2TFC5wYSDMjbSbM00Wii50ZYMlaCRkDZECkJVRzhlsU+INJuoQyl6kuJsbE3IggOaAEVduZ2LjINigcXFoDGh1EtCVzId51rPkUJoBTIAo3YPNkMibP6tqvnPA22OKnGt3NRSyK3xUsngngUgtOWvSxBCsc0etgOpAmIK6BhUHqAnuVSdMASiEhG/9Cez/u/XwWgy7MwapR9aeH/Ht0ese82IuPSuzpMfPm+gy+J0nZ3qhad9eQwkBT4kRrFtwSwVr3AQccNCvuvuZpaX5iQpjFfSycydcmmT0xiINk+2lOvncCYHbAt0oEgAFQw6Jp1eHKwUgPbOLs6vE9JX9r9ewuqVWziduUvV/X13CX+AyHLzCt+lHTFWtYhM0g2V4vlJcYq7caU6bJBOjnSpOJOTKScKPOnf4w0z6w4P18TSvj6Z5j47FaUiRXu8q/3HXVQ2oM+lBtpCRkVw5JZzuUmmiolVCy0J16nJ3rJKXwPZ9BWT1+URfI3ecQNeFAN3fPoavU8xet3H5/6nnb3Cohy9dAOviaD8cHlPfVszMQ2JD/0YhPmVGnnpTPpExEQnTjIw1mAeRBiZju86aRkJd0BeIGOwrW2yhZ2GTDYx0NHiD/jmYPe7dV+gMAiar+wkXOpAcsBcrryqG7fNGx/Rn+1CwMPR87T/Ohy99Os3tUatrc2Ow11+kz9Y4L4SIsU9jJsGgtCOBejmIrJRDPa1Thkg1G5WoW3KYsTo7YkPHVseorXVLCPOp+wN5rW7dtPaH0G5JNSWaWTfJ5zsErP1xd1j+hBj3G5a8TTSSMkXRB14/g8)

**Current Workaround:**
Right now my workaround is to use [Scene.drillPick](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#drillPick) and return the first item in the array. Especially with the number of primitive I am rendering, this is actually _much_ more expensive on the computation side which is clearly visible when interacting with the globe.

**Browser:**
Chrome 108

**Operating System:**
Windows 10 Pro Version 22H2

**Closing Remarks:**
It is totally possible that this is "expected behavior" but not the behavior I was expecting. Regardless, it would be awesome for this functionality to work as outlined above to help certain apps with a large performance boost.

Thanks in advance Cesium team for all you do!

**Comment by ggetz** [comment] 2023-01-05 21:19
> it returns undefined instead of attempting to find the nearest "pickable" Primitive

I think this is expected behavior. This is because the red unpickable object, even though it has a transparent appearance, occludes the blue pickable object. I think the behavior you are requesting in covered in https://github.com/CesiumGS/cesium/issues/1592. I'll close this as a duplicate and note your request in the original issue. 

In the meantime, your workaround using `drillPick` is what I would recommend. We are aware that  [picking performance, including drillPick, really should be further optimized](https://github.com/CesiumGS/cesium/issues/630). Thanks for the report!

**Closed by ggetz** 2023-01-05 21:19 UTC

**Comment by easternmotors** [comment] 2023-01-08 20:49
@ggetz thanks for the clarification and confirming `drillPick` is the recommended approach for the time being. I was glad to see picking performance is going to be getting some performance improvements! Hoping that issue gets some love soon! 😄 

One near term feature that I would be interested in is expanding `drillPick`s parameters. Right now `limit` allows you to opt out of the drilling early after a certain number of picks. It would be nice if there was some sort of logic added in there to be able to opt out after some explicit or arbitrary condition to avoid a full picking iteration. Might be it's own thing or a possible feature as part of #1592
