### ISSUE TITLE
Memory Retention: XHR response referenced by Request

### ISSUE THREAD

**Issue by bn-dignitas** [CesiumGS/cesium#8843] opened 2020-05-13 02:49 UTC
While memory profiling our Cesium based app, I found instances of XHR objects and their response data referenced by the Request cancel function.  See below:
![3d-tile-request-xhr](https://user-images.githubusercontent.com/12056433/81763858-339ea500-949e-11ea-81b7-d59f75f2d107.png)

In this case, the cancel function added by **Response._makeRequest** ( https://github.com/CesiumGS/cesium/blob/master/Source/Core/Resource.js#L1347 ) is leaking the xhr object.

This can be seen with any Cesium instance with loaded 3D tiles including the Sandcastle example https://sandcastle.cesium.com/?src=3D%20Tiles%20Interactivity.html

Fly around a bit with Chrome browser and then perform a memory heap snapshot.  Look at the system/JSArrayBufferData objects.

**Why this may be a problem:**
If the xhr response data is referenced by other objects directly and not copied, this would not be a huge deal other than the xhr object should probably be released for GC.  However, if this were not always the case, then chunks of memory are being retained inadvertently.  I found an instance where the **RequestScheduler** **Heap** is referencing Requests for tiles that had been destroyed in our app.  This may also be due to the Heap pop function not actually removing Requests out of the array (or maybe that is intentional?), but in any case, if the Request object was not referencing the XHR object then it would not be leaking large amounts of memory (we have some big tiles).

**Possible Solution**
A quick solution might be to simply delete the cancelFunction in **Response._makeRequest** when the promise is fulfilled/rejected.  I ran a quick test and things seem to work, but I'm not sure if there are any other repercussions.

**Comment by OmarShehata** [comment] 2020-05-13 13:25
Thanks for reporting and for the detailed write up @bn-dignitas . Would you be able to share a [Sandcastle](https://sandcastle.cesium.com/index.html?) with instructions on reproducing this and if you can indeed see a memory leak from this? You can use one of the 3D Tilesets from the asset depot for testing if you cannot make your own data public. I think [this Vricon one](https://cesium.com/ion/assetdepot/57590) is currently the largest available there.

**Comment by mramato** [comment] 2020-05-13 13:42
I can reproduce this easy enough with the provided instructions.  At first glance it definitely looks like we are holding onto ArrayBuffers because of unreleased XHR requests, but it would be nice to get a second opinion.

I suspect you are correct and the Heap is implemented as a circular array so it doesn't automatically clear out old values as much as push them out once some size limit is reached.  I don't think I've ever actually touched Heap.js, so @lilleyse or @kring may be able to provide some better insight here.

I took a quick look at the "set cancelFunction to undefined" strategy, and that might work assuming there's nothing about the Heap we want to change, but the trick is finding out where we need to put it.

Thanks @bn-dignitas!

**Comment by lilleyse** [comment] 2020-05-13 15:35
> I suspect you are correct and the Heap is implemented as a circular array so it doesn't automatically clear out old values as much as push them out once some size limit is reached.

Yes this is correct, and is likely the culprit.

@bn-dignitas I don't see a problem with the solution you proposed. Would you be willing to open a PR with that fix?

**Comment by bn-dignitas** [comment] 2020-05-13 17:28
@lilleyse Sure.  This would just be a change for the XHR ref and leaving the heap alone, correct?

**Comment by lilleyse** [comment] 2020-05-13 17:33
@bn-dignitas yup, just fixing the KHR ref is fine

**Comment by bn-dignitas** [comment] 2020-05-17 17:24
@lilleyse I should have noticed that the **request.deferred** is also referencing the data returned by the XHR response.  I think it also needs to be set to undefined, otherwise there is no real effect on memory retention.  Does that work for you?

Some uncontrolled testing shows decent results in memory retention improvements.  The snapshot below shows the top 10 retainers before and after changes. 
![image](https://user-images.githubusercontent.com/12056433/82155242-76b39c00-9841-11ea-99d6-dc89078c5564.png)

**Comment by lilleyse** [comment] 2020-05-27 13:10
See https://github.com/CesiumGS/cesium/issues/4549#issuecomment-634503841, possibly related

**Comment by mramato** [comment] 2020-05-27 13:20
@bn-dignitas are you still working on this?  If so, I would recommend just opening a PR with whatever you think is best to do and then we can discuss the details as part of the PR process.  Thanks!

**Comment by bn-dignitas** [comment] 2020-05-27 13:39
@mramato Yes.  I got distracted with other priorities, but I'll try to get this in ASAP.

**Comment by mramato** [comment] 2020-05-27 13:48
Awesome, thanks! We really appreciate it.

**Comment by lilleyse** [comment] 2020-06-07 15:50
Fixed in https://github.com/CesiumGS/cesium/pull/8883

**Closed by lilleyse** 2020-06-07 15:50 UTC
Labels: type - bug
