### ISSUE TITLE
Using 3D Tiles for classification doesn't seem to work

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#11341] opened 2023-06-07 13:00 UTC
As an experiment, I threw together this simple Sandcastle to attempt to classify Google buildings with OSM data. [Link](https://sandcastle.cesium.com/#c=fVRbb9owFP4rR2gPqURNQhJCNlqto9VWiapoZXuK1JrkFKw5NrINjFX97zu5sNHrixWf63e+fMe5VtbBRuAWDZyAwi2M0Yp1yX7WNi/r5PV9rJXjQqHJOl14yBSAEyVKsnyEey4tdisbV6LkTmh1aLQ5KrzSBU5F/gvNoWvOLU74Ds1z1+PRp0xlqteD2RJhIfUcodBoQWlHKLEAp6GyCbuSVKDo1sFWqBzBUcp0qZ02yKWwTuQQnsNMSMqnALkuKAaNoXky1czOapCsbsTsUm+JjBrLHsZZUbxVM1PO7BpO8ppOV1nRUQm+5cLtGc0p1eFXrRcSn5YKz2dNileNDfAE08qIUjixQct4UXht8SrwEXLu8iV4NIs2R/8haIlM6oV3d1E5QGpeCLV4k5O2JKvSPzzUxR7v6gbt8FMtlKtpzXmJhgNvbs0sK4m/n/HYhDEqWsnIq4EVSF1Vq44DoY25cfTFVehVYQDH/UEaJmnC4jjwB36UJN3WEfXTJAhjFgeJn0ZJP24d4TCOEt9nCZ1REIWDqLIf1V5tBJJ0X7T9hjUpU0EMftdSts0jNohjn/qm/TgI0vRfj2Of9YeDcJhGdAbhcBgOWk/AwngQJIS0HydJGCQhHid7ACRkqFhslKFt+WUtZNXYzt5TyfVB4JndqbzhkH6v5NaKe5HXE812K9q/PZEvXGx8cXP54+o2PL+dXU4u2rV6T12vAGw2MVOdbmdk3U7iaYME4LMoV9o4WBvpMdZzWNIu0r/szde0zY7l1jZ6Bhj1DlNHhdiAKE5eeVyaAclzv5byRvzBrHM66lH8i9RW1dcbNPQCVGHL4HTSGBljox5dX890Wss5N88q/wU)

Everything is kind of broken visually, the OSM data should be draped over Google, instead it just appears to render incorrectly.

To make sure this was a problem with the OSM tileset and not google, I took our basic classification example and used it with Google and it worked as expected (though it doesn't full line up this is a data problem). [Link](https://sandcastle.cesium.com/#c=xVVRa9tADP4rWtiDA8beFvrSpmVbUkahZYWkezK0F5+S3HY+hbtzSlry3yf77DVOk/VtA4Ox9En36ZNOzsk4D2uFj2jhHAw+wgidKovkR22Lsl5ef4/IeKEM2qwXw3NmALwqULPlFOZCO4wrmzCqEF6R2TW6HA3ekMRblf9Cu+uaCYfXYoN237Xtn2UmM2kK0yXCQtMMQRI6MOSZJUrwBJVNuZXmBDKuwU6ZHMFzyO2SPFkUWjmvchiMYao0xzNAl5IxaC3Xk5lQe1KTTOqDErekRxaj5tLS+CLlsZyZ8XYTNMlrOX1lRc8pxKNQvlU051CP34gWGrupBuNpCImqsgE6nFZWFcqrNbpESBk1yYM+7Ym5Fs6pucpr8Ztkd1bDeYUByHpJkk5EsdI4Fl6kgVFzbDrqRKc1t4UVRYFcWNocmPx0ZLJeza/SA2YDWfwptXShJQ2RTd2DVSdRi32D9b5qHapMY26p4MqiUNixwuPgfg6vV7jNise2PeCVKxldTq7ubu4H4/vp1fVlk2tbvUJ/Dp6aOL/R2L1Eu+QnlTtqGOWkicc969nFTESfTk5i+BCe5KTPV6xCbd8ehoNE2tFoLo8TBR5o1pzsXh0xzEoPFo1EywBDthBabwKSipWwikcgeemfITP6dy2sbuXu7uh05BiV/9GUY1w6kU9ExZT+3sCJMDIXzmus8k5pwYvja+k9GV7Lk2pJdcOr1extiTHMS5NXFmg1XiLvV1nr1Sp6ZIjD7msCzgL0uLoB/W4XXiu0BQbmS4h4zZLtv2xH4mI0LaKHy8oBmoRUZtGO5im8f64jtg8hSy/uDesWXrRj8FkVK7I8xDxAvNQ88lLjterSWckUfJI7129oD9Pd0KFUa1Dy/MAfLWjBnnmp9UQ9Yda7GKaMfxXa8P2+Rsu/nQq2/HhxHYxJkgxT/jwc6Yn0TNi9zL8B)

**Comment by ggetz** [comment] 2023-06-07 14:21
Testing this out in 1.96 (before ModelExperiemental became the default implementation in 1.97), and I see the following error

> A 3D tile failed to load: https://assets.ion.cesium.com/asset_depot/96188/OpenStreetMap/2023-01-02/root.b3dm?v=0508c930-914b-11ed-af01-7f8b0e38194d
Only one node is supported for classification and it must have a mesh.

@lilleyse Do you know if this is still a requirement? Should OSM work as a classifying tileset, or should it be throwing the above error?

**Comment by lilleyse** [comment] 2023-06-08 13:20
That shouldn't be a requirement any longer. The old `ClassificationModel` did its own glTF parsing and had requirements like that to keep the parser simple. I don't think it was a requirement related to the rendering side.

**Comment by ggetz** [comment] 2023-11-27 15:43
Also reported in https://github.com/CesiumGS/cesium/issues/11223.

**Comment by ptrgags** [comment] 2024-01-04 15:12
I made an [Updated Sandcastle](https://sandcastle.cesium.com/#c=tVVtbxo5EP4rc+ikEol4WZZlIU1z1yZRWym5RAd3n5BaszuAFWMj2xvKVfnvN7aXipAXXT+chADPu595ZlxqZR3cC9yggXegcAPnaEW9Yn8HWXvaKsP5XCvHhUIzbXXg+1QBOLFCSZITmHNpseNlXIkVd0KrfaEtUeG1rvBWlHdo9lUzbvGKb9Ecqh6O3k7VVCUJTJYIC6lnCJVGC0o7qhIrcBq8TNi1pABVJxhboUoERy63S+20QS6FdaKE7AImQpI/Gci6Ihs0hu4zVfHuLBTJQiJml3pDYIRadmW8r6qXYk6VREdw0F90ZO/MdodQEFEovuHC7ZAtKYTDj1ovJD4OmV1Moku7VhXOCdyqAZtQpKJOwJka/TngA/Co+LURK+HEPVrGq6rdZPeGD1ByVy6hTZfW5iiGLKn1WiKTetH+eukVIDWvhFq8CF4Tknn3X7+HYA9fQ4IGpVstlAv4l3yFhgOPp3jZtcRvB4BHM0ZBPd/aobAKKatqaLTHyHNuHP3jKmtHSI57g1FWjAqW52l30O0XRadR9HujIs1ylqdFd9QvenmjyIZ5v+h2WUHf/bSfDfpefhS02ggkjj9J+wkDKLeCEPxTS9kk77NBnncp76iXp+lo9CPHcZf1hoNsOOrTd5oNh9mg0aQsywdpQZX28qLI0iLD42JXAHUUPIplmEhtVx9qIX1iO3mNRjd7hu/tVpURQyglt1bMRRkuNNmuaU53OD5RsfPL8ee/rr9kF18mn68uY7nUzo02d9xoIiPMiR5L59b2JEkWwi3rGSv1KokhP46TuCUSYW2NNknT/jBAC6j4TOKYyHtTu8N1sc/pwOjX+PwMJHFJPKNg1m0lPl5o8SeO2NirG6RoEKSm1TNtmcWMt3t53oFu/LD8iNbdj3nb20gzlLQj/EZSb1zAqQN8veaGKCS3nvMG31jgMKsXsPEnoDv42eJgkXpcUdr1FvQ8hLwZX5Nlcweandr6aaM8gvbAN+9G626hKZG62zK45lvafcJRBoOSWBDWoY4A299eIdEf+nH3f45UTcNCA5uO/Ycc/18zfpIuh4Xtwoy5qkpuHS1D8pzoBe2qD7VzWtHz56l7ME3+CfSk7cC8VmWAsVkK5RLpHavCTO8W97P0jC9MY/72RcOnUEbHX/Y9CY5Wp3UaUD6LoQB+F6u1Ng5qI9uMJQ5Xa08Um8xqcnSstPaoyXua7LueVuIeRPXumYc/wkCaeS3lWPyD09bZaUL2T1ybh+TmHg29zt5smZ5dRSFj7DSh4/OeTms54+Yg8r8) that adds the "Show Classification" button like in the AGI HQ one to see how the two tilesets line up. It required turning off outlines for one copy of OSM buildings due to https://github.com/CesiumGS/cesium/issues/11484

No classification:
![image](https://github.com/CesiumGS/cesium/assets/8422414/fdd96238-97b9-4204-91a0-9ccdc6bdf3aa)

With classification (bug still reproduces)
![image](https://github.com/CesiumGS/cesium/assets/8422414/46db48a4-3607-4fc3-a598-9f3c66524bad)

I'll look a little closer to see if I can at least identify what's going wrong with classification

**Comment by ptrgags** [comment] 2024-01-04 17:59
Looking at the artifacts closer, notice that there are odd/even fill artifacts for fragments where the geometry overlaps itself:

![image](https://github.com/CesiumGS/cesium/assets/8422414/26b4b320-870f-4ab6-bb71-d6f3ae18f16a)

I talked about this a bit with @lilleyse, one place where classification could fail is if the classification mesh is not watertight. This is a limitation in the algorithm that uses the stencil buffer to track how many front/back faces are rendered at a given pixel. It's a bit like tracking the number of opening/closing parentheses. For a non-watertight mesh, it's like you forgot a closing parenthesis, so the rendering will be inverted.

OSM buildings tend to not have a bottom face, this breaks the assumption of watertight classification meshes! This can be seen in a top-down view:
![image](https://github.com/CesiumGS/cesium/assets/8422414/3fdb951f-6bc8-4cfa-8062-beede860236a)

The documentation for classificationType doesn't mention requiring water-tight geometry, so this should be added to the list of limitations.

**Comment by ggetz** [comment] 2024-01-04 18:10
Thanks for looking into this @ptrgags! Please update the documentation to include this caveat.

**Comment by mramato** [comment] 2024-01-04 20:21
> The documentation for classificationType doesn't mention requiring water-tight geometry, so this should be added to the list of limitations.

How often is a 3D Tileset watertight? Is there an easy way to detect this for each tileset? From a user-centric point of view simply documenting it seems to equate to "Sometimes this feature will work and sometimes it won't, good luck". Can we do better?

**Comment by ggetz** [comment] 2024-01-04 20:39
@mramato IIUC, fixing this entirely would involve moving away from the stencil buffer approach entirely, fundamentally changing how we do classification.

I think it'd be better to have a separate issue tracking the overall limitations of this approach (there are others besides watertightness) and we can consider priority given the high LOE needed.

**Closed** 2024-01-04 21:28 UTC
Labels: type - bug, category - 3d tiles, type - regression

**Comment by mramato** [comment] 2024-01-05 14:06
@ggetz So since this is closed, is there another issue we opened to track the larger limitation?

**Comment by ggetz** [comment] 2024-01-05 14:11
I've added the [Classification label](https://github.com/CesiumGS/cesium/labels/category%20-%20classification) and will open  the new issue shortly.

**Comment by ggetz** [comment] 2024-01-05 14:46
Opened https://github.com/CesiumGS/cesium/issues/11740
