### ISSUE TITLE
Removing data sources with many entities seems to be significantly slower in the recent release

### ISSUE THREAD

**Issue by abhimonk** [CesiumGS/cesium#8767] opened 2020-04-17 18:23 UTC
Crossposting from [cesium forum](https://community.cesium.com/t/removing-data-sources-with-many-entities-seems-to-be-significantly-slower-in-the-recent-release/9297):

In the most recent Cesium version, it looks like removing a data source containing tens of thousands of points is slower compared to older releases.

[Here is a sandcastle link](https://sandcastle.cesium.com/#c=hVTfb9owEP5XrLzEWUMILVonoGhb+7hp0jrthaDKJAe4dWzkH7Rs6v++c0IhCW2XPMS+++7uO/u7CLBky+ERNLkiEh7JNRjuyuR3ZaNhXm2vlbSMS9BhNM6kwJjcGavKG2bZrXI6h3b0dcdLs6DcHbdZ4NPUZZPiYDYJKwrazeyh/vVVV5oXT1jqPE3HR8vuxLJQThbGI2fD85gMh/MTpw+a9S4HMeldXsyrGkulCfUojr50jJ9JXRGXZ2cR+ZtJgs8Bdl/D7vewHS4bMP90e0lAWm75vtMG0D8bZdCn5OhwikxbXDF5kSw1poGVBjB0BfaOSwt6c4chtNFSXPOIyX2Ey7dgTzUMPxxhH9M0ittEJCthRMI1CKHCjq8Ak2u+qXmGCzhFbBRWHZFOc5WHP4G45X8w+af41J0rofSoJSNvod+ZXSeayUKVFAm/t43aWZ+P22cvo73tubpsJ3PfxdvnFBPpyqobXHJZHG5Wg3VakgZ0NpiTXkNcs3QekQ8+iPSPWchZGzKuqGyZJrng+QOqacmEATTfYj85M1aAF8oNLJkT9pdSYsH0V2etkjT8CaXaAjmKK4yRmbd1Z+fQatdNDy3xJaEViZZ8vci3A+S1AY2qL5lECUv1SF8O832N1+W+CNHCvzL2NfDVyW9ROf8fFSWNwjMTakUponvIPsIbGKRpioefBcQAYgpT/4AqORDAI2/N7P4urHbQ0EwQBxNjdwKmte0zx1vVljgtaJL0LZQbwXBc+wuXP4BNcmN8jUn/JWhS8C3hxVUWdP6pSCsXzBj0LJ2oBiQLppM+4lthQrGCy9WPLWjBdh6yHky/1cYkSSZ93J5G2Vo1jYz/AA). The linked example creates 40,000 points in a dataSource and removes them all when you click the “Remove DataSource” button at the top of the example. It then prints the time taken in seconds to the console.

Time taken in 1.68 to remove data source:
~7 seconds

Time taken in my local copy of 1.43:
~1-2 seconds

Our application recently upgraded to 1.66 and we’re seeing the same regression there as well.

Is there anything I can do to speed up the removal of these data sources? Is this a known regression? I’d appreciate a way to get the performance back to where it was in the older releases.

I can’t show a sandcastle example of the speed in 1.43 because I’m not sure how to open sandcastle in a previous release (you used to be able to go to the downloads page to open sandcastle from old releases, but that link seems to be gone). If anyone can tell me how to open sandcastle from a previous release that would also be very helpful.

**Comment by OmarShehata** [comment] 2020-04-17 18:32
Thanks for providing the Sandcastle reproducing the issue @abhimonk . Have you had a chance to run a [git bisect](https://git-scm.com/docs/git-bisect) between the last known version that had the higher performance and the current version? That would help point to exactly what code change caused this.

Otherwise if you can identify which version caused this changed that would still be helpful. The easiest way to quickly test old versions would be using the hosted CesiumJS links like in the getting started tutorial: https://cesium.com/docs/tutorials/getting-started/#your-first-app

So to test version 1.55 for example you'd include: `https://cesium.com/downloads/cesiumjs/releases/1.55/Build/Cesium/Cesium.js`

**Comment by YonatanKra** [comment] 2020-05-09 22:32
@OmarShehata 
The issue arises on version 1.58.
There is a difference in the way the DataSource destroys objects. You can see it in the following image:
![image](https://user-images.githubusercontent.com/6459899/81486213-eaf7a980-925b-11ea-870b-71ed3a9d8f1c.png)
It stems from this commit: 
https://github.com/CesiumGS/cesium/commit/d40f0992c1da0c0e5a07d05e002bff7704691d85
This commit is supposed to solve a memory leak, but introduces this performance regression on destroy.

**Comment by YonatanKra** [comment] 2020-05-09 22:59
Update:
Looking at the 1.57 version and initiating GC after the DS removal, I see there's no memory leak:
![image](https://user-images.githubusercontent.com/6459899/81486930-41b3b200-9261-11ea-9751-7b8b720f35eb.png)
I've tested this only on the points example and it might be there is a use case in which there's a leak, but the use case was not specified in the mentioned PR nor in the commit.
Are there more scenarios in which you'd like to test this?
Here's the PR: https://github.com/CesiumGS/cesium/pull/7854
Here's the relevant explanation: 
```
Also discovered the GeometryVisualizer wasn't calling destroy on it's updaters, so entities from Datasources weren't getting cleaned up at all.
```
In the profiler, I do see that `destroy` is not being called when removing the DS. Would that be problematic in case we have listeners on the entity itself?

**Comment by hpinkos** [comment] 2020-06-12 18:01
I'm going to close this issue, because as @YonatanKra correctly determined, the decrease in speed was the result of fixing a memory leak related related to memory not being cleared when an entity was deleted.  We do not plan on reverting the memory leak fix.  @abhimonk Instead of constantly creating and deleting a massive number of entities in your application, I would recommend reusing your entities, or setting `show: false` for ones you wish to hide from the display.

**Closed by hpinkos** 2020-06-12 18:01 UTC
Labels: category - entity, type - bug
