### ISSUE TITLE
camera.computeViewRectangle still doesn't work in 2D or CV

### ISSUE THREAD

**Issue by ShenTiger** [CesiumGS/cesium#12342] opened 2024-11-27 05:20 UTC
### What happened?

In 2D, When the camera zooms in to Earth, the return value is undefined.

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by jjspace** [comment] 2024-11-27 15:43
Duplicate of https://github.com/CesiumGS/cesium/issues/4346

**Closed by jjspace** 2024-11-27 15:43 UTC
Labels: type - bug, needs triage
