### ISSUE TITLE
Globe incorrectly occludes things behind it when using smaller ellipsoid

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8683] opened 2020-03-16 18:50 UTC
When using a smaller Ellipsoid, the globe incorrectly occludes entities behind it. [Sandcastle example](https://sandcastle.cesium.com/index.html#c=jVPfb5swEP5XLF4CUmTSdVrWhkaLsikvnbYpWp94ueALeDU2sg1ROu1/r4GQQMqmISTju+9+fHcfFWiigfHSkAfy7v3dfDabLWIZhmfjh9v5x5vbuTPGsnLoiuMBtXNIPJA1Gl7m9Kmx+ZOkua6VtMAl6smU/I4lcY/JVCnYSvIcLJJ7sgdhcHryPR9XNlemyFDj0JVD8V2rX5hYruR9v+IGVaqhyHhyAfg9/xcheGEUZ35LZDo4giCWf4KG0hYkS8BYgVSjQeuI7UvZ5gu69lvOlIGFrSq1o0mBMf9Ua/2Si89nFxUKmD+hNHTvFvJCYO0MDa8/aeLAk6Cu3SR2A8Wu1eFM3zAgw7Ntv0uSCrXDYYJNbfLP2S/4BktRwk7gI08zy2Va064Hv+hD3NYOG61KyS4L6gEv1V3VsYVc9TO2spH2TsM2CUqkHa/mXPwNQHdgcK2EqnXZbaW+0tWPn6vxzHuVnmbArsgPYLlSshnEv0Cm/A9MBkwdvkIxUtWpceFNvcjYo8BlG/zJ6UVpS0otfKcki04+7ucx4a5MntHSxDQSiMIuKGK8Ipw9xN7Vbxh7JBFgjPPsSyG2/AVjbxmFDj8Iq4XrpPCtQi3gWEOym+Vja6SURqG7vo2ySokd6F7GVw). 

It almost seems like there's a rectangle around the globe that occludes entities behind it:

![occlusion](https://user-images.githubusercontent.com/1711126/76790120-9e7c7a00-6794-11ea-91fe-598a5ec83167.gif)

The effect disappears if you set the radius up to Earth-size (comment out the second line in the Sandcastle). 

This came up in [this forum thread](https://groups.google.com/forum/#!topic/cesium-dev/pDezVst5b_I) where the use case was visualizing different planets.

**Comment by OmarShehata** [comment] 2020-03-16 18:55
It's definitely coming from the globe, since removing the globe entirely (with globe: false) fixes it. But setting `viewer.scene.globe.show = false` does not fix it.

**Comment by lilleyse** [comment] 2020-03-16 18:55
Maybe depth plane related? What happens if this line is commented out:

https://github.com/CesiumGS/cesium/blob/d48ac3ee47fd77c9f27297b833cbe88dd5aebfcc/Source/Scene/Scene.js#L2310

**Comment by OmarShehata** [comment] 2020-03-16 18:59
That sounds right, commenting that out makes nothing be occluded here:

![image](https://user-images.githubusercontent.com/1711126/76791064-74c45280-6796-11ea-9160-b6b28be7aa39.png)

It looks like `DepthPlane.js` is getting the ellipsoid from `frameState.mapProjection.ellipsoid`, but for whatever reason it's producing this incorrect approximation for smaller ellipsoids?

**Comment by lilleyse** [comment] 2020-03-16 18:59
The problem is `czm_ellipsoidInverseRadii` is hardcoded to WGS84. `DepthPlaneFS.glsl` uses it. Instead `czm_ellipsoidInverseRadii` should be based on the actual ellipsoid in use.

**Comment by lilleyse** [comment] 2020-03-16 19:01
Same with `czm_ellipsoidRadii`. They should both be added to `AutomaticUniforms` instead of hardcoded.

**Comment by mramato** [comment] 2020-03-16 19:02
Also, if you really want to modify the ellipsoid in Cesium, you are probably better off doing:

`Cesium.Ellipsoid.WGS84 = new Cesium.Ellipsoid(radius, radius, radius);`

before you do anything Cesium related.  That's currently the only way to ensure that all data and calculations actually use the custom ellipsoid (such as loading entities that require ellipsoid-based conversions).

**Comment by OmarShehata** [comment] 2020-03-16 19:04
Thanks @mramato . That was the first thing I tried here. I added a link to the the forum discussion where this came up in the OP.

**Comment by mramato** [comment] 2020-03-16 19:04
Here's an example: var radius = 2497000;
Cesium.Ellipsoid.WGS84 = new Cesium.Ellipsoid(radius, radius, radius);

var viewer = new Cesium.Viewer('cesiumContainer', {
    shouldAnimate : false,
    skyAtmosphere: false,
    mapProjection: new Cesium.GeographicProjection()
});

Sandcastle.reset = function() {
    viewer.dataSources.add(Cesium.CzmlDataSource.load('../../SampleData/simple.czml'));


    viewer.scene.globe.enableLighting = false;
    viewer.scene.globe.showGroundAtmosphere = false;
    viewer.scene.globe.baseColor = Cesium.Color.AQUA;

    viewer.scene.fog.enabled = false;
    viewer.scene.moon.show = false;
    viewer.scene.sun.show = false;
    viewer.scene.shadowMap.enabled = false;

};

**Comment by lilleyse** [comment] 2020-03-16 19:05
@OmarShehata I'll submit a PR with the `czm_ellipsoidRadii` / `czm_ellipsoidInverseRadii` fix

**Comment by cesium-concierge** [comment] 2020-03-18 18:24
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/pDezVst5b_I

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8683 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by cesium-concierge** 2020-03-18 18:24 UTC
Labels: type - bug
