### ISSUE TITLE
How to destroy GPU memory and webworker after destroying an instance?

### ISSUE THREAD

**Issue by qq1066536** [CesiumGS/cesium#11869] opened 2024-03-04 08:16 UTC
### What happened?

After destroying the cesium instance, the corresponding GPU resources are not completely destroyed. Repeatedly creating instances in the pop-up window will cause an increase in GPU memory. Loading custom elevations in the instance and then destroying it will cause the GPU to self increase

### Reproduction steps

1. initial cesium viewer  
2. destroy viewer
3. initial cesium viewer 
4.destroy viewer
...

### Sandcastle example

https://sandcastle.cesium.com/#c=bVDLasMwEPyVxT1YhiDRcxRTSAs9BHoI9KSLIm0TEVlK9XBwS/+9qhVIX7rt7MzsaJR3McFo8IwBVuDwDGuMJg/0ecaIaNQ8r71L0jgMoumWwoH2Kg/oEn3NGKYtWlTJB9LeaIwp+KnK245KrR/GQtyYmLDoSausUcd2AaSDVQ/vwgnHmCpBvEVq/Z7UODSqgOi2J6lwdniUTtuCm3hfb6Am3VcY4S6Ky21SQZjfR7dsFg2PabLYV/DODCcfEuRgCaUs4XCyMmFku6yOmKiKcf4jcHaVcW1GMHr1TyGgrIyxbF6ytVvzhqLpOSv8X0LrpTZu/zRisHIqpBqHH277TV1RSjkrYz3+1yF5b3cyXKW7nJJ3dfmj+UK5tAQV4Kxyv3l/Ag

### Environment

Browser: Chrome
CesiumJS Version: 1.115.0
Operating System:win 11

**Comment by ggetz** [comment] 2024-03-05 14:21
Hi @qq1066536, would you mind letting us know how you measured this?

This may be a duplicate of https://github.com/CesiumGS/cesium/issues/9298.

**Comment by qq1066536** [comment] 2024-03-08 08:39
Run the cesium instance in the iframe and destroy it directly after use. Use the iframe sandbox to perfectly handle the issues of GPU memory not being destroyed and webworker processes still existing

**Closed** 2024-03-08 08:46 UTC
Labels: type - bug, needs feedback, needs triage
