### ISSUE TITLE
Windows 7 problem

### ISSUE THREAD

**Issue by fironalia** [CesiumGS/cesium#8483] opened 2019-12-20 08:25 UTC
when i run my application on windows 10 everything goes fine.
but when i run my application on windows 7 a problem starts to appear.
i loaded a kml file, but labels and icons are not clear, they are not rendered well.
and a console message starts to appear:
GL_BLEND with floating-point color attachments requires the EXT_float_blend extension.
any idea on whats happening here??

**Comment by fironalia** [comment] 2019-12-20 11:32
![win10](https://user-images.githubusercontent.com/57382120/71252180-f427be80-232c-11ea-9873-1be1dfab0416.png)
![win7](https://user-images.githubusercontent.com/57382120/71252183-f4c05500-232c-11ea-9f2a-86de4af9679f.png)

these are 2 snapshots. one for win 7 and the other is for win 10.
Same Application but different result as you can see.

is it a vga driver problem? or what???

**Comment by OmarShehata** [comment] 2019-12-20 12:14
What browser are you using? What version of browser? Have you tried updating to the latest browser version?

**Comment by fironalia** [comment] 2019-12-20 13:45
FireFox 68 and latest version of chromium embedded

**Comment by fironalia** [comment] 2019-12-24 14:22
its not a version problem because i am using the same browser on win7 and on win 10.
i tried on another computer that has win 7, it works, this is getting confusion here.
on a device works, and on another it does not.
cant see where is the problem.

**Comment by mramato** [comment] 2019-12-24 19:59
@fironalia 

1. Does other WebGL content work?  Does https://webglreport.com/ give you a success message?
2. Make sure you have the latest drivers for your video card installed and that all Windows updates are applied.

**Comment by fironalia** [comment] 2019-12-31 13:00
@mramato  
WebGL 2 is not working as https://webglreport.com/  shows.

**Comment by OmarShehata** [comment] 2019-12-31 15:50
@fironalia does WebGL 1 work? Does other WebGL content like this ThreeJS demo work? https://threejs.org/examples/#webgl_animation_skinning_blending

**Comment by OmarShehata** [comment] 2020-05-28 15:45
Closing since we are not able to reproduce.

**Closed by OmarShehata** 2020-05-28 15:45 UTC
