### ISSUE TITLE
WMTS Provider with Time not reloading all tiles

### ISSUE THREAD

**Issue by malaretv** [CesiumGS/cesium#11644] opened 2023-11-22 00:49 UTC
Sandcastle example: https://sandcastle.cesium.com/?src=Web%20Map%20Tile%20Service%20with%20Time.html

Browser: Safari, Chrome, Firefox

Operating System: MacOS 14

To see the issue go to sandcastle example above and slide time slider. You should notice some tiles do not update.

https://github.com/CesiumGS/cesium/assets/381932/e8bdc20c-97f5-4805-8192-e9f74a7390df

I ran into this issue while trying to implement a custom provider that is similarly dynamic. 
It appears the `provider._reload()` function does not always fully clear the tiles for the layers.

**Comment by ggetz** [comment] 2023-11-22 21:29
Thanks @malaretv.

I can replicate, but I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/6156. I'm going to close this issue to keep all discussion in that original thread.

**Closed by ggetz** 2023-11-22 21:29 UTC
