### ISSUE TITLE
Bug!!  A geometric part of the mobile terminal will disappear about 100 meters from the ground

### ISSUE THREAD

**Issue by PZD2937** [CesiumGS/cesium#9800] opened 2021-09-09 10:15 UTC
When I set the ground geometry, part of the geometry disappears when the camera zooms in to a certain distance；
This is the effect of the official example opened on the mobile terminal
https://sandcastle.cesium.com/gallery/Materials.html
![f4af1ed77cfb31bae68f9cdb24bf816](https://user-images.githubusercontent.com/50706050/132667820-c80cfc4d-fef9-4970-adb7-8e76468ba268.jpg)
It will trigger when zoomed in to a certain level

all  mobile terminal

**Comment by ebogo1** [comment] 2021-09-20 17:38
@PZD2937 Thanks for opening an issue. I can see that the red rectangle also disappears when zooming in enough on my desktop browser - are you able to replicate the same issue on mobile and on desktop too?

**Comment by PZD2937** [comment] 2021-09-24 10:19
Of course, I can reproduce this problem on all my test mobile terminals, but my PC terminal does not have this problem. My browser version is Google Chrome 93.

**Comment by PZD2937** [comment] 2021-09-24 10:20
> @PZD2937 Thanks for opening an issue. I can see that the red rectangle also disappears when zooming in enough on my desktop browser - are you able to replicate the same issue on mobile and on desktop too?

Of course, I can reproduce this problem on all my test mobile terminals, but my PC terminal does not have this problem. My browser version is Google Chrome 93.

**Comment by PZD2937** [comment] 2022-02-16 06:24
excuse me？

**Comment by ggetz** [comment] 2022-02-16 13:57
Hi @PZD2937, there's no update on this issue yet. 

I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/9702. There is more info about this bug in that issue. I'm going to close this issue so we can track it in one place. Thank you!

**Closed by ggetz** 2022-02-16 13:57 UTC
Labels: type - bug, category - graphics, category - entity
