### ISSUE TITLE
ExportKml doesn't export ellipse graphics.

### ISSUE THREAD

**Issue by amock78** [CesiumGS/cesium#10609] opened 2022-07-28 22:00 UTC
I'm trying to export ellipse graphics from cesium to either a KML or KMZ file if it uses an image. I've stepped through the code to see where it's supposed to be adding the entities to the KML document, but it looks like you don't have any support for ellipse when it goes into the recurseEntities() function. Is there any work being done for that currently?

I also would like to request some better examples of how to add external image files to the KMZ file. For example, we use a '.png' image for any drop point that we add on our map. If I try to export that point to a KMZ file, I don't see a way to add the image because:

1. I'm not using a model, so using modelCallback() to access the external files won't work for me for the KMZ.
2. I'm not using a CZML file that already has the image files embedded, like you have in the ExportKml sandcastle example.

The only way I can see this being accomplished is to add the external files to the result.externalFiles after I create the KML, but then I would have to write my own method to take those files and parse the KML file to replace all the <href> tags with the image that I'm using for points. I thought this functionality was already baked into the exportKml() method.

Please correct me if I'm wrong.

Here is a sandcastle that I modified to include various shapes (CZML and Entity), and write the KML output to the console.
Sandcastle example:
[ExportKml example using CZML data](https://sandcastle.cesium.com/index.html#c=1VhtTxs5EP4rc/m0kfY2CRRxDVAdhL6pIE5Ae1IJH5zdSeLitSPbS4BT/vuNvS/ZTUJb6PV0FwkSr+f9mRmPN1bSWLjlOEcNByBxDgM0PEujT/5ZMGzFfj1Q0jIuUQ9bIfw1lABmqjKRHEqeMot9sDrDcCgX7b2hHMrYy01VgmLwkAoSfeV4PCMAT/owbCUqzlKUliTmjyVL0W0MPp+ewKnjrbZuURuupNvtRd3i8SJck0lWxDe53nWx3hE45eIGLh1dRTFThlsvvhAGEDNt1USz2ZTHxzjRiKYPV7/u7oawTX/d64J1UXx7lTX+ibDjfrkA0h5FnQuWzgQeM8s6ntx0cpOcRd6g1XU0EaPKyEXl83UtxPHzovsWVYpWc+fVgOtYoAEmE3gtBJ8ZNE8OvJmyGfbWlL2lwEmIvQZgFqbIJ1P7jMD3eqQ+hBdd97+306VPtAYC5tbXpBlM+SmXSh/ecZKz3c0Zw8Y++/Lofm5vH7ZWN1zSa87qkJM0JXgyUELpxmNyasMzAD0ZMfKNHNra2aGc8t/XYZ1oUVstfy/WUmITGltraJxjUsYI5txOYT7lFkFlVlBpg5JgMj1mMT4HoO72EqCnI7O183VkXjyGzE+BpMTD5drW7lMggTKaRUeETqcwFdKM6nWE5JmFsdIloQGrIOFmJtj9iox1u+v2Nf5dPzE5tpvJUTIPW0ciQzKdSSOymPpHCFpZimwS+gaBd+RWsppHhb3PSJuXO7Wy7j6zrHs7Tyzr0ot3j5W399k70I12f9vZfvmTCr+s/R/Mss0nxDiTsXMCEjWXQrHkSKhRMOYCHeYhjGjZzm3jYwjmXBJhJNktnzCrdJSaC3aLZ/pshvJoSQvwCKUX74SGUCpx0wCZRBBSqhTc+cGFAlM6uApR5WkVxRopwK9pk1Y0fbBhK5cBniOaahwv2T6enxQcZ6MvGFtaewMaLKX3xFaaVWxXWkcquY/YjPxMBlMuksAxNoTEgsc3QXsjo8ZU3eIq44KGoQYKGqnygyKI+cgVUaHFN5i8lpbbezIwkwmOCddkr0aU0MRwoTJNk1ih61AIb4tXQB3mT4Qx2ngKdopOT05MKzpy51wI13YwHWHiKpdLT/bh9LOPR1SOEglDP3T9oVXKCa6DchQ8LwRGXodH2fuQadF/7mRDyny3aMyLluoy0/ivGPBlNqkbQEG8nHJDbUqIEWEC9K3mBjLfnl3LdjGj/AI19j+9GreXGfTsDAZnJyeHx4flzNSk5OQgUhIWDyfi8k1JGHn+95Z0GgUCrVdrZhjz8b2ndjh9A068mylNbdrhGtWyLp/BC68Cv3qbd2ETguWuD1DUUUsm3jgtRX7mgJSpRFA0OKNM82iC9hOj0yJwUvIo5o2k5CIqEVGh4t3ZOCjn7woBKmz45eAAfu1VfaVhyNWw5XVuTp1rMmklYfeeIsTD74Q0c67wglo00lMJX7WhLHP3ZadaVXen80y6mLzWWrkb1Ed5I6kHlVeaqnCFGwSKjnSpXAcle4YtL9jtLeu+bt0FHcMxM5YqlyXJpVKErD5FmQXOjqvc/OrAce65Grlwh/5yrKcDRBrqVTFtVqkStBujRt6u9pZPNtiai41u0ociHPlnzfJlLbvr4HG1HbnGHLhLTF3Ret+rH43O7WBNQ7tBQhUhg6VjS+r26ln8SCNeckTontFNySX80f37JGgKgNrtp7lTd4kSZblchAVjY8xZx4zONRp97M/ArRL9o9jVXVxtxYa7n5GDtx6br0P9CLxVZda4YnJKs2gs7t/RdTbo1iP8jdg2Xy/8U2H1Un80otVbk/91STTexHx3XdRRywfiYWum1Qy1U+e6nBPmODa2waPMWiWp5R6XM9+H0xP3xmoN1LVg5Zq/K0rF2VBAmB+8H1IR1MJYBqi/KWq10Z5ShTKOzn2sYlCGY9HebBIlYiZsuz5NK+FSZ1JsUf7VUqfT2Tj950kbwjpLpTdmNGwFpXx0h5k/utqPH0Nr8f/Px752fape45XTUr+5DJ8LEcD3QfDwJAhaYWvf2HuBr0otv1O7pXC4sTigRmyRui/1edMZUSki3a2MKTXsd+qs+wm/BZ4cbHjZC7FgxtDOOBPigj/Q2PNqv0P0a6zOPy4nZzTUujcZRDbtvTrJH0ZRtN+h5WZOmycPsZSeLPdWi78povidr/4G)

Browser:
Chrome and Edge

Operating System:
Windows 10

**Comment by ggetz** [comment] 2022-08-17 16:32
Hi there @amock78. This looks like a duplicate of https://github.com/CesiumGS/cesium/issues/9344. If you have any further thoughts, please continue the conversation there. Thanks!

**Closed by ggetz** 2022-08-17 16:32 UTC
