### ISSUE TITLE
Ground Primitives are producing a "kaleidoscope" effect

### ISSUE THREAD

**Issue by OHalford-Novetta** [CesiumGS/cesium#8666] opened 2020-03-05 20:56 UTC
I'm currently experiencing issues with the geometry merging, or "kaleidoscope" effect, from instancing ground primitives that I've seen with normal primitives. I'm confused as to why it's happening this way, since in another example with ground primitives it renders exactly how I had expected it to [Overlapping Ground Primitives Example](https://sandcastle.cesium.com/index.html#c=3VVdT9swFP0rVl5IUHDKJjTYQrWqhA2pqKirgGlBk5tcWmuOHdlOWEH89zlOA0nY3jrt4yXR9T3n+PjEdkoiUUnhDiQ6Rhzu0BgULTJ8acfcncSWY8E1oRzkjvcu5qXhqAQ4GErNxbY0rbpJudKEJ9CV/AAiAy3XZ5uu+xBzhJabUfS2jZ1BYjBLBg2pBiMkm4bB97H4VorsBJYSQLl7+4MBHvjolX3uHdnXa/P0/FqpBKnh+6mQGdHPYhcgG39jwYQc5TkQWZX4MprNo+uvp9PZ+WheaTzWUkRrSReFBmVkNjaTittdkpXrZzBquNa7hbhtPL76eDaPPDtbzB+9p4gJF3r17PWPJn140Ar6zcG/GfTnaDKZXv0kab2iMv0rcj76H3KeRSe9kO3dgXNJM6ppCQqTNHXbKUtR8PSi6XdDbuatrH5p7h2/fzz87le8qZf5lER3Xb9OzPUq07XrYHd7vntub/wg+A2Ot+d3y9Z2A8d3QqXXDIb1bntPs1xIjQrJXIwDDVnOiNmPwaJIvoHGiVIVMQwaUpjSEtH0OHZ6P6zYQQkjSpnObcHYJ3oPsTMMA4Pv0JggKeXLqTlEjKwryGp/OKkHMcZhYMqXLC0EWxDZUvwB). Would it be possible to add a zindex to the geometry instances?

Sandcastle example (Rendering all at once and then as batches): [Ground Primitives Kaleidoscope](https://sandcastle.cesium.com/index.html#c=fZV9b6JAEMa/ysZ/qg0FsZrW1jbHVWqNrTae17ukNpcVpkoOFrO7aL2L3/12FyggcmpwX+b58ewMjhtM0caDLVB0gwhs0R0wLwr0F7VWP3HU9C4kHHsE6Enjek42QsMcICAksVZX02TLCSPCFa8pVuT7PSIO90IibzAkjGPiQN2FJQVgGkpv4Ye0gf7OCRIvCjyiJG9oAGEAnO4+9UkkQstkB13l46fgiLilD6kwE0h8sik0h/H6Ow2Dfmyurut64rOhZfINUA4f9yENMM8Iz0BTc+ow1noNmMqp/mJPZ/bPX/eT6ZM1Szn7DIk5p94i4sAELufTkZziuRT6MBlWqlfmVUg9n9bPW8aDvaziXlZG1muBubMyRble4918kV7PzGZTb2qopa5nXfV1Lq5vWsGRPrX76XkOAGasMRVA4joaaptlwtfH77ZEvF0XnLWqnHW7kpRwY2PHsJOpNR7Y//WWHC7xdux0w3F/OJg0SubOK9NmthS5k5BbitwpkwdT2x4fd9e9kKIEcXmpsniE8GQN7PHMKptrV9e0kytJV03azWMVse5GFZmLEelj0al6LH48DGd22VqnOm9xRS4KFbkogx8ms+fhuNJdM5e6bqsqdX1rOho9WKNhwSH2/ZTFpE/RBOLfiIbSYSsbnmfDdjbsxDjj9BTxlceQ+GxXolts4YQCciJKgXB/h9zQI8tTY05UB9XX1As87m2A6dh16/n+R0VbdZ/T/bSbLQ86Absq2E+ygz9bESs0k+qWVRcZ2Tdkn6hptR7jOx9uY9YXL1iHlKOI+qI9GhyCtY9F5zIWkfMbuO4wJmU9IxX1XG+DPPdmXjv4M5nXkONjxsTOe+T737w/MK/d9gwRX5D5IXZFliai7fp4J0NW5u1jvCjy3TPEtKziYegvMM0R/wE) 

Browser: Chrome

Operating System: Windows

**Comment by mramato** [comment] 2020-03-19 17:50
@OHalford-Novetta does this happen in Cesium 1.66, or did it start with 1.67?  We accidentally introduced a regression in 1.67 that has been fixed in #8694 and will go out in our April 1st release.

Can you provide a screenshot that demonstrates what you're seeing?

**Comment by arimbey** [comment] 2020-03-19 18:01
We first got this issue while using cesium 1.62

This is what we expect to see
![image](https://user-images.githubusercontent.com/29377887/77098697-25c22b80-69e9-11ea-926f-d67388f003fc.png)


But instead we see this
![image](https://user-images.githubusercontent.com/29377887/77098785-4f7b5280-69e9-11ea-8002-15402a997d94.png)


We have added all of those geometry instances (1 circle, 3 polygons, and 1 rectangle) to a single ground primitive and used the `PerInstanceColorAppearance` so that each geometry could have its own color, but for some reason the colors over flow outside of the shape

**Comment by mramato** [comment] 2020-03-19 18:12
Thanks, @arimbey.  Unfortunately, that use case is specifically not supported. (@likangning93 can you confirm this for me?)

Basically you can't use GroundPrimitive to batch overlapping geometry.  That's actually what #8694 was fixing for the Entity API layer, but it's still a case for the underlying Primitive layer.  (The Entity API simply has heuristics for avoiding it).

Unless you have other limitations preventing you from using the Entity API, I suggest you check it out for this use case (though 1.67 has a bug earlier and the upcoming 1.68 do not).

I wrote up #8695 to figure out how we can improve this and I'm sorry for the confusion.  Feel free to post your thoughts, ideas there.

I was recently bit by this myself, which is why I reached out for clarification.  Thanks for providing it.

**Comment by arimbey** [comment] 2020-03-19 18:19
Thanks!

We did end up switching to the entity api for this particular case, but primitives are way better performance wise, so it would be great if batching was one day supported. 

Ill keep my eye out for further updates on the linked issue.
Thanks for responding to us!

**Comment by mramato** [comment] 2020-03-26 22:05
> but primitives are way better performance wise, so it would be great if batching was one day supported.

The Entity API actually uses primitives under the hood, so I would be interesting to hear more about your use case.  I'm going to close this issue since the immediate problem has been identified with a workaround, but feel free to reply with additional thoughts and if there is anything we can improve in the Entity API, I'll write up separate issues for them.

Thanks again!

**Closed by mramato** 2020-03-26 22:05 UTC
