### ISSUE TITLE
Incorrect shadows on models with transparent textures

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10082] opened 2022-02-07 16:23 UTC
Discovered this in #10077. While replicating model-related unit tests in `ShadowMapSpec.js`, I found that the cutout test didn't work properly for `ModelExperimental`. I loaded the `BoxCutout.gltf` model as both a `Model` and a `ModelExperimental` in [this sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=xVZbb9s2FP4rgp7kQqVsx2mzxA1WX5oNSLagbjdg0Asj0RZRihRIKrE35L/v8KKLHXXoCgzzg+1z9J37x0NlgisdPFLyRGTwLuDkKVgSResS/WZ1URpmVl4KrjHlRKbh6CrlmbVTGeEEzJw9siI8tL9IFTgXT3e4QoTjB0ZyAGpZG0Bjz+iu0CsqSaap4Mfxl1hq+If5WTRB4zgY+69RG8BaHxu1vjC7NU+jv1IeBHmjvTyJmPLnkU0nSYI7kRPWJFYa4bNk4D0Nk01FMpWssMaJRalkY2tTyULsl7UWtUY7prdp2KvNurgXivrSXpSFtlKUK7KThKjIpPl6Mj1D47ez2ZvJD7FRzGZofD4+ezt+Y8VxykenAdb7ikhaEhjO9wab9mNdnA+FKqoTcvxEcE757p7qrPgoGLMu/bM7rAukxUdAYK6iycV45HwOed7SPck/SFySTxLQWyHLLv1WpRATGWYOJz60NjdAA4m1kDZ+GnIhdZGGsZOeiNJpONC0E8aiCjoInXskCuE8t766aoyB7d4NTNjxyXxqyS5bmsSN1iqgAZLuLweqKE7a1q8lanwEx9SJOz2MoSd592vGaKUEzdHvN5uLWQ8w0Nvm4aiFuVOq2mwds03VaP3L+8XteuWQzyPz+4/8+9dt7RsPtNgcqf+2x0On53/vdwvNBBOyBS6NhBa3n9cvB2KLQRIqP9xDG6kiSBeER9uau80aWcQosL1148sgT4m7mTn5qgeAjS+hgfZi8Cs9g/3BNxXOyNLCly3mqsvaGINN15gpGgevOtEuiBLvXVLoQdTcTGxTFUQSJGF8tYp9fkCLWmkonxMsR/0gPi4qKadlXf4hYL9RpTHPzI0kg1dwWZz3y4Ep21K6NQUMmqGyZppW7LA43AvKtaeIS61HtbivP0nZufaI4SusHVaTjqfpUT79tTk983ddY1AZQn8V/nrawV3jmBBf3jflfC3Doz2O+Y5EPq/YxYttI2F+Xf7+xtxgnmdYaUbM4f4kdjtGFrXWgsMrgxMDf0vCQvZ98+SPg46YNuOCZF9IDpvaEZRuI6/yiuDYvuvCy9Nz1cMf7ZdvszXWzwFc8eTbI69+3nx/6CPjZ/9CEsbhXOkDI9cN4X+kZQWXm7l2IoQSTcqKYSBX8lBDnzTKlGpOxzzpm85z+hjQ/N3Ae1yQMawUPNnWjG3onyQNr+cJ4F+YMmFJ8esjkQwfDKyYXN86JUJonoA4bKmFYA9Ynnj+Gw), and here's what shows up (blue is `ModelExperimental`):

![image](https://user-images.githubusercontent.com/32226860/152817062-d87bf914-ed9d-45fd-9884-67e5196dc6ea.png)

It seems that `ModelExperimental` couldn't handle the texture transparency at all. @ptrgags suggested it was due to the model being a version 1.0 glTF, so I created a [version 2.0 glTF](https://github.com/CesiumGS/cesium/files/8016425/BoxCutout2.zip) with the same concept. This one displays properly for both `Model` and `ModelExperimental`, but it seems like the shadowmapping fails for both. (Again, blue is `ModelExperimental`.)

![image](https://user-images.githubusercontent.com/32226860/152828094-08c42326-8a93-45ee-84b0-d6bce378f7be.png)

There's something about transparent textures in glTF 2.0 that isn't being properly handled by the shadowmapping system. Perhaps issue #9260 is related to this too?

**Comment by lilleyse** [comment] 2022-02-07 20:58
This is indeed a duplicate of https://github.com/CesiumGS/cesium/issues/9260.

Changing the `alphaMode` to `BLEND` shows the correct shadow.

**Closed by lilleyse** 2022-02-07 20:58 UTC
Labels: type - bug, category - ModelExperimental
