### ISSUE TITLE
KML clampToGround disappears on mobile

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7273] opened 2018-11-19 17:02 UTC
Here's a [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=jVVtUyI5EP4rU3xx2OLCgICKrHUesjqciAorq0XVVZhpmEhI2CQD4pb/fZN5YQbFug1UQbqffnu6k5TL1qXATFltkCRcdAcW9jyQ0lLc2vBQWIQzC0sJSo5ZjEEuZ8iHKQ6pOo/AQz4HZn21DmDTDSaXHumTrvv91a3cEFe67L7utd2GO1/+eGh3T5AG/fQv5xrkvjyOOvX+RRA8DSq093pXux7ek96zpx6fbxaPA6fyuLiZ90a9+s3wfv707JLrdnf5pJ31ho+b3mZN8Oib4z7zl5uhW++99qq957vN9A5NflTcB/JfH67okRidEKfisBfhdY57jXYXT/qr8HI0ue0/rau1g9Mxiz8rLKwVgTUIXQqDdUIJeohk9rjgRfs2ZwoTBmJcKJ7GVgqE0KJ78JQ2TczMDrMZBTQVfHEBMwEg7QaqNhq1klWvooZzeFiyGqhxUjmKBMeV4+PU5YSHzCds9mc+a9Wj2OeRc1g3PuuHTiUW1KqRT+01KgMBU0QRkAj7vv1rzCy9GF5A0xoXkjr+EmmYcaEUI7aSppXYmOVxLnSSWIFs5kkoZZCFVgqCaTMtoc0pF2h05Q47aE1UcE6XAbYdVC/mrKaEaospphJyUhlgn6/l1tUg2ve4D+jCHZz/c925yKHhRYnQB/8KyCxQTevQcRzkJIC3MXtLaNFkSw8YaJYTiqLtuz7ccqkBkQZ5mi6B0QzUth/tSNTO+LDzDXzf1DYW+nhtuxptZwIvA+JFjTUCrcLMzoU3TnYcoCCqTPupOY5W7iSnD6yZW/uX5YNUJid9kJt7Iyr+MV4EKFoRR4avOP9w6evabjndzLg579OQecavHQ3VppjOBplaiQgtY3AxPza7KsRDRUnEf9Tw06xDp9nBDJc6cicy/MZFXEY+A4o3ILZRol026itMQ/0z5aKDvcD+LG2zdkpMAWlK5k+cVPlLwuS/C3qBFR7oq9IDRDn27QOEyvo7wIslBaMszxe07APQGUwI+MCQFhyU0rBxx5o705e0sZQiNAfyA8IIUwTV0Yb8Upj+6bMoQjATjlQALKs3I2gfnVqdFJrE8beFxbdFpNckfCmnXVnqYSUSslHWT8M9yJgMM8nn5uVwfbvi1GqNYux9NynLFonBTh8EqFAw63OWU6tS3urP6MyQ/0frFrmP3lT5ls3H/gIzHt+N2p4e5LCnGfSThnwEb1PgOgex1r3J5aEvaC6Kuxc4k5waRmeJNj/qhVKhJdWGwlks/JssllwoKxTU1gOuQA+4uevKk9Cbg0KejC6pVjk1avlkZRH/656n01AqpdZMQ0oH5FU/NWetssbvmJlO69uovwKhj7SGxIm0gsrZdaxCCLXKemvCvrdWnNMJFjnPvwE) that loads a KML file clamped to ground. 

On desktop, everything looks good. On mobile (so far tested on Android Huawei Mate 10 Lite and Huawei P20, as well as an iPad) no KML appears. If `clampToGround` is set to false it appears. 

Not sure where to really begin debugging this. The console shows no errors. [Original forum thread](https://groups.google.com/d/msg/cesium-dev/oHWKqmeWx9o/dpmDl-BIBAAJ)

**Comment by mramato** [comment] 2018-11-19 17:47
Are ground polylines/polygons on terrain supported on those devices?  My assumption is that they aren't and we have a missing check somewhere that's trying to use them anyway

**Comment by OmarShehata** [comment] 2018-11-19 18:14
Ok, this is interesting. I just tried https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Clamp%20to%20Terrain.html on the ipad and all the drop down options work except:

* Draw polygon
* Draw textured polygon
* Draw corridor

Both `Cesium.Entity.supportsMaterialsforEntitiesOnTerrain` and `Cesium.Entity.supportsPolylinesOnTerrain` return true.

**Comment by WilCodeBoer** [comment] 2018-11-20 13:41
Original form poster here. 

The devices we tested on also had both Cesium.Entity.supportsMaterialsforEntitiesOnTerrain and Cesium.Entity.supportsPolylinesOnTerrain return true.

**Comment by OmarShehata** [comment] 2018-11-20 13:58
Thanks for the info @WilCodeBoer . Are you also getting the same results I am on https://github.com/AnalyticalGraphicsInc/cesium/issues/7273#issuecomment-439989992 ?

I think @likangning93 mentioned somewhere that it was likely because materials on ground primitives are not actually supported, even though it reports that they are, and that using the fallback method should make this work. So either creating a better way to detect when it's supported or creating an option to force the fallback would fix this.

**Comment by likangning93** [comment] 2018-11-20 14:09
Related: https://github.com/AnalyticalGraphicsInc/cesium/issues/6739

**Comment by WilCodeBoer** [comment] 2018-11-20 14:14
@OmarShehata I've tested your sandcastle example and I am getting the same results as you are with one exception

Rectangle also doesn't work on my Huawei Mate 10 Lite and my colleague's Huawei P20.

**Comment by Spec1alFx** [comment] 2018-12-04 03:11
Hi!
I just have opened a issue on polyline clamped to ground because there are some rendering glitches when camera is too near / far (https://github.com/AnalyticalGraphicsInc/cesium/issues/7377);
I tried some demo and with the one linked by Omar I encountered his same problem;
so I tried with three different devices, I don't know if it useful but I paste here the results.

Please consider my new issue as related with this one because corridors are the easy fallback of clamped to ground polylines.

Results:

**Galaxy Note 9**
Point with label: OK
Billboard: OK
Corridor: not displayed at all
Polygon: not displayed at all:
Textured polygon: not displayed at all
Rectangle: not displayed at all
Model: OK
Sample line: OK
Polyline: OK with glitches I described

**iPhone 6 / iOS 12**
Point with label: OK
Billboard: OK
Corridor: not displayed at all
Polygon: not displayed at all:
Textured polygon: not displayed at all
Rectangle: not displayed at all
Model: OK
Sample line: OK
Polyline: OK with glitches I described

**Galaxy Note 3**
Point with label: OK
Billboard: OK
Corridor: OK (LOL)
Polygon: OK
Textured polygon: error message "not supported"
Rectangle: OK
Model: OK
Sample line: OK
Polyline: not displayed at all

**Comment by likangning93** [comment] 2018-12-05 20:39
@Spec1alFx thanks for checking on so many devices! Adding to the list, it looks like the Google Pixel (Adreno 530) can handle the above cases as well as desktop. I'd expect similar results on the iPad 4 (A6X/PowerVR SGX554MP4) based on similar tests in #6735, but the gen 1 iPad Pro (A9X) has similar problems with glitches and polygons on terrain not working.

What this problem boils down to is that some devices don't support WebGL extensions as well as desktop, which is kind of hard for us to detect automatically since the devices only report "support" for the extensions instead of how well they support the extensions. We're discussing workarounds.

**Comment by WilCodeBoer** [comment] 2019-01-08 12:52
Hi there, it's been a while since this was posted. I'm still having the same issues though. I was wondering if there were any updates for this problem or if there are any quick solutions.

**Comment by hpinkos** [comment] 2019-01-08 16:57
@WilCodeBoer no sorry, no update yet.  We think the problem is related to precision support on some newer mobile devices, but we have to do some more research into alternate techniques for drawing the geometry.  The only workaround I can think of would be to disable `clampToGround`, but I know that's not helpful if you need terrain enabled on the globe.

I'm not quite sure when we'll be able to get to this, but becoming more of a priority because it impacts several features and many of our users.  Thanks!

**Comment by WilCodeBoer** [comment] 2019-01-09 13:51
@hpinkos No problem, it's good to see that there's time being invested into the problem, the simple prospect of a better future is good enough for now! For now we are thinking of ways ourselfs to get aroun dit but those would definatly not be a fix to this. 

We're also thinking about not adding terrain and simple hover the features a few inches above the ground since most of our projects at the moment are in the netherlands where terrain height isn't that much of an issue. 

Thanks alot for the update

**Comment by damenking** [comment] 2019-06-16 19:42
Hello,  I am having what I believe is the same issue on the latest version (1.58) while viewing on mobile.  Was wondering if there was any update or workaround to this issue.  Thanks!

**Comment by Maarondesigns** [comment] 2020-02-18 19:17
I’m glad this issue is getting looked into. I am attaching some screenshots where this happens on iPhone and iPad with poly lines. When you zoom in the poly line breaks up into a bunch of parallel line segments and they move along the path as you zoom in or out and they rotate to be more or less vertical relative to the screen. Weird. 0_o
![55F5C5BB-E62A-4EBB-B915-9869CFBCE66D](https://user-images.githubusercontent.com/40376601/74769882-30a66680-5259-11ea-9d68-55c5d951bcea.png)
![6019252F-05D4-4900-859D-926B3037124E](https://user-images.githubusercontent.com/40376601/74769892-356b1a80-5259-11ea-9b1d-a3dc631715f7.png)

**Comment by Spec1alFx** [comment] 2020-02-19 08:37
> I’m glad this issue is getting looked into.

Sorry for the straightforwardness, but after 15 months I've given up that they'll solve this bug.

**Comment by lilleyse** [comment] 2020-02-19 14:17
@likangning93 would https://github.com/CesiumGS/cesium/issues/8311 fix this?

**Comment by likangning93** [comment] 2020-02-19 14:21
I don't think so, the main problem is the precision of the depth texture itself.
#8311 should make falling back to corridors more feasible though.

**Comment by likangning93** [comment] 2020-02-19 14:24
I have a test set up here: https://likangning93.github.io/webgl-examples/tests/depthPrecisionDepthTrue/
Code here: https://github.com/likangning93/webgl-examples/blob/gh-pages/tests/depthPrecisionDepthTrue/webgl-demo.js

**Comment by likangning93** [comment] 2020-02-19 14:28
There's a little more information here too: https://groups.google.com/forum/#!topic/webgl-dev-list/O34GBqZBfmk

**Comment by Spec1alFx** [comment] 2020-02-20 10:38
> I have a test set up here: https://likangning93.github.io/webgl-examples/tests/depthPrecisionDepthTrue/

I test it with a Note 9 and a iPhone 6, trying both precision mediump and highp:

Note 9 & mediump: red lines (equally spaced)
Note 9 & highp: no red lines
iPhone 6 & mediump: no red lines
iPhone 6 & highp: red lines ("random" spaced)

I'm not sure it could be relevant but I found that:

https://stackoverflow.com/questions/50256568/why-differs-gl-fragcoord-z-from-pos-z-pos-w-1-0-0-5

**Comment by lilleyse** [comment] 2020-07-28 23:54
The original sandcastle code gets a 404 when loading the KML, but I think this is the same issue as https://github.com/CesiumGS/cesium/issues/6735 judging by the screenshot @Maarondesigns posted.

@WilCodeBoer @Spec1alFx @damenking @Maarondesigns if you have a chance, could you test the branch in https://github.com/CesiumGS/cesium/pull/906?

**Comment by OmarShehata** [comment] 2020-07-29 01:56
@lilleyse I think you meant to link to https://github.com/CesiumGS/cesium/pull/9064

**Comment by lilleyse** [comment] 2020-07-29 12:32
@OmarShehata oh yes, thanks for pointing that out, I fixed the link

**Comment by Spec1alFx** [comment] 2020-07-29 13:20
@lilleyse I'll be happy to test the branch but I need some help. I cloned the repo and then npm install / npm run build but I have the following error:

                ...taskOptions
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
[...]

Can we have a live demo? Thank you

**Comment by lilleyse** [comment] 2020-07-29 20:30
@Spec1alFx - you can test with these:

Sandcastle: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fix-highp-live-demo/Apps/Sandcastle/index.html
CesiumJS build: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/fix-highp-live-demo/Cesium-1.71.0-fix-highp-live-demo35240.zip

**Comment by Spec1alFx** [comment] 2020-07-30 13:33
@lilleyse thank you! I don't have much time now so for now I just tried two demos. I will try all clamp to ground demos.
Current results:

Galaxy Note 9
Textured polygon: displayed, but when I zoom in it partially disappear and then partially reappear
Polyline: OK with no glitches! Nice

iPhone 6 / iOS 12
Exactly the same behaviour of the Galaxy Note 9

**Comment by lilleyse** [comment] 2020-07-30 13:46
Thanks @Spec1alFx, I see the same results.

The polygon disappearing issue is being tracked in #8953

**Comment by cesium-concierge** [comment] 2020-08-05 19:28
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/oHWKqmeWx9o/dpmDl-BIBAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/7273 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by cesium-concierge** 2020-08-05 19:27 UTC
