### ISSUE TITLE
An error with the fit degree problem of KML file loading line segment

### ISSUE THREAD

**Issue by DivinerDream** [CesiumGS/cesium#9975] opened 2021-12-10 15:02 UTC
when i want to add kml in cesium, that wrote it myself，to simulation of road, then find a problem, i add the terrain, tile data and kml, and i want to make the road i write in kml clamp to ground, but it can't work. so i set the "clampToGround = true", but it also can't work
then i modify the source code(KmlDataSource.js). this is a before and after comparison
befor：
![微信图片_20211210221424](https://user-images.githubusercontent.com/44227082/145587732-53757ef4-a5d2-4785-86cb-00d621165173.png)
after：
![微信图片编辑_20211210221511](https://user-images.githubusercontent.com/44227082/145587819-7a462e08-3ea3-4c66-bdd3-9ce8c66075c8.jpg)

i modify the source code in KmlDataSource.js :
`if (canExtrude && extrude) {
    ...
  } else if (dataSource._clampToGround && !canExtrude && tessellate){
    ...
}`
i write console.log() in if, to print something, it print nothing, when i remove the last two conditions in elseif it works. I try to package projects ,error occured, and the size of project is much bigger than before, so there is what i found ,I hope you can provide a good solution
(Homage from a young Chinese developer,Please bear with me for asking questions for the first time)

**Comment by ebogo1** [comment] 2021-12-22 20:58
@DivinerDream Thanks for opening an issue - we've had problems with KML and clamping to ground in the past, specifically with the `tessellate` flag when it's false. I think this may be a duplicate of an existing issue: 

- https://github.com/CesiumGS/cesium/issues/8760
- https://github.com/CesiumGS/cesium/issues/8238

I'll close this issue for now but it'll be mentioned in the other two for future reference.

**Closed by ebogo1** 2021-12-22 20:58 UTC

**Comment by DivinerDream** [comment] 2021-12-23 01:29
OK, thanks for  getting back to me，i will try again

**Comment by DivinerDream** [comment] 2021-12-23 01:29
> @DivinerDream Thanks for opening an issue - we've had problems with KML and clamping to ground in the past, specifically with the `tessellate` flag when it's false. I think this may be a duplicate of an existing issue:
> 
> * [KML lines can only be clamped when tessellate is set to true #8760](https://github.com/CesiumGS/cesium/issues/8760)
> * [KML line positions not being clamped to terrain #8238](https://github.com/CesiumGS/cesium/issues/8238)
> 
> I'll close this issue for now but it'll be mentioned in the other two for future reference.
OK, thanks for getting back to me，i will try again

**Comment by DivinerDream** [comment] 2021-12-23 02:05
> @DivinerDream Thanks for opening an issue - we've had problems with KML and clamping to ground in the past, specifically with the `tessellate` flag when it's false. I think this may be a duplicate of an existing issue:
> 
> * [KML lines can only be clamped when tessellate is set to true #8760](https://github.com/CesiumGS/cesium/issues/8760)
> * [KML line positions not being clamped to terrain #8238](https://github.com/CesiumGS/cesium/issues/8238)
> 
> I'll close this issue for now but it'll be mentioned in the other two for future reference.

But for linear KML loading problems, the lines in the KML file, not attached to the tilted model, when clampToGround=true is set, It's just sticking the KML data onto the terrain, Instead of landing on the tilting model, unless remove the last two conditions in elseif ,by the way, there is a big problem with the rendering mechanism and the memory reclamation mechanism , can you  optimize it?

**Comment by DivinerDream** [comment] 2021-12-23 02:06
> @DivinerDream Thanks for opening an issue - we've had problems with KML and clamping to ground in the past, specifically with the `tessellate` flag when it's false. I think this may be a duplicate of an existing issue:
> 
> * [KML lines can only be clamped when tessellate is set to true #8760](https://github.com/CesiumGS/cesium/issues/8760)
> * [KML line positions not being clamped to terrain #8238](https://github.com/CesiumGS/cesium/issues/8238)
> 
> I'll close this issue for now but it'll be mentioned in the other two for future reference.

@ebogo1 But for linear KML loading problems, the lines in the KML file, not attached to the tilted model, when clampToGround=true is set, It's just sticking the KML data onto the terrain, Instead of landing on the tilting model, unless remove the last two conditions in elseif ,by the way, there is a big problem with the rendering mechanism and the memory reclamation mechanism , can you optimize it?

**Comment by ebogo1** [comment] 2022-01-21 18:58
@DivinerDream sorry for the late reply - 

> It's just sticking the KML data onto the terrain, Instead of landing on the tilting model

From your original writeup I assumed the issue was that without modifying the last two conditions (`!canExtrude` and `tessellate`) in KmlDataSource.js, you were unable to get the KML clamped to terrain. Is the second screenshot your intended behavior?

> there is a big problem with the rendering mechanism and the memory reclamation mechanism

If you have any details about this that you're able to write up in a separate issue, we'll be happy to take a look!
