### ISSUE TITLE
wrong version export in npm package source

### ISSUE THREAD

**Issue by LHolst** [CesiumGS/cesium#9086] opened 2020-08-10 07:21 UTC
npm package of 1.72.0  @ `https://registry.npmjs.org/cesium/-/cesium-1.72.0.tgz`

`Source/Cesium.js` contains VERSION 1.71

```
export var VERSION = '1.71';
```

**Comment by mramato** [comment] 2020-08-10 14:37
Thanks @LHolst I can confirm this issue.

@baothientran Any ideas how this could have happened?  @lilleyse we haven't changed the release instructions recently, have we? Both built versions of Cesium correctly identify as 1.72, so I think this is a mostly harmless mistake regarding order of operations.  Perhaps a `git clean` step was skipped?

**Comment by baothientran** [comment] 2020-08-10 14:48
I just remembered I switched to a different branch and make a build in the middle, then switch back to master. so CesiumJS is not cleaned again

**Comment by mramato** [comment] 2020-08-10 15:10
Spoke with @baothientran offline, we're pretty sure the only difference here is the incorrect version number in Cesium/Cesium.js. 

If we have a reason to believe otherwise, we can publish a 1.72.1, but for now there's no need.  We'll leave this open until 1.73 in case anyone else stumbles on the issue.

**Comment by dzungpng** [comment] 2020-11-10 23:00
Closing this issue since we are on version 1.75 now.

**Closed by dzungpng** 2020-11-10 23:00 UTC
