### ISSUE TITLE
JobScheduler do not support JobType.PROGRAM any more ?

### ISSUE THREAD

**Issue by airchik** [CesiumGS/cesium#10952] opened 2022-12-13 09:40 UTC
It seems CesiumJS has not use JobType.PROGRAM in JobScheduler since using new Model architecture, I just set a debugger such as "jobType === JobType.PROGRAM" in JobScheduler.prototype.execute method, then run some sandcatlse examples;

I want to know the reason why not support JobType.PROGRAM ?

**Comment by ggetz** [comment] 2022-12-14 15:12
Hi @airchik, `JobType` is a private API and is therefore subject to change without a deprecation period. As this is not a bug, I'll close this issue.

Can you give us some more details about why `JobType.PROGRAM` is helpful for your use case?

**Closed by ggetz** 2022-12-14 15:12 UTC
