### ISSUE TITLE
Polygons that contains a Pole are not filled (so not clickable)

### ISSUE THREAD

**Issue by spiderdab** [CesiumGS/cesium#10857] opened 2022-10-17 08:50 UTC
Sandcastle example:
https://sandcastle.cesium.com/#c=dZJPSwMxEMW/ypBTC9ts66GI3RahoiCCQsGL6SHdHWswmylJtmUVv7tJ1/5fDyHz3rzfHDLJyTgPa4UbtDAGgxuYolNVyV+3XkewfKunZLxUBq1g3ZEwwjQML6SXM6psSHFZFB1hYDfhAenRkbnbJ7gm2SQAvpsLQDBfr1Cwm1Ddo/SVDSI5dJdIJXpbx8QeOsVeSNdLMkdY7OdEtlBGenQx9nbowakIsp8M+/PkzBy2uoOrdvu61e79E++1D7805wexL3+aYnt1hWn2wRIm2ChauwOQOV9rnOy4W1WuyHqorO5wnnosVzo+T7qo8k/0PHeuO/oj02M0K9QaVDFu+QyQa+lc6LxXWs/UV1jJJEtD/gKNy1dm+bxGq2UdYx+DyVNjcs6zNMh20hPphbRnk38B

Browser:
Firefox v.105.0.1

Operating System:
Pop!OS 22.04   (ubuntu)

I saw this issue developing in Angular. Sandcastle behave the same.

**Comment by ggetz** [comment] 2022-10-17 14:13
Hi @spiderdab, changing the arc type to geodesic allows the polygon to fill. Otherwise, I believe the polygon appears to not be filled due to intersecting with the earth's ellipsoid.

[This comment has a workaround](https://github.com/CesiumGS/cesium/issues/8042#issuecomment-519591381) that may help.

**Comment by spiderdab** [comment] 2022-10-19 12:47
Hi and thank for helping.
I've tried the Geodesic workaround and the fill was ok with the same polygon:
[here](https://sandcastle.cesium.com/#c=dVNfa9swEP8qwk8yTeV0D2UsbthIu7JS6CClL3UeVOmciClSkM4u3uh3n2QnsdO6BnO635+zuTsJazySWsErOHJFDLySBXhVbdlTi9EiEW2+sAa5MuCKJJ0VpuaOSI58aSsnIDj3rluwd96a6yPFtOWSFoaE518XCCkSbHZQJN/C6SdwrFxIJj27BrsFdE1UHE2ntt9WN2trBrbIC2udVIYj+Ch77jlymoR0OrmcribvwMtR9OLLOPx1FD7/RH4+XvwjuOqT4/GtO7QhDqAwffsZbsDQsjIClTU0Eumhb6V1hMZpqTCk6SyEvB0cA4MKFXhWc12FoMGscRMEZ2fpsOnR22qbUGDM+axWs16uSkL3uyChDAsjaedmu25i6Un1+JzyjDvxGMbc79SPDmC3Nw/XN8tfi8HXhl0h+zVmfWM841LSPo+Ne0tnySQpkrbK4SUk99homB9Kf1fbnXVIKqcpYxnCdqfjVmUvlfgDyIT36f4/8mxozaWqiZJXI/eGCM29D0xZab1Uf8Mmz/Ms6D9Y451RZv1Qg9O8ibLNxfy+AxljeRbScSdaq1+4e1f5Pw)

but if I put a more complicated polygon (taken from a satellite geojson) it gives me an error..
example:
[here](https://sandcastle.cesium.com/#c=rV3bbhzHFfyVBZ8oWGr19XR3JBsJbMdIEMABHOTF9ANNruRFqF2BXMpQAv976qwki8qUEUzBAgRyL1Ps7uk+p851rg77u+PmzW778/Z28/lmv/158+X2bnf/Kvzz9N75xdnV6fWXh/3xcrff3l6cPXp2sX9zebu5vjxefne4v73a4sr3V32zPfz17rD/6tePws3h8vr8Yr/Bv/+8+7HZXJwd377eXpz9Ab/9eXt5vL/Fi8cfP325PbzaHm/f+jd+vejTy/5+uHn78rB/cJl/fnU43F7v9pfH7Z1/7fuPn20+fbF4udk8Sa2EGNvjxQcth55j/fT9Hx7/f7wcrDC8FHpMWcHL3QheDNaHrcdLYea+xKszWGtZwWtjELyBdYhTwcttErweLArTjWEWNl3DsJXbi2XPleC10FpNCl5JbHw1tNwlvJjY7Sihzrl+/bAtOp1vDrWnpuBVej9SqDV3BS81ctxqDDWV9fcX23Z0Mr4yQxnFFDyLZP3KCKWVouCVQsRB6aHk3BS82DPBs5BnEsbXw0iJ4DU/1k3Bw7kieDXk3LOCVwhaCWlWaXSxEmFVckiWhN1nYUS2eimkPBS41thmgZCYgrACXklk+fIMsc2p4NHNl7EpcxM2XwujsPFZmDNmBa9Nsn65hdnqVPDY2c01zDSl6SamynMJYyiyr4YxiSzNOYzai4JnRs5uTpARsSt4tTC8GHovEl5m1C9B5xUT1q+EyXRHgg6YU8LrbHhgQuAgClzL5HQkc0ozFLw8CdVIODXDsoIXOxsfqFDtwnx927LxYR3iTAqe0fU7USEJr9D1AxUqeSp4ia4fKOaswv2ApcCUG5hQawJ1Bh6lkmA0yaI0PnI6uptLijCF3dHJ6MCDSu9DwaPUADJ7DhPubgwjE11ZwX+noisjdBtZPzChHBXpgl1mZDfnEEdUDI8YUiHr58uaBOEMAj8JswITwmxzUfDIdDG6YjYUtEpkFRavN8EKBFxOS6aBewvOJYxuhDmWe8+3XrGmwPW6HJ2fjCyhQZwv0PzcpijNlXAqSBWbTRpcXIpkSLzYBUIAI6+P5eAgkKsJCghwrS5H5/piSIPLhCy7NsupK3CxLufqyrYJyhv2bGejc7eIFQWu1eWJcKpSijS6PJbC2JmUCbITcLCflnAgerEJR6KFbmSfgIdCFCtwdZI7C5bcFVnX3BOwhAOJT1mAgzFGHEpuY1TrCpx1ItjBhUaU4ApZO7fQkkDxAJfSchu7AakYfKVQjgL7dnTBPVDcYCFrB+s7paHA5bxUFO4cqMqZzWESOps7jEDBGAWcJQI3QVAEvyPgmHHmnp8ieJIKbAEShcDb0QQvIa4zQneKk8WpoBWyi92pl5pwJ2KYttwnflaq4NMDnBGPPMRWMkXzRBofgchPU4iPYH+NSdYOylyYK9BaWgpP51RFUDyAYw4uZ7etCXMF7yQCAJYGLL+mwJW8NCnckBTsT5cbxPXrToIUkwJXiX1SC8YsRPkAF9lcoY7KEG4s6NNSmrh7tAlKEWhxLEWne6tNiEBm9/qSuXbAzazARXIjsHl6E04YGObygFWYAIpBAbRIBudBySF4oMAbKrHZW/LYmXAk3IG3RMs+VwktEznccCK6EHgEg2tL0dRwIKwIByJCDC/3XPMTkRS0REhnw4Eodf3KJY/ZksHhQCQFDkS/Lvdwg5IYQoQwecSR3AkoCRMEZ3I6uNx1BiUBvavAxaV6tRTSUNAgS4jFbtl9ZQKcH/+lHLYCiSXQf9jmk00Wf0UJ1SbuLzY30ITElxShEclkWxhD8BNFcBPiYjP3M+T1k40e1FkeCsPbUyBiEXSQpB3YgNAS5lpDJXadQS6sP68Rhg7ZJR06Jwp+7Ah6vTwRPTlZXz24OUIdk6HNtp6rT9yERtw6PbsvYbVomsXjdEs53D2eNVZrsAmVQ6hErx7wWL2BB6Qw0/2Am2X9Bh5Oc4zsEo8tCnAw6VhiRccdGuvN4d5xutjamRsYq+9Ed08CMcK6G2Gr9zDOeDXidAaalfWeBCiDnojTubufYz0Ng5bvJZF94ibiWD1ZsLdmrTC4GtcrCbBy3IhG4QR9DeNtzsRHJ5gS7v6vfLKwrlfLE/c4sZAd4JKQCQoTsReir7FRhq0X7NlJSKWHok7BmMC+S0bhYhP8JjUYS6boHheIghYDCSH+NYi72dfHxLBEabAz6+bE+tiua4REYuOQ7TaEUKxHv4hhBz3mQnolXAtp+4T4nIBm4Ni5gtzlYmvvMAbZy6CwkFNrRXwJozATCpIfnHTtCsKkmCxzBDTFbLXqxmkHzaaEbNRqq9GyJTY2oMXV0Z0JCVWZZnR6t1Yc45BBGlN2h5uwdtlg7MCYpkPr671OHoe0TNHmakIB4TQSA8tuEq9lO8k9y20wtLY+5uRBw9To2HpbvXeTZ2sTg9gZ1fqZZs8ZJyZi9+zgtUPLGYqlTwZW0+oAtkfkIpeZtjqRNzc35+g8ISpXT9QV8qTMP65XhR6PSCTXxM2StjpK5wGlQjxh3TNJV3uaPTQ8R6F6MK8WIKe8lU4NsBFXB66rlysRh+TJ/uprxZFnFlc6UXD+tctWcZUVanzFuFrfA61T9uARitVZiV5mMzql1Ni8bT0auAG5pTNEU8aW+liuG4zZOFYfLE9ObqTyZkCVCnfBrUJiUI8cEtT/erTKyNYo7tds69FSJnn245QqKZyr0WMcs7dhI5FalNEg6dNqQ72FRomrCHdKhMEdLqCnE5uwxvo7QoMD8BW1rKU7VSJHcbstlinldhHzBHuxgcFKmWck7QQHpVk1KS/O2CFutUppcZUZijPA1JHgrFNvTIsa3OhUNtehLB2ksFEju5qS7QTjpFIju9Yija5mahVL+cRYcmY3QTRGDY6UooAXl6HksIwwKzNOikUpdTpFaiKWMrVk586CEyX1JmViMzj3DCrJRDiYRNSZlykUCY7ZO2Zgx0oq5qRJJ+YplUKqQwUzYUEsr7MS0s49MYfEOwz6fSjFml4HM2nwVKrVhAT/jdBusaTAdaInLHoSm1TeMchkG5ioEp70ahZjIXvc1ybV2mSaUBBrleAKOWPNQ+9RqgRqLD/BrT8hZu9lT7GzvJMpVY2lMIjTvmVIaFNqxmKmGTszR60EbRaWTzSU6glPfiM2bZ1YgtkVOOJ58or/WiQ0Y1lnp3QU+72qFavnEyjbpIRIIk/VU/mrVDuaCE90Y7woky2hkCPmVmWcUiVqSzR3EhbbVOAYKcbJM2UTl0BM2+p9RIZUox2JD9ur0WKUSrRZcNfJaFfOf6UH9lRoJGTsn5qg0FznlqS5dqKwvRxFMRO9Wp74egrofxMSO2uj9aIF/F/JO6tO4RrLsC9KvRPgKiGKnnlvQgWgN1botDqhrA/VneA6ySfOMAGiBjeJtyN7ZaBJTT0SSVDMMAFqk5pm5EnLWLJEFN0Xk1mRDUi21HLErLMSoNS0jiOj0QKllEvR+rWw6imQ4qqg5Uxru6SimOph+8kqz2KJUqcbS6zKbk6l+QFoDVm61MO0PhW4SbwdnnxbFEtxeIyS1U/OKBjtnpxPaKzHVZVCkequncJqT0E8JbjOJus1gFnqKMXCd559q7iKQM5ZU5UE81ZqGjG9jxcpee644RIc6+ExQBSHUHnmlghp9oeT14bUW46snHdnUeodgJaJJPbili6oHcDVQWp2QrMuNHsBXCc+QBD50rWlm4XoCc+MFQIUsH8TKbJLofapNA10B8VyslhRqScf4CzTXhYgVUMI7wBwNNa4CEaFkH7mPSsjbSTlrTEFN6WX/LCmgcUbIQmFCs0jQ7SXio05pfkS/9OT5imHgnL0lqRseOa+X0Eke4lTGaxVTjdltsVFCOvj02ftXcEbhKk8OWWCCIZZA9fkbZCGUr8LOGb6eJumYUJxVvOOAEbbSEEFFQVvsiZ/oBczCa7eBsuR5LV5yussRcJrrClfOoWrk4I38qRtzKZSyNeMbxdnqFlBo/1N0wxRqeMFHusB50aB1B4WBhCpbfeWfFFpguA1gLPSloFRSEl3PBYFOWWDd6GbxylC0WjLxSgELgBXWXdTr/GdgqfBqyHo8Lx8S2gS1uZvdITsHkWS8FirFm/QCVOjKXgszf3JqdBf8Oh7VSbrMFm8eZigOoBnlnn/1SK0IDQcq87bwypl84CrrNe2d7pQWjYBb7Jm0d7qogjbxTLtb+qtLopA++zU1Yb2Jk5Z0LxWQma8qvjpELyYXhplhfZ2TorbwePkbdDe03EKlj3wOhP2HqbvghPY0wIm792N6TYFb5D4vpdNRaVdiEH3sl7bp1iY0HofeJOYvI43h8CErMPsmLTX+2xCeMRzUhLvRT+T0KsKeINJP3fCdoHY2wTzq7SV/1Ckc4e0Z0zSHWJDmK/jGccbCrny6mqKNz1Pqir7hZENb8mvKA8/bZU+SCIVgelapbl+jlemJk0Hh7MmUDVXHoPCjSHY5K4qKV7yVupdwaPtZv3xF6bIghgqc+E0byYsMBcwNWN72X1PMUlEnDU4OT0WpQm5nN4tJPP7MZROODA8KtO97srKUbIqjXEN4OFvFQUvJqN42QTd61Z+5HhlDslLUuj+85ybIfnAKmP2/nidZpIPbMVjfh6+fPDi119/effL6Yc/Geli//G5SOH403Z//uJ+f3XcHfbn/sGjDw80enG43Zz7Y5R2m8838Rl+PD89USls98fdcbe9C28ub+7x42a7f3n8CV/47LNHD5+G5NeevvsWAOzK73c/PPv49d2Lzfn7hzRdb1/s9tvr83dXh9fvHqX06BN0//fp5+Hy9uofb18/eNjTn969Eb75+tuvvv7uL18++GsPV2Xz/vlS4ePC3IXL6+vzj6994X559Ozs8dnF2Qnlw//N5vnd8e3N9osP0H/cvXp9uD1u7m9vzkN4ety+en3jj3t6+uP91b+2x3B1d/fo/TieP3146fPr3ZvN7vpz8kCrzdXN5d0dPnlxf3Pz3e7f24uzL54/xfcXl/rDrHb7l9++2d7eXL71r/2UvvjbuzdDCM+f4iW/8ng43Px4efs/yP8F)

I also tried to reverse the points order (maybe a problem with anticlockwise..) but the result is the same..
Any idea, where the problem is, here?
p.s. the border seems correct.. it is just the fill. I have put the same coords in Mapbox and they look ok, so I think the numbers are correct.

**Comment by GatorScott** [comment] 2022-10-19 15:12
@spiderdab I suspect that the original representation in 3D did cover the pole, but the 2D data in the GeoJSON does not.  Below is an image from QGIS showing the poles and the points creating the polygon.

![image](https://user-images.githubusercontent.com/4126790/196723624-a2f57fbb-344c-470b-8559-fc7276ebbb18.png)

Obviously still a problem, but not due to covering the pole.

@ggetz Is there any "Inspector" for polygon triangulation to help see what's going on or a description of how filling works?

**Comment by spiderdab** [comment] 2022-10-19 16:28
Indeed I think that this satellite returns a footprint with a hole around the pole, so I was wrong with the issue argumentation..

**Comment by ggetz** [comment] 2022-10-20 13:03
> Is there any "Inspector" for polygon triangulation to help see what's going on or a description of how filling works?

No, but that's a good suggestion @GatorScott! I'll add that suggestion to https://github.com/CesiumGS/cesium/issues/4871.

@spiderdab I do think the root issue here is a duplicate of #8042 as part of fixing that will need to include [special consideration around the north and south poles](https://github.com/CesiumGS/cesium/issues/8042#issuecomment-534214829). The overlapping in the second example (as @GatorScott alludes to) is likely a separate issue with [triangulations for large polygons](https://github.com/CesiumGS/cesium/issues/4871). As a workaround, [users have had some luck by breaking up larger polygons into smaller ones](https://github.com/CesiumGS/cesium/issues/8042#issuecomment-777905254).

If you agree, we can close this and move this discussion to those issues.

**Comment by spiderdab** [comment] 2022-10-20 16:33
Thanks for your answer and suggestions.
Yes of course it can be closed.

**Closed** 2022-10-20 16:34 UTC
