### ISSUE TITLE
camera.flyTo goes underground 

### ISSUE THREAD

**Issue by angrycat9000** [CesiumGS/cesium#10555] opened 2022-07-15 13:48 UTC
`camera.flyTo` ends up underground in a location where the globe does not have a height.

The expected result is that that camera flys to 100 meters above the ground at the given location and the vehicle is visible on the surface of the ground.

[Sandcastle example](https://sandcastle.cesium.com/#c=hVNdb9owFP0rVrSHIDFnDKoNGtAmkLqHrlQt614stca+BGuOjWyHilX89zk2MMKYeIl8zz33w8cnTCvr0FrAKxg0RApe0RisqEr8FLCUJCzEY60cFQoMSdrojSiEHBjjkXuj14KDGewLmQHq4Kc2ks8iJW21idq2rokiioWBUqtCuIrDBAoDYP3oTq+PrzpX3e7H6wOLuhPS+24P9z/3PvX7R81W2gontPL53Qpjapw/UdXFC6PLXX1ab306uR3A5qCAfSDqeGNQnrLxI6JWOMQCLKacp0GP/RqDwyn0KTUHOYiSIVQZMUAkwTh7pOVKwoQ6mgWKzW6MrhR/gqVgEpoRLuTcCx97LEEUS/cACzCgGByE/9bE8fj26/f759n0+eZh+uNuEqq3py/BvFS6MHTl5zQF3KOXJUQXNZTg9n6JW/4V0jJQ9f303H/BxXR6vFZrZwjtdZC6SF8anYbv3hrx9iWObLRntARD8UJuZjq+FgfrhKLxwS7b5j/GOX/tcHGEDq5P2klu3UbCKGYR+iLKlTbO20Gm3gsOvBf8T2OzecV+gcPM2rqwpubZcWnOxRoJPjzzWyImqbU+s6ikfBS/gSSjPPP8f0qlplyoYroGI+mmpi07o9sIYozzzIfnK53Wck7NSec/)

Browser: Chrome 103.0.5060.114

Operating System: MacOS

**Comment by mramato** [comment] 2022-07-15 14:00
Regarding:

```
let terrainHeight = viewer.scene.globe.getHeight(cartographic);
console.log(`terrainHeight=${terrainHeight}`);
```

It's correct behavior that `terrainHeight` is undefined here because `globe.getHeight` only works with terrain tiles that are actually loaded and only suitable for querying data as-is on-screen.  You need to use the async `sampleTerrainMostDetailed` to get the true height of terrain at a location, which will definitely return a height.

I still think there is a bug here because flyTo should not end up underground, but you _are_ telling the camera to fly underground so we should clarify exactly what the official behavior is supposed to be. I expect the camera terrain collission to handle this though and pop you up above grown at that location.

If the goal is to fly to the entity, you should be using `viewer.flyTo(entity)` but the biggest issue here is that `viewer.flyTo(entity)` doesn't appear to work either when heightReference is CLAMP_TO_GROUND.

The below tweaked code demonstrates what is going on here. Click `FlyToModel` and it will be incorrect. Click it a second time, and it will be differently incorrect. Click it a third time and it is correct.  There is clearly a race condition going on involved with clamping to ground.

```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  terrainProvider: Cesium.createWorldTerrain(),
});

const longitudeDegrees = 149.515332;
const latitudeDegrees = -34.984799;

const position = Cesium.Cartesian3.fromDegrees(
  longitudeDegrees,
  latitudeDegrees,
  0
);

const entity = viewer.entities.add({
  position: position,
  model: {
    uri: "../SampleData/models/GroundVehicle/GroundVehicle.glb",
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
  },
});

Sandcastle.addToolbarButton('FlyTo Model', ()=> viewer.flyTo(entity));
```

**Comment by javagl** [comment] 2022-07-17 13:53
<sup>I'm occasionally thinking "Well, athough I'm not familar with CesiumJS, I'll have a look at this bug - it cannot be so hard..." (and I'm  regularly proven wrong...). But even at the risk of distracting others from the _actual_ cause here, two observations:</sup>

When enabling
`Cesium.ExperimentalFeatures.enableModelExperimental = true;`
in the last sandcastle, then clicking the "FlyTo Model" button _does_ reliably zoom to the model: 

![Cesium FlyTo Result](https://user-images.githubusercontent.com/5597569/179401291-6709055f-f7a0-4627-a895-d0576595b395.gif)

But... the model itself is underground. 

I started diving into the rabbit hole of comparing `Model` and `ModelExperimental`, and noticed that `ModelVisualizer.prototype.getBoundingSphere` computes significantly different bounding spheres...

![Cesium FlyTo](https://user-images.githubusercontent.com/5597569/179401565-a58d7328-d696-4caa-9142-dc7a3feea490.png)

Even though the `model` has the same `modelMatrix` in both cases. I haven't been able to figure out the reason for that one, but maybe someone can narrow down the search based on that...

**Comment by lilleyse** [comment] 2022-07-18 12:52
@javagl are you on a commit pre-https://github.com/CesiumGS/cesium/pull/10395? @j9liu might have more background here.

**Comment by j9liu** [comment] 2022-07-18 14:13
I'll look into this later today. It's strange that `ModelExperimental` doesn't seem to be accounting for `heightReference` at all; the model stays underground the entire time.

**Comment by mramato** [comment] 2022-07-18 15:51
I labeled this next release, since ModelExperimental seems to add an additional regression on top of the existing problem.

**Comment by j9liu** [comment] 2022-07-18 21:07
I confirmed that `heightReference` works when directly passed into `ModelExperimental` via #10448 (local Sandcastle for proof). It works for the ["Clamp to Terrain" sandcastle](https://sandcastle.cesium.com/#c=7Vrrc9q6Ev9XdPPJTKnwE5s07VyS0J7MIZAhnHY6pdMxWIBujcVIImnayf9+V36AX+TRXs49H9rpBCztSqvV7m8f5owIulnh3rc14XRFIumHb4kvN5wITCJ/GpJLFpAwP49eI8k35NUkmrFISHRDyS3hMBqRW3SWrPc+HtMmR7P4+YwBI40Inxw10Y9JhJAknMPIFWc3NCD8OGOccdidfGA8DMYJidZoTqL7BmyXbITFjEQEL0I2JTgga7kcEyG7CyAVMuXZiTiJrv0omPlChgT7QXBO5v4mlGPGwqnPL0m00ZQ4n9QfhJK/P5IPJeQ3eYwmR+fcv0WxHkD+bBLOTkIyA4L5JppJyiKkNXa8CCXaISBLKjhoj0oKigU5tBwhQmsmqFphq4Yzn0v45kcWnnO2OicLTojQXhqmiY2O4zWR3YYvhtNo5tdZKRmPUWFthDacqlNg3Lr2V+uQnPvSb8WkopXsd+lH6bcv8BV0O80dNPm3JHSxlCMyJ5xEM7KV9I/iOD7rdy+vvoyHX96Nhn8NzkurrGhEV5vVFf1Gwmv6HZYxTK9M439TNNczP1Tzul6Yv889xVaxe0zVLLk/+0qCntL2HWhfmUGRN/vc6qnV2n1DY4ZmISgKboVGUiDG0ZSG4ZT5PBBIEInkkpT1gSRDpaMrxlGv3x1fvO/tRqtbFqzsSu2Jbqlcor4//ccbXKyiisHNWMh2Ln2mnvD1nx9P+3/1Sne9zhmCXppjGxkCZpzVLPax1+8PP9TTf6CBXB4j6wD2e194CtX9VM6e3eaZMiESKLtYcLaJgopHzVkUUxr2WiLhR+KlAIydH8jzlozT7wqGwyGnC7q7+T9KE7jfezsuMd8QLumswvq+MIxPu9e9/sWgfMdzcJ66Szztd8/+LNGKJbs9BfdNVHYco3iJZLqdThfNhZ14RDOaKPmvY7exl/sKnIJGiyJ/5gWmpiy+zBxQoSLieRZ0zqmQfnwlg81qCg53Nby+iN39YvD2YnAx/thUgBKAY4sYNGKTQRCfwMfAzdk8i4MHR7gCyJxmcPYPR5ct7Fa8jK78BUmDWvxdtOb+jIagD7w4kA8dPvKcMc5pwLhoggrDuwVoHEH2gjjcix8tQiIgMoQhmpIkQgG8+BvJVn7sheEdonNlZnfI5yR2OyCIQ4mf3J4PNhdjs1o1t+/SFyhiqZJU2AJj4ZsAuJMhnKMdDMe9Y3RNpATnyVgA5PREtNRFEvmAAj8S77IjH8gSZ+nyFQPKTFQ8YqNdcM877VORGaHUcpvl8cSM7WYtvWnU0deMJtTWk6g/l0HqNol/pq7rWK+kVoA31A9LSPxu1OsNsLKUbrhe+pqOS474uOl/Z2w1ZhppPBOKrhI7PxgQxatXbn9JCff5bHlXmSlYRuXaUW2wsLQqHVyiaTmeYXnYs13L1k2ves8xmeXatu6a2HY6jm3AUy2ZDWsZjocd17AN17Fcp0rVaP6qvK5pGdjumLC+3tatvQI7hm5h1/Pabd00PGefxLqrm7jjOq7bNtvWQSR2OgZsoZum7tjWAxo27Q7WzY7rerazV8MmXBM2YCHXgwMeRsG6B3LoHccBjbT3ygsHszBIrdueZzxgEp22gb22ZcJNmJ2nCPy5NHL/NIRQqfv/ByDG8LDhEIp+AikgHBZu4l/pmZIAjcVmvWZcisv0zGLOeC/FkmGUtR9KmXCuB5GfaeweGkVMuaVRwG4xFLNclhabHGX9ijRlyLQv4ggeMagLEhnh/HA6uaQCrUNfgqCryVFh/1f5J05AZ1Fu6D5/I78B9DeA/gbQgwNovjhJm2t9tmBfEkT9z3pRqVIgaRaCziGZV/4zvlvvCpWzyhQe90aj7sWgXEHLEZN+ofoCfFtiyUZ+AKoVmv23Yfcoq1sOlN5t66KaDhTjUN3DXewS/K00hRq0NveuTb31+jxdr6Mt2X7jaVF21Dv/24Ns0hJGqnO2Q+646lRti6R8jLvswAH3ktZ3P9E5CEm0gFVeq46u/qoaj6A85bLPVO++3m69Nu4ArnasfKxLrSUKHuH0Om274zZq9oVwupfRdHHH80ynljFt3SQKvNqq7jX69DknIIRqpIVEIgoz+iv4OElV8Qq9eEFLyUIqUuUskDysS6aanLni/YkSS8MUtZQQ8QW8REZjf+aQCJAZQvGljoJntuD+eklnGsjYVLorstfrBK83Yqllizb25SVX4JZUEMyJYOENKZw3FUHEC6dZ0yUT8pxIn4I91qdppbdMzXKrtk7YfVkdlksSaTsTT0QRpQtUN83mc/WWQFk61gvqqTOGdB283yhQRvOJfsZpx+XF63SbwvoFdaLHATRJ8JTvP5zHZXlzGNK1YDTAH95dezae5QwibpSM2TaEJ42TakRNj1KeqAZaSC8LEbCbPOPBsNJh3jY9qonUDmlzhnyVHnqYvDHI8n8wkzUk6Xfaj6rYda80hqPu4F2vJrUovokw91M8tS2u8L4yFKPyW7D+y585Y1WmH3U5Ut25IUzV5lOPH/snDh4b9cO2UkzBSpFxi9Y+X8RO+ZR809J114X4q3uQ0HsdyysnkE7bslXibFiG1YE8smx4kCh7hmNiyCsdB7J9o70fcrdw8RTJYF8bKgJb73ht13PaZS2/hPiILdvouB1PV5lvOaWHPL4DcVSH2kN325bRNvdLluLHzF9BtYdDxr52pZYospmK/TjDmEMkVQWrtgtonH6z8cV5bzC+GH8sxIPnppgZfsXlcfou5Zkdgj1dgcyBcq2AfPHfeE6Zv10rJ+Yvlfj3Ncnfw1V8Lcj/Yhd8m5FVvFYlTqZKnJrP4/H28ST525N5Kl3x+H3EmL3b/15xTwj53wSQZ4SPx1D0mQh6/+Qa4tk4+QhKPoyRDyFkNcF/BkY+jJCP4OND6JiX6pnI+Iu4WITCpAMxOVLF3ulGSpWzAlA0yr92gjQ6VlkF+sp4wcmK3ZBuGGpqjft4naPm0YmQdyF5kwnxb7pSMIU2PNQwbkmyUjBFRGu6mX0lEs+EyCQ+aeVZTwJ6g2jwuubHYEnHA2bmmzD+Gcjk6M1JC+grrCHz1dv64Q3hoX+nyJbGm34yiDE+acFjPadMfuoFLNlJcnNpIUGiTWnnPFVB0XupIBNehKSvsnOQ6QHCJAOuXzD//b8) but changing `viewer.trackedEntity = e` to `viewer.flyTo(e)` reproduces the buggy behavior. I'll have to see if there's something in the entity API that `ModelExperimental` isn't interfacing with correctly

**Comment by ggetz** [comment] 2022-07-19 16:16
> I labeled this next release, since ModelExperimental seems to add an additional regression on top of the existing problem.

@lilleyse Does it make sense to address both the model experimental "regression" and the underlying problem at the same time, or are these two distinct problems?

**Comment by lilleyse** [comment] 2022-07-19 18:11
@j9liu is going to open a PR with the fix mentioned above so that `ModelExperimental` behaves like `Model`, but there's still a separate underlying issue.

**Comment by j9liu** [comment] 2022-07-19 21:09
I opened #10571 -- the camera is still bugged, but at least it behaves the same with `ModelExperimental` and `Model` now.

**Comment by sanjeetsuhag** [comment] 2022-08-03 14:44
Here's some of my notes on this issue so far. 

<details>
  <summary>How does <tt>HeightReference</tt> work with <tt>ModelGraphics</tt>?</summary>
  <ol>
<li>When the <code>Entity</code> is created, the <code>ModelGraphics</code> object can be assigned a <code>HeightReference</code>.</li>
<li>Per-tick, the  <code>DataSourceDisplay</code> calls the update function of each <code>Visualizer</code>, including <code>ModelVisualizer</code>. This is where the <code>Model</code>/<code>ModelExperimental</code> object is initialized and all relevant properties are propagated, including <code>heightReference</code>. The <code>heightRefence</code> is not passed into the constructor, instead, the public setter for the value is used.</li>
<li>Per-tick flow for <code>ModelExperimental.update</code>:<ul>
<li><code>updateClamping</code><ul>
<li>Check if <code>_heightDirty</code>, which can be set by any of the following:<ol>
<li><code>heightReference</code> public setter is used</li>
<li><code>scene.terrainProviderChanged</code> event is raised</li>
<li><code>getUpdateHeightCallback</code> is called</li>
</ol>
</li>
<li>The cartographic position of the model is computed</li>
<li>The <code>getUpdateHeightCallback</code> is registered with the <code>QuadtreePrimitive.updateHeight</code> function to be called (from the <code>endFrame</code> function of <code>QuadtreePrimitive</code>) whenever a new tile is rendered that contains the cartographic position of the model. The value returned from <code>updateHeight</code> is a function to be called to remove this callback from being called whenever <code>updateHeight</code> is called.</li>
<li>A new Cartesian3 position is computed from the the current <code>height</code> for the cartographic position of the model, which is obtained from <code>globe.getHeight</code>.</li>
<li>The <code>getUpdateHeightCallback</code> is called.<ul>
<li>The <code>model._clampedModelMatrix</code> is updated with the new position.</li>
<li>The <code>model._heightDirty</code> flag is set.</li>
</ul>
</li>
</ul>
</li>
<li>The <code>updateBoundingSphereAndScale</code> updates the bounding sphere from <code>model._clampedModelMatrix</code>.</li>
<li>The <code>updateReferenceMatrices</code> updates all relevant matrices from <code>model._clampedModelMatrix</code>.</li>
</ul>
</li>
</ol>

</details>


<details>
  <summary>How does <code>flyTo</code> work with an <code>Entity</code> with <code>ModelGraphics</code> with <code>HeightReference</code>?</summary>
<ul>
<li>The <code>zoomToOrFly</code> function cancels any existing zoom and assigns a new <code>Viewer._zoomTarget</code>.</li>
<li>Per-tick flow for the <code>Viewer._postRender</code> function:<ul>
<li>If the <code>_zoomTarget</code> is an array of entities, loop through all the entities.<ul>
<li>Check the <code>DataSourceDisplay.getBoundingSphere</code> for the entity and see if the state is <code>BoundingSphereState.DONE</code>. If it is <code>BoundingSphereState.PENDING</code>, the function returns.</li>
</ul>
</li>
<li>Compute the bouding sphere from the combination of bounding sphere of all entities.</li>
<li>Clear the current zoom in flight.</li>
<li>Call <code>camera.flyToBoundingSphere</code>.</li>
</ul>
</li>
</ul>

</details>

**Why does `flyTo` go under the ground when called for an `Entity` with `ModelGraphics` with `HeightReference`?**

If the camera is far away, the bounding sphere computed for `Model`/`ModelExperimental` will be based on the lower LOD terrain tile. This initial position computed will be enough to complete the `updateZoomTarget` function called in `Viewer._postRender`. Essentially, there's no correction for the recomputation of the bounding sphere based on the higher LOD tiles loading during the flight of the camera to the initial position.

**Potential Fix 1**: Store the current target bounding spheres that are being flown to and in the per-tick update of Viewer, check if they have been updated. If so, update the bounding sphere the camera is flying to. The issue here is that there needs to be some sort of termination condition i.e. at some distance, we're close enough stop receiving height update and finish the promise. I tried implementing this one and it seems kinda clunky. Having to cancel and begin a new camera flight doesn't look very nice.

**Potential Fix 2**: Compute an estimate of the bounding sphere in the model that uses `sampleHeightMostDetailed` and use this as the initial bounding sphere for the `flyTo` function. This is the one I am currently pursuing. The code changes here are so far limited to `ModelVisualizer`.

**Closed** 2022-08-09 23:54 UTC
Labels: type - bug, category - camera, category - entity
