### ISSUE TITLE
Transparent background affects billboard visibility under it. Even though you give 0.01 opacity for label background.

### ISSUE THREAD

**Issue by onderaltintas** [CesiumGS/cesium#10745] opened 2022-09-01 11:41 UTC
This problem exists since 2018-2019 or such. 
sandcastle:
https://sandcastle.cesium.com/#c=tVLbauMwEP2VQU8OuHJDGtLNpmFbpwtlTVvavbwYimxPbFFZMpKc9EL/fSUncUM2r4tl0Jw5Z3Q0o1xJY2HFcY0aLkDiGmI0vK3p7w4LUpJ3caykZVyiTsngayr9B1sdRWm55WgoK4rg3ScAGmUcpuR0Vy9m2rodkyO61KpeYKkRTXAyGdPxl8lkEsLZKT0dnZ+PBuGmRMaFyBTTxRS2RQF4zUqcQkoojbq9iaTSNRM1a2gjy5RsmB9djQ9v9T+7FCxDsefQ4ov1Bu8rLliBoqk4S0m4Sy/dpWIllP480kf04XrRc1RrhWv1MdpVchn/OCT+4YWtpjDucWNfBfbKxDt89BD9fpMkT5e3i6e7Xz+Tm9vrT0Wl1lcsfy61aqVruNUt9smsT2wt7T2TDgmGIWyWa85wcDAAEpKU+EHA7geYdRbnuxO+8bpR2kKrReAma7FuBHODiLI2f0ZLc2O6UXpltC+dFXwFvLg48kwhF8wYl1m2QjzyN0zJfBY5/j9SoVjBZXm3Qi3Yq6dVw3myASmls8iFx5VWKZExfVD5Lw

os: windows any
browser: chrome recent
Reason of fix request:
You cannot pick labels easily and have to hit exactly on letters when you do background: false. Lowers user experience. If pick algorithm would be fixed for labels, no need to fix this one for me.  

Edit: Same problem doesn't occur on normal billboards, so there must be a missing part in label's backgroundBillboardCollection:

https://sandcastle.cesium.com/#c=zVJBasMwEPzKopMD7johDW5dJxTcY6CHQk+GINsbV60sGUlOSEv+XstOILS59VIWgXZ2ZtgRKrWyDnaC9mRgCYr2kJEVXYOvAxbkrBz6TCvHhSKTs8lDrnzBSYeknHCCLPKqCr78AKDVtse0Ss5+GTeuv3E1x63RzRPVhsgGN/ECF/dxHIdwO8Xp/O5uPglHi0JIWWhuqgROpgCi4TUlkDPEaLjbSGnTcNnwFltV5yw8U0sttUkuEmUeCGahrykuJiPxOAiOPtT/yDP6b9a61pthZXxv/5KLhSxnPh2cD0Bq3UHS6mz5KJpWGwedkUG/iKOmlbxPFxVd+UEOS2uH9/HK6FKaVmIHolpe+SVQSm5tP9l2Ur6IT8rZKo16/i+p1LwSqn7ekZH84Glvs9V6BBExjfr2utJpLQtufjh/Aw

**Comment by onderaltintas** [comment] 2022-09-01 12:07
Seems like the problem was there for polygons and such as well. This guy reported the bug for polygons in 2020:
https://github.com/CesiumGS/cesium/issues/9001

**Comment by ggetz** [comment] 2022-09-02 13:33
Thanks for the report @onderaltintas! This appears to be a duplicate of https://github.com/CesiumGS/cesium/issues/9001, so I'll close this to keep the discussion in one place.

> You cannot pick labels easily and have to hit exactly on letters when you do background: false. Lowers user experience. If pick algorithm would be fixed for labels, no need to fix this one for me.

This is a good insight, thank you for pointing it out!

**Closed by ggetz** 2022-09-02 13:33 UTC
