### ISSUE TITLE
Cesium fragment shader error for displaying billoards

### ISSUE THREAD

**Issue by heinerlamprecht** [CesiumGS/cesium#6911] opened 2018-08-13 12:29 UTC
I'm using billoards for my entities. On MacOS, they are properly displayed, but on Linux, webgl crashes. Sometimes it is enough to just kill the browser, sometime I have to kill X completely.

Sample code:

```
const entityOptions = {
    id: id,
    position: position,
    billboard: {
        image: '/assets/symbols/symbol.svg'
    }
};
this.viewer.entities.add(new Cesium.Entity(entityOptions));
```

I do get the following stack trace:

```
f         @Cesium.js:formatted:45195
y         @Cesium.js:formatted:45312
d._bind   @Cesium.js:formatted:45369
G         @Cesium.js:formatted:78362
k.draw    @Cesium.js:formatted:78607
n.execute @Cesium.js:formatted:43787
Ge        @Cesium.js:formatted:106273
Xe        @Cesium.js:formatted:106363
tt        @Cesium.js:formatted:106661
$e        @Cesium.js:formatted:106575
ht        @Cesium.js:formatted:106889
pt        @Cesium.js:formatted:106900
xe.render @Cesium.js:formatted:107294
A.render  @Cesium.js:formatted:115880
t         @Cesium.js:formatted:115580
```

Cesium version: 1.48.0

The error was introduced in Cesium 1.45. Version 1.44 works properly, 1.45 crashes.

**Comment by hpinkos** [comment] 2018-08-13 15:15
@heinerlamprecht can you please post the stack trace from the unminified version of Cesium?
Also, can you paste the results from http://webglreport.com/?
Finally, try setting `viewer.scene.logarithmicDepthBuffer = false` and let me know if that fixes the crash.  Thanks!

**Comment by heinerlamprecht** [comment] 2018-08-14 08:09
@hpinkos, I tried to reproduce the crash with the unminified version.  However, even after several attempts, I wasn't able to get a stack trace.  I always had to forcibly kill the X server, so I had no access to any stack trace afterwards.

Setting `viewer.scene.logarithmicDepthBuffer = false` fixes the issue.  Unfortunately, that wouldn't be a solution.  I'm using Cesium in an Angular/Typescript environment and the compiler always complains that this property is not available on `Scene`.  So it's only possible to run in development mode (unless I patch the type definitions myself).

Besides, I did a bit more testing.  The issue only occurs on my Chromium (65.0.3325.181) on Linux.  On Windows and Mac, I used v67 and v68 without any problems.  In addition, Firefox (52.7.0) on Linux also works properly.

Here are the results of WebGL report:

![webglreport com__v 1](https://user-images.githubusercontent.com/42345124/44079388-2ade56d6-9fa9-11e8-962c-a15284c337a6.png)

![webglreport com__v 2](https://user-images.githubusercontent.com/42345124/44079391-2f607162-9fa9-11e8-923e-dbdb4e52ff2c.png)

**Comment by hpinkos** [comment] 2018-08-14 18:36
Thanks for the info @heinerlamprecht!  Regarding setting `scene.logarithmicDepthBuffer`, our team doesn't generate an official TypeScript definition file so it's possible that whatever you're using is outdated needs to be updated to include this property.

@bagnell it looks like this is related to log depth too.  Any ideas what might be causing the issue?

**Comment by bagnell** [comment] 2018-08-15 20:25
Also, are your drivers up to date? Since the browser hangs and the only way to exit is to restart X means there's most likely a browser/driver issue.

**Comment by heinerlamprecht** [comment] 2018-08-17 11:09
I can check with our IT guys (still waiting for the browser update).  But Firefox on the same maschine works.

**Comment by heinerlamprecht** [comment] 2018-08-22 07:54
Meanwhile the Chromium browser was updated to version 67.0.3396.79.  Although this does not fix the issue, I managed to get a more useful stacktrace.  The error appeared after I killed the GPU-process of chromium.

Again, setting logarithmicDepthBuffer to false works as workaround.

![chromium_cesium_error](https://user-images.githubusercontent.com/42345124/44450468-4f3e8980-a5f1-11e8-97f5-742b74aec6b3.png)

**Comment by hpinkos** [comment] 2018-08-22 20:32
Thanks for the extra details @heinerlamprecht 
@bagnell is working on fixes for a few other logdepth related issues, so we'll add this to the list too

**Comment by kring** [comment] 2020-02-24 11:34
@heinerlamprecht if you're still having this problem, are you able to check if #8600 fixes it?

**Comment by mramato** [comment] 2020-06-03 15:01
Closing this because we think the issue is most likely fixed.  If there are still problems please re-open with details for reproducing it.  Thanks.

**Closed by mramato** 2020-06-03 15:01 UTC
Labels: category - graphics, type - bug
