### ISSUE TITLE
support vite

### ISSUE THREAD

**Issue by mioxs** [CesiumGS/cesium#11395] opened 2023-07-06 00:49 UTC
https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Core/Resource.js
 
not use node module,and Vite doesn't support CommonJS files.
https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

**Comment by ggetz** [comment] 2023-07-06 19:40
This is a duplicate of https://github.com/CesiumGS/cesium/issues/11306.

`https`, `http`, `zlib`, and `url` need to be marked as external when building the library from source. We also maintain https://github.com/CesiumGS/cesium-webpack-example as an example of how to configure webpack-like builds.

**Closed by ggetz** 2023-07-06 19:40 UTC
