### ISSUE TITLE
Edge and IE lose context to 'Window' with webpack-example

### ISSUE THREAD

**Issue by e-dong** [CesiumGS/cesium#8383] opened 2019-11-11 13:26 UTC
# Observe
1. `Clone` https://github.com/AnalyticalGraphicsInc/cesium-webpack-example  
2. Replace cesium declaration in the `package.json`:
*Replace this*:
`
  "dependencies": {
    "cesium": "http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/no-import-meta/cesium-1.62.0-no-import-meta32711.tgz"
  },
`
*with*:
`  "dependencies": {
    "cesium": "^1.63.1"
  },`
2. Run `npm install`
3. Run `npm start`
4. Navigate to `localhost:8080` using IE, Edge, Firefox, and Chrome.
5. Observe the following:
IE & Edge report a Web GL problem.
FireFox and Chrome has no issues.

## Error in IE & Edge dev console:
` Error constructing CesiumWidget.
Visit a href="http://get.webgl.org">http://get.webgl.org/a> to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:
TypeError: Invalid calling object
TypeError: Invalid calling object
   at requestAnimationFramePolyFill (eval code:68:9)
   at startRenderLoop (eval code:93:9)
   at useDefaultRenderLoop.set (eval code:549:25)
   at CesiumWidget (eval code:354:13)
   at Viewer (eval code:417:9)
   at componentDidMount (eval code:65:9)
   at wrappedMethod (eval code:704:7)
   at commitLifeCycles (eval code:21963:13)
   at commitLayoutEffects (eval code:25287:7)
   at callCallback (eval code:363:9)`

# Work Around
Edit `requestAnimationFramePolyFill` function in node_module code:
cesium/Source/Core/requestAnimationFrame.js

replace `return implementation(callback)` with:

`var boundImplementation = implementation.bind(window);`  
`return boundImplementation(callback);`
`

This works because the context within `requestAnimationFrame` is lost for some reason before function call.

# My Browser Versions

Edge: 41.16299.1419.0
EdgeHTML 16.16299

IE: 11.1451.16299.0CO
Update Versions: 11.0.155

Chrome: 78.0.3904.97

Firefox: 68.2.0esr

**Comment by e-dong** [comment] 2019-11-11 15:03
Also note that IE and Edge support WebGL 1 but not WebGL 2

Chrome and Firefox support both versions:

https://webglreport.com/

**Comment by OmarShehata** [comment] 2019-11-11 15:21
Are you able to reproduce this just by opening https://sandcastle.cesium.com/ in IE or Edge? I'm not able to reproduce this. 

Note that after the [switch to ES6 modules](https://cesium.com/blog/2019/10/31/cesiumjs-es6/) in CesiumJS 1.63, only the built version of CesiumJS will run in IE/Edge, and I wouldn't expect that to be fixed with a `requestAnimationFrame` change. What version of CesiumJS are you seeing this on? You can test older versions of CesiumJS with the hosted Sandcastle. For example below is a link to the 1.61 CesiumJS (which is also working in IE/Edge for me):

https://cesium.com/downloads/cesiumjs/releases/1.61/Apps/Sandcastle/index.html?src=Offline.html

**Comment by e-dong** [comment] 2019-11-11 16:05
Hi @OmarShehata, https://sandcastle.cesium.com works fine. I have updated my issue with more details. Basically I have having issue with IE and Edge on this web project with webpack. https://github.com/AnalyticalGraphicsInc/cesium-webpack-example

**Comment by OmarShehata** [comment] 2019-11-11 18:22
Thanks for posting the exact steps to reproduce @e-dong.  I'm marking this as a bug here until we can verify if this is an issue with the webpack example perhaps missing something in the build step or an issue that should be resolved in CesiumJS itself.

**Comment by e-dong** [comment] 2019-11-15 21:09
@OmarShehata I have updated my issues reproduction steps again:

For some reason it works fine with this value for the cesium dependency:
`
  "dependencies": {
    "cesium": "http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/no-import-meta/cesium-1.62.0-no-import-meta32711.tgz"
  },
`

I get the misbehavior when using this:
`
  "dependencies": {
    "cesium": "^1.63.1"
  },
`

**Comment by ggetz** [comment] 2022-09-22 15:54
Closing this due to the fact that we've dropped support for IE, and https://github.com/CesiumGS/cesium-webpack-example has since been updated.

@e-dong If you are still seeing this issue when building with the latest recommendations for webpack, please open an issue in https://github.com/CesiumGS/cesium-webpack-example. Thanks!

**Closed by ggetz** 2022-09-22 15:54 UTC
Labels: type - bug, category - tooling
