### ISSUE TITLE
Globe.pick inconsistently returns undefined

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#6312] opened 2018-03-06 14:44 UTC
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/3xzT6__pakk

> I'm trying to use globe.pick to find a point directly below another point, but while IntersectionTests.rayEllipsoid does find an intersection, globe.pick is returning undefined

**Comment by hpinkos** [comment] 2018-03-06 16:05
@ggetz I think you linked to the wrong forum post.
Also, can you see if he can put together a code snippet to reproduce this?

**Comment by Luiz-HSSD** [comment] 2018-03-06 16:22
Obter o Outlook para Android<https://aka.ms/ghei36>



De: Hannah
Enviado: terça-feira, 6 de março 13:05
Assunto: Re: [AnalyticalGraphicsInc/cesium] Globe.pick inconsistently returns undefined (#6312)
Para: AnalyticalGraphicsInc/cesium
Cc: Subscribed


@<https://github.com/ggetz>ggetz<https://github.com/ggetz> I think you linked to the wrong forum post.
Also, can you see if he can put together a code snippet to reproduce this?

**Comment by ggetz** [comment] 2018-03-06 16:32
@hpinkos Whoops, updated to the correct link. There is a code example there, and here is a sandcastle-friendly modified snippet:

```
var viewer = new Cesium.Viewer('cesiumContainer'); 
viewer.terrainProvider = new Cesium.CesiumTerrainProvider({url: '//assets.agi.com/stk-terrain/world'}); 

// The Earth 
var globe = viewer.scene.globe; 
var ellipsoid = globe.ellipsoid; 

// Place "satellite" 
var scratch = new Cesium.Cartesian3(); 
var kansas = Cesium.Cartesian3.fromDegrees(-101.2921054, 39.4166685); 
var aboveKansas = Cesium.Cartesian3.multiplyByScalar(kansas, 1.5, scratch); 
viewer.entities.add({ 
    id: "satellite", 
    name: "satellite", 
    position: aboveKansas, 
    point: {pixelSize: 10, color: Cesium.Color.YELLOW} 
}); 
var satellite = viewer.entities.getById("satellite"); 
var satPos = satellite.position.getValue(viewer.clock.currentTime); 

// Place ray on "satellite" pointing down 
var ray = new Cesium.Ray(); 
ray.origin = satPos; 
ray.direction = Cesium.Cartesian3.negate(satPos, scratch); 

// Intersection with ellipsoid 
var ellipsoidIntersect = Cesium.IntersectionTests.rayEllipsoid(ray, ellipsoid); 
if ((ellipsoidIntersect !== undefined) && (ellipsoidIntersect !== null)) { 
    // rayEllipsoid returns an interval, where on the ray is the interval? 
    var intersectPosition = Cesium.Ray.getPoint(ray, ellipsoidIntersect.start); 
    console.log("ellipsoidIntersectPosition"); 
    console.log(intersectPosition); 
} else if (ellipsoidIntersect === undefined) { 
    console.log("ellipsoidIntersect undefined");
} else if (ellipsoidIntersect === null) { 
    console.log("ellipsoidIntersect null");
} 

// Intersection with terrain 
var terrainIntersect = viewer.scene.globe.pick(ray, globe); 
if ((terrainIntersect !== undefined) && (terrainIntersect !== null)) { 
    // globe.pick returns a Cartesian3, so it's fine as it is 
    console.log("terrainIntersectPosition"); 
    console.log(terrainIntersect); 
} else if (terrainIntersect === undefined) { 
    console.log("terrainIntersect undefined");
} else if (terrainIntersect === null) { 
    console.log("terrainIntersect null");
} 
```

**Comment by jjhembd** [comment] 2023-04-13 17:24
@ggetz, as discussed: closing as a duplicate of https://github.com/CesiumGS/cesium/issues/8768, since that issue has more specifics about the problem.

**Closed by jjhembd** 2023-04-13 17:24 UTC
Labels: type - bug, category - picking
