### ISSUE TITLE
Shadow volume artifacts in geojson clamped to ground

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#8049] opened 2019-08-08 20:03 UTC
![image](https://user-images.githubusercontent.com/3451886/62734050-f9c3de00-b9f5-11e9-8330-29eae6f336b7.png)

```js
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.dataSources.add(Cesium.GeoJsonDataSource.load('../../../../Apps/SampleData/ne_10m_us_states.topojson', {
    clampToGround: true
}));
```

**Comment by OmarShehata** [comment] 2020-03-23 15:10
Came up [on the forum](https://groups.google.com/d/msg/cesium-dev/MDXTSunXSPk/HNcW-6u-AgAJ):

![shadow_volume](https://user-images.githubusercontent.com/1711126/77331257-dcc6eb80-6cf6-11ea-856b-0b7a8f5bb2d4.gif)

**Comment by OmarShehata** [comment] 2020-03-24 01:28
I think this is the same issue again [on the forum](https://groups.google.com/d/msg/cesium-dev/5A2mfG1dq60/NLj1AOOlBQAJ):

![shadowvolume](https://user-images.githubusercontent.com/1711126/77378733-3d811300-6d4d-11ea-8a0b-488ad493b2e3.png)

**Comment by mramato** [comment] 2020-03-24 01:47
Are we sure these polygons causing this issue are not self-intersecting or potentially have any other oddness to them?  In my experience a lot of polygon data has precision issues that cause slight intersections that are not visible in 2D but create problems when you have to tessellate in 3D.  Otherwise, I would expect a simplified rectangle at the same location to have the same issue.

**Comment by dzungpng** [comment] 2021-03-16 23:25
Looks like this issue is gone in Cesium 1.79.1: [Sandcastle](https://sandcastle.cesium.com/#c=bY9RS8MwFIX/SuhLWxiJe3XdECYMRPCh4lOgZM1Vo2luSW46pvjfTVYRmcvbvec75+ROyrPJwAE8WzMHB7aFYOLAn067quxP4xYdKePAl/VKOulmB9eKVIvRJ4grrasf7w7wLqC7/VW5RaWrknPRqmG0kBXhoFteDV0MXSBFKYFwxLfkKxfsUzqWXm8T/og7j9Hpa0Y+gnRfdb0qFkUT6GhhM4OM3ZhhRE8selulHoLUk1PFPvbvQLwPIX89o434a220mZjRa1mcnSqL3B9CUp6jta35AFlsGpH4f9Z8n3EvDxN4q44Ze11u7ucl57wRabzsJES7V/4s+Rs).

**Comment by mramato** [comment] 2021-03-17 13:27
I couldn't reproduce this either.

**Comment by cesium-concierge** [comment] 2021-03-17 13:27
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/MDXTSunXSPk/HNcW-6u-AgAJ
https://groups.google.com/d/msg/cesium-dev/5A2mfG1dq60/NLj1AOOlBQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8049 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by mramato** 2021-03-17 13:27 UTC
Labels: category - graphics, category - polygons/geometry, type - bug
