### ISSUE TITLE
Make Models be affected by Fog

### ISSUE THREAD

**Issue by laurensdijkstra** [CesiumGS/cesium#4196] opened 2016-08-12 10:39 UTC
glTF Models are currently not affected by Fog. This creates a highly unrealistic image. It would be desirable to have Models be affected by Fog just like the Terrain Primitives are.

**Comment by ptrgags** [comment] 2023-12-06 15:20
This feature has two parts: fog culling (tiles in the distance for horizon views should use lower-resolution tiles) and fog rendering (Blend the model color with the atmosphere color like terrain does.

Fog culling is already implemented in CesiumJS, but not enabled by default. It goes by the term `dynamicScreenSpaceError`. I find this a bit confusing, and [the documentation](https://cesium.com/learn/cesiumjs/ref-doc/Cesium3DTileset.html?classFilter=Cesium3dtileset#dynamicScreenSpaceError) could be written in a clearer manner.

This is an unfamiliar part of the 3D Tiles code for me, so I explored the code a bit yesterday and now can explain the parameters better:

| Parameter | Effective range of values | Description | 
| --------- | ----------- | --- |
| `dynamicScreenSpaceError` | `{true, false}` | The switch that turns fog culling on/off. |
| `dynamicScreenSpaceErrorFactor` | `>=0.0 px`| Fog culling works by reducing the computed screen space error (SSE) in pixels for tiles far away from the camera for horizon views. This factor is the maximum SSE adjustment. For example, if this is the default of 4.0, then tiles far away from the camera will be `SSE = tile.SSE - 4 px`. Increasing this value is the easiest way to increase the intensity of the fog culling's effects. Setting this to 0.0 has the same effect as turning off fog culling. Furthermore, this should be restricted to positive values, as negative values will cull tiles _near the camera_ |
| `dynamicScreenSpaceErrorDensity` | `>=0.0` | The adjusted SSE falls off from the original value like a bell curve as distance from the camera increases, to simulate fog being more intense in the distance. Increasing this density parameter makes the bell curve have a sharper peak, which simulates thicker fog. Setting this value to 0.0 Has the same effect as turning off fog culling. |
| `dynamicScreenSpaceErrorHeightFalloff` | `[0.0, 1.0]` (a percentage of the height range) | Fog culling depends on the camera height such that the effect is largest when the camera is near "street level" and gradually falls off to no effect when the camera is above the data. This falloff value is a percentage of the height range of the data[^1]. When the camera is below the falloff point, fog culling will have the strongest effect. Between the falloff point and the maximum height, fog culling will gradually taper off. Above the maximum height, fog culling has no effect.

[^1]: The height range that is computed depends on the the bounding volume of the dataset. For smaller tilesets with a box/region bounding volume, this is based on the min/max height. For large world-scale bounding volumes, an approximate height range is computed relative to the ellipsoid.

Another observation: Fog culling rolls off with the camera angle. It has a maximum effect when the camera is facing the horizon, and no effect when the camera is facing straight up or straight down.

Here's a diagram of what the fog culling SSE adjustment looks like:
![image](https://github.com/CesiumGS/cesium/assets/8422414/a3e6e2bb-1676-4451-850b-d1abc66f64aa)

Here's what the density parameter does:
![image](https://github.com/CesiumGS/cesium/assets/8422414/5f489750-9250-46da-89b7-6e1a0394548b)

Here's what the SSE Factor parameter does:
![image](https://github.com/CesiumGS/cesium/assets/8422414/1a5e8105-4dd4-468f-aaaf-10441b3bdff7)

And here's an animation that shows how culling is strongest when the camera is low, but rolls off as the height increases past the falloff point.
![2023-12-06_SSEFalloff2](https://github.com/CesiumGS/cesium/assets/8422414/8b234a49-1b11-4a9d-b83a-3a55f92c225a)

**Comment by ptrgags** [comment] 2023-12-06 15:29
Before we enable fog culling by default, we'd like to do some performance testing to evaluate how well it works and what parameters would be the best defaults. 

For the first round of tests, I'm using Google Photorealistic 3D Tiles to test how well this feature helps reduce tiles loaded for world-scale datasets. This involves

1. Measure initial tiles loaded time and tiles loaded/selected for the dataset without fog culling
2. Measure it again with the default fog culling settings
3. Try increasing just the density parameter to have the maximum effect (I'm going to try setting it rather high at `0.1`)
4. Try increasing just the SSE factor parameter to simulate somewhat aggressive fog without going crazy. I'm going to try `32` px. This is twice the default maximumSSE threshold, and causes a noticeable difference in the background of landscape views.

I've already started some of these measurements, I will post the data and a summary once I have the rest of the numbers.

**Comment by ptrgags** [comment] 2023-12-06 19:30
### P3DT Fog Performance Test Results

I ran the above tests for comparison. I used 5 different areas of Google P3DT, and for each area 3 views (aerial, street level, top-down) for comparison.

Here's an example HTML file for one of the test setups. I adjusted the parameters in the `tilesetOptions` object and then refreshing the page as needed). 
[performance-example-setup.html.txt](https://github.com/CesiumGS/cesium/files/13590748/performance-example-setup.html.txt)

Here's a summary of the time to first load, averaged over all the different views:

Configuration | Average time to first load (s) | % difference from no fog
-- | -- | --
No Fog | 7.989 | N/A
Fog enabled with defaults | 5.678 | -28.93%
Fog with SSE Factor = 32 | 3.658 | -54.22%
Fog with density = 0.1 | 5.403 | -32.37%

For the full data (which includes other metrics like number of tiles loaded), see this CSV file:
[Dynamic SSE Perf Testing - P3DT.csv](https://github.com/CesiumGS/cesium/files/13590736/Dynamic.SSE.Perf.Testing.-.P3DT.csv)

**Comment by ptrgags** [comment] 2023-12-06 20:02
Here's some visual comparisons of the data in CesiumJS vs Google Earth to compare how much is culled. It's hard to get the camera views exactly the same since the camera controls are so different, but here's something roughly similar:

| CesiumJS P3DT | Google Earth | Comments |
|---|---|---|
| ![image](https://github.com/CesiumGS/cesium/assets/8422414/1c2ee494-620e-4924-ad02-7474fff342d5) | ![image](https://github.com/CesiumGS/cesium/assets/8422414/c06b6439-9a87-4d92-baed-67bbdca6bd55) | CesiumJS seems to load more tiles in the distance. | 
| ![image](https://github.com/CesiumGS/cesium/assets/8422414/eeafdbd6-9aaf-4cb6-aa59-fbbd10786680) | ![image](https://github.com/CesiumGS/cesium/assets/8422414/f277d73d-8879-4a45-bf1e-8b7800622654) | Here Google Earth has a bit more detail in the distance |
| ![image](https://github.com/CesiumGS/cesium/assets/8422414/c9361b6b-1041-4c53-bd35-ca93ef0dc897) | ![image](https://github.com/CesiumGS/cesium/assets/8422414/09b14398-3790-4167-9468-3c68847df416) | Google Earth has a bit more detail in the distance |

So overall, it seems like `dynamicScreenSpaceError: 32` does create somewhat intense fog culling, but not extremely so.

**Comment by ptrgags** [comment] 2023-12-06 20:16
Another thing we wanted to check: Does fog culling serve as a workaround for horizon culling for world-scale tilesets? Freeze frame will help here:

With fog off:
![image](https://github.com/CesiumGS/cesium/assets/8422414/42df5095-e865-4a5b-b299-5df8bfb47525)


With fog on, (`SSEFactor 32`):
![image](https://github.com/CesiumGS/cesium/assets/8422414/69e70275-7de5-42b9-a578-6911c8615912)

As I suspected, it doesn't completely replace horizon culling (as tiles on the other side of the globe still render), but it does reduce the LODs loaded. Not perfect, but definitely an improvement!

**Comment by ggetz** [comment] 2023-12-06 20:33
Thanks @ptrgags for the research!

1) There does appear to be a significant performance gain from implementing fog, so we'll likely move forwards with the process
2) Based on the screenshot comparisons, we may want to do a bit of tweaking to the default parameters to get the best balance between performance and visual fidelity, but we're definitely in the right ballpark
3) It sounds like [horizon culling](https://github.com/CesiumGS/cesium/issues/8612), or even outright culling a tiling which is completely in fog, may provide and additional benefit, so we may want to take a look at that next after this is completed

**Comment by ptrgags** [comment] 2023-12-07 20:06
More notes from exploring the existing globe shader and a discussion with @lilleyse:

* The sky atmosphere, ground atmosphere and fog currently are enabled and configured independently.
* Dynamic lighting (based on sun position over time) affects fog too.
* see [this Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bY/BasMwDIZfxeTUwXDYuWnY6KGXwg6DnXxxHLUxVeRgyQnZ089JYRtrdPul7xOSC8SiRg8TRHVQBJM6AvvU68+1tzOFW/MxkFhPEE3xtDdk6O5odkCgrxga0EC2QTj7ayeernmdxAT7TZS7MJ1iSNS+SR946CBCFi4W+cHg2/wLreYPWTwXFcuMUBtSa736fghRVIq407oU6Ae0Alw2yd1AtGNe7l/QqvyrVq0flW8PGw8rh5Y5Ty4J8cN/gSnqqsz8g4rBtvn19xEi2nnBupf6fG9qrasyx21TQsDGxn+bvwE) for some of the relevant settings for turning off the atmosphere but keeping fog (while enabling dynamic lighting
* To get the fog to use the atmosphere color, there are several uniforms in `AtmosphereCommon.glsl` that need to be added to the Model shader. These uniforms can be found in the `Globe` (for ground atmosphere/fog for terrain) and `SkyAtmosphere`, but neither are accessible from Model.
* One thought is to make these AutomaticUniforms, so the `Globe` settings will also apply to 3D Tiles fog.
* Longer term, we could even combine the `SkyAtmosphere` parameters with the `Globe` so they only need to be configured in one place. But this is out of scope. I'll open an issue for it.

**Comment by ptrgags** [comment] 2023-12-18 20:12
Update: I added some new automatic uniforms and created some new builtin functions for computing the scattering color. I also created a new `Atmosphere` object (stored as `scene.atmosphere`) to handle updating the `FrameState`.

The shader for FogPipelineStage is still very bare-bones, there's quite a bit of code I have to add from `GlobeFS`. Also the color doesn't yet look correct, it's quite dark when screenshots above are lighter and a bit more bluish in comparison. But the fact that you see something and not a shader compilation error is progress.

![image](https://github.com/CesiumGS/cesium/assets/8422414/e3baa43f-a08a-455d-8c1d-20f82033b7fb)

There's still a lot left to do here, so let me organize my thoughts:
- [ ] Debug why the atmosphere looks black. Is it due to code I haven't yet added? uniform optimized out?
- [ ] Handle dynamic lighting
- [ ] Determine how to toggle vertex shader vs fragment shader fog computation like the globe does.
- [ ] Sweep through `GlobeFS` and `GlobeVS` thoroughly and see what other details affect fog that are not globe-specific.
- [ ] Add a uniform for whether the tile is in fog or not (as fog should only be computed for distant tiles). This likely will be similar to the `dynamicScreenSpaceError` computation
- [ ] Allow enabling/disabling fog through the settings. Sometimes this will require the Model pipeline to be rebuilt for infrequent changes to the shader code.
- [ ] Determine how to unit test
- [ ] Set up performance tests before and after fog
- [ ] Determine how best to test this. Unit tests may be difficult since this requires rendering things far from the camera. Rendering an image and comparing to catch regressions might be a better idea.
- [ ] Plan a deprecation strategy for #11681 and document it, as the change to the GlobeFS is not exactly trivial given the differences in uniforms and defines.

**Comment by ptrgags** [comment] 2023-12-18 21:08
There were a couple typos so a couple uniforms were `NaN`. This coloring looks better, but now I get this artifact where everything above the horizon looks darker:

![image](https://github.com/CesiumGS/cesium/assets/8422414/689b624d-fc68-4b96-8ae6-ee58d75acc3e)

I'll have to investigate further.

**Comment by ptrgags** [comment] 2023-12-19 15:57
It looks like the scattering code is likely where it happens, though I'm still trying to figure out why.

Along the way, I'm finding some corner cases with some of the variables that seem a bit off to me, though these don't seem to be a problem for terrain. Documenting them for future reference.

First, the variable `w_stop_gt_lprl` (weight for representing whether [ray intersection].stop greater than `length(primaryRayLength)`). This is a measure of "sky or horizon?" It seems to be sensitive to the difference between an ellipsoid and a sphere since it uses a sphere for the intersection test.. It seems to hover around 0.5 due to the `0.5 + 0.5 tanh(x)` almost everywhere, but when the camera zooms in near the poles it jumps to 1.0 due to the camera being above the ellipsoid but underneath the sphere used for the test.

Second, the variable `w_inside_atmosphere` has a weird behavior on the horizon but only for certain camera views. it's 1 wherever it is yellow. The yellow at the bottom seems consistent with the behavior in most views when the camera is hovering close above the earth, but not sure why it's also 1 on the horizon:

![image](https://github.com/CesiumGS/cesium/assets/8422414/7d159c09-3349-473b-8cb7-28c128e3142e)

Still poking around the code a bit. I also want to do a bit of reading up on atmosphere rendering to understand the scattering functions better.

**Comment by ptrgags** [comment] 2023-12-19 19:23
[This article](https://www.scratchapixel.com/lessons/procedural-generation-virtual-worlds/simulating-sky/simulating-colors-of-the-sky.html) was a helpful resource at understanding the concepts here about Rayleigh and Mie scattering, with plenty of good diagrams.

**Comment by ptrgags** [comment] 2023-12-19 20:43
Well that's one thing that seems off. For fragments above the horizon, the lightHeight computed in the inner loop seems to be negative somehow :thinking: 

![image](https://github.com/CesiumGS/cesium/assets/8422414/68d4761c-5b1d-4c91-8862-729db6218069)

`lightHeight = length(lightPosition) - innerAtmosphereRadius` so either the reference point (which is based on positionWC for the fragment) is wrong, or the light position calculation is wrong for fragments above the horizon.

**Comment by ptrgags** [comment] 2023-12-19 20:57
Huh, when rendering `(innerAtmosphereRadius / 1e7, length(lightPosition) / 1e7)`, both variables seem to get noticeably larger above the horizon. not sure why.

![image](https://github.com/CesiumGS/cesium/assets/8422414/02cda6eb-8363-4498-95fa-454e2ec0940e)

**Comment by ptrgags** [comment] 2023-12-19 21:20
Hm, rendering `positionWC = computeEllipsoidPosition()` (same exact function as in `GlobeFS.glsl`)

I get weird values. the reddish colors above the horizon would mean +x here which is definitely wrong (+x is eastern hemisphere, this view is California). Also not sure why there are two colors.

![image](https://github.com/CesiumGS/cesium/assets/8422414/77026c74-fbdf-413a-a767-e2fcc793763c)

Terrain for comparison for a similar view. All blue, even above the horizon.

![image](https://github.com/CesiumGS/cesium/assets/8422414/f723443d-8047-4863-8d37-13b8cdbad665)

So something about the coordinates used for the computation must be different between globe and Model... though this function uses only built-in uniforms so not sure what's different here.

```
vec3 czm_computeEllipsoidPosition()
{
    float mpp = czm_metersPerPixel(vec4(0.0, 0.0, -czm_currentFrustum.x, 1.0), 1.0);
    vec2 xy = gl_FragCoord.xy / czm_viewport.zw * 2.0 - vec2(1.0);
    xy *= czm_viewport.zw * mpp * 0.5;

    vec3 direction = normalize(vec3(xy, -czm_currentFrustum.x));
    czm_ray ray = czm_ray(vec3(0.0), direction);

    vec3 ellipsoid_center = czm_view[3].xyz;

    czm_raySegment intersection = czm_rayEllipsoidIntersectionInterval(ray, ellipsoid_center, czm_ellipsoidInverseRadii);

    vec3 ellipsoidPosition = czm_pointAlongRay(ray, intersection.start);
    return (czm_inverseView * vec4(ellipsoidPosition, 1.0)).xyz;
}

```

**Comment by ptrgags** [comment] 2023-12-19 21:40
In SpectorJS, the only difference in uniforms is the frustum is quite a bit different. Model on the left, terrain on right:

![image](https://github.com/CesiumGS/cesium/assets/8422414/2541e771-424c-4f06-bdc8-681f1ee14346)

**Comment by ptrgags** [comment] 2023-12-20 21:01
Today I've been focusing on other details of 3D Tiles fog and thinking towards the future of atmosphere rendering.

See https://github.com/CesiumGS/cesium/issues/11681#issuecomment-1865080064 for more details on what I think the atmosphere setting structure should be (although getting there requires quite a few deprecations). For now, I'm sticking to non-breaking changes until it can be discussed further.

Then I wired up the flags that enable/disable the fog pipeline stage. `fog.enabled/fog.renderable` are the main settings that control this. This is simpler than for terrain which is tightly coupled to whether the globe exists.
![2023-12-20_EnablingFog](https://github.com/CesiumGS/cesium/assets/8422414/73d0d866-3c05-4dd7-b20d-68a3cd8a9713)

**Comment by ptrgags** [comment] 2023-12-20 21:58
I added an enum to select between the 3 dynamic lighting modes (`OFF`, `SCENE_LIGHT`, `SUN_LIGHT` like I described in the other issue (as this is cleaner than 2 separate flags that depend on each other). Here's it in action:

![2023-12-20_DynamicLighting](https://github.com/CesiumGS/cesium/assets/8422414/70862746-96ae-486c-842e-229176b56a46)

- black fog: scene light. I don't think I had the right direction vector for this view.
- sunset fog: sun light
- pale blue fog: dynamic lighting off; fragments are lit from above.

For safekeeping, here's a [Local Sandcastle for WIP branch `4196-3d-tiles-fog`](http://localhost:8080/Apps/Sandcastle/index.html#c=rVVtb9s2EP4rB2MDZNShJcuy7MYOliVOWyBNg8bpPlTFykgXmyhFGiTtzCvy33eU5MTOC4YB+yKJ934PnzvlWlkHa4F3aGACCu/gBK1YlexLJQuyVl6dT7RyXCg0WasDPzMF0O06UaIk2Vu45dJip5ZyJUruhFa7Ypujwo+6wEuR/0Czq7rhFs/5Bs1zVbcLswXCXOobhEKjBaUdFYkFOA1eJuxSkm+xNbdC5QiOnC4X2mmDXArrRA7xKcyEpAhkIFcF2aAx1JD3q+I/5r1vH2Ykp2hTxW8kgkFVoBFqXgW2PzaZqhFjVVuMJMeu1Ha5QEOnhb4jKJ1Z4TbOcVG8Vk+mnNnUgObVXTgvRUcR+B0XbnsdObk6fKf1XOJ+qPh0VrsEvm6AvdKWRpTCiTVaxosiaIJ7w3vIucsXEBAO2rQfS9ASmdTz4PvUK0BqXvjWX8OzCcm8+y8/q2D336sETfOXWihXIZfzEg0HXp/qXpYS/3oCZ23GKKjnYFAVViBlVQ2tdlh6wo2jL67iwJsBHPQGozgdpSxJonAQ9tO00yj6vVEaxQlLojQc9dNe0ijiYdJPw5Cl9OxH/XjQ9/J2pdVGIPH+Wdr3WIFyKQjBz1rKJnmfDZIkpLyjXhJFo9FDjoOQ9YaDeDjq0zOKh8N40GgiFieDKKVKe0maxlEa40G6LYCYCB7FmhlSzBduf0hPhcHcV8fludc2YG2lr0H1f4BUA5RrqWlktyn8if3x/sNsWmnp4lFZ4TZvqc9wO1p7l71tqnpX85KpK66KnFtHRCTSzvScePL7yjmtaB2d6Xkzl4VfRX7MOhDkC6TlUbRhclQzeS/JrZ4zrH0oVWN7+DDp/5rvc7UAvP9/Smke3F7KmilJY052U7UqySAkKXH+A2Fm1lwGwWPk+v6nF9cf//xyfH49vSLzr1nr09mZrydrXZ1ML6bN5/VF1vp2+HSYd3y/Nim/1eviWeX8cZUVG8VLkVfU8jtgsi238my+37zZPcGvE4h9kx2IwjBsH7Y6rbF1G4lHNZMAfhPlUhsHKyMDxroOS9rhRM3uzYoQciy3ti4NYNzddR0XYg2imLzwT4JccmtJc7uS8kr8TRd1NO6S/TPXZp99WqOhP4c3W0RH57WQMTbu0vFlT6e1vOHmSeR/AA)

**Comment by ptrgags** [comment] 2023-12-21 15:29
@ggetz I clarified the product details of 3D Tiles fog with @shehzan10 today, and he clarified that right now the priority is focusing on 3D Tiles performance for world-scale datasets like Google P3DT. The visual rendering details are at a lower priority for now. So I'm splitting this issue up into the following smaller issues:

* https://github.com/CesiumGS/cesium/issues/11715 (high priority)
* https://github.com/CesiumGS/cesium/issues/11716 (lower priority)
* https://github.com/CesiumGS/cesium/issues/11717 (lower priority)
* https://github.com/CesiumGS/cesium/issues/11681 (lower priority, involves breaking changes)

I'm closing this issue in favor of the 4 above.

**Closed by ptrgags** 2023-12-21 15:29 UTC
Labels: type - enhancement, category - model
