### ISSUE TITLE
Label backgroundColor changed when show/hide

### ISSUE THREAD

**Issue by JiaoJianing** [CesiumGS/cesium#10974] opened 2022-12-23 08:14 UTC
Sandcastle example: [Online Link](https://sandcastle.cesium.com/#c=dVRRb9owEP4rHi8NUuQ0dHtYStFU6NSHTiAVVZqUhxrnAieMHdkOlE7899lx2gZKT44Uf3ff+XL3OVxJY8kWYQea3BAJOzIGg/WGPjVYlPd4sx8raRlK0Hmvf53LXPKGKdgCxEwZtKikS9CSx0xb98bkFS212kxgqQFMlKaDmFz9jEl6GZJsmQ4p7qRFuz+uIGDRv1wSZ1V7SHZ8Zhy8DZaRNtabhRebddONmRALxtczrSrQLnFZS96UHVncQEw0mFrYfjeJNw221pJcsK/s4vqDcIhJyYSBfvyBmZXa3bqDl1rVssiI1TV03It311gJpY9r9kiUuoaF1U1boGELAROo7GoOxk7QWCY5ZK67wTrBpRtfRp4HP6oX8ge5VkaVlvxl94DP3TAU4qsqLmMS1lEVK6Xx1WtDTDUu0Y2nJd2fOOjD3e95h7h1M0D+ifZ0BNP5dNbhVPgCYlqWBk5H28ptEKXfXY39QDm0VD+ALMylRSrka9+8Fs3lwesxXAMKXncIhrKiiDrqbCUbggwHCZSzDWhGS7GfKy/Uws0BJTujU3+Epz8yWXBmrACffgIlc5qbK+WkqW9ra5V0V84XnKywgLzn9PQu01aanZKoj3S35tsp1n5RL+7lvUaebw8hQ2P3AkZvXf2Fm0ppS2otIkoTC5tKMNfNZFHzNVjKjem3Ah8mXeqwwC3B4ubMH4JwwYxxnrIW4hFf3XeMhomL/0QVihUol1OnBsH2PmyVjh4CSCkdJm57nmlDz04y/wc)

Browser: Chrome 108.0.5359.125 x64

Operating System: Windows 10 Pro x64

When run the example, label's back color is pure white. 
![image](https://user-images.githubusercontent.com/12868409/209298646-a31e3188-0dfe-406b-9c85-4e6baee0b769.png)

Click "show/hide" twice, background color changed:
![image](https://user-images.githubusercontent.com/12868409/209298727-7753b165-dfd8-416e-b92d-169b4033a095.png)

**Comment by jjhembd** [comment] 2023-01-02 14:40
Hi @JiaoJianing, thanks for the report! This looks like a duplicate of https://github.com/CesiumGS/cesium/issues/10461. (See especially [this comment](https://github.com/CesiumGS/cesium/issues/10461#issuecomment-1198949507).)

I will close this issue to keep the discussion in one place.

**Closed by jjhembd** 2023-01-02 14:40 UTC
