### ISSUE TITLE
cesium warning in node terminal

### ISSUE THREAD

**Issue by biqbalgis** [CesiumGS/cesium#9936] opened 2021-11-22 07:22 UTC
I am using ol-cesium 2.10.0.

when i run the project i have the following warnings on terminal.

WARNING in ./node_modules/cesium/Source/Core/buildModuleUrl.js 80:25-32
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/cesium/Source/Core/buildModuleUrl.js 114:14-21
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Thank you

**Comment by bampakoa** [comment] 2021-11-24 21:29
@biqbalgis you may find #8401 useful 😉

**Comment by biqbalgis** [comment] 2021-11-25 04:36
> @biqbalgis you may find #8401 useful wink

Yeapp. A great thread. thank you. :)

**Comment by ebogo1** [comment] 2021-12-03 20:57
@biqbalgis Thanks for reporting this. Since this looks like a duplicate of the linked issue, I'll close this one. If anything new pops up feel free to leave a comment here or open another issue.

**Closed by ebogo1** 2021-12-03 20:57 UTC
