### ISSUE TITLE
Glitch bug in CesiumJS- Fundamentals tutorial

### ISSUE THREAD

**Issue by jillianlong** [CesiumGS/cesium#11690] opened 2023-12-12 18:30 UTC
Code for adding Cesium World Terrain and Cesium OSM Buildings in Step 2 of the [flight tracker tutorial](https://cesium.com/learn/cesiumjs-learn/cesiumjs-flight-tracker/#step-2-add-global-3d-buildings-and-terrain) is causing app to break

Sandcastle example [live site](https://peaceful-dandelion-humerus.glitch.me)
Sandcastle example [code](https://glitch.com/edit/#!/peaceful-dandelion-humerus)

Browser: Chrome

Operating System: Microsoft

We suspect the the Glitch template doesn't allow the await keyword out of the box. Also that tutorial targets 1.82 which is outdated, we should update it to 1.112.

**Comment by jjspace** [comment] 2023-12-12 18:54
Duplicate of https://github.com/CesiumGS/cesium/issues/11650
Try the solutions in that issue until we can update the tutorial fully

**Closed by jjspace** 2023-12-12 18:54 UTC
