### ISSUE TITLE
Error when setting modelMatrix of 3DTileset to identity

### ISSUE THREAD

**Issue by UniquePanda** [CesiumGS/cesium#11893] opened 2024-03-22 11:48 UTC
### What happened?

When setting the `modelMatrix` of a `Cesium3DTileset` to `Matrix4.IDENTITY` the rendering crashes.

This can easily be reproduced in one of the default demo sandcastles (see sandcastle example).
Just move the slider in the top left corner to something different than `0`.
Then enter `0` in the input field and hit enter.

Could be related to #11285 but I am not sure, so I opened this new issue.

Error text and trace:
```
An error occurred while rendering.  Rendering has stopped.
TypeError: result.computeBoundingVolumes is not a function
TypeError: result.computeBoundingVolumes is not a function
    at createRegion (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:121285:14)
    at Cesium3DTile.createBoundingVolume (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:121345:34)
    at Cesium3DTile.updateTransform (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:121440:33)
    at Cesium3DTile.updateVisibility (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:120882:10)
    at updateTileVisibility (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:123046:10)
    at Cesium3DTilesetTraversal.updateTile (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:123037:5)
    at Cesium3DTilesetBaseTraversal.selectTiles (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:123223:38)
    at update3 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:125488:54)
    at Cesium3DTileset.updateForPass (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:125566:32)
    at Cesium3DTileset.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:125537:10)
```

### Reproduction steps

1. Modify the `modelMatrix` of `Cesium3DTileset`.
2. Set the `modelMatrix` back to `Matrix4.IDENTITY`

### Sandcastle example

https://sandcastle.cesium.com/?src=3D%20Tiles%20Adjust%20Height.html

### Environment

Browser: Chrome 122.0.6261.131
CesiumJS Version: 1.115
Operating System: Windows 11

**Comment by ggetz** [comment] 2024-03-26 12:37
Thanks @UniquePanda! This does appear to be related to the same root cause as https://github.com/CesiumGS/cesium/issues/11285.

I'll close this issue and add your report there to keep discussion in one place.

**Closed by ggetz** 2024-03-26 12:37 UTC
Labels: type - bug, needs triage
