### ISSUE TITLE
CDN. Version `1.96`. Workers don't work

### ISSUE THREAD

**Issue by turansky** [CesiumGS/cesium#10617] opened 2022-08-02 09:57 UTC
### Related discussion
https://community.cesium.com/t/import-from-cdn-cesium-1-96-an-error/19799

### Error
```js
cesiumWorkerBootstrapper.js:30 Uncaught Error: importScripts failed for Workers/createVerticesFromQuantizedTerrainMesh at https://cesium.com/downloads/cesiumjs/releases/1.96/Build/Cesium/Workers/createVerticesFromQuantizedTerrainMesh.js
http://requirejs.org/docs/errors.html#importscripts
    at makeError (cesiumWorkerBootstrapper.js:30:1741)
    at req.load (cesiumWorkerBootstrapper.js:31:13911)
    at Object.load (cesiumWorkerBootstrapper.js:31:11762)
    at c.load (cesiumWorkerBootstrapper.js:31:4812)
    at c.fetch (cesiumWorkerBootstrapper.js:31:4751)
    at c.check (cesiumWorkerBootstrapper.js:31:5004)
    at c.enable (cesiumWorkerBootstrapper.js:31:7878)
    at Object.enable (cesiumWorkerBootstrapper.js:31:10863)
    at c.<anonymous> (cesiumWorkerBootstrapper.js:31:7735)
    at cesiumWorkerBootstrapper.js:30:1488
makeError @ cesiumWorkerBootstrapper.js:30
req.load @ cesiumWorkerBootstrapper.js:31
load @ cesiumWorkerBootstrapper.js:31
load @ cesiumWorkerBootstrapper.js:31
fetch @ cesiumWorkerBootstrapper.js:31
check @ cesiumWorkerBootstrapper.js:31
enable @ cesiumWorkerBootstrapper.js:31
enable @ cesiumWorkerBootstrapper.js:31
(anonymous) @ cesiumWorkerBootstrapper.js:31
(anonymous) @ cesiumWorkerBootstrapper.js:30
each @ cesiumWorkerBootstrapper.js:30
enable @ cesiumWorkerBootstrapper.js:31
init @ cesiumWorkerBootstrapper.js:31
(anonymous) @ cesiumWorkerBootstrapper.js:31
setTimeout @ cesiumWorkerBootstrapper.js:26
req.nextTick @ cesiumWorkerBootstrapper.js:31
o @ cesiumWorkerBootstrapper.js:31
requirejs @ cesiumWorkerBootstrapper.js:31
self.onmessage @ cesiumWorkerBootstrapper.js:26
cesiumWorkerBootstrapper.js:26 Uncaught TypeError: Cannot read properties of undefined (reading 'baseUrl')
    at cesiumWorkerBootstrapper.js:26:168
    at Object.execCb (cesiumWorkerBootstrapper.js:31:11809)
    at c.check (cesiumWorkerBootstrapper.js:31:5271)
    at c.enable (cesiumWorkerBootstrapper.js:31:7878)
    at c.init (cesiumWorkerBootstrapper.js:31:4326)
    at cesiumWorkerBootstrapper.js:31:10189
    at setTimeout (cesiumWorkerBootstrapper.js:26:202)
    at req.nextTick (cesiumWorkerBootstrapper.js:31:12475)
    at Object.o [as require] (cesiumWorkerBootstrapper.js:31:10128)
    at requirejs (cesiumWorkerBootstrapper.js:31:12374)
```

**Comment by ggetz** [comment] 2022-08-02 13:16
Thanks for the report @turansky!

@sanjeetsuhag The deployment process grabs the release zip from the [github release](https://github.com/CesiumGS/cesium/releases), and uploads the contents. It looks like the uploaded version is missing some files in `Build/Cesium/Workers`. 

However, if I run `make-zip` locally, those missing files are the resulting zip file. Do you know if any of the contents of that zip was modified?

**Comment by sanjeetsuhag** [comment] 2022-08-02 14:36
@ggetz I'm not sure how those files would have been deleted. But upon running a diff, I do see a difference in the uploaded version versus a local run on `make-zip` from the `1.96` tag.

**Comment by ggetz** [comment] 2022-08-02 14:41
Ok, at least we are seeing the same results now. Please update the github release with the correct zip, and then let me know and I can re-run the website deployment.

**Comment by sanjeetsuhag** [comment] 2022-08-02 14:50
@ggetz Uploaded new release zip.

**Comment by ggetz** [comment] 2022-08-02 15:14
Thanks @Samulus! The uploaded release version is now working as expected. I also confirmed the version uploaded to NPM had the Worker files, so there should be no need to republish there.

I'll close this, but I'm looking further into the build script to see if there may have been anything to cause the missing files in the first place.

**Closed by ggetz** 2022-08-02 15:14 UTC

**Comment by Samulus** [comment] 2022-08-02 17:40
@sanjeetsuhag * I don't work here anymore 😂

**Comment by Tobevictor** [comment] 2023-04-04 03:14
clear chrome cache

**Comment by dmenneck** [comment] 2023-08-09 11:39
Hello @ggetz,
i'm also experiencing the same issue: 

```sh
Uncaught Error: importScripts failed for Workers/createVerticesFromQuantizedTerrainMesh at http://localhost:8000/Workers?lang=de/createVerticesFromQuantizedTerrainMesh
```

when trying to render the world terrain:

```js
  const viewer = new Viewer('cesiumContainer', {
    terrain: Terrain.fromWorldTerrain()
  }); 
```

I'm using cesium version `^1.108.0` and the `createVerticesFromQuantizedTerrainMesh.js` file is present in the module (`node_modules/cesium/Build/Cesium/Workers/createVerticesFromQuantizedTerrainMesh.js`). 

I'm also using webpacks `copy-webpack-plugin` to host the required static files on the server:

```sh
const cesiumSource = 'node_modules/cesium/Source';

new CopywebpackPlugin({
    patterns: [
            {from: path.join(cesiumSource, 'Assets'), to: 'Assets'},
            {from: path.join(cesiumSource, 'Widgets'), to: 'Widgets'},
            {from: path.join(cesiumSource, '../Build/Cesium/Workers'), to: 'Workers'},
            {from: path.join(cesiumSource, '../Build/Cesium/ThirdParty/Workers'), to: 'ThirdParty/Workers'},
      ]
}),
```

Do you have any idea why I am getting this error?

**Comment by ggetz** [comment] 2023-08-11 13:14
Hi @dmenneck, did you set `CESIUM_BASE_URL` at all? If it's not set, CesiumJS attempts to autodetect the path, which may be wrong in this case.

It should be possible with the webpack define plugin:

```
new webpack.DefinePlugin({
            // Define relative base path in cesium for loading assets
            CESIUM_BASE_URL: JSON.stringify('')
        })
```

**Comment by dmenneck** [comment] 2023-08-14 08:04
Yes, the `CESIUM_BASE_URL` is set. Here is my webpack config file:

```js
const path = require('path')

// The path to the CesiumJS source code
const cesiumSource = 'node_modules/cesium/Source';
const cesiumWorkers = '../Build/Cesium/Workers';

const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CopywebpackPlugin = require('copy-webpack-plugin')

exports.onCreateWebpackConfig = ({
  actions
}) => {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /\.geojson$/,
            use: ['json-loader']
          },
          {
            test: /ol-cesium/,
            use: ['null-loader']
          },
          {
            test: /\.(png|gif|jpg|jpeg|svg|xml)$/,
            use: [ 'url-loader' ]
        }
        ]
      },
      context: __dirname,
      entry: {
        app: './src/index.js'
      },
      output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist')
      },
      plugins: [
        // Copy Cesium Assets, Widgets, and Workers to a static directory
        new CopywebpackPlugin({
          patterns: [
            {from: path.join(cesiumSource, 'Assets'), to: 'Assets'},
            {from: path.join(cesiumSource, 'Widgets'), to: 'Widgets'},
            {from: path.join(cesiumSource, '../Build/Cesium/Workers'), to: 'Workers'},
            {from: path.join(cesiumSource, '../Build/Cesium/ThirdParty/Workers'), to: 'ThirdParty/Workers'},
        ]
        }),
        new webpack.DefinePlugin({
          // Define relative base path in cesium for loading assets
          CESIUM_BASE_URL: JSON.stringify('')
        })
      ],
      resolve: {
        fallback: {
          zlib: false,
          https: false,
          http: false,
          assert: false,
          util: false,
          url: false
        },
        alias: {
          // CesiumJS module name
          cesium: path.resolve(__dirname, cesiumSource)
        }
      }
    })
}
```

As you can see in the following screenshot, the OSM buildings are rendered, but the terrain is not.
![Screenshot from 2023-08-14 10-02-49](https://github.com/CesiumGS/cesium/assets/57823837/a81577d6-c3f6-4dfb-aba3-eb2e8c8fb26a)
