### ISSUE TITLE
The raise or lower of datasources is not effective ，I will provide a minimum Sandcastle example for you to confirm this issue

### ISSUE THREAD

**Issue by zendguofans** [CesiumGS/cesium#11925] opened 2024-04-10 03:10 UTC
### What happened?

 I need to modify the order of multiple GeojsonDatasources. When I use the raise or lower of datasources to implement functionality, I find that it does not work and there are no errors.

### Sandcastle example

https://sandcastle.cesium.com/#c=7VndjttEFH6VUXoRRwrOeMYe29nNFrr9EahVq24FEk2FvM4kMXU8wZ7sEla54YpLLhDiARBcAeISbngZWl6DM/6LnU3SBa+QFtVaZe3zP+fMnG889kWUSHQW8HMeowGK+Dk65kmwmOkfpjRt2PLT52MRSS+IeDxsdQ6G0TAaLyJfBiJCofBGdz3pnYhFDLIPvSWoher3WIx4F32aiEjxu0jMlcLgYtVBF8MIoZBLdIESuQxBbByEksddJJdzjlYQSyZ9oAR9iFKEXA/FZG25c1DYUB5AIbWJUFtZaPdR+z735CLmxyIMeRpqu5tLjDNOAlJFdHpBS2VWpW3IyIkKUCVnEYYlPZGxeKlsi3iThVAw8yb8JPhCaWHdzN1mKlGh076F8X242nX2R8FIToFNczLkJdyloniP554fyCVwjTSCYIy0NKWdIiFZmtFchMuJiLLRqASnUgeZjNKqCpTK9QCqIrd1P6XerlGft1Nq+wXqr8M9qNpaB1y3JnJ63V5J7qtMloY2clm3lDO3h1dl7ohyoxJbjZ+nzB3GU2ZqnOZGV+msKuqTzvHBAAr6JFNvl/muzLeLejz9YmWmg9bHsZgdJ0n6cCLjIJpo1aR0utWcv1m3rHJHPw/k9L1wPvW0SrnW9jIvaXL6tVTlEtnaWZULJW0LT8BjkNRWkUpEMdpy+JvSedgPuPggX6hZm9FV19HU4u2WKcsawgrxEFT/tb3OOvyasi6nPNK0UanSQYOjws2aqkfeTDkq21Q+AbIWq68FE90bjarm6oKJzyOux/yzBU/kUx6NoKkWIjGHThVVnGYhd1RbXqkfVDbnCZcbDbmThtzrvfrq+9ff/vT6u19eff0D/FY6eFG5MABoGGyL/JPKQ1lLJa6HPJrAujhCuNJBlLFA8plKixIaB9FI0xSlmsPsysemmHkqB5eTqQZb3irfma1dhtZaZWlz7tiDuXJQZG0rkinp9vHUiyYfT8Win/hTIUIj68C5w2FLLehhqw93l0Bn2OoWUmo8mRQlRoXux4kil+FX7WU63TVrHos5j2XA6zp1+zC2vpj4/REf98F6/96Tkwf9vmm6eNiqJQP+lWEUCKhMPC+kag4uDbMS2dbY1sxVTXDCxYzLeLkxhLqPR4tQBnmDrDlKcyZEPAoiT27Em10bj1sIW0kIGYaru4RQgxDLoJbFqNXdJkcN3SYuNg1KCbNMm5qXpV50/4lTbGLXMhkBk65t73RKDcdlBBMVGTYaOnVcGxNGGLYpjJbsduqYxGCGa7q2Q8zGTrFtE5syw6aY7XZqEQP+wLNrG9RonF7LNpmBmaWqS3c6ZcyF9BoUK6eNa0osCzPXYTBV4G+3U0yx41pQfQtTq6lTw7Gxy2zbhFlMnZ1OTSi5y7Bh2rbNGju9riWzSdog1B4rD6uNpvaibPTVPq1ai2os656S7YFrrbe6obvUYdNdY9adblE6hmujA1Z3l1eQSzeKSo7WuPmeVzGwbm027AzsAbWujlfkLV79j/HKYLD4LNuyGTzugQ5mM5PaGDqr5brN8cq0FSrYjukwugc6HIVYEJfr/GdOYeI4gDAWA4xxaWOnGNsKiqCJ287uLm5a2AGUoZS6xKE3Eq8UDGGqdgU2sXZDByOwATHANcYGbjxSArsASm1LpY+yPXhlwoaBEoeofUhjkLymJXOD8Mr3x2OM34xX++Sa4RV6C1jXDVg3Eq6gLzNYfRZljrW7n1LXtTC2DHgfYow07qcONBiKLaawYXeTgbchgAxMMHPYW7S6+iudaxHXsV0oqIn3oJWqgWVYsCcwLdYYOBQIYcN2APwI2QeRkH9o9PBmYjZOLzUJvKfDnoaarrvHKTVhkptqvKbjNB8pvHablDIKmLuvpsCmBNDZdEy7MURe0zK9QRCpgO8qELlPriFEFsetPkBN7OnjcPlMaMUpM0+k6skAeusDfS+GHh14EU1P9e/yScx5om2r4LZ6dQ01kuJwX8QBj2TuoJKlKfcADCal00eenOpSPAWqFyUa1nGnMth5IP3pLtl33JpsLCofJzbNdsrsrLJvjiPhL2YQoT7h8l7I1e2d5fsjre2r7QN/yM942O7oIvLDwH85KE7BtezMOz2HVifX2bn+oDwb33K8uz5e3nb+HQqgPBN3hJRipq1Ndoqj5Fa3dZjOw6PCzLvBbC5iiRZxqOl6T/LZPFTo2jtd+C+51P0kKXwe9qqqh6PgDAWjwZYPscgPvSQBzngRhupz47B1dNgD+UuqauMFBXx8xuPQWyqxqXH0MCPqun7Yg8ftmhLScerFm5ZPFzB0dfCfBrbOPgSFshU4UOsuCdK55J0mIlxIfhDysezDlJt/fiDFvG+pm3TB5MQpDyZT2acE7sHln3/8/Pqb3179+uVfv/942Mt85hH8DQ

### Environment

Browser:
CesiumJS Version:    cesium 1.115.0
Operating System:  window

**Comment by ggetz** [comment] 2024-04-11 17:31
Hello, I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/4108. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

Also note that Cesium uses order independent translucency, so even to see a difference, you would need to turn it off:

```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  orderIndependentTranslucency: false
});
```

**Closed by ggetz** 2024-04-11 17:31 UTC
Labels: type - bug, needs triage
