### ISSUE TITLE
Cluster going to be hidden on Cesium Terrain Layer? Can anyone help me out. Thanks in Advance

### ISSUE THREAD

**Issue by 94ankitshrivastava** [CesiumGS/cesium#9216] opened 2020-10-28 08:05 UTC
Whenever i switch the layer from ellipsoid to terrain my Cluster going to be hide and seems like it going under the layers. I saw Cesium Demo for cluster tutorial and i noticed that there is also same issue which i am facing right now. So do we have any alternate solution ? if yes please let me know as soon as possible. Thanks

**Comment by 94ankitshrivastava** [comment] 2020-10-28 08:05
![image](https://user-images.githubusercontent.com/44662445/97408703-7ce69200-1922-11eb-8a3f-503eed6c2b0a.png)

**Comment by OmarShehata** [comment] 2020-11-01 19:03
@94ankitshrivastava I think this is happening because `globe.depthTestAgainstTerrain` isn't turned on, and/or you need to clamp your geometry to the ground. Closing this issue because it's unclear without a minimally reproducible test case that we can run whether this is a bug.  

I encourage you to post your question on the Cesium community forum to get help on how to debug this in your app: https://community.cesium.com/.

**Closed by OmarShehata** 2020-11-01 19:03 UTC
