### ISSUE TITLE
Scene.pickPosition returns points underground

### ISSUE THREAD

**Issue by paherbst** [CesiumGS/cesium#11313] opened 2023-05-26 15:01 UTC
version: 1.105.1

In certain cases when calling Scene.pickPosition, it returns points that are underground.  It seems to be as much underground as the camera is above ground.  So if you zoom out, the pic position moves further underground.

i was able to reproduce it here.  It shows up in my application all the time, but i could only get it to manifest in Sandcastle by setting the camera pitch flatter.

In the example, view the console and right-click to trigger a pickPosition.  Zoom in or out and right-click again to see the changes.

[Sandcastle Example](https://sandcastle.cesium.com/#c=dVNtb5swEP4rJz6BRA3dizS1STQtq7RN3Rot07RJfHHNQawaG9kmXTb1v+8MYSFZ+gEhn5+3uwNhtPOwlfiIFuag8RGW6GTXsO99LS4i0Z+XRnsuNdoiSq4LXeiBw5xAjUxwveWO8bK82aL2t9J5Kvds4uEv36DuiiiFqtPCS6MhxgBM4E+hAWQF8ZFeK8XDyjgZoOuubY31WO7BAAo9tEZqf5x4yQnlJNcvBnEmlKTXjxSmx58h/qgiiPKyJJln3ePeaOSEoCNnPodOl1jRUA7RAKhhZxQyZWpqfyp1dcCnEC6krgGVkq0zshzmutc4iSV4g5b3uW5G/HGwp0lPNREnIzG15e1GClZZ0/yb0b6NkT9N/Wl994U5bymerHaxqJMBRR5Pw+4LPazAzZ/zeY+1RXTxxZs8hVf05IF53E6ldt/MO0NDIad1u0GLcfCZrPTk9pybN4eeKFGSpEFjv46ys3wYfZ4OFVNVDv3V1OQD8uCxkl5svnJdY0x5Lz5zv2Grj9nrFC7zPB9kaQTJNakUOkqjmfM7hYtxaW9lE75T6KyKGcs8Nq3iFCy778QD0ufn3DjtWTalzkq5BVnOz/xqIBR3jm6qTqm1/I1FtJhlhP+PqkzfxN0WreK7ANtcLm6HImNsltHxPNMbo+65PVH+Cw)

**Comment by ggetz** [comment] 2023-05-26 18:56
Thanks for the report @paherbst.

I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/4368. I'll close this issue and add your report there.

We recommend using `scene.pickEllipsoid` for picking globe heights.

**Closed by ggetz** 2023-05-26 18:56 UTC
