### ISSUE TITLE
Restrict camera to keep globe in the center of viewport

### ISSUE THREAD

**Issue by ligaofeng0901** [CesiumGS/cesium#9229] opened 2020-11-08 07:53 UTC
In some cases, I want to keep the globe always in the center of viewport when zooming, tilting with mouse, like google earth. But now,  then globe may be out of viewport when the orientation of camera is not default value, it looks wired. sometimes I even don't know where the globe is after some interactions.
I guess I can use a parameter to control the behavior, like below:
```
var viewer = new Cesium.Viewer({
    restrictGlobeCenter: true
});
```
or
```
viewer.restrictGlobeCenter = true;
```
I wanna know how to implement this, or there are some other ways to do it.

**Comment by dzungpng** [comment] 2020-11-10 18:14
This is a duplicate of https://github.com/CesiumGS/cesium/issues/4802.

**Closed by dzungpng** 2020-11-10 18:14 UTC
