### ISSUE TITLE
In 2D and Columbus views, the position of 3dfiles is shifted?

### ISSUE THREAD

**Issue by verybigzhouhai** [CesiumGS/cesium#9100] opened 2020-08-19 03:08 UTC
Hi，
Is this a known problem and how to avoid it？
last image is 3d mode.
![image](https://user-images.githubusercontent.com/37999729/90587291-9f19b080-e20b-11ea-82ba-b6dfb0c5c825.png)
![image](https://user-images.githubusercontent.com/37999729/90587325-ad67cc80-e20b-11ea-8074-6633419a2b29.png)
![image](https://user-images.githubusercontent.com/37999729/90587348-bc4e7f00-e20b-11ea-9a02-821e451548ef.png)

**Comment by OmarShehata** [comment] 2020-08-19 11:56
Closing as a duplicate of https://github.com/CesiumGS/cesium/issues/5955.

**Closed by OmarShehata** 2020-08-19 11:56 UTC
