### ISSUE TITLE
An error occurred while rendering. Rendering has stopped

### ISSUE THREAD

**Issue by qq617564112** [CesiumGS/cesium#8647] opened 2020-03-02 07:07 UTC
I've currently use cesium with angular, the model is loaded successfully but when I try to change  view this error occurred:
`DeveloperError: compressed is required, actual value was undefined
Error
    at new DeveloperError (http://localhost:8080/bundle.js:21790:19)
    at Object../node_modules/cesium/Source/Core/Check.js.Check.defined (http://localhost:8080/bundle.js:13572:19)
    at Object../node_modules/cesium/Source/Core/AttributeCompression.js.AttributeCompression.decompressTextureCoordinates (http://localhost:8080/bundle.js:5642:59)
    at TerrainEncoding../node_modules/cesium/Source/Core/TerrainEncoding.js.TerrainEncoding.decodePosition (http://localhost:8080/bundle.js:72960:87)
    at getPosition (http://localhost:8080/bundle.js:168299:18)
    at GlobeSurfaceTile../node_modules/cesium/Source/Scene/GlobeSurfaceTile.js.GlobeSurfaceTile.pick (http://localhost:8080/bundle.js:168335:22)
    at Globe../node_modules/cesium/Source/Scene/Globe.js.Globe.getHeight (http://localhost:8080/bundle.js:167057:38)
    at adjustHeightForTerrain (http://localhost:8080/bundle.js:220533:32)
    at tilt3DOnTerrain (http://localhost:8080/bundle.js:220345:13)
    at tilt3D (http://localhost:8080/bundle.js:220162:13)
` 

but when I turn scene.globe = false, the error won't occur.

**Comment by sweerwen** [comment] 2020-03-16 03:19
same error occurred when i upgrade to version 1.67

**Comment by OmarShehata** [comment] 2020-03-18 17:15
@sweerwen are you also using AngularJS? If so, it might be related to https://github.com/CesiumGS/cesium/issues/8673.

**Comment by sweerwen** [comment] 2020-03-26 02:03
> @sweerwen are you also using AngularJS? If so, it might be related to #8673.

i haven't using anglurjs ,just vuejs.

**Comment by sweerwen** [comment] 2020-03-26 10:02
i'm sorry!
it's my mistake, i had set the CESIUM_BASE_URL to the old version path.

**Comment by OmarShehata** [comment] 2020-03-26 13:01
Thanks for confirming @sweerwen .

@qq617564112 I'm going to close this since I've unable to reproduce your original issue. If it's an Angular-specific issue, check out the possible solution recommended here: https://github.com/CesiumGS/cesium/issues/8673#issuecomment-604068054

If you're still having an issue please add a minimal code example with instructions on how you're setting up your project so we can reproduce (including what version of Angular and CesiumJS).

**Closed by OmarShehata** 2020-03-26 13:01 UTC
