### ISSUE TITLE
Polylines are rendered as disjointed segments on iOS 17.2

### ISSUE THREAD

**Issue by chenosaurus** [CesiumGS/cesium#11759] opened 2024-01-13 00:54 UTC
### What happened?

We are experiencing an issue on iOS 17.2+ where polylines are rendered not as a continuous path but a bunch of disjointed line segments.  This issue does not happen on desktop browsers.  This also was not an issue in iOS 17.

### Reproduction steps

1. Open Cesium sandcastle demo: https://sandcastle.cesium.com/index.html?src=GPX.html&label=DataSources on an iOS 17.2 device using Safari.
2. Zoom into the path.
3.  See the path is not continuous.

on iOS Safari
![image](https://github.com/CesiumGS/cesium/assets/509698/74d0bb5a-5e53-4b96-9b9f-ed5c4dc238d3)

on Desktop browser
<img width="1500" alt="image" src="https://github.com/CesiumGS/cesium/assets/509698/90c75c4b-e19c-4a75-869a-b9ab278fed84">

### Sandcastle example

https://sandcastle.cesium.com/index.html?src=GPX.html&label=DataSources

### Environment

Browser: Safari 17.2
CesiumJS Version: 1.113
Operating System: iOS 17.2

**Comment by ggetz** [comment] 2024-01-16 14:13
Thanks for the report @chenosaurus! As @syzdev mentioned, I do think this is a duplicate of #9417.

I'm going to close this issue to keep discussion in one place. I will mention this report in that thread.

**Closed by ggetz** 2024-01-16 14:13 UTC
Labels: type - bug, needs triage
