### ISSUE TITLE
cesium 1.96.0 breaks (at least vite | vite-plugin-cesium) build chains due to export from mersenne-twister.js

### ISSUE THREAD

**Issue by meschg** [CesiumGS/cesium#10650] opened 2022-08-07 15:42 UTC
Dear cesium-team,

looks like cesium 1.96.0 might breaks some build chains - at least my vite-build is not working anymore. I got the following issue on my dev system. I did not test it yet on another system but I can reproduce the issue by updating from 1.95.0 to 1.96.0 in my update-test project and also in my main project (not public available). I added the error below:

**Issue**
`export { default } from '/node_modules/mersenne-twister/src/mersenne-twister.js?v=9f8ad086';`
cesium 1.96.0 is not working with vite, vue, vite-plugin-cesium

![2022-08-07_17-16-39_firefox-91 11 0esr](https://user-images.githubusercontent.com/5106318/183298290-9c4138fd-4500-4ac5-8fc5-2536a82af0ff.jpeg)

**Sandcastle example | How to reproduce**

use commit:  https://github.com/meschg/vue-stack-cesium/commit/8141e225e9f89a01aac8bdff077358742891f89b
`npm install cesium@1.96.0 -f`
`install vite/vue dep`
`vite` or use `vue ui`

**Cause | How to fix**
- Sorry, not absolutly clear to me :(
- vite-plugin-cesium might be the issue but I did not test it yet without the vite-plugin-cesium
Mabye someone else can check if it also is an issue when not using vite-plugin-cesium
 https://github.com/nshen/vite-plugin-cesium/issues/34  

***Browser:***
Firefox 91.11.0esr (64-Bit)
node v16.132 
npm 8.16.0

***Operating System:***
Debian Bookworm 2022-08-07

Most errors I had with cesium in my vue project over the last two often where pretty similar in angular, react and anything with webpack. I am not sure if this also applies here. I hope this is no duplicate and also anyone else can reproduce this.

Thanks for you effort!

Kind regards,
Gerhard

**Comment by ggetz** [comment] 2022-08-08 15:06
Hi @meschg, we did recently update our internal build process. However now we are using esbuild, which I believe is what vite uses under the hood, so it still should be possible to build Cesium with vite.

We don't maintain `vite-plugin-cesium`, but would suggest the configuration be updated as needed based on [these recommendations](https://cesium.com/blog/2022/07/19/build-tooling-updates-coming-to-cesiumjs/#for-developers-building-cesiumjs-apps). It also looks as if `vite-plugin-cesium` uses the built Cesium distributable, where it may be beneficial to use the Source modules directly instead if possible. Here is [our esbuild configuration for reference](https://github.com/CesiumGS/cesium/blob/main/build.cjs#L132).

As an aside, we do plan on [factoring out the `Source/ThirdParty`](https://github.com/CesiumGS/cesium/issues/10568) directory and using imports in place. If a more specific import would fix this problem in `vite-plugin-cesium`, we'd be happy to review a PR.

**Comment by nshen** [comment] 2022-08-08 19:12
Hi @ggetz, I made a pr https://github.com/CesiumGS/cesium/pull/10655, please check.

And BTW I hope cesium team can help my [vite-plugin-cesium](https://github.com/nshen/vite-plugin-cesium)  and [create-cesium](https://github.com/nshen/create-cesium) projects. I think they were the best and the fastest way to develop cesium-based projects before 1.96.0, and hundreds of projects are based on it.

![image](https://user-images.githubusercontent.com/181506/183494033-d250b74c-a251-493b-ac66-9d3dd5646050.png)

PR is welcome, or if you are interested in officially maintaining this project please talk to me  [@nshen121](https://twitter.com/nshen121) or email me nshen121@gmail.com , thanks.

**Comment by an501920078** [comment] 2022-08-12 07:47
![D77745FD-62D3-4574-9238-E706EFAA6E7B](https://user-images.githubusercontent.com/45625953/184308698-ee1e6331-51c1-4d3e-9833-b22d5727dbd4.png)
Many people use it, including me!

**Comment by nshen** [comment] 2022-08-13 03:38
Thanks @an501920078 , I hope it will work after [Refactor "Source/ThirdParty" imports].(https://github.com/CesiumGS/cesium/issues/10568)

**Comment by ggetz** [comment] 2022-08-18 17:14
@nshen After the fixes from https://github.com/CesiumGS/cesium/issues/10568, have you had any luck with `vite-plugin-cesium`?

**Comment by nshen** [comment] 2022-08-18 19:50
I replaced cesium 1.95.0  with the one I build, seems don't work, I don't know why. @ggetz 

<img width="769" alt="image" src="https://user-images.githubusercontent.com/181506/185481437-4333c881-73ee-4cba-b48e-17119214cf9f.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/181506/185481534-fda49209-70d1-43f1-a66d-e2edcfd5877b.png">

---

code 

https://github.com/nshen/vite-plugin-cesium/tree/main/demo

**Comment by ggetz** [comment] 2022-08-19 14:14
@nshen I'm actually having trouble reproducing the error with 1.96 myself.

1. Clone `vite-plugin-cesium`
2. Edit `package.json` to use `cesium@1.96`
3. `yarn install`
4.  `cd demo`
5.  Edit `package.json` to use `cesium@1.96`
6. `yarn install`
7. `yarn serve`

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/4439461/185637682-56d891c1-d74d-47a6-8ff9-eeefa177818f.png">

**Comment by nshen** [comment] 2022-08-19 16:56
@ggetz Thanks for trying, the error will only show when you run `yarn dev` with 1.96

**Comment by ggetz** [comment] 2022-08-19 18:28
Thanks @nshen. Based on [the vite docs for `optimizeDeps.exclude`](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude), I was able to get everything working with the following tweak in `src/index.ts`:

```diff
      userConfig.optimizeDeps = {
-        exclude: ['cesium']
+       include: ['cesium > mersenne-twister']
      };
```

**Comment by nshen** [comment] 2022-08-19 21:07
Oh thanks, @ggetz, I just have to remove `exclude: ['cesium']` then everything gets working!

But I remembered why I exclude cesium was because while we don't exclude cesium, vite will [pre bunding](https://vitejs.dev/guide/dep-pre-bundling.html) cesium library for page load performance.

when cesium is being bundled, it makes chrome's breakpoint jumping inside cesium very slow. because the bundled file is very very big. It prevents me from investigating the internal structure of cesium.

so I think I should not remove `exclude: ['cesium']`, maybe I should keep exclude cesium but include all third parties like:

```
userConfig.optimizeDeps = {
  exclude: ['cesium'],
  include: ['cesium > mersenne-twister', 'cesium > urijs', 'cesium > earcut', ......]
};
```

what do you think?

**Comment by nshen** [comment] 2022-08-20 05:29
I just make it work first, maybe it's not a big problem,  now vite-plugin-cesium 1.2.21 can works with cesium 1.96.0. 

@meschg 

```
  "devDependencies": {
    "cesium": "^1.96.0",
    "vite": "^3.0.4",
    "vite-plugin-cesium": "^1.2.21"
  }
```

**Comment by meschg** [comment] 2022-08-20 11:05
Hi @ggetz and @nshen,

thanks for your effort investigating and fixing this. I can confirm that both my vite projects work now with cesium@1.96.0 and vite-plugin-cesium@1.2.21.

Kind regards,
meschg

**Comment by ggetz** [comment] 2022-08-22 13:50
@nshen I'm glad this is at least working for the time being!

> when cesium is being bundled, it makes chrome's breakpoint jumping inside cesium very slow. because the bundled file is very very big. It prevents me from investigating the internal structure of cesium.

Ah, good point. We've seen this before on some of our internal projects that use CesiumJS. What we've tended to do is [blackbox the script](https://umaar.com/dev-tips/128-blackboxing/) when debugging. That way, developers have some flexibility if they want to step through CesiumJS or not. If that works for your use cases, perhaps you can recommend this approach in your documentation?

If not, your suggestion should work. However, I think `mersenne-twister` is the only third party module which needs to be included, as it is an older module which is not ESM.

**Comment by ggetz** [comment] 2022-08-22 13:52
We can continue the discussion here, but I'm going to close the issue since no additional changes are needed in CesiumJS itself. Thanks!

**Closed by ggetz** 2022-08-22 13:52 UTC
