### ISSUE TITLE
viewer.zoomTo rectangle failed

### ISSUE THREAD

**Issue by zouyaoji** [CesiumGS/cesium#10517] opened 2022-07-06 10:10 UTC
Sandcastle example:

https://sandcastle.cesium.com/#c=bVJNbxoxEP0ro73EKxFv0ooeEkBVSG+VWpUoh3aryNjDYsXYyB6DSMV/rxfY7C7Bpxm/efP1psxiQAjktaQyuy8tnF5RzIRVUgQy+PKAlbYtJp0NBBuNW/QwBotbmGLQccWfD3+szOTBnzpLQlv0ZZbfn/OVIBFc9BL7OaYxkFs9JnR2QNkVYaCrvOUfK3P1HhK4UIq1CXNOS7RMBRhP4F9LBFCBoyVN+sTpgQAeJQlbGbyDM6Tu2nmlrUjd3PX6FcbMhXz96d0aPe0Yyz+UbbJT9Lbh/Wpq8YVP82LlEQO7/nLDhwP4/GkA18PaGObnifYDWAgT8AzYd919B+zaPVm/WdUi7T9faKvDEtV3J9LAFetq1wlL+3tyLs3uHyKRs0n2386tnlyZpQ6jlaSdhbSN3ipq8V1iG1exk5BvBxa7IOtLx/lz8zfvTdW7Vlg4DwrnsQJnza6Fttoqt+Xv13o0skE2CrQzOGkiv+rV2nmC6A3jvCBcrU2tdTGP8hWJyxCaiqOiSx0pvQGtxheOHqQRISRkEY2Z6Tcss8moSPEfqOa46h8b9Ebs6rDl7eS0f875qEjuZSYdJTjL/B8

As shown in the above code, the positioning of the rectangle loaded with CallbackProperty fails, and it has been in the pending state.

**Comment by zouyaoji** [comment] 2022-07-12 01:03
@ggetz 
Is there any follow-up?

**Comment by ggetz** [comment] 2022-07-12 13:01
@zouyaoji I'm planning to take a look this week and will let you know what I find.

**Comment by ggetz** [comment] 2022-07-28 13:08
Hi @zouyaoji, this is actually a duplicate of https://github.com/CesiumGS/cesium/issues/5164. I'll close this so that conversation can continue in that original issue. This happens since the callback property makes the geometry dynamic instead of static.

**Comment by zouyaoji** [comment] 2022-07-28 14:51
@ggetz 

But in some 1.8x versions, there is no such bug.

**Comment by zouyaoji** [comment] 2022-07-28 14:59
There is no such problem in version 1.89

**Comment by zouyaoji** [comment] 2022-07-28 15:19
@ggetz 
Please see this example, in version 1.89, the behavior is normal.

https://codepen.io/zouyaoji/pen/abYVmqE?editors=1111

**Comment by ggetz** [comment] 2022-07-28 16:48
Thanks for your explanation @zouyaoji. I was able to identify the issue and I believe I have a fix in https://github.com/CesiumGS/cesium/pull/10607.

**Closed** 2022-07-28 17:15 UTC
Labels: category - data sources

**Comment by zouyaoji** [comment] 2022-07-29 01:17
@ggetz 
thank you very much for your help.
