### ISSUE TITLE
HDR Sandcastle crashes when log depth is off

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8214] opened 2019-09-23 22:49 UTC
[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=hVRpa9tAEP0rwl/sgLK6r9gJbeNCCj0T01Lwl400tpasdsXuyqlb+t87umzXKVQYrJl5c+y8t9pRZe0YPIOyri0Bz9YtaNZU5Gvnm03zzryVwlAmQE1t69daWPgYUApdn5XcsQKzr8bMXAE18E0qXqx6zOzC7nN0SQv5rBFrVANr8ftivhZr0fcnOgcBZMvlI5ACalOuQJvXWyygzVAJZ9xQrmF+lsTllipmyorlyzbzTbPZdCca0Wf4nFagKNFg2nPOhiMV2I8JapgUOOLJMm6pMvhGRTC79DIvcrOEJGkcJKGXRpFtXYZJGgRRTNLIi4Isc1PbwmCapgkJgzD24zQYdyAVA1zmyyZ3QAsmtp+Zyct7yfksJl4cu24YhWmQplEcYiOXuGHgh37oegnG4jTL0I1e1/eSLIu9LIoyBCfh2A9EsVJU6I1U1ZGkD9Qo9iMk75ZvP67erb7/m4uSbcvlXlBc6z0VW8CFtsR1wAcqipxqw4HQoljJ7ZbDm8YYKWbTu+U9CqWF2tamEXl72FleQv4ExcUooP91GvDz42go1UZxDE0JcQ6/13WtnQda1RyW1FCnkgVw7SwVzeWtrGoFWkPh9Af/wPjTSjX5E+rMbKbzvmotNesIuX7JONkoWd0jNbhDZJ9kkRfj/v0EXxI/jdvtx4HvB1niZmno+1mc2ZaHNpKCBHlhHHhuFl0Mvcqe5mMrpKIkRh5bRMQdwXUrBoS6g61QFydmWZ/d2hcaGrrZfSW7KzAWP1XiYZqDVjQpz4p9afBeK9FyOS7MbkcY6+mc8pY4D+V4IAw7MLNH70B3ZzPQrWjGe4e0A0oTuR00e+Dj6vD6z9tzYg3xjnyMDJXbp1Hsr+Ldh6gb9ar/792/B51N7MlCmz2Hm97/ilW1VKYtMEO1GUCh4R6084gqAkNyrdu0hTMmLQq2s1hxvZ6cfTvXEyvnVGuMbBrOH9hPWE9uFg7i/0rjstv7px0oTvctpPRu3vdOQsjCQfNllpGSP1J1UvEP) - click the HDR button to disable HDR. Then it crashes with this message:

> An error occurred while rendering. Rendering has stopped.
TypeError: Cannot read property 'execute' of undefined
TypeError: Cannot read property 'execute' of undefined
    at executeCommand (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:244061:60)
    at executeCommands (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:244427:17)
    at executeCommandsInViewport (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:244840:9)
    at updateAndExecuteCommands (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:244633:13)
    at render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:245284:9)
    at tryAndCatchError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:245304:13)
    at Scene.render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:245375:13)
    at CesiumWidget.render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:259308:25)
    at render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:258679:32)

**Comment by jjhembd** [comment] 2024-12-03 22:25
Duplicate of #8372.

**Closed by jjhembd** 2024-12-03 22:25 UTC
Labels: type - bug
