### ISSUE TITLE
drawing polyline bug

### ISSUE THREAD

**Issue by abigstupidbear** [CesiumGS/cesium#11384] opened 2023-07-01 15:31 UTC
I encountered a problem while drawing a polyline. When one of the points is far away from the other points, I noticed a broken line segment. Is this a bug.
Sandcastle example:
https://sandcastle.cesium.com/#c=pZRfb9sgFMW/CvKTK0XY4BhD5kar0movkyZtU1/mPRCbNmgYIsCJ0qnfffhP0qnry2o/IN/DOT9fkK5ro50HBymOwoJroMURbISTXQvvBy2uonqoN0Z7LrWwVXT1odKVroekClLIjQAotJdeCgd508S/Kw2A5q1YgSr6ZIXQwO66djtkqmjRb++NOvXlCgzuXnCBENCrcx8bbn144zqDD9a0t+IxoNyNtfwU/0CogBineIkXIEOQZjnOlosR9Z/PgEIEk+yCytEcVIERG1GIMcxmoHCWMjKhaBbO+n7UkhF6QTEy565Ihgo0oQiZhSooYfkZhdLinSicBhSjuD9gDmm6RDSf0RUlWUrHrgIK4VkoPF1VitKc/byaWON6lI3frUBwXKSWe2ElVy9jYJSx8Ovd7ZB8DuvzOIfT6D0Z03438atB7C3RIiqdPymxPvf/UbZ7Yz3orIohTLxo9yp8zyXbrv4lPKzdEOytZfJ3tGzkAcjm+o2fAqgVdy7sPHRKfZNPYcLXZRL8/0SV4Y3Uj18Owip+6m07tP48ihDCMgnl20lvjNpy+4r8Bw

Browser:
chrome 110

Operating System:windows 11
![1688225465716](https://github.com/CesiumGS/cesium/assets/29300501/d0433d5a-d3d1-4d84-9ead-204aa4b61cf3)

**Comment by GatorScott** [comment] 2023-07-03 12:31
It looks like an artifact of line antialiasing as the line doubles back on itself.  Avoiding the doubling back shows "regular" antialiasing issues.

**Comment by ggetz** [comment] 2023-07-03 20:03
Thanks @abigstupidbear for the report and @GatorScott for the tip!

The steep angle has already been documented in https://github.com/CesiumGS/cesium/issues/5231. Given the example, I'm going to go ahead and close this as a duplicate, but let me know if this was intended to discuss more general anti-aliasing of polylines.

**Closed by ggetz** 2023-07-03 20:03 UTC
