### ISSUE TITLE
Missing CesiumMilkTruck.dae for export KML Sandcastle

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8713] opened 2020-04-01 15:34 UTC
The [export KML Sandcastle](https://sandcastle.cesium.com/index.html?src=Export%20KML.html) needs to be able to reference `CesiumMilkTruck.dae` to download it instead of the glTF in the exported KMZ. This works fine in 1.67, but in 1.68 you'll get a 404 for this model.

Here's the deployed Sandcastle for master:

http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/master/Apps/Sandcastle/index.html?src=Export%20KML.html

This file is supported to be here: https://github.com/CesiumGS/cesium/tree/master/Apps/SampleData/models/CesiumMilkTruck. But I can't seem to find it even when going back through the git history. Here's that folder in 1.67 and it's not there:

https://github.com/CesiumGS/cesium/tree/1.67/Apps/SampleData/models/CesiumMilkTruck

Which doesn't make sense.

@sanjeetsuhag was this removed when you were optimizing models?

**Comment by mramato** [comment] 2020-04-01 15:36
Dupe of #8510 This is an easy fix, no idea why no one has done it yet.

**Closed by mramato** 2020-04-01 15:36 UTC
Labels: category - sandcastle, type - bug

**Comment by OmarShehata** [comment] 2020-04-01 15:40
Ah, thanks @mramato . It still works likely because of how our deployment process doesn't delete files. I'll just fix this now.

**Comment by sanjeetsuhag** [comment] 2020-04-01 15:52
@OmarShehata No, it was removed in 1.63
