### ISSUE TITLE
OSM Buildings causing low FPS in latest version

### ISSUE THREAD

**Issue by JackRenner** [CesiumGS/cesium#11862] opened 2024-02-27 00:45 UTC
### What happened?

It looks like in a newer version of Cesium (presumably @cesium/engine v7.0.0), something changed that is now causing serious FPS lag when loading/rendering 3D buildings (specifically `Cesium.createOsmBuildingsAsync()`).  I have an application I was developing with an older version of Cesium and @cesium/engine that did not see this problem with low FPS when zoomed in over 3D buildings.

Versions without issue from my package-lock.json:
- @cesium/engine = 6.2.0
- @cesium/widgets  = 4.4.0
- cesium = 1.113

### Reproduction steps

1. Load sandcastle below
2. Zoom in over any city (Los Angeles, California)

### Sandcastle example

https://sandcastle.cesium.com/#c=bU/LasNADPyVxScHypqe45i2gZ4KKRh68mW9qyai+zCS1sb9+toOhdJEt5HmobEpsqgRYQJSBxVhUkdgzEF/bLuyK+yGjymKwQjUFbt9F68KzRYi6IEwoOAIrI1zpZkMyq+NJTACJw4vGb3DeOZnnqMtdzcuDvp8bi9peiUTgN+BWrApuuUtoQz74qGoWWYPTRfVNk8YhkSiMvlS60ogDH4J46rP9gtEW+Y1ZaXW1V9p7XBU6A53yinrDfNy+czet/gNXdHU1cK/kfpk1j6nEcibeaVdHpu361JrXVcLvK+UlHxv6J/zDw

### Environment

Browser: Chrome
CesiumJS Version: 1.114
Operating System: Windows 10

**Comment by ggetz** [comment] 2024-02-27 14:08
Thanks for the report @JackRenner!

This is a duplicate of https://github.com/CesiumGS/cesium/issues/11811. It has been addressed and a fix will be out in the next release on March 1.

**Closed by ggetz** 2024-02-27 14:08 UTC
Labels: type - bug, needs triage
