### ISSUE TITLE
Small area polygon clipping through the ground

### ISSUE THREAD

**Issue by FranchoPlz** [CesiumGS/cesium#12103] opened 2024-08-01 08:35 UTC
### What happened?

Hello, I'm trying to draw several polygons that are relatively small and I've come across an issue. The polygon representations are having a weird effect when drawn with no height, and if given a height of 0 relative to the ground half of the polygon goes under the terrain. 

I imagine since the polygon is so small that the difference in height in the terrain might not be taken into account, but I'm not really sure. I've built a sand castle with an example of a single polygon having this issue.

I've already tried several ways of representing this polygon but either of the two problems always persists.
Any help would be apreciated, or clarification if this is a bug or has already been solved, since I haven't been able to find a solution.

### Reproduction steps

1. Create a small polygon
2. give it no height

### Sandcastle example

https://sandcastle.cesium.com/#c=nVhtb9s2EP4rnLEP8ubSepecpsHSxFgDtE2Ruh2GOkhVmba4yqJA0Um9wP991JtJKjlsWPLBEh/e23N3lE4pKyqB7il5IBy9QgV5QBekorst/tysWctR2txfsEIktCB8OZqgx2WBkCCcy5WTXmDR3uM1Z9s/GM9X3YI1niyLw/jlslgWgu9b4bSxK2hOKiKk4eQhoaLX1P54l4sWbjReseK8kjdXK8u34zCs9aHOcVylpCC45HRLBb0nFU5WK6tT3hruLX5ju2JFi83HMiOcSMPdLmwCuvI02RKe4PrutbHJqjehgcpJu6gR+YYkNfyBijS7SYpNL4eQje1Jf/3CxsHxxlSJuVSwq9CvKLClSLtpXP+Mn/EzZ+z7uVjwpKjWjG+tzot3ieD0h4+vLufvF1eLP2vRA0oT6RSyZKIYH6vMsJxIPRvr67wGUM6aCHquTtDPj43E4WujpZZaFi2/G8K2ktVH1CyOxL4kyxE6kZcfWL7fsKIunxZLGeNSbSJI1Wz50vy7Hg6jWexHE+TF2I7CeOai24lCAhBwFeKZCCgTOiDiQdpC0LVwBiERaCcC7UQ+KBNDCAwocuLYRJSZeGYiirY4MhAVZ+ybgAciAYgoPmPT6ZkKJ3Z0ZGY7IKJ5YAIBKBJBIirOaAYiBjUzxwMRRXTkm4hyLfJMJDwioemBo7gxzahEh4EJKM9C10SU/dCkxlX2g4EZRVowkFGe+aCM70IyXgzJeAHkmzfQpph2Y4gD1wNocyGenRDKjTPImgshttJmz6DytE07torG9qEusH2oc2wH6sMhorgx14/RRLMQOCCeIBAQaUgAHHfRzAwm0hwYHMUxiESQtmAGIhHkW+CCiALMI9IHKfAjEAlBbRDggWY8TZmZUM9TiHniu7PnS0BrwkHRaEeHbTLjuiCila0ZjQO1R6wdkUNEla3pmuMAXSgbDEQCoNtj7bkyRICjIwaOGkk6cDzpMgMR6KyLtH72QhPxgZMz0jrdH2hTsfghJGOe97qdIIB8CwaBRsCzSCcnDJ+n03wS6pmJwGxGZgmCz+9YO7uHiAe8DejFOahB9/k3C705YrChBuWkNeHgDcpzQUR7uTMZ8CII8aG3Pt+H3iEHb+vN/6GZu9qpoGSVHMzkpRwNvtxKoB4TsDYAfLFvsZxW5kmaWZZaH6NXZ+1U0v8dNeFyV2X9cHORcME2PCkzmmLB6lsJJIWlixpDmS4x2FWPQL0D0i/0C7Lk8JThD1doipzYHrcDDCDgPCdg7B+Pm6mpnUu1eFhpjQ3OmnlJMtbNd6QQcms33DakdFtOeooyKgdAnmb7E8VTZ3srfeM0yY/T+gXLGcc380v8QEV2npdZYskRtPc1zZOqomsqB0SpZSHHOCX5BMKvrxdvpOB0ik5foE8ygO1WeosEQxUhSGTkGE2a01IucLbbZA2w4fWsi16cNeJ1EIRuMnFD1nLyLVJl9o25Ll1/e764+jy/W1zf/X5z/en95cRUcYLa6fqgPj+Yk/I63y+Y9bgilahzR2smj7zJzB/0dPQEXpfHQq6Vd8wL8kPUQ+4NWaF33U456bag3E5yksoN612R1uLIGquy7qjB/W9vSZr4l1y9bFUcjmE+8Wchf3f8fzhF10hri586R+Z1Ce5xtStLxkXVK60/NMy76rwu+s8+etHr32nU+ri/HOtN/kCLFXvASU64MJTU4TSqUevHMScVSjhBBROo80wGLOMRGa1QmSei/g6yHGl2X/bXh/+QhOUI4yndJhtSTVse7t6yDbtrs/JXuVmOniTitqmcj0mxSpNK5KTu2QVj+beEvyPFzhpUU+3QaDI6rcQ+J2e9T7/RbR0M2vHcki4Isq2DkV5826XficBpVfWRnE510dMVvUd09eqZb3dtY0tkvcvzj/RvshydnU7l/iei3Uef63vC82Rfb8ucs7ftIsb4dCpvn5cUbaADzf8A

### Environment

Browser: Chrome
CesiumJS Version: 1.119
Operating System: Windows

**Comment by ggetz** [comment] 2024-08-15 15:40
Hi @FranchoPlz,

I noticed that when setting a height of `0` for each individual position, rather than setting `height: 0` on the polygon entity itself, [behaves as intended](https://sandcastle.cesium.com/#c=nVhtb9s2EP4rnLEP8ubQst6dpsHSxFgCtE2Ruh2GOkhVmba4yqJA0Um9wP991JtJKj5sWPLBEh/e3XMPj5ROCctLgR4peSIcvUY5eUKXpKTbDf5cj1mLQVLfX7JcxDQnfDEYoedFjpAgnMuR085g3tzjFWebPxjPlu2ANRwt8v3w1SJf5ILvGuOkjitoRkoiZOD4Kaai89T8uFfzBq493rD8opQ3N0vLs6MgqPyhljguE5ITXHC6oYI+khLHy6XVOm8CdxG/sW2+pPn6Y5ESTmTgdhY2Ad15Em8Ij3F198aYZFWTUM/lqBnUhLwmcQV/oCJJ7+J83dkhZGN71F2f2Ng/3JguMZcOtiX6Ffm2NGkmDauf4RGeGWPfL8Scx3m5YnxjtSzexYLTHx6+uZq9n9/M/6xM9yiJJSlkyYVifKhWhmVE+llbX2cVgDJWZ9BpdYp+fq4t9l9rL5XVIm/0XRO2kao+o3pwIHYFWQzQqbz8wLLdmuVV+TRYwhiXbmNBynrKl/rfcXEQTiMvHCE3wnYYRFMH3Y8U4oOAoxDXRECbYAIiLuQtAKkFUwgJwTghGCf0QJsIQmBAiRNFJqLCRFMTUbJFoYGoPCPPBFwQ8UFE6RmZpKcqnWiiI1N7AiIaAxPwQZMQMlF5hlMQMaSZTlwQUUKHnokoaqFrIsEBCUwGE6WNGUYtdOCbgGIWOCai4gemNI6K7/fCKNH8no1i5oE2ngPZuBFk4/oQN7fnTSntRJAGjgvI5kA6TwJobSa9VXMgxFbe7ClUnrYZx1bZ2B60C2wP2jn2BNqHfURpY44fsgmnAXBAvEAgINQQHzjuwqmZTKgR6B3FEYiEkDd/CiIhxM13QEQB5hHpgRJ4IYgEoDcIcMEwrubMXFDXVYh54jvT4yWgbcJe0WhHh20q4zggopWtmc0E2h6RdkT2EVW2JrXJBNiFcoOBiA/s9kh7rvQR4OiIgKNGig4cT7pNzwQ660JtP7uBiXjAyRlqO93reVO5eAFkY573ehzfh7j5vURD4FmkixMEx+U0n4T6yoTgaoZmCYLP70g7u/uIC7wN6MXZq0Hn+JuFvjkicEP1yknbhL03KNcBEe3lzlTADSHEg976PA96h+y9rdf/+7rvarqCgpWyMZOXsjX4ci+Bqk3AWgPwxb7HsluZxUlqWWp8iF6fN11J93fwhIttmXbNzWXMBVvzuEhpggWrbiUQ55ZuajRlukVvVtUCdQQkL/QLsmTzlOIPN2iMJpE9bBoYwGByzKA/30bjMTo7OUHvK0ZsSYwJw2HdVjWNq5YwK6yhIWrdUElJ2waQ5EJObbvfWrV2ymmnYUplh8iTdHeqhGzJbSR5TuPs0M5fsoxxfDe7wk9UpBdZkcaW7FG7ZJIsLku6orKDlF7mss9Tli8g/OZ2fi0N66zRJ5nAZiPZIsFQSQgSKTlkk2S0kAOcbddpDax51Qyjk/M2BULXqbgjK9kY54kKem2OS+JvL+Y3n2cP89uH3+9uP72/aomPx42LU9Q033v1dcJspFfZbs6s5yUpRbW0tNLxoJosjL2+GJ18t8Whzivnre6C/BBVD3xHluhdO1M2wg0op5OMJHLCapsnlTmyhqrqW2Fw99tFkiH+ZaVeNS72hzRf8JnL3y3/H6ToCmm75qeWyKwqwB0ut0XBuCg7p9V3iFlbm7d591VIL3n9M44aH3aXQ/0MeKL5kj3hOCNcGE6qdGrXqOFxWJMSxZygnAnUMpMJy3xESktUZLGoPpMsBlrcV931/j8swmKA8Zhu4jUpx40OD2/Zmj00q/JXsV4MXizEfV05H+N8mcSlyEi1Y+eMZd9i/o7kW6tXTRWhwWhwVopdRs47Tr/RTZUM2vLMkhQE2VTJSBbftsl3InBSll0mZ2Pd9GxJHxFdvj7yaa/Z1hJZbbPsI/2bLAbnZ2M5/4Vp+03o9pHwLN5V09LJ+dtmEGN8Npa3xy1Fk2jP8z8).

While I'd agree this is not obvious from [the documentation](https://cesium.com/learn/ion-sdk/ref-doc/PolygonGraphics.html), the example above should be enough to resolve the issue so I'm going to close it. If there's more to this though, feel free to re-open and add more details.

**Closed by ggetz** 2024-08-15 15:40 UTC
Labels: type - bug, needs triage

**Comment by FranchoPlz** [comment] 2024-08-20 06:10
Hi @ggetz ! I'll be trying setting the individual heights to 0 on my personal code and I'll let you know if it worked later on. but on the sandcastle you provided and even setting the height manually to 0 on mine. I can see the pollygon still behaves weirdly. 

![image](https://github.com/user-attachments/assets/a4cf5c77-3fa7-4c28-94a5-0a37eda1e2ce)

Does this also happen to you? Could be something hardware related? Thanks!

**Comment by ggetz** [comment] 2024-08-20 12:56
Hi @FranchoPlz, 

No I don't see that artifact on my machine. Strange. I'd suggest updating your graphics card drivers. If that doesn't work, visit webglreport.com and take a screenshot of your results.

**Comment by FranchoPlz** [comment] 2024-08-20 18:42
Ok! I'll give it another try. Hopefully everything works as expected after updating everything. Thanks for confirmation :)
