### ISSUE TITLE
High-Precision Line Geometry Issue on ARM64 Apple Devices

### ISSUE THREAD

**Issue by MisterGC** [CesiumGS/cesium#11603] opened 2023-11-03 10:58 UTC
I'm experiencing an issue with high-precision polyline geometries that appears to be specific to ARM64 Apple devices. I've attached an example polyline that demonstrates the problem. On AMD64 systems, the polyline is rendered correctly as a straight line without any disturbances. However, on ARM64 devices, the line exhibits jitter and zig-zag artifacts. Please refer to the attached screenshots and the Sandcastle example for a clear illustration of this discrepancy.

Could you please confirm whether this is a known issue and suggest any potential workarounds for ARM64 architecture?

Environment Details:
- macOS Sonoma 14.0 with M2 Chip
- Safari Version 17.0 (19616.1.27.211.1)
- Issue also replicable on recent versions of Chrome, Chrome Canary, and Firefox.

This [sandcastle](https://sandcastle.cesium.com/#c=nVn9axxHEv1X5gSBFZhVdXX1l08yd/iCIYTkSEJ+OeWHsTSKl1vNiNmRHSXkf8+rlXWxPXWQskDLfsy86a6ueu9V99U0Hpbu7W54N8zdRTcO77qXw2F3f7v98fjd5vLk6vj55TQu/W4c5suT079fjpfj1fHOn4fpq8M0vpym+Xo39stwAMp/Lsfu+Pe/N10XwjawcCZmyiXn/OzP36RsW0u51BBCC1T5g9/o6e1Pz/4vamgpihTJIcQ1bKwhEkfOzQsbKSXOUVIrK9jUapCakqTshKWcSqbEkeoaNVVOlFuS4kUlqhUj5RTXMUihYvoUShQfbGxBJJdQqMa0gpUsLROCHpyjjZUrSSvSQlwnggQMNBEuiU7YUlhKKTEEaitY/CopkmABvLABwUsF+VDDGlYw/UAZ8U9O3JxDjBGrTUnWuFRb4dpSEDcuBptDLoV4nbiMOmnUUGrFmwwJM5UmhVHEa1wGaoypNHbDkiC/ckkhGbCoiITJeBctEZWYBaVfjSCQlm+rlPkzcAU5jyzNFmwWFBl7SSFKI05IshA5GrCRsZgtB28mgKEE9JezGVoiJC8iROKGpVLLMcLrOgutRMxFpHlRQYu6LqnFYKBioEpw7kSQghcGSYElDdigeYuaYDcsxUCBQynJgKVCohLS3EuWG4aDmWapFm7CalKM0Q8baw1HDbZgQQcJ9FbcsAm3J8SXjSjUqnKPlK5uWGRQRc7XVAzYVIVLLMlfZqmFzBpFExehhZEAtBs2VWrCjauxZmoUJEhp5B8uxIer1GbhlgbirOljH/GXYJVtoFelBKN8IaIgcry661fDAH4sYsImAtNUhmlw4zLMkto7I8UQnqRk5EeNFeQPOSzVKIhCCZjIMXdsY4IZCFg0Q9NDxvwxE0i7mxZiSKTu2HA2AUVYSubiJ3IuSriBSjISLMP5CCQpuIPAckwg/pj+nmCDaj2owR8EBiHkirzPa5WEbgS4u5zFHQVkEYy+GiMjuHggeDxxckchRCghFzC2QTYJVSiolNz8wyUOAelJhicPcExRO5fqhiUIS9HmpBjyC7NUsaifsWYo+4r41mh5BWi+SkcjL9lEbe1yxZ1kBFfU5qLlY0pu3EygqNSyJevwIJBQdYFuWFYaE7UhBixCr6UoXoGApDcOyM9WjODGqk41p+yPAnwjofXjLEZ0tcEQeKrCblhEL2cIjFG+MUI9GcH3epCIjM0V0hINDoNERohSSe4EQy+Jfga+yOIaVHWt4M0UvLCQABgY9Lhi5BdLZf0XdwzQikuDZ2rGrkJgrGMMnyGSEW0kmqSka2bAYrEiErC68wDshMAiwSwGC5WPRr+5lwyNIsqowOAZQYDuVLh99g8WkYuVWzN8AkoXLcvRjHphpYJpatU9CwMXZhRWH62vGzZhxA3uw2h7A3rI9LhP4mYacExFDgkHI7bwNPCS4raMYISMCmW2fAKhQwUjNHJvgCACSIOsyWuwLYyHpALX4x9tAI1DccTYZ4QzQ2lnCu7WLKrDr5FVWlawyC5EHosp7sYX2QPfAk9eRQxc2GkYvOhufNHrFWR8K8lQSHQOsGesbbqba5Dy6PvgxUxcuFEoEjyeG1ZaQ1VkonX9wojDnKFD9Ssk+ASy3QSlb8CWQLGh83PbJZglrujstGE3cNFJUoWkuYNLEDPtlowMqyp0tfj3GbEgCTeDVaIFS9q1qfJ6B8tgVG66uWxIL5UCbwY9K35YlFGuKLVm1ANGCqLhjzvtvwYLzy1wBMHYWaGC9jVIyMTe6MINQSJjTtYeCCHB0D6Akd1RqNpK5ob8XBM5aa+DlkUCu2FhBggVasUWc4AZ1U0QLypIHGFACCxqzGh0gm4bsx+XQbhy1FgDl7Q3g3x4uYazzjMrhRlLloraMFFBc+NC0JAGZB3u4Es9NAG9eU0jmjJwlO4xGdtLpNuBhIm4mxJO2ulgzclaNO34tPtlPyyhn5OoxGDAJmKlBfbTgm6NshCzlQvCglQpfmvD6D/hb7NUY2sFxdeQKRTdRK5bKtBt/mTH+gm2RD2ZgP+xo/v45qfjAe7leHbW/TD34+Fmmm+75c3QvRqmr77/9pvu6oPj3N24TMcf9ap+6YZf7oarZbjuXj+8PyruNv3Y9fPcP3TTTTfe374e5sPp0wnx4/Hxv6fDbtnhi+7CODPe3uz7ZXO6vdntl2HebN72+/vhGR59Pfxy2l28eHzXfdHF7m8XFx1/dAI9D8P43Rs89evdOAD+8TB7O4wLngjs/vp685tOfOxvh+fd5ckrvaPTqy9PjlG6m/YPe3x83v32GKC7p9E+fzoNf9nPGOeuH+P2Zp5u/zXoYw//1ElvPpnh6fvIv9tdL2+ed08cgtgN867f/wk57ad5++q7L7/85njJ73j9/XFm76fw6zTd/jBtPpmQXnLy7OT8sDzshxdPS/uP3e3dNC/d/bzfbLdny3B7t9fQnr2+v/rvsGyvDscb9dLzsw9vPb/eve121xfGQX93te8PB/xyc7/ff7/7FfF6cX6G61e37qceS/nzt2+Hed8/6GVvwouvH7/cbrfnZ/ho37lM0/51P3+C/Ac) demonstrates the issue.

On AMD64:
![polyline_on_amd64](https://github.com/CesiumGS/cesium/assets/2118573/c03d776d-81e0-4d12-8d5a-2bef7c421c11)

On ARM64:
![polyline_on_arm64](https://github.com/CesiumGS/cesium/assets/2118573/5e58a8cd-74ca-4e2e-8dfd-c08b54e1fe20)

**Comment by ggetz** [comment] 2023-11-03 13:00
Thanks for the report @MisterGC.

I believe this is the same issue documented in https://github.com/CesiumGS/cesium/issues/9417, where there's further discussion of the cause and possible workarounds.

To keep discussion in once place, I'll close this issue as a duplicate.

**Closed by ggetz** 2023-11-03 13:00 UTC
