### ISSUE TITLE
The globe doesn't show when I zoom to whole globe in moble phone browser.

### ISSUE THREAD

**Issue by YuWebGIS** [CesiumGS/cesium#11571] opened 2023-10-19 02:14 UTC
Sandcastle example: Cesium 1.110（from Cesium 1.96 to 1.110 occour this problem, but 1.64 doesn't）

Browser: Weixin(Any browser in this mobile phone will occour this problem)

Operating System: Android(A low performance device)

When I zoom to whole globe, the globe doesn't show, but I zoom in a high level, the image can show.

When I change to 2D mode, the image can show.

![微信图片_20231019100527](https://github.com/CesiumGS/cesium/assets/9292914/a0f4947b-c2e1-4bec-a97a-06a789b02299)
![微信图片_20231019100535](https://github.com/CesiumGS/cesium/assets/9292914/68a8945b-ac75-4e08-bf9c-841acdc6a01d)
![微信图片_20231019100542](https://github.com/CesiumGS/cesium/assets/9292914/a52c5fdb-279d-433a-a755-d26fef15a804)
![微信图片_20231019100545](https://github.com/CesiumGS/cesium/assets/9292914/9dfd446e-88c3-4020-b3ea-363121ad840c)

**Comment by syzdev** [comment] 2023-10-19 10:11
I have tried various methods, but this problem seems difficult to reproduce.

**Comment by IKangXu** [comment] 2023-10-19 11:45
refer to this reply. [11289](https://github.com/CesiumGS/cesium/issues/11289)

**Comment by ggetz** [comment] 2023-10-19 14:02
Thanks @syzdev and @IKangXu. I'll close this as a duplicate of #11289 to keep discussion in one place.

**Closed by ggetz** 2023-10-19 14:02 UTC
