### ISSUE TITLE
Partial terrain cause half globe become transparent

### ISSUE THREAD

**Issue by wxia5** [CesiumGS/cesium#6598] opened 2018-05-18 03:23 UTC
prior to 1.41, the `Cesium.CesiumTerrainProvider` works fine with terrain data located in a specified area. When upgraded to 1.45, the terrain still works, but causing half globe become transparent , here is the code I imply terrain service.
![426a4d3dc717e7478598c11cf66f8fab](https://user-images.githubusercontent.com/11541946/40214503-b540ff74-5a8d-11e8-8353-a82703cf6fe5.png)
![3a251bcdaaa6874a8ed8cdcc7458539a](https://user-images.githubusercontent.com/11541946/40214504-b720245a-5a8d-11e8-9800-f3e46843498a.png)

`var terrainProvider = new Cesium.CesiumTerrainProvider({url:"myservice"})`
`viewer.terrainProvider = terrainProvider  `,

**Comment by wxia5** [comment] 2018-05-19 02:34
@Vineg I guess it could be the same, but everything works fine for me in 1.41. Will check your workaround when I got time.

**Comment by hpinkos** [comment] 2018-05-21 15:10
Thanks for reporting this @wxia5
Since this is a regression I've marked this as 'Next Release' so we'll try to fix it ASAP

@bagnell @tfili any ideas here?

**Comment by wxia5** [comment] 2018-05-22 01:29
@mramato yes, I only have data covered a small part of globe, basically from latitude 34.71 to 34.72 and longitude 113.31 to 113.33, so I have no data for the other half globe.
 [link to data:](https://www.dropbox.com/s/txhfc0teru64wg2/terrain.rar?dl=0)

**Comment by mramato** [comment] 2018-05-22 01:34
@kring, @bagnell, or @shunter can confirm, but I believe that has never been officially supported in Cesium and if it worked at all, it was only by accident.  I could be wrong though; hopefully one of them can chime in with the details.

**Comment by kring** [comment] 2018-05-22 04:25
Yep that's correct. You at least need both level zero tiles, one for each hemisphere. If you have no data in one hemisphere you can just create a tile with all zero heights.

**Comment by hpinkos** [comment] 2018-05-22 16:50
@kring @mramato should we close this issue then?

**Closed as completed** 2018-06-01 13:25 UTC
Labels: type - bug, priority - next release, category - terrain and imagery
