### ISSUE TITLE
Gltf model: Some parts seem inverted since recent update 

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#11045] opened 2023-01-24 14:16 UTC
As reported on [the forum](https://community.cesium.com/t/gltf-model-some-parts-seem-inverted-since-recent-update/22055)

In the screenshot below, older versions of CesiumJS (which ion currently uses) loads the below GLB model without any problems, but the latest release shows some parts in the wrong place.

From the user:

> I suspect that this might be related to the fact that some parts possibly have negative scales & this was handled wrongly in cesium till the recent update introduced with the new gltf model class, see [here](https://github.com/CesiumGS/cesium/blob/1.101/CHANGES.md#198---2022-10-03)…can you confirm this? Thx!

![image](https://user-images.githubusercontent.com/1495196/214316118-a078da6b-df75-4c74-983d-f28b2e5636b7.png)

I can see this going one of two ways:

1. The previous model was wrong and the new model refactor (not used by ion yet) has fixes that cause the scaling to be properly handled now.
2. The model is correct but the refactored introduced a bug.

**Comment by mramato** [comment] 2023-01-24 14:17
This model also has animations, not sure if that changes anything.

**Comment by ggetz** [comment] 2023-01-24 14:44
@lilleyse or @ptrgags, since this has appeared since the model refactor, would one of you be able to take a look at this?

**Comment by ptrgags** [comment] 2023-01-24 19:04
I downloaded the model and tried it both in CesiumJS and [another glTF viewer](https://gltf-viewer.donmccurdy.com/) for comparison I was getting similar problems in both, so it's likely a problem with the GLB itself.

First of all, the GLB file passes the glTF validator (up to the validator not supporting the Draco extension)

The reverse thruster flaps on the starboard side of the plane seem to be flipped/inside out on the right side in both viewers:
CesiumJS (`main` branch):
![image](https://user-images.githubusercontent.com/8422414/214382933-08aa3bad-a2fb-4326-ace7-8694529a10e8.png)
glTF viewer:
![image](https://user-images.githubusercontent.com/8422414/214382840-24a6378b-66f4-4ae2-a2c6-6efc13cfef24.png)

The covers over the wheels on the starboard side and the wheels on the port side also seem to have the same problem. CesiumJS:
![image](https://user-images.githubusercontent.com/8422414/214383689-1cb5972d-effe-4459-98f8-4e9ca0e84581.png)

![image](https://user-images.githubusercontent.com/8422414/214384035-93a70885-d952-4fc4-9e35-b02f41333850.png)

glTF Viewer:

![image](https://user-images.githubusercontent.com/8422414/214384550-594beed1-28b9-40b1-a66b-ca5359f5a1fd.png)
![image](https://user-images.githubusercontent.com/8422414/214383913-43337619-e751-4ae9-8ae5-fc31e558bfb7.png)

**Comment by ptrgags** [comment] 2023-01-24 19:23
I looked into the glTF and I do see some negative scaling factors which might be the cause of this.

| reverser left | reverser right |
| ------------- | -------------- |
| ![image](https://user-images.githubusercontent.com/8422414/214386299-dabe0fba-d950-40a2-8674-b03d52aee7d5.png) | ![image](https://user-images.githubusercontent.com/8422414/214386576-5c253969-b7ae-451a-825c-5ead54c3aaaa.png) | 

Also see [this section of the glTF 2.0 spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#instantiation) -- basically glTF uses the determinant of the computed node transform to determine winding order. Applying a negative scale has the side effect of swapping front/back faces. The data would have to have clockwise triangles for the negative scale to work correctly.

**Comment by ptrgags** [comment] 2023-01-24 19:31
As for why is this behavior different than the old Model:

https://github.com/CesiumGS/cesium/pull/10405 -- this PR fixed it for the new model architecture (back when it was still called `ModelExperimental`) but the PR description mentions that it would have been difficult to fix in the original `Model`. 

So if the model was working in the old `Model` it was likely by accident.

**Comment by ptrgags** [comment] 2023-01-24 20:00
To summarize:

1. This specific plane model, while a valid glTF, is visually incorrect due to negative scales without updating the triangle winding order.
2. The old `Model` from before CesiumJS 1.97 incorrectly handled the negative scale so it "accidentally" canceled out the problem and rendered fine.
3. The problem was fixed in the new `Model` implementation, so now the problems in the plane model are visible when they weren't before.

Closing this issue since there's nothing to be done in the CesiumJS code.

**Closed by ptrgags** 2023-01-24 20:00 UTC
Labels: type - bug, category - model

**Comment by tkazik** [comment] 2023-01-28 18:53
Thx a lot for the detailed analysis and insights, @ptrgags.
It wasn't an "accidental" cancellation, but we had to deliberately export our assets "wrongly" so that cesium would display it properly (kind of like "minus times minus is plus"), for details see [here](https://github.com/BabylonJS/Exporters/blob/0a3964acc8145a27180c07f52438116c14305b6e/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs#L1025). 

@lilleyse luckily fixed the issue for objects with negative scales (see https://github.com/CesiumGS/cesium/issues/6304) and now we no longer have to export our models with wrong winding order if they have negative scales.

So all good now and thx a lot for your great work...I just wish I had seen the model update somewhere in the release notes of [1.97](https://github.com/CesiumGS/cesium/blob/1.97/CHANGES.md) as a major change) 😄
