### ISSUE TITLE
CallbackProperty doesn't work when requestRenderMode and pickTranslucentDepth enabled

### ISSUE THREAD

**Issue by vladyslav-tk** [CesiumGS/cesium#12005] opened 2024-05-30 08:04 UTC
### What happened?

When I use CallbackProperty with enabled requestRenderMode and pickTranslucentDepth, I get an error and the app freezes after zooming with the mouse wheel or clicking near the entity. It is only the case for volumetric objects like polylineVolume, box, etc.

### Reproduction steps

1. Open sandcstle
2. Zoom in\out with the mouse wheel

...
[sandcastle](https://sandcastle.cesium.com/#c=nVXbbts4EP0Vwi+RAS1NUjfKdYLddQ20wBYJEqMFWvdBkeiYG5rUkpQTt/C/78jyrW67WdR+sGZ45gxnzmi8KixaSfEkLLpEWjyhsXCyWeL3W19wUW7NsdG+kFrYixB9nWkEHy+sBdeNNStZCTvcB5ZWFF58MFZV0w4SdgElcIhnf117abQboq9P4v5BDfd87ac2kPPGirmwQpdiiC4W8mHxWy3s3NhlAa6LHdlms3uw4p9GOH8rNFzinakgyNtGwOmm/2qmZ3oFBbpSaAH1dYXirQmH21/cOPFa1H5xI8tHqR8A1hIcjmtwT22hnWrA9lvoEdN92xyLQlfqvIt30A2h7+qiFJMVRL/pQEFHXRYQ6Y7XvDfPYwCdk4wL6+Gp0FEQR1FMKMEpIzSKeJyHKKWM8AineURIzkjKQhSnLEppikke0zTNorxLMW902fYedRKNlaxrKPhGFVoEum2wClElnW8b3d/rYoVvrP7mPv8dCLk2bTrQ23mQ1Mmt4FDTp73SPy0u4ynBUcqSmBDCobiI8ITjNM5JTElMorY4mjCa4YSQmCcZ5/3wJdo4Y9AzRmOW5FkaAy1hecxwSiPO44wk+ZaWUA4+DpRJQuOXaVnGgSTPs4TzLEpClOQs5xRHYEEFWxdIkScswSzhlMWMpS/TUpA1wgzCGYsSCrcFgXOOOfACLaVpSxvFSZLjtk9JCtlepv213n7ezXgnplOyBOH/NM8T7aVfH18p0dpSOFxUVbCbnL30w+NgH25ZG7VWsFDeG9UsxdkS2E3M8NtalLovykfYN7AO/DoI+ujy6jTuMKoHgldoMEB/N3BxWB+wsJw/ojchmhfKiWPj2g1lYcVN17U4bLPxwYXfvZ1ObievT/Cm8W0Nw47p5GAJr5eVhTqhUcbiD2+AAj9Jv/hD1YsigJk8Te8WRZv502lJ6DstGf44ub0OfwH0o8lgAQwY6f8vJAkRhdE5Q3/eG5vjyu1m4osxy6kJzoemxfTC3sj5tRJX++jf5bI21qPGqgDjgRfLWkEX3eC+KR+Fx6XbLsoWOhqcho4quUKyupz1zv6qZj1UqsI5OJk3St3JL2LWuxoNAP9dqDJFBXe8XgmrinULW9Crvzonxng0APPHkd4YmEt7xvwv)

### Sandcastle example

https://sandcastle.cesium.com/#c=nVXbbts4EP0Vwi+RAS1NUjfKdYLddQ20wBYJEqMFWvdBkeiYG5rUkpQTt/C/78jyrW67WdR+sGZ45gxnzmi8KixaSfEkLLpEWjyhsXCyWeL3W19wUW7NsdG+kFrYixB9nWkEHy+sBdeNNStZCTvcB5ZWFF58MFZV0w4SdgElcIhnf117abQboq9P4v5BDfd87ac2kPPGirmwQpdiiC4W8mHxWy3s3NhlAa6LHdlms3uw4p9GOH8rNFzinakgyNtGwOmm/2qmZ3oFBbpSaAH1dYXirQmH21/cOPFa1H5xI8tHqR8A1hIcjmtwT22hnWrA9lvoEdN92xyLQlfqvIt30A2h7+qiFJMVRL/pQEFHXRYQ6Y7XvDfPYwCdk4wL6+Gp0FEQR1FMKMEpIzSKeJyHKKWM8AineURIzkjKQhSnLEppikke0zTNorxLMW902fYedRKNlaxrKPhGFVoEum2wClElnW8b3d/rYoVvrP7mPv8dCLk2bTrQ23mQ1Mmt4FDTp73SPy0u4ynBUcqSmBDCobiI8ITjNM5JTElMorY4mjCa4YSQmCcZ5/3wJdo4Y9AzRmOW5FkaAy1hecxwSiPO44wk+ZaWUA4+DpRJQuOXaVnGgSTPs4TzLEpClOQs5xRHYEEFWxdIkScswSzhlMWMpS/TUpA1wgzCGYsSCrcFgXOOOfACLaVpSxvFSZLjtk9JCtlepv213n7ezXgnplOyBOH/NM8T7aVfH18p0dpSOFxUVbCbnL30w+NgH25ZG7VWsFDeG9UsxdkS2E3M8NtalLovykfYN7AO/DoI+ujy6jTuMKoHgldoMEB/N3BxWB+wsJw/ojchmhfKiWPj2g1lYcVN17U4bLPxwYXfvZ1ObievT/Cm8W0Nw47p5GAJr5eVhTqhUcbiD2+AAj9Jv/hD1YsigJk8Te8WRZv502lJ6DstGf44ub0OfwH0o8lgAQwY6f8vJAkRhdE5Q3/eG5vjyu1m4osxy6kJzoemxfTC3sj5tRJX++jf5bI21qPGqgDjgRfLWkEX3eC+KR+Fx6XbLsoWOhqcho4quUKyupz1zv6qZj1UqsI5OJk3St3JL2LWuxoNAP9dqDJFBXe8XgmrinULW9Crvzonxng0APPHkd4YmEt7xvwv

### Environment

Browser: latest Chrome, Safari
CesiumJS Version: 1.117
Operating System: macOS Sonoma 14.4

**Comment by ggetz** [comment] 2024-05-31 14:31
Thanks for the report @vladyslav-tk. This looks like a duplicate of https://github.com/CesiumGS/cesium/issues/11427.  I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

**Closed by ggetz** 2024-05-31 14:31 UTC
Labels: type - bug, needs triage
