### ISSUE TITLE
Incorrect rendering for self-overlapping translucent object

### ISSUE THREAD

**Issue by darkpaw** [CesiumGS/cesium#8781] opened 2020-04-22 06:47 UTC
![image](https://user-images.githubusercontent.com/1531935/79949234-8cd77200-84b8-11ea-9342-002caafbeb14.png)

Sandcastle example:
https://sandcastle.cesium.com/#c=3VVra9swFP0rl3yJC4kUtxmjWVpW0rENNja614e6UNW+ScT0MJKckJb890mWQ14MypbAmD7Y0tU5x/deH9kzZmDGcY4GLkDhHEZoeSXJ9zqWtPN6OdLKMa7QtE9eZSpTM88yWPxgQnha5BNUjjuOlrCiSJ4yBX4oJhEG0L7BAuYBzRxMkU+mrt2JiDo6gAYfRqmt19HK+nCTzYgZ52dMnZGx0fIaJwbRXhnDFu9qNZvcdtP0Bel1oN8P19NeGH621v3D0T3v7cvenWwIS664rGSTic/6No3Phni/28Qyh4YzsVGbFtqQmzfXEbTM1HLd5FCnen6b3wZ4bGnoE9jKjFmOMOduCrpywr/DIzS+97Lu0Nmq5L9sfPf8OHq9Q+mtCj644FbF2x5b+2bjlL6XbIIfm63PRpdo3CL5fSJPwANjAPdT50o7oNQyVeTMOoEkHnWSa0mj/DcVnD3mWNAra9FZWj/PUu+Rbu7PP3ekVJP7DjjDlC2Z8d4c+EWFsAzJrxNpvAdxd9fpe24//dftnq4+CAey5zH00kO68yiC/f/L7s81e+PsR63lV53s+DyAWp3W0LqFwMtIfs1lqY2DyoiEEOpQlsJ3wdKHKv+JjuS2pg3pijQs+Ax4cZG1dv7fWQtywaz1O+NKiC/8EbPW5ZB6/BZNaFZwNfk0QyPYIkCm6eWHGCSEDKlf7rOc1uKBmQ3FXw

Browser:
Chrome.

Operating System:
Linux

**Comment by OmarShehata** [comment] 2020-04-24 16:13
@darkpaw the wall itself is correctly opaque in the areas where alpha is 255. You can see this by placing another object inside the wall and see it's occluded:

![image](https://user-images.githubusercontent.com/1711126/80233700-eb216380-8624-11ea-88f9-cbd43e29a07a.png)

The issue is that this translucent object overlaps itself, which I believe is a more fundamental graphics issue. 

[Sandcastle with sphere in the middle](https://sandcastle.cesium.com/#c=3VZtb9owEP4rHl8IEjiwUk0DitayaavUaZNKtw/LpLrJJVhz7Mi+gGjFf5/zRngZWyfBh80frORy99zdk+fizJkmcw4L0OSCSFiQCRiexvRLbnOafn47URIZl6CbbfLkSWKX0gHoaxlAAnaTONVMGpH6IP3lgKBOwZOr1tCTnizwqXXiyMFQFgROiZIoY21KDqq8E6bRXjF5RkOt4rcQaQDjdHrdl7TbJv18P+/aRbutdgECQvDEKB6QQVVdtjQLOLemja5qdKfEWIPtoWYrZgiaM0Hq+pRQml7d3L0rvFZ1l5ZJXJOAX5kQltLf9C5ZDBa4+d52KMki889aJibVIfOBLDjOiEpRWOKbZVG511aXFYOG/IHDS63Z8gPwaIbG+WYJfZUTepbtvW5JQo37t6vz+jR43WPhVQ0fHXCr4+8H5LMhwuuYRfCxfPRZqwQ0Lp3DhTwRnkUMyP0MMTED1zVMBj4zKIAW80l9FbsF/J2MueQhh8C9NAbQuHk+41qNdHwNAUeayOi+XYg1YdpqsxhYssqKrwsptUeqcd7Xu1GCB/+C0nv2PfWPqMxT4PWOKcyTAPb/B6WHTJhS6s8Tuidv6yqsqqdKiQemr1JEJZ3mVEWRgM1Pf65de1KGqfQzwTqtUsU7xwM1M7Wwk/PiV/bhOv9zsueDeDDvekzXGbctw41eyzF+VCqeKmdnqDOnRrsxMrgUMC7A3/A4URpJqoVDqYsQJ8K+cuM+pP4PQOqbPGzkVkGjgM8JDy68xs7PhdcgvmDG2CdhKsQtfwSvMR651n8rTCh7ssvo0xy0YMvMZdYb3xRGSunItbf7UVgQt4H4Ew).

**Comment by darkpaw** [comment] 2020-04-25 02:12
@OmarShehata Thanks Omar. The walls also render correctly in front of the terrain, but that was two different wall entities in the example. 

My real case is multiple fairly straight walls that don't self-overlap much at all.

![image](https://user-images.githubusercontent.com/1531935/80268812-b3cab980-86ed-11ea-87f0-552968cd3505.png)

**Comment by hpinkos** [comment] 2020-06-12 17:52
@darkpaw although it's not ideal, what you're seeing is fairly expected behavior.  By default, we use "order independent translucency" to draw transparent geometry quickly, and as a result the blending of two transparent images is the same no matter what angle you are viewing them from. so we don't have to sort them in by.  Setting `transparent: true` tells the renderer to treat the entire image as transparent, and even if some alpha values are mostly opaque, they are blended as transparent colors.  We are tracking this problem in this issue: https://github.com/CesiumGS/cesium/issues/4170

For your use case, you can try setting 
```
var viewer = new Cesium.Viewer('cesiumContainer', {
  orderIndependentTranslucency: false
});
``
to disable order independent translucency and see if that will give you a better result.  It should look better for the case where you have rows of individual geometry, but probably won't help for self-overlapping transparent geometry.

I'm closing this issue because there's not much actionable for us to fix here.  We'll track the related problems with translucency in #4170 instead.

**Closed by hpinkos** 2020-06-12 17:52 UTC
Labels: category - graphics

**Comment by darkpaw** [comment] 2020-06-13 01:41
Thanks @hpinkos I'll try that. Happy to have performance optimisations of course, but it's also nice to be able to turn it off like this.

**Comment by Amber-372** [comment] 2022-03-31 01:32
![image](https://user-images.githubusercontent.com/13759303/160958102-5719e01f-be3a-4218-8133-53d90d15cc51.png)
If the ball also has transparency, the transparency of the wall seems to be wrong @OmarShehata

**Comment by Amber-372** [comment] 2022-03-31 01:46
![image](https://user-images.githubusercontent.com/13759303/160959569-81117690-54f6-455f-8498-fff8108c66a1.png)
When OIT is false, the ball can be occluded, but the back wall is displayed in front of the front wall @OmarShehata
