### ISSUE TITLE
Exports not found in '@cesium/engine'

### ISSUE THREAD

**Issue by claustres** [CesiumGS/cesium#12035] opened 2024-06-12 10:13 UTC
### What happened?

The following error appears when launching an app bundled with Webpack:
`export '_shaderspbrParameters' (reexported as '_shaderspbrParameters') was not found in '@cesium/engine'`

It seems to me that the `cesium` package is using `"@cesium/engine": "^9.1.0"` as a dependency requirement, which could lead to the installation of the 9.2 engine version that does not appear to work well with 1.117 version.

A similar trick as in https://github.com/CesiumGS/cesium/issues/12034 can solve this in your `package.json`:
```
"resolutions": {
    "@cesium/engine": "9.1.0"
}
```
The problem does not appear with version 1.118.

### Reproduction steps

1. add `"cesium": "1.117.0"` in your `package.json`
2. run `yarn install`
3. launch your app

### Environment

Browser: Chrome 125
CesiumJS Version: 1.117
Operating System: Linux Debian 12

**Comment by ggetz** [comment] 2024-06-14 14:36
Thanks for the report @claustres! I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/11834. I'm going to close this issue to keep discussion in one place. Thanks!

**Closed by ggetz** 2024-06-14 14:36 UTC
Labels: type - bug, needs triage

**Comment by claustres** [comment] 2024-06-14 14:55
@ggetz Yes you are right, I missed this one. Maybe the use of a `package.lock` file will help solve this kind of issues.
