### ISSUE TITLE
Camera does not follow trackedEntity when entity is cylinder or ellipse 

### ISSUE THREAD

**Issue by xxbld** [CesiumGS/cesium#9455] opened 2021-03-29 09:18 UTC
Sandcastle example:
[example](https://sandcastle.cesium.com/index.html#c=xVpbc9u4Ff4rGPdh6VamLMmSbcXJNPF6k3TstWu52YdVpgORsIQ1RHBAUJG24//egxsJipSjbKRJJrHJA5wLPhycC5gFFmhByRci0GuUkC/okmQ0n4efNC0YH0T6/ZInEtOEiPHB4atxMk7a7RGRSM4IEjiJ+Rwl+XwCQjJCYvTIBYp4ktFMkkQiQbKcySwcJ1b4DZazMCPyXrP+qjlHwBj0fOETnidxhvgj4jkIpvOcYUl5giSdk3GyAMsziYUEw63cf+WM4uRnLEn4KPhcPQRqTfqhe9zpt1AX/sKvzuBQqTIyeNooAsfxiMAy4iwYJ8joaqmnTvdY//bgKtmCw3HiVnGDnwjKckEcxDRD2KAWA58AqNRaABgzHkaMR0+h1vQAA2CWflb0BCS/qk3kaTGPp5umRbkQsA/bSNQ/YVumpITksqCF17e3d/8dPdzevULt9jUH4OxySBKvSYLdkjRlVDtWp2b5jOcsfpvQOUAGE6TIie9XYCoDd0OS+xtvPKIQ5WaFf3I+f+CB2SENhdmBhXXuGx4TBlr+p3aNzGmWgbR70DxE/dDs5VTgBZWrITq2hDkF4/L5HYikESPX9BFmd8KuGcTLFwYN5ygFj1bUY5/FUk8sVZs8ijAj5UzA0lKccanVM6J/ArVryM96iXaPnhJAlecylAJHT0GxaOfkknM2wWorYh7lc/CGcErkFSPq8d3qYwwn3c4xJ3xdLk5TtnpHk5gm06yU33KSS8BBIAB5xzOq96wSVS5hIfCEk17gLDPTbwWFB1zn+HcO2yQSoBccgpuJEEUEXVanG1opfa6M3DzxJDB2P+ZJpHVHfJ7mktyUbIExsKV98tC4kCAyF4k1PWzgUXNbjeqUvucCqjmVsLqbbYzUuwixNmN4K1wdSl+Fc5auhf4PBKtdvqMymt1zxjz1WXXmQ2nPvVWnPXcDqle15QYWUGPDBv0mlpOpICQL1PFE5Q9gVLqQsi2swlODRsuxLm9COkJH7iCi4uBDfA9P7JMnURFKVR66NWS1nhqIYGmr2BSDT+FI1e3W/BuhdYZl1sS6DzlLCzdLedbZCIgDVnEdnfbDTv/07LTXOR50TvrnA62kdx6en54NuoPBWa/THZyemQxnRXe3Fz3o9Qbnnd758Um/X0ju9/r947Pzc8iqa5IbAsgIz1NGYhdd7gRPiZAr63COR6duPdPlBAWBmtM4g6d6Qnc9hoFqm2n0OyWZYgu0x+IFpgxPKNNJwz8TcPQ/JrAjC8wuYeOJPgLB72a3Nkw0MtUfbe/QKzYMkadD/dOSng/1w2fzSwe5IbIyckGHaHwQhm2zQChKcFtPydpG9Q1lTw8ij57W38Mpm4wPrA6XAOmSMJN4BuZYPJssxRhNM1KohcpvTm9owsXbJc0gS7nTZAbwH2sDRkq0ggQeE1GIYSSZyhkkw/I4wrLv4TDl2dA7oxMuJZ87er+gq3pCUAxwOJ/kjIvw/upnT6va1V/AQYcbYuhR57gMMfrZAO28Z1g8aTIvk1dF4icCtU41uRUO6wQowc9eGabzN4mvnAMaTywcM4tIQkq/1K/uwLgiYQVV91wVemowTAWFCEEX1nnX6ta7CpNzQ6jKpqTuRNmcP4HAZKp9xEzVjqoxXkP8+uP7Dw+jq7fv76+ufg2/UDl7y9IZhgB+euhCVxI3cf724ePDVYVDw+/ps+VRUYWEJbUUXZvkaIWsxhKvnN8wXDjZ8kXG+vC6TlsG1pRpelVLfapHL+TqLTPHtMmnu4GLJaUcv6psvTxsRstdqNbQHsQevZg8yUUm4ZD+7nS026pnyIgZQV8oY4hHEVacmLEVylZJpEr/SBDVHmCkm4lIeQe0TOTxEYKqE9bgzO+U2DKkIl26+UHC2wgVaXyqwVZRS/LzYevbtXkBrKKuvyd1G1bXPW7U12vS97nYMgYua+UOtNxKrVF1MSrAKlvaBV3/rNZLk+FLpWDBl6cxbPsluMIEguEQ6d7jvWnQTBQvemwV+GzrNooEhmLrxcLYq0l9oQEUALG0tSh4528EZKjmnDt7wQchlmMGtqEFeB8X+pKDYFDoDgqiCZoSDlEX1hOhLMWRau3hTFXLmTR0L7YKrFdPkEXnmMHBK/JEa22ZphStc9q2e/VupWIdFvbcV5ntfpfn1g6jvwMMrSYOV1PqLBgubGJrrPxclvEntl6wopxVLVy9DAdJjPxHO4WSfrUAhK/13RJ4XLGhgZ5a6dOqKTGsNoNfa/XsasEd3kYRzxOpdxwnKxTN1GVIptxD330YXzZlmCpAQFTYoL6x23vhPJQGjFJwLV8VfYQMhydQCWtF8Bp4yRBmH7p6qiTPTEeC/vFa3TS8Wh9OVaeyaVBAIeuPPduipXZPoAbVzcLtJFOFLVjo3xWMD/wEMT441NOzfJJFgk6It5dwhD9hlpNiHXUsCznqSGGRkV8Yx7LkNIb+JSsrqe9brKzUYcD8kml19zQx+6PL5OHSsBfStmRbbcdmUsE3a1tna9T212BvKLi+x0caxO3eVRpqve+yuS5uDzZ7teYOANZy9obs91vpydm9lWXn8T02llJ2b6Fre74r3FoZW1inQiBPlVh1WahrfitTkqVUTaWpGJFNecV9AzAQdVsyRKVdhT2bkulatVerRW0Qe/aa/zVrRumMiL1YYySX1vS3sOaSJ/tBBuQ6S8p2wP8cJ7m6TMFJFpxAK3HoJm1h8zu+3IfJILZucXNp37EXNe7nC9Z/1k46wkkM/aZkuqB8MJ8wbkiSB9Z1FeNB6+AikytG3jhx/6TzlAuJcsGCMGyD6SmDAiRrT/LoicgwyjJXtak/f3NfXbxuTXU0U6G+Yw2RmE5wcNJtIffvODxzFhuUYlWxDdFJuvTIEy5iIo6EvfvyB58blNMECkzfhAVR4GN2BB3GNBlCrxjHjNT1Hulbx25Ftxsy12/V0SbluuokFQQeeSKPvhA6nYF3TDiLfQHq10XbR/0ipgtE49cNX6JRxHCWwchjzpip1d5ctGF+jRXClTL7FpbO8EpNm3XeXBtiGIYXbXht5iw+ihVOcCFVjH1TLuhCTni88giKJCrvihK/UcXqRRse6kNVCtDMrslVSsAIofoNWC8kXHgDB1fPeAnP+nIS3uAYpeoVHqFNwkcTmijrFyo8DyvXNS2kiaadGqKftKKfvPU1m6AOu9IDKMNb/+t6ahJrKweCQunruKmt3QFu3QK1wTagVa7H9ghatdnYGWg30DKq8nEnDtcpoOttA13TzekeEWzsG3YHJF7+OCAbbpL3CWRTM7NTj9RV+I5j4Le4pLk0378v2q5lp07447DzPzjs3/12jd1I/ycx3b/sPPtugZ73bWqP2Pl96M6Qu0riH4db8blunwVL0RvvDDP7SWEHiB11fcy622BmL9j3CZlVsTVi3mulTIZ3r452xbd5+z8)

```js

var entity = viewer.entities.add({
  availability: new Cesium.TimeIntervalCollection([
    new Cesium.TimeInterval({
      start: start,
      stop: stop,
    }),
  ]),
  model: {
    uri: "../SampleData/models/CesiumMilkTruck/CesiumMilkTruck.glb",
    minimumPixelSize: 64,
  },
  ellipse: {
     semiMinorAxis: 20,
     semiMajorAxis: 20,
  },
  cylinder: {
    length: 10.0,
    topRadius: 0.0,
    bottomRadius: 5.0,
    material: Cesium.Color.RED,
  },
  viewFrom: new Cesium.Cartesian3(-100.0, 0.0, 100.0),
  position: position,
  orientation: new Cesium.VelocityOrientationProperty(position),
});
viewer.trackedEntity = entity;
```
Browser:

Operating System:

**Comment by xxbld** [comment] 2021-03-29 09:23
resolve way
```js
```

**Comment by dzungpng** [comment] 2021-05-03 16:18
@xxbld Thank you for proposing a solution! Could you open a [pull request](https://github.com/CesiumGS/cesium/pulls) and include some testing to make sure it does not introduces any side effects? 

It looks like the issue is because the bounding sphere state is PENDING when the tracked entity gets set, so the function above automatically returns pending. The cause is NOT because there are multiple entities (if we comment out the model entity and one of the two primitive shaped entities, the bug persists).

**Comment by dzungpng** [comment] 2021-05-03 16:22
I can confirm that it's happening to box entity as well: [Sandcastle](https://sandcastle.cesium.com/index.html#c=xVptc9s2Ev4rGN+H0ncy9WbJtuJkLvG5SW7s2rXc9EOVuYFIWMKYAjggqFjt+L/f4o0ERcpRGmmSSSRygX3BswvsLpQlFmhJyRci0GvEyBd0QTKaL8JPmhZMDiL9fsGZxJQRMTk4fDVhE9Zuj4lEck6QwCzmC8TyxRSEZITE6IELFHGW0UwSJpEgWZ7ILJwwK/way3mYEXmnWX/RnGNgDPq+8CnPWZwh/oB4DoLpIk+wpJwhSRdkwpZgeSaxkGC4lfvfPKGY/QdLEj4IvlAPgVqTfuh1uoMW6sFf+OoOD5UqI4OnjSJwHI8JLCPOgglDRldLPXV7Hf3twVWyBYcT5lZxjR8JynJBHMQ0Q9igFgOfAKjUWgAYMx5GCY8eQ63pHgbALP2s6Awkv6pN5Gkxj6ebpkW5EOCHbSTqT3DLjJSQXBS08Orm5vZ/4/ub21eo3b7iAJxdDmHxmiTwlqRpQnVgdWuWz3mexG8ZXQBkMEGKnPhxBaYmEG5Ict/xJiIKUW5W+Cfni3seGA9pKIwHlja4r3lMEtDyl/IaWdAsA2l3oHmEBqHx5UzgJZWrEepYwoKCcfniFkTSKCFX9AFmd8OeGcRPLwwaznEKEa2oHZ/FUo8tVZs8jnBCypmApaU441KrZ0z/BGrPkJ/1Eq2PHhmgynMZSoGjx6BYtAtyyXkyxcoVMY/yBURDOCPyMiHq8d3qYww73c4xO3xdLk7TZPWOspiyWVbKbznJJeAgEIC85RnVPqucKhewEHjCrB84y8z0G0HhAdc5fs3BTYIBveAQ3EyEU0TQp+p0QyulL5SRmyceB8buh5xFWnfEF2kuyXXJFhgDWzomD00ICSJzwazpYQOPmttqVKf0PRdQLaiE1V1vY6T2Ipy1WYK3wtWh9FU45+na0f+BYOXlWyqj+R1PEk99Vp15X9pzZ9XpyN2A6mVtuYEF1NiwQb85y8lMEJIFanui8gMYlS6kbAur8NSg0XJsyJsjHaEjtxFRsfHhfA+P7ZMnURFKVR66NWS1nhqIYGmrcIrBpwikqrs1/0ZonWGZNbEeQ87SIsxSnnU3AuKAVVxHJ4OwOzg5Pel3O8Pu8eBsqJX0z8Kzk9Nhbzg87Xd7w5NTk+Gs6N72oof9/vCs2z/rHA8GheRBfzDonJ6dQVZdk9xwgIzxIk1I7E6XW8FTIuTKBpzj0albz3Q5QUGg5jTO4Kme0Fs/w0C1zTT6nZJMsQU6YvES0wRPaaKThr8nYOt/ZOCRJU4uwPFEb4HgD+OtDRONTPVH2zvyig1D5OlIf1rS86F++Gy+IC8+jVAhIgbBTGW4bLThjOjqvVN+HhaaVDoWFCejgosnXGhvmmIt+AvhJJ1jna6cHWCQ/lZo/QxTN+k96nbKraufDb/zyqh40mReJoWKxE8Eaohq0igCwQlQgp+98kbnRRJfOscaDxcOzyLCSOlv/eoC0SXfFVSzC1VAqcEwFRR2Hl3aoFirB28rTM69UO3MIIFPDsKwbaIPKkbczhb8EQSy2eSgZc4FGwca/DVXXH18/+F+fPn2/d3l5S/hFyrnb5U/4GA8cc6AAqKJ8/cPH+8vKxwafk+fLTuK7B6W1FJ0bZKjFbIaS6dyfsOwld5YVnmM9eF1nba8qinT9KqW+lSPXsjVLjN1V1NM9wK3c0o5frXWennYjJZeqNamHsQevZg8zUUmYY//4XS026oWz4gZQV9okiAeRVhx4iRZoWzFIlVSR4KoshsjXaRHKjqgFSEPD3BYOWENwfxOiS2PKqRLorJKtSeIARzOhwrVYKuoJfm5PHe219btNKsb7EndhtX1Oo36+k36PhcuSyBkrdyhllvJ4dUQowKssiVT0PP3aj3lj14qsQq+PI3B7RcQClM4DEdI1/TvTeOjTX0ueld18NmWaBwJDEXMiwWnV+v5QgNIrLG0NR5E5+8EZKimlzt7IQbhLMcJ2IaWEH1c6MsDgkGh2yiIMjQjHE5dWE+EshRHqmWGPVUtE9LQvdjqql6VMC4WOIGNV+SJ1toyTYlX57Tt7OrdSp11WNh9X2W2/i73rR1G/wQYWk0crlbTWTBc2sTWWFG5LONPbL1gRTmrWhB6GQ6SGPlNB4WSfrkEhK/0nQ1EXOHQQE+t9D/VlBhWm6yvtVB2tRAOb6MIGnqpPY7ZCkVzdcmQqfDQdwomlk0PpyoTEBU2qG/sol7YD6UB4xRCy1dFHyDD4SlUmFoRvAZeMoTZh67MKslzU+mjf71WJdGr9eFUdQCbBgUUiP7Ysy1aav23GlQd+800UwUjWOj34JMDP0FAA6+nZ/k0iwSdEs+XsIU/4SQnxTrqWBZy1JbCIiM/JxzLktMY+resrKS+b7GyUocB80um1cPTnNkfXSYPnwx7IW1LttV2bCYVfLO2dbZGbX8P9oaC63tipEHc7kOlodb7Lpvr4vZgs1dr7gBgLWdvyH6/lZ6c3VtZdh7fY2MpZfcWurbnu45bK2ML69QRyFMlVl3C6ZrfypTkSaqm0lSMyKY83UuqYWAg6hZihEq7DsvbguZkulbt1WrRV37bbz7XrBmncyL2Yo2RXFoz2MKaC872gwzIdZaU7YD/M5fkd1AfYJYFx9BKHLpJW9j8jj/tw2QQW7d4y3uizdZ/1kE6xiyGflMmuqC8Nz8NXBOWBzZ0FeNB6+A8k6uEvHHi/k0XKRcS5SIJwrANpqcJFCBZe5pHj0SGUZa5qk39+Yf7NcPr1lRHMxPq96ERErMpDo57LeT+dcJTZ7FBKVYV2wgdp08eecpFTMSRAHflWXXwuUE5ZVBg+iYsiQIfJ0fQYczYCHrFOE5IXe+Rvs3rVXS7oSmXUt2f9b6iXFedpILAA2fy6AuhszlEx5QnsS9AfZ23fdTPY7pENH7d8AsvihKcZTDykCeJqdXenLdhfo0Vjitl9g0sPcErNW3efXNliGEYnrfhtZmz+LGpCIJzqc7YN+WCzuWUxyuPoEii8q4o8RtVrJ634aE+VKUAzXhNrlICRgjVb8B6IeHCGwS4esZP8KwvJ+ENtlGqXuER2iR8NKVMWb9Ux/Oocl3TQppo2qkR+kkr+slbX7MJarMrPYAyvA2+rqcmsbZyICiUvo6bcu0OcOsVqA23Aa1yPbZH0KrNxs5Au4aWUZWPOwm4bgFdfxvomm5O94hgY9+wOyDx048DsuEmeZ9ANjUzO41IXYXv+Az8lpA0l+b7j0Xbtew0CH8cdv4PDvsPv11jN9b/+Ur3LzvPvlug5/02tUfs/D50Z8hdsvjH4Vb8XLfPgqXojXeGmf1JYQeIHfV8zHrbYGYv2PcJmVWxNWLea6VMhnevjnbFt3n7Pw).

**Comment by dzungpng** [comment] 2021-05-03 16:25
This is actually a duplicate of https://github.com/CesiumGS/cesium/issues/5164

**Closed by dzungpng** 2021-05-03 16:25 UTC
Labels: category - entity, good first issue, type - bug
