### ISSUE TITLE
A BUG about picking up entities

### ISSUE THREAD

**Issue by ShenWeiQun** [CesiumGS/cesium#10847] opened 2022-10-09 02:05 UTC
Sandcastle example:

[bug demo](https://sandcastle.cesium.com/#c=tVRda9swFP0rwk8OGMWSv6Q2LStt2AbrOpquL/MYqn2TispSkJWUdPS/T07idGsCY4U9GOtenXPv1TlCldGtQ0sJj2DRCdLwiM6hlYsG365zYRlU6/jcaCekBlsGg+NSlxqhas21UH8xajUz2vM3hTBoJ52EFou6Dn92WIS0aOAIlcE11Gi+IZRBtNnbxkdoi0XoXoIVtrpfHfXznAvr/EroBE+taS5gZgHaM2vFKvzW0xAihOEkJnGSEhIzTnkRoYRiWhBGU56mpGBFkUV7BE4TTmmasIztCCnLCpJRzpN9POOcJHle5DHp8RlnNMtIxg7h44LRhHUNenhO4pjkqW/AojfP/32wWzbCgZVCvShmlLH4enyxhTyv/89/2tepqP/JwPcd4/9bGLOCc5ZT0h13IwGlCeUkzWOW0DTaJ9Cs4IVXmfOdZt5DSnOSH9KYE5JzwgqSvmhceI8YJzw+hKcp9f19J7IbKKcxL2LOsix68wH+7uH76/H4876LqLfryZjmxoSvzOuN3qbbqjNuMhcVjJce80HoWnV5cB/1fOHOKieNDqcLvV6gsDFLaDxw0Hu6uTFTEG5h4eWytBVowHNZPewofgb/KrSyK7SZFCE5ReGWO+jP21U0CrAys34Pyxp3V22NeY56ISavpr9ZzQFfXn2djH9cXt2OB8dBFJTBulX/ITRq3UrBad/tnWzmxjq0sCrEeOigmSsveDu8W1QP4HDVtv2wo+Hv1FEtl0jWJwceQ1Qp0bZ+Z7pQaiKfoAxOR0OP36MqI2qpZ1dLsEqsOtg9Of20SWKMR0MfHmY6Y9SdsK8q/wI)

Browser:

    Chrome 106.0.5249.103

Operating System:

    Windows 10 

Description:

    Please load demo and enlarge the map
    There is no need to rotate the camera Angle
    You'll find it hard to pick up the red entities

**Comment by ggetz** [comment] 2022-10-12 12:43
Thanks for the report @ShenWeiQun. I can reproduce.

The selection indictator also appears above the green entity one selected:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/4439461/195345494-418407cd-a555-4218-adbf-472a57566de0.png">

**Comment by ggetz** [comment] 2023-06-02 17:34
I think this is actually a duplicate of https://github.com/CesiumGS/cesium/issues/7116. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead. Thanks!

**Closed by ggetz** 2023-06-02 17:34 UTC
Labels: type - bug, category - picking
