### ISSUE TITLE
HeightReference.CLAMP_TO_GROUND Can't clame to ground	

### ISSUE THREAD

**Issue by gitgitczl** [CesiumGS/cesium#10274] opened 2022-04-05 12:06 UTC
When I draw a polygon and set Cesium.Heightreference.CLAMP_ TO_ Group, but some polygons will not be displayed. The terrain used here is ArcGISTiledElevationTerrainProvider.
like this,The lower right corner is not shown.
![image](https://user-images.githubusercontent.com/34705741/161750008-be2f8efc-1482-40b9-b84c-9425c95d72f1.png)
this is my code:
![image](https://user-images.githubusercontent.com/34705741/161750165-fd74377b-54b7-4376-98a7-2ce54d8ff5d4.png)

**Comment by ggetz** [comment] 2022-04-06 13:08
Hi @gitgitczl. I'm having trouble reproducing the issue with [this sandcastle example](https://sandcastle.cesium.com/#c=7VrpbxrJEv9X+vnToJBmTmawnehhm3jRYrCATRSFKBqggX47TKPuxo4T+X9/1XPAXPhI1rv7IVEkz1FdU13Hr45mxkIh0Q0lt4SjNygkt+icCLpd4/fRM21yNIvuz1kofRoSPjmqo++TECFJOIcn15zd0Dnhx9nFbT677I7GNCDzTkBufElZOM7TaxEThLY8OI6vEJocraTciONGg6SrrDn2+WxJBZ6xdSO+bHAiZEMQfkNBuMYHxoP9Z6yLRvIluOqu/SUZAWEkt/rMfQ3+3NdOkj1jMSMhwcuATQmek41cjYF3ewnLhUz4gF4k35KTSTgJR344n/lCBgT78/kFWfjbQI4ZC6Y+vyLhVlPf+BTv53u6rUZjf4XGDM0Cf71BG0ZDKRDjaEqDYMp8PhdIEInkiqAVocuVHJIF4SScESQZOu+1r66/jAdfLoeDP/oXauGw02uPu+87+6flT0ryVR6DZi+4f4uu1TfRLZUr1POnJEiUov6BI4DSZ0C72IYzpUmk1fZ7QGgWuQoBbSSqI6GkkhKhNKFlCBFsTVDF4Tj1h3OfS7jyQwsvOFtfkCUnRGivDdPERsvx6shuwoXh1Op5PiDuMcrxVoIEjO9Zqzs8+v3jWe+PTj1PuaFfSTCi38gxMvTCO7aVAfjzeQWzj51eb/Chmv4DncvVMbIKbwv22jH8Lf8cF4yY43KfuwuUfUp7T615rlyIzJVfLDnbhvOMJeN/CxZGlIa9kUj4oXgNAUMXJbq/QnLgwjj9piAiGHC6pHvL/1Z4gXudd+PCYohOSWelpe9zj/FZe9TpdftFGy8geKqMeNZrn/9eoBUrdnvmz/6MVXYchXWBZLp7nTDNoFr0RDPqKP6vY7d2cPU1BAUNl/n1aRSYmvL44uI5Ff40IBcpCl1QIf3IJP3tegoBdz0YdaNw7/bfdfvd8ce6ApQ5BLaIQCNyGQSABTEGYc4WKUYf8jLAwUnmZRLXksMuALhVeN9BuCvky69N/36vBJmzFM7+5eiyg91SlFGVNtR+MG5E16Kx8Gc0AH3g5QvF0IvYJZd5zhnndM64qIMKg7slaBxBOkMc7OKHy4AIyAxBgKYkzlAAL/5WsrUfRWFwh+hCudkd8jmJwg4IolTix9bzwecibFZcM99d+QKFLFGSSlvgLHw7h9XxI5yh7Q/GnWM0IlJC8KRLAOT0WLQkRGL5gAI/ku/SLb+QJ84S9iUHSl1UPOKjbQjPO+1TfjFCiefWi89jN7brlfSmUUVf8TSmtp5E/bkIUrdx/jN1XcfFlAqeAinGDwpIfDnsdPpYeUo72Kx8TceFQHzc9b8xth4zjdSeCUXXsZ+/GBBF3EvWX1HCoVJd3ZXe5DyjZHZUmSwsrUwHRjQtxzMsD3u2a9m66ZXtHJFZrm3rroltp+XYBtxVktnAy3A87LiGbbiO5Tplqlr9Z+V1TcvAdssE/npTtw4K7Bi6hV3PazZ10/CcQxLrrm7iluu4btNsWi8isdMy4BO6aeqObT2gYdNuYd1sua5nOwc1bIKZsAGMXA82+DIK1j2QQ285DmikeVBe2JiFQWrd9jzjAZdoNQ3sNS0TLGG2niLw58KT+6chhCrd/xmAGMPNlkMq+gGkgHSYs8R/kj3FCRqL7WbDuBRXyZ7FgvFOgiWDtBsumDLblGbf1PY3tTym3NJwzm6xH0CxXGA2OUob2KRkSLUvogweMugLYhlh/7A7uaICbQJfgqDryVHu+yfZO05AZ2Hm0X3WIr8A9BeA/gLQFwfQbHMSb/BLjy3ZlxhR/7dZlroUKJqFoAso5qNx3N1m36icl17hcWc4bHf7xQ5aDpn0c90X4NsKSzb056Baodl/G3YP077lhcq7XV9UMYFiHLp7sMW+wN9Jk+tBK2vvytJbr67T9Sragu/XnpZlh52LfybJXrH5v37UuFYylgy95TSJtBE0nAG58KXfiEjToLvywzT84BIvg+kLTdjWNKTr7fo6M9I0vZLhvyqaEbTr0chTr/9tk59YP0iNSPcpOhovqPlUPCeI5uuwAmybNPI/MCIKSLgELm/U9vSTcuEhJDhAj6mpfTVAeU3cggTasrJFTeJx4fyRlV6rabfcWsV3oW46uNB0ccvzTKdyYTKjixV4vVPdG/Tpc0ZAqMmQFhCJKLzRT+DPaaKKE/TqFS1UhYlIpb1AlbgpYFK85xLMx0osPKaooYSIDPAaGbXDJWIsQOoI+ZMlFaFsyf3Nis40kLGudJdfXq0TvNmKlZYyrR0qQK8h7KkgmBPBghuS228igogYJ+XxFRPygkhfnVZV1+OFo656cSZfJeyh8h3LFQm1vYvHooiCAZWl2WKhjoOUp2M9p54qZ0j44MNOgVKaT/QzTkZrr94kn8nxz6kTPQ7CcSWvYv/hgj1tkIKAbgSjc/zhcuTZeJZxiGgiNmY7FI8nZOXSKdlK8UW5ooI+IlfqtON73B+UjhJ2061yxbxPqRlHvk42PYiPhtJGD9xkA93Ynfa9LHbV2dVg2O5fdipqyPyRk3mY4qnnH8nxZ/5RhMrvwPuvfmSPZZm+VxXDVfuGeqSycH582z+w8cipH/aVfK1dyJA7tPb5MgrKpzQWlq67LhRaugedm9eyvGKn4DQtW3VIhmVYLWgYio4HHZFnOCaGBsJxoK0zmochdwcXT5EMvmtD62frLa/pek6zqOXXkB+xZRstt+XpqsUp9m7QsLUgj+rQZOpu0zKa5mHJEvyY+Wto63HA2J9tqcWKrCdiP75gzCGTqsmEtk9onH61cfei0x93xx9z+eC5JWqKX9EcJDk0e+Yo6MD4Jw2gzMwnO+WpPWees+OVEfOnZjn3FUXgw+OaSpD/yeOOXUVWilpVOJmqcKo/b413aE1cvz15Ten4Izp4GrPLwwfIB1LIX5NAnpE+HkPRZyLo/ZObxWfj5CMo+TBGPoSQ5QL/GRj5MEI+go8PoWNWqmci40/iYh4K41HT5Eh19WdbKVXNCkBRK/7OCcroSGUl6CviBSdrdkPaQaApHvcRn6P60amQdwF5mwrxX7pWMKV+96VBXy3JWsEUEY3pFnpPiWdCpBKfNrJLT+f0BtH5m4pfpMWjLXiz2AZRczw5envaAPrS0oD56mcZgxvCA/9Oka2Mt734Icb4tAG31Stl/CMvWJLuJPMuaSRIuC18OUuVU/RBKqiElwHpqeocZHqAMK6Aqxlmr/8P) which uses an ArcGISTiledElevationTerrainProvider. Can you provide the positions which you're seeing the issue with?

**Comment by ggetz** [comment] 2022-04-08 13:33
Thanks @gitgitczl, I'm able to reproduce your issue with those positions. This does appear to be a bug. We'll update this ticket when we're able to take a look.

**Comment by ggetz** [comment] 2023-07-20 17:17
I believe this is actually a duplicate of https://github.com/CesiumGS/cesium/issues/8480. I'll mention this report in that issue to keep everything in one place.

**Closed by ggetz** 2023-07-20 17:17 UTC
Labels: type - bug, category - polygons/geometry
