### ISSUE TITLE
when i use CallbackProperty set polyline positions，render difference whith data;

### ISSUE THREAD

**Issue by jakejoue** [CesiumGS/cesium#11919] opened 2024-04-02 08:41 UTC
### What happened?

when i set to ConstantProperty，it is render correct；but not with CallbackProperty;

![image](https://github.com/CesiumGS/cesium/assets/25574065/11daff4d-1fd3-4a85-a0a1-6d5b2ee909f9)

[demo link](https://sandcastle.cesium.com/#c=zZdLb9pAEID/yooTSNayO/smBFVKj5VaqVUvdQ8OXsCKsS3bJKJR/nvHgCoaU+TGUYi5sOudb562Z+Z5VtXkPvEPviTXJPMP5MZXyWZNv+/2huFgvlvf5FkdJZkvw8HoKszCbL6TLCqU+hFmhDySNM+WSb2J/YRw4BSM00oGJI3qwy4oykBxUCogK58sV/WEMPIU9BCXjEpmgSljhFRG8344rjV12hkAxo3Wkol+POEcdcdXP5xljLKjC/rhABH/JhhmMaJcglW6TZICQCvBNAe4HFGhS4phxpSGFtEILblkXEgNoitRSG6lxPCBaQEdOM24dFrwzhZyZZWwGsCZls+IAWOtM47rywGxUCx30oASZ3niPQJBG2RiWVkFl8FZrjhnDIuXWX6Gx51+n8SXFM0bA5UBKZ10zjIpXoMoGUBzFxg+65cCnivE9877KyX6YsCzL8OXVM0bE1+UFskYZ9qBcifyjB2MtiCt4/j0dc4LMK2dQJlTJhqmhTMIdrwz0KGYMNiUtYOI0VAO3Vaq+zcKKwZbGov9XTsnGF6HjY3Q/9GIgNUcv/NWQhsIIFCPxRDrzgE03AqHnkn8td7Y1hpsULXUctf3dO6VnGJMSUx0u1eyBvOClzVKdLdRany0mGPWtohCc2GwbjCKtiuwf4v5NoRX7pplX3tee8h4PgOZfjj0Lsx+Hs94eZLVzZxXVHQdFcOCXM8a/mFQvInKGv9FmaCLMl9/9MvS+2pY0D/aA4KLg87m/17TKMyOJ0mf4YEtatkPo3S3TnxFozgePjb6ijzdpjiCTshu2WxUeASlJ8eD602UprfR/O5LmRe+rLfD4QgNPngRkEWUVn4U7AkPSVyvJkQ1K/T6aW/QwYJFuv2WD/d2BRjNeFNGjbpdiEZXg2Awrept6md7FiEfknWRlzXZlOmQ0nHt1wW67avx7WZ+52s6r6pGQXN0Oj4WncbJPUni6xPDNpmnUVXhncUmTb8mv3w4mE3HeL4lmuZRnGTLz/e+TKNtc2zFZ5/2m5TS6RiXpyXrPMeIlc/IvwE)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment] 2024-04-04 13:56
I do see there's an issue with heights when `isConstant` is set to `true`. I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/11074. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.

There's and example of how to achieve a dynamic polyline in the [Drawing on Terrain Sandcastle](https://sandcastle.cesium.com/?src=Drawing%20on%20Terrain.html)

**Closed by ggetz** 2024-04-04 13:56 UTC
Labels: type - bug, needs triage
