### ISSUE TITLE
requestWebgl2 Bug Cesium 1.92

### ISSUE THREAD

**Issue by Lemonjay** [CesiumGS/cesium#10329] opened 2022-04-27 01:56 UTC
![image](https://user-images.githubusercontent.com/9245295/165422787-864bbd69-fd94-4c34-9072-3ca7f6927485.png)

**Comment by ggetz** [comment] 2022-04-27 13:29
Hi @Lemonjay,

I'm unable to duplicate this error. Could you please provide more information about your system? It helps if you visit https://webglreport.com/ and take a screenshot.

**Comment by Lemonjay** [comment] 2022-04-27 14:46
This package of the Cesium 1.92 is which I build from the recent updates.  It may be a bug from Cesium recent update。

**Comment by ggetz** [comment] 2022-04-27 15:52
Ah I see. Thanks @Lemonjay. I can reproduce this in `main`.

@lilleyse Could this be due to https://github.com/CesiumGS/cesium/pull/10063?

**Comment by lilleyse** [comment] 2022-04-27 16:11
It's possible... what shader is the error coming from?

**Comment by ggetz** [comment] 2022-04-27 16:22
`GlobeFS.glsl`

**Comment by ebogo1** [comment] 2022-04-27 18:16
Ah, I noticed this in the atmosphere PR and mentioned it offline but I didn't realize at the time that the new shaders would be on by default. I can reproduce this on `main` but not on the live sandcastle.com site.

**Comment by lilleyse** [comment] 2022-04-27 18:16
Pushed a fix here: https://github.com/CesiumGS/cesium/pull/10333

**Closed** 2022-04-27 18:35 UTC
Labels: priority - next release, type - regression
