### ISSUE TITLE
Label letters have uneven vertical offset when scaling

### ISSUE THREAD

**Issue by cguinnup** [CesiumGS/cesium#5745] opened 2017-08-14 18:05 UTC
Used the label Sandcastle, but disabled FXAA and set scale to 0.5:
![image](https://user-images.githubusercontent.com/15824044/29284138-7f0731be-80f7-11e7-9c6d-c2b9623f3c2f.png)
You can see the vertical height of the "a"s are off, and the horizontal line in the "e" is very nearly missing.    Reproduced in FF and Chrome.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
    label : {
        text : 'Philadelphia',
        scale: 0.5
    }
});
```

**Comment by pizza2code** [comment] 2017-08-14 18:31
Similar misalignment also occurs when I set the font size to 14px and 16px, but don't use scaling.  This bug combined with #5746 makes it very difficult to display quality text without making the font size giant.  Also note that FXAA doesn't solve either case, which I notice was discussed as a solution in the blurry text & billboards issues.

**Comment by ggetz** [comment] 2023-07-18 15:18
I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/8474. Closing this issue to move the discussion there.

**Closed by ggetz** 2023-07-18 15:18 UTC
Labels: type - bug, category - labels
