### ISSUE TITLE
Billboard mirrored when loading ImageBitmap

### ISSUE THREAD

**Issue by bjoeni** [CesiumGS/cesium#9235] opened 2020-11-11 21:05 UTC
When adding a billboard image from an ImageBitmap it appears mirrored (upside down) in Cesium. This does not happen when loading from a Canvas or URL.

See [**this Sandcastle example**](https://sandcastle.cesium.com/#c=rVTdT9swEP9XTn1ZkDqngDRNUNBKtmlI25gGYi95ceJr4+HYke20MMT/vrPd9EP0ET9EOd/vvn/nJbewlLhCCxegcQUFOtm37D7eZeWojnJhtOdSoy1HR+elLnWeFxa5R3C87RRCzfWSu5I+dv2/9nczn7vaIuoi3mbHHyZjOJ0ELxHrHwmYLNgCfQiEj54Cn4gUixBsTrcEK0enk+4RZlZyVY4GnVTq1j9RDgFgUexp7pKzb6iUgT/GKlKPYZPCTiGV9C3vYG5Nu6mmjqrrli/wKqqzpDlivkGdzXuKI42GLBkfwXNwCXTyfCYE9F1Hja0oj8pwK5IqtZuh9tJLdIwLkT0nVTgb9Bns3IYjQx5n60THFOLr75sfcHV992P2a4t8GW//O+NkSPBsGGvBrac/rk9ZKPQzLmg0Lnv/MXUkWb6kzmzLUGb19mWkTm7KKGY/72e3b1DGycEy1kPmWgAlCjxyc03UOPLU1QH+t3cevIGWPxDFe4vgG+5B+ncOtPHkB6RzPcJK+oZ0uGcfiE3+i2EPhKn7lhrFEp++KAxSWK7Es8jzYLgxYi4wmg2FR2rzyhnVe4z83kevpKA0LtZJJPEVqEG5aPwWleTz/ZTjOm5tDm7k4JZWTFi+iuuRDaykCUwG0KbuyognxmkZtCgaqUS2iRCgNKjReDSNJV8OU/8k285YD71VGWO5R3pmqHcur/r6AamVzg1hpvmu6VTIJUhxceDpglpx50gz7+nNkP+olZfTnPCvTJXhQurFzRKt4k8B1hxffk+XjLFpTuJhS2+Mqrjd8ZwQ/wE):

```javascript
var viewer = new Cesium.Viewer("cesiumContainer");

//Create sample canvas
var canvas = new OffscreenCanvas(160, 30);
var ctx = canvas.getContext("2d");
ctx.font = "30px Arial";
ctx.fillStyle = "red";
ctx.fillText("Hello World", 0, 30);

//Create bitmap from canvas
createImageBitmap(canvas).then(function (bitmap) {

    //Add upper billboard
    viewer.entities.add({
        billboard: {
            image: bitmap, //FROM BITMAP
        },
        position: Cesium.Cartesian3.fromDegrees(-80, 30)
    });

    //Add lower billboard
    viewer.entities.add({
        billboard: {
            image: canvas, //FROM CANVAS
        },
        position: Cesium.Cartesian3.fromDegrees(-80, 20)
    });

    //Create and add a new canvas from bitmap
    //just to make sure that it's not an issue with the bitmap
    var newCanvas = document.createElement("canvas");
    newCanvas.style.position = "absolute";
    newCanvas.width = bitmap.width;
    newCanvas.height = bitmap.height;
    var newCtx = newCanvas.getContext("2d");
    newCtx.drawImage(bitmap, 0, 0);
    document.body.appendChild(newCanvas);
});
```
Using `rotation: Math.PI` rotates it 180°, but it's still going to be mirrored.
This is how it looks in Chrome, haven't tried with different browsers yet:
![](https://i.imgur.com/FPMxYex.png)

In my application I'm getting a lot of ImageBitmaps from a worker that I'd like to add to the viewer without performing any further, potentially costly operations.

**Comment by OmarShehata** [comment] 2020-11-11 21:35
@bjoeni textures in CesiumJS require being flipped. Normally they are flipped on upload to the GPU, see: https://github.com/CesiumGS/cesium/blob/ec320dd43f56219036625c8d7a4d7fded9b1dc5a/Source/Renderer/Texture.js#L178.

However, an ImageBitmap cannot be flipped during GPU upload, because it's already been decoded. You must instead flip it during decode. This is why the canvas one appears correctly, it's flipped during GPU upload. So in your example you'd need to replace the following:

```
createImageBitmap(canvas)
```

With:

```
createImageBitmap(canvas, { imageOrientation: "flipY" })
```

You can read more about the history of how this works and how these decisions were made here: https://github.com/CesiumGS/cesium/pull/7579 and here: https://github.com/CesiumGS/cesium/pull/7701. If you have ideas on improving this API/implementation we're happy to consider it! I'm closing this issue for now since it's working as designed.

**Closed by OmarShehata** 2020-11-11 21:35 UTC

**Comment by bjoeni** [comment] 2020-11-11 22:21
Oh I see. Thanks for your response!
I don't exactly understand why the everything needs to be flipped in the first place (and not just the imagery on upload), that seems a little counterintuitive but I assume that's just how the project grew. Or is that more performant because there are usually more tiles than other textures?

It's a bit unfortunate since I'm not only displaying the bitmaps within Cesium. So I guess I'm gonna flip it when creating the bitmap and the whole project has to work with flipped bitmaps now if I don't want it to be converted back and forth for/within Cesium.

Maybe it's worth noting that in the documentation? I know that it doesn't claim to be supporting ImageBitmap at all but I guess there are quite a few use cases where it's much more performant to keep existing ImageBitmaps.

**Comment by OmarShehata** [comment] 2020-11-28 23:57
> I don't exactly understand why the everything needs to be flipped in the first place (and not just the imagery on upload), that seems a little counterintuitive but I assume that's just how the project grew. Or is that more performant because there are usually more tiles than other textures?

@bjoeni this is actually a WebGL convention, not specific to CesiumJS. See: https://webglfundamentals.org/webgl/lessons/webgl-image-processing-continued.html

> Finally in the original example we flipped the Y coordinate when rendering because WebGL displays the canvas with 0,0 being the bottom left corner instead of the more traditional for 2D top left. 

I think it may make sense to explicitly document it since the engine does support ImageBitmap (internally most things are created as an imagebitmap to move decoding off the main thread) and you can explicitly creating one by passing in `preferImageBitmap` here: https://cesium.com/docs/cesiumjs-ref-doc/Resource.html?classFilter=Res#.fetchImage. 

I'm not sure if there are code paths that won't accept `ImageBitmap` anywhere that `HTMLImageElement` is currently accepted. Feel free to move the discussion to the community forum (https://community.cesium.com/) or open a PR if you find it works in cases and is missing doc for it!
