### ISSUE TITLE
Consider creating a "relative to 3D Tiles" height reference

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8606] opened 2020-02-11 16:11 UTC
Right now your options for a height reference are absolute, relative to ground or clamp to ground.

Since 3D Tiles are often "the ground" in many applications (such as photogrammetry of cities), it can be useful to be able to position things relative to this ground. It is already possible to clamp entities to 3D Tiles as shown by this Sandcastle:

https://sandcastle.cesium.com/index.html?src=Clamp%20to%203D%20Tiles.html

But this is done in a `postRender` call that continually adjusts the height. It would be nice if this were a built-in height reference that can be used from the Entity API/with CZMLs. 

My use case for this is placing labels on buildings in a photogrammetry 3D Tileset. To do this currently with CZML I need to manually specify the height for each label depending on where it is to make sure it's visible.

**Comment by lilleyse** [comment] 2020-04-20 20:54
I'm a little worried that `scene.clampToGround` won't scale super well. Terrain keeps triangle data in CPU memory, wonder if we need to do the same for 3D Tiles at some point.

**Comment by ggetz** [comment] 2023-09-22 20:03
I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/7044. Closing to consolidate.

**Closed by ggetz** 2023-09-22 20:03 UTC
Labels: type - enhancement, category - entity, 3D Tiles as Terrain
