### ISSUE TITLE
Shadows may have bug.

### ISSUE THREAD

**Issue by ZhengQixv** [CesiumGS/cesium#9031] opened 2020-07-16 12:02 UTC
Sandcastle example:High Dynamic Range.html

Browser:Google Chrome

Operating System:windows 10

By default, HDR and shadow are turned on and LogDepth is turned off. You can run the example, and then turning off HDR will produce an error. The browser can output error messages. Remember to close LogDepth for testing.

**Comment by lilleyse** [comment] 2020-07-16 17:56
@ZhengQixv I believe this is a duplicate of https://github.com/CesiumGS/cesium/issues/8372

**Closed by lilleyse** 2020-07-16 17:56 UTC
