### ISSUE TITLE
Cesium.d.ts did not export EllipsoidalOccluder

### ISSUE THREAD

**Issue by JaylanChen** [CesiumGS/cesium#10700] opened 2022-08-18 13:02 UTC
Cesium.d.ts did not export EllipsoidalOccluder.

![image](https://user-images.githubusercontent.com/7055008/185401015-734b9530-fdcb-4f76-89fa-24529774f010.png)

![image](https://user-images.githubusercontent.com/7055008/185400871-c7b7c3ec-2582-450a-a782-313961a9c5aa.png)

Sandcastle example:  none

Browser: Edge 103

Operating System: win 10

**Comment by ggetz** [comment] 2022-08-18 14:43
Hi @JaylanChen, this is because `EllipsoidalOccluder` is marked as `private`, and is not part of the public Cesium API. So there are no typing for this class by design.

**Closed by ggetz** 2022-08-18 14:43 UTC
