### ISSUE TITLE
a bug that when I render a world-scale polygon with 'holes' options

### ISSUE THREAD

**Issue by luotiancai** [CesiumGS/cesium#9967] opened 2021-12-08 04:14 UTC
Sandcastle https://sandcastle.cesium.com/#c=lVRtb9owEP4rFp+CxJywinR0FA0xuk7q1KqtukkFTSY5wJoTR2eHLqv473MSDHHoPowP4bmX587P5ZwtQ7Ll8AJILkkKL2QKiucJfap83rwTVfZUpprxFHDe6X6cp6T6RTJVmmRSFGuZfjWYpRF853pzLQW45b6ATEBjYbO8V1uEkPU+dtEk3NVVLa+ZT2zLaw7IMNoYphMmxPdJ0CPvPgzpcDjskf75Hpx6rCOw8KRQPwiqcH/Q+A9LEFTAJWRScc3NYC6skilDbRBLz+gKZfIZ1gigJois8J73Jc+PpzjgsI6FwaLbc3tszHhN/eeW6P9u3n8f0EGPnFXP0ghPjbA26rRw0XVb7hZNe+eccwum9e8riQnTh/PMhOCZkjx+yHHFIphkGTAsN4I+ze4fZz9+Xt3ef5s8HgvtmuqZ1siXuS7lO+ojKSQ6CzQtPe21m1i+F9ByvI3HoCFtZ+Gupbe+KVRFkALNkCdm3FtQlMWxd8xsrrHNcRd43TpX+Tb/cY8WzlDZYV7ubQG0vEr3caxeU9YBdzu9zkjpQsDYuj7xJJOoSY7Co9TXkGSCmUH7yzz6BZpGStmbP/Kb1FHMt4THl298KkgkmFImssqFeOB/YN4Zj3yTf0IVksU8Xd+apRGsKNM2/fFN7aSUjnxjvs3UUoolw1blvw

Browser: google chrome(latest)

Operating System: win10

![image](https://user-images.githubusercontent.com/43865037/145147053-554b2ce1-0ead-4dbc-94dc-d7900274c17c.png)

**Comment by ebogo1** [comment] 2021-12-16 22:27
@luotiancai I can reproduce the above screenshot with your Sandcastle but I'm not sure what the bug is. What behavior are you expecting?

**Comment by GatorScott** [comment] 2021-12-19 21:51
I'm seeing two problems in Edge 96.0.1054.62.  I've added points making the hole easier to see.

![image](https://user-images.githubusercontent.com/4126790/146691902-0bb076df-9a2d-4322-9185-1b96e1d1a8ff.png)

1. There's a black area running through roughly the 30 degree latitude line.
2. The hole is darker than the area inside the outer ring.

**Comment by ggetz** [comment] 2023-07-20 17:44
I can confirm this is a duplicate of https://github.com/CesiumGS/cesium/issues/4871. I'll move this report to that issue to keep discussion in one place.

**Closed by ggetz** 2023-07-20 17:44 UTC
Labels: type - bug, category - polygons/geometry
