### ISSUE TITLE
datasource index doesn't work when billboard image is transparent

### ISSUE THREAD

**Issue by Noah-Gilga** [CesiumGS/cesium#8795] opened 2020-04-24 08:01 UTC
![image](https://user-images.githubusercontent.com/42824389/80188492-d7392a00-8643-11ea-8a61-a5cb9f0ca4f1.png)
![image](https://user-images.githubusercontent.com/42824389/80189198-e2408a00-8644-11ea-8bf2-e9cf70bf654b.png)

I have raise the blue billboard datasource to the top and lower the transparent red billboard datasource to bottom.But in fact, the transparent red billboard still cover on the blue billboard.But if i change the transparent red image into an untransparent one , the datasource index setting works correctly.

**Comment by OmarShehata** [comment] 2020-04-24 15:55
@Noah-Gilga can you please create a minimal code example on [Sandcastle](https://sandcastle.cesium.com/index.html?) and share it here so we can reproduce?

There was some discussion in this z-ordering issue about transparency causing ordering to not work but we were not able to reproduce https://github.com/CesiumGS/cesium/issues/4108#issuecomment-544988437.

**Comment by OmarShehata** [comment] 2020-04-26 21:50
Closing since we don't have a reproducible test case.

**Closed by OmarShehata** 2020-04-26 21:50 UTC
