### ISSUE TITLE
viewer.scene.pickPosition does not work when scene.pickTranslucentDepth = true & pointCloudShading.attenuation = true

### ISSUE THREAD

**Issue by ugnelis** [CesiumGS/cesium#9824] opened 2021-09-23 08:09 UTC
I have this Cesium configuration for `Viewer` and `Scene`:
```javascript
var viewer = new Cesium.Viewer("cesiumContainer", {
  terrainProvider: Cesium.createWorldTerrain(),
});
viewer.scene.globe.depthTestAgainstTerrain = false;
viewer.scene.pickTranslucentDepth = true;
```
and for tileset:
```javascript
var tileset = new Cesium.Cesium3DTileset({
  url: Cesium.IonResource.fromAssetId(16421),
});
tileset.pointCloudShading.attenuation = true;
tileset.pointCloudShading.eyeDomeLighting = true;
```

the [Scene.pickPosition(...)](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#pickPosition)  fails to provide a position of the tile. This issues disappears when either `tileset.pointCloudShading.attenuation = false` or `viewer.scene.pickTranslucentDepth = false`.

If you have `tileset.pointCloudShading.attenuation = true` and `viewer.scene.pickTranslucentDepth = true`, and the `pickPosition` provides a define coordinates, try to rotate point cloud, after the rotation almost always the position is `undefined`.

Sandcastle example: https://sandcastle.cesium.com/#c=nVVdb+I4FP0rVzyMgsSahCSETmm1iFY7lVoVFWbmBWllkkvxjLGR7dBlV/3ve52PtpTOy/ASbJ97ju/x9XW/DxMF+A/f7iSC3egnoR6Bw04L5SCXuizACYkW/YhbK9YCC1gdCPMX6i06c2gBbKn23MBe4BMauACFTzBFK8ot+1bNBctOXo2nWjkuFJplpwf/LRWAQ2NoZmb0XhRoPreBuUHu8Ls2sljUkKDbW6rn7jmJVaTM5qiQPUq9Qlbgzm0WaN3kkaDWNTG0mTWXFt8H7UT+c2G4srKksbvy0YR1pvTQper3YdEkLzUvyBo/N6u8mVbekBG05zWDGVIKMJESVQ+mWpbbleDwVYk9GivcAR70SjuRW7jlKwbznCvlrSaCicQfXBVGw8LoPNdSAA3hjhIXMBU650YKbNxtD+PI3voTXzWbDSpLSyNfbLzR6gGtLk2ObG30dmIJdlME0TAZRC+GtudYHX6V33xTZc24c6hK7oRWr/78Go4HvKLauBWPG+eTfGPpsf9GbIUjiyzjRRE0hN1TYM63aDijRV9JdX4FHbNQ1Z4+H5nBjaN/XMWBhwEkSRhlScKGSRIlaRwlvXp+MEjDNGJJFGajsygK00GzkKRnaTIIWZwl2ShJ4thPd6tFbQQVyqnoF6wynwmXbx60lI10SqLDLI5HYRrGZ1maNQp/hGyQDYdhFqXxKD4bjYbNwpANRhHtZZSlSRiGo7SVfu62FfmFikPS1VG5pgqHTT08Log53RtU8x3P8XpPG25igsZUKr49t56xifbO3qhd6Sa5Ty0I0Ed14eKyvp611FaXFmeayrmugwrEUBXt3PkrtpYg0JFklQOApALevfKc3MmWLzhS7Fb0NUMt4rFY3K9+YO7se6LCCClnhPiIxcdriUzqx+CIpV5eawPBqQbo9bFmt7YHQKwhaLwvcE2trTiiZcTlKkc/fYKPFsB3K65yJIWGZ/ZyreqLPW0pGkn4bQv9b0WN9Wczevaf59rcd9a8iaMa7P2qvhaHHbK7+6/z67/v7r9dd887vc7YuoPEy1bwT7HdaeN8WwoY6zukF4c6nO2vSrKDjLC23d24/zZ0XIg9iOLig8ejfpJoZV1KORf/4rJzOe4T/iS0ad/31I0lP3jYJrq8rScZY+M+DT+OdFrLFTfvmP8H

Browser:
- Firefox
- Chromium

Operating System:
- Linux Mint 20

**Comment by ugnelis** [comment] 2021-09-29 12:09
It seems the bug occurs when `environmentState.renderTranslucentDepthForPick = true` https://github.com/CesiumGS/cesium/blob/48c8abaca6257b568edc8c992ede5f2c487cdd38/Source/Scene/Picking.js#L337

**Comment by ugnelis** [comment] 2021-10-05 11:24
I overpass this bug with this code:
```javascript
const handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
handler.setInputAction(
  (event) => {
    const mousePosition = event.endPosition;
    // Somehow viewer.scene.pick overpasses the bug.
    let pickedFeature = viewer.scene.pick(mousePosition) // <-
  },
  Cesium.ScreenSpaceEventType.MOUSE_MOVE
```

**Comment by ggetz** [comment] 2022-02-16 14:14
@ugnelis I believe after https://github.com/CesiumGS/cesium/pull/9991, the remaining issues are a duplicate of https://github.com/CesiumGS/cesium/issues/8179. 

I'm going to close this issue to track information in one place. Let us know if you think this is still a sperate problem.

**Closed by ggetz** 2022-02-16 14:14 UTC
Labels: category - picking
