### ISSUE TITLE
The model compressed with draco cannot be displayed in cesium without any error message

### ISSUE THREAD

**Issue by lanvada** [CesiumGS/cesium#10516] opened 2022-07-06 07:13 UTC
I use **[gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline)** to compress the model. however, the compressed model cannot be displayed in cesium.
this is the input parameter :
`gltf-pipeline -i {input} -o {output} -d --draco.compressionLevel=7 --draco.quantizePositionBits=20`
I also tested the model in [gltf-viewer](https://gltf-viewer.donmccurdy.com/) and it loads correctly in the gltf-viewer
![image](https://user-images.githubusercontent.com/32893646/177488222-0b6a7f06-6eba-467f-b2b1-02552316b639.png)

I found the following four situations during testing:
1. The model fails to load in cesium once any `quantizeBits` parameter is set.
2. The model loads correctly if only the `compressionLevel` parameter is set.
3. Set the `unifiedQuantization` parameter while setting the `quantizeBits` parameter. No matter if the `unifiedQuantization` parameter is set to true or false, the model can be loaded in cesium but cannot be loaded in gltf-viewer
4. After the unifiedQuantization is set, the model can be loaded in cesium but cannot be displayed correctly (the model will suddenly disappear partially when the camera is close). I guessed that the bounding box of the model might be incorrect, but after I turned on the bounding box display of the tileset, I found that the bounding box of the tile looks fine, and the above display problem will not happen again.

Sandcastle example:
This is my model before compression:
[stairs-raw.zip](https://github.com/CesiumGS/cesium/files/9052496/stairs-raw.zip)
This is my compressed model:
[stairs-draco.zip](https://github.com/CesiumGS/cesium/files/9052499/stairs-draco.zip)

Browser:
Edge
Operating System:
Windows

**Comment by ggetz** [comment] 2022-07-06 19:54
@lilleyse Would you be able to take a look at this, or recommend someone else to look into what may be causing this?

If this is strictly an issue with gltf-pipeline or the draco module, we sure ensure the issue is in the right place.

**Comment by lilleyse** [comment] 2022-07-06 19:56
@ptrgags or @j9liu could you check if this is fixed in ModelExperimental?

**Comment by j9liu** [comment] 2022-07-06 20:02
@lilleyse No, this isn't fixed in `ModelExperimental`. The raw model shows up, but not the draco-compressed one.

**Comment by lilleyse** [comment] 2022-07-06 20:06
I'm going to close since this is a duplicate of https://github.com/CesiumGS/cesium/issues/7471.

**Closed as completed by lilleyse** 2022-07-06 20:06 UTC
