### ISSUE TITLE
log depth interpolation not handled correctly for large geometries

### ISSUE THREAD

**Issue by likangning93** [CesiumGS/cesium#6573] opened 2018-05-08 17:59 UTC
Our "big" geometries aren't tessellated enough for log depth to interpolate correctly right now, which causes issues that look kind of like near-plane problems but don't present as a planar cut:

![ezgif com-optimize](https://user-images.githubusercontent.com/5395255/39773913-612e17e6-52c7-11e8-8baf-ad04bac93c22.gif)

[On Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZZHLboMwEEV/xWIDkagpaRX6IFHVpLtKldKqKzaOGcCqsaOxIUqq/HsdyLuzmzP3XmvGLUPSClgBkjFRsCJTMKKp6XfHAp937VQry4QC9AfPmcpU76CGgwIqdclQ2KoWfAZLW702RdHFWWzgXA7KCivAUJbnwW+miCvFaiBPxOcV8B/AhWaYEwRumSol+GGvOgIn3Rt3VYEoK+tYTG/DE+ZaYy4Us2DcbL/Q/BBBC9T1DEoEMMFNPBzSOEmSh5Dcj+jdKB49hsTR+EiTng7OHqhdNAomT+lTLTXS+dusF20ztb241Ebr+ksHV4fYSbzQS41dS5j01hdRLzVa0qAMKI0s1Eu52yRaNO5AlnLT2dLoYEpz0RKRjzPv6q8yj3DJjHGTopHyU2wg8yZp5PQXNqmZu1b50QJKtt5Jqnjy3kNKaRq59r/Lai0XDM8S/wA)

I'm pretty sure it's the "minimum tessellation" problem (described here: http://outerra.blogspot.sk/2009/08/logarithmic-z-buffer.html) because adding `#define ENABLE_GL_POSITION_LOG_DEPTH_AT_HEIGHT` to the top of [`vertexLogDepth.glsl`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/vertexLogDepth.glsl) seems to fix the problem.

**Comment by mramato** [comment] 2018-05-08 18:00
@bagnell was this a problem pre-log depth? (even if for different reasons).  If not, looks like a regression we should fix sooner rather than later.

**Comment by themikelester** [comment] 2018-07-04 01:49
I believe this is also contributing to a problem that I've posted about: https://groups.google.com/d/topic/cesium-dev/kMZIgIa6lqQ/discussion

**Comment by likangning93** [comment] 2018-08-09 15:31
Related, with `depthTestAgainstTerrain`:
https://groups.google.com/forum/#!topic/cesium-dev/NZwZnQnmC2U

**Comment by hpinkos** [comment] 2018-08-09 15:52
@likangning93 that's an issue with polylines, not geometry, so I added a comment to https://github.com/AnalyticalGraphicsInc/cesium/issues/6741

**Comment by ggetz** [comment] 2018-08-09 17:56
Same for vector tiles.

Brought up on the forum here: https://groups.google.com/forum/#!topic/cesium-dev/WhCZhIUaJIQ

Specifically how you can see this in https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D Tiles Terrain Classification.html when zoomed in.

**Comment by lilleyse** [comment] 2018-10-25 18:45
This can also happen in the BIM demo. Note how only the floor is getting clipped.

![bim-clipping-2](https://user-images.githubusercontent.com/915398/47522796-7d944b80-d864-11e8-9cb3-24fac66c9af5.gif)

**Comment by lilleyse** [comment] 2019-01-16 14:00
Brought up again in https://github.com/AnalyticalGraphicsInc/cesium/issues/7488.

**Comment by mramato** [comment] 2019-03-11 16:10
I run into this constantly with building size BIM/CAD models (floors clip in most views).  How hard of a fix is this and can we prioritize it anytime soon?

**Comment by OmarShehata** [comment] 2019-06-06 16:19
This has come up again in the case of creating a large clipping plane, [see forum thread here](https://groups.google.com/d/msg/cesium-dev/hsPdXyBATS4/zNF17JkFCAAJ). Notice the big missing chunk close to the camera.

![clipped_clipping_plane](https://user-images.githubusercontent.com/1711126/59049114-49025c80-8855-11e9-9929-2b5c90a55db4.gif)

**Comment by OmarShehata** [comment] 2019-06-10 12:07
Another case reported here, trying to simulate flood levels with a large polygon: https://github.com/AnalyticalGraphicsInc/cesium/issues/7918

![flood1](https://user-images.githubusercontent.com/37060597/59099516-3c1d6000-895e-11e9-8296-75c6f67a0f69.gif)
![flood2](https://user-images.githubusercontent.com/37060597/59099521-3f185080-895e-11e9-9089-3c94b40443c5.gif)

**Comment by likangning93** [comment] 2019-06-10 13:30
> simulate flood levels with a large polygon

coooooool

**Comment by JiaoJianing** [comment] 2019-09-10 10:29
@likangning93 Hi! Sorry to distrub. 
How is going now about this bug? I knew Cesium uses log depth buffer from this [blog](https://cesium.com/blog/2018/05/24/logarithmic-depth/).In this blog it mentions two log depth algorithm version: version 1: [Logarithmic Depth Buffer
](https://outerra.blogspot.com/2009/08/logarithmic-z-buffer.html)
version 2: [Logarithmic Depth Buffer Optimizations and Fixes](https://outerra.blogspot.com/2013/07/logarithmic-depth-buffer-optimizations.html).
Version 2 seems fix the big geometry issue. 
Now Cesium seems to use version 1. Am I missing something?

**Comment by likangning93** [comment] 2019-09-10 12:27
Hi @JiaoJianing, we still need to take the time to quantify the performance impact for the recommended changes for writing log depth in the fragment shader. This is important since Cesium has to run on so many different platforms, and since we also use the depth buffer for many other effects and features in the engine. In the meantime logarithmic depth is easy to deactivate if it's causing problems for your use case, just use `scene.logarithmicDepthBuffer = false;` in your code.

**Comment by OmarShehata** [comment] 2019-10-28 16:46
Came up again here: https://groups.google.com/d/msg/cesium-dev/fXHvE2psXD4/t181NoF1AgAJ

**Comment by cesium-concierge** [comment] 2020-02-25 00:24
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/topic/cesium-dev/kMZIgIa6lqQ/discussion
https://groups.google.com/forum/#!topic/cesium-dev/NZwZnQnmC2U
https://groups.google.com/forum/#!topic/cesium-dev/WhCZhIUaJIQ
https://groups.google.com/d/msg/cesium-dev/hsPdXyBATS4/zNF17JkFCAAJ
https://groups.google.com/d/msg/cesium-dev/fXHvE2psXD4/t181NoF1AgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/6573 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Closed by cesium-concierge** 2020-02-25 00:24 UTC
Labels: priority - high
