### ISSUE TITLE
Version 1.114 Zoom view not working as expected when zoom-in

### ISSUE THREAD

**Issue by honglzhu** [CesiumGS/cesium#11822] opened 2024-02-09 22:24 UTC
### What happened?

The Zoom view (Right click + drag, or Mouse wheel scroll) is not working as expected in Version 1.114 (the latest)

### Reproduction steps

1. Open this page, will display this map:
![image](https://github.com/CesiumGS/cesium/assets/17101537/39debe83-7ea4-49f7-9cbd-b196d0254d6e)

2. Start to zoom-in the map view (Right click + drag, or Mouse wheel scroll), it will stop working in the middle when I try to zoom-in a bit further to street or building level:
![image](https://github.com/CesiumGS/cesium/assets/17101537/f804aa51-e55a-4356-ab9b-0d471a5f731f)

3. In my test, Version 1.113 was working fine.

### Sandcastle example

Since I don't know how to upload the dataset (Cesium3DTileset), I created a standalone test using CesiumJS v1.114 in another environment:
http://150.136.7.93:8080/mapviewer/cesium/nyc_v1_114.html (for comparison, the same test using v1.113, which works as expected: http://150.136.7.93:8080/mapviewer/cesium/nyc_v1_113.html)

### Environment

Browser: Chrome/FireFox/Edge
CesiumJS Version: 1.114
Operating System: Linux

**Comment by javagl** [comment] 2024-02-10 02:01
This is probably a duplicate of https://github.com/CesiumGS/cesium/issues/11812 

You can try creating the tileset with
```
const tileset = await Cesium.Cesium3DTileset.fromUrl('nyc_v2/tileset.json', {
    disableCollision: true
});
```
which should restore the behavior from 1.113 for now.

**Comment by honglzhu** [comment] 2024-02-10 13:56
Indeed, after I add that property, it works like a charm!  
Thank you @javagl !
(FYI: this test has that property added: http://150.136.7.93:8080/mapviewer/cesium/nyc_v1_114_dis_colli.html)

**Comment by ggetz** [comment] 2024-02-12 16:08
Thanks @honglzhu and @javagl! I agree this is a duplicate of #11812. Closing this issue to keep discussion in one place.

**Closed by ggetz** 2024-02-12 16:08 UTC
Labels: type - bug, needs triage
