### ISSUE TITLE
Inconsistent setting of viewer.scene.globe.depthTestAgainstTerrain

### ISSUE THREAD

**Issue by LaurenceCaraccio** [CesiumGS/cesium#9177] opened 2020-09-28 10:34 UTC
Using the default terrain provider of EllipsoidTerrainProvider ends up with viewer.scene.globe.depthTestAgainstTerrain set to true.

Switching to using the CesiumTerrainProvider still has depthTestAgainstTerrain  set to true.

Switching back to EllipsoidTerrainProvider ends up with depthTestAgainstTerrain set to false.

I think the value should still be true when you switch back from CesiumTerrainProvider to EllipsoidTerrainProvider.

Browser: Chrome

Operating System: Windows

**Comment by LaurenceCaraccio** [comment] 2020-09-28 10:55
It should be noted I'm using VUE Cesium (https://zouyaoji.top/vue-cesium/#/en/index) which might be setting it to true initially?

I don't know enough about how it's set to say for sure.

**Comment by OmarShehata** [comment] 2020-09-28 13:22
Duplicate of https://github.com/CesiumGS/cesium/issues/6991.

**Closed by OmarShehata** 2020-09-28 13:22 UTC
