### ISSUE TITLE
Pick/Drillpick returns wrong (polygon) entity

### ISSUE THREAD

**Issue by matvey-tk** [CesiumGS/cesium#10863] opened 2022-10-19 07:26 UTC
I have an example where the wrong polygon out of the two on the screen gets picked.
This happens on/off, and more often in some areas than others when clicking.

In the example I randomize the colour of the picked entity.

If you can't recreate the issue from my sandcastle please watch my gif and see where I am clicking. Don't move the initial camera position as it occurs more often at close-to-ground camera angles.

[Gif of issue in the example sandcastle](https://global.discourse-cdn.com/business4/uploads/cesium/original/2X/2/2908ec84b900d67a3d13e2eeee78a270c7d08d86.gif)

[Sandcastle example](https://sandcastle.cesium.com/#c=nVdtT9tIEP4rq3yoHDXZ7PtLCtz1KFXRIbWi7fVDU1WLvZC9OnZkO1Ba8d9vHNvBBKNWZ0Fg1/PMPvvM7MxmkcV5Vlbo+O3Z23N0iI59GTYrfJyneYHPT17hm1AtX6brpYsIluMXi2zRIq6Dv/EFQDJ/08H+2c5Fi1G8HR/nWeVC5ovFaIJ+LjIET+WLAubeFfl1SHwx76Bx4V3lP+VFmnxoTKLxpIGUPvVxFfLsNEtC7KocUJcuLf0iu6sZNUxws+ankFz5Cpfgz2fv1y72J9c+q964LEnBqPCr/NqfZutN9XLrM2rXf78H+HC79vjs5PWHr6/efvzr7OTr8dnp8d99AXxtVoIA1TKU+Otu2NPj/TCLqGVcxj7zOHbZtStrz6h9Gle49FWfaOTH6PCo07F7wiWKPF7nZaiN0LNn6H6Ev4/3zetnNkMfy5BdoaQIaYoufOw2pUcQgHQK/0xjB6Mk9yXszKPSrTwC3mjpSlQzdkXIS3Sz9IVHVb5G3xGwhfXA3sFU5n3iE1Q4ABfgwWWI4sckGg3zi38htLVqDyTZEnsX4m+9rU2QmSAOP32lHnqLT2oit+Ct9YtTn11VS3SECPqjm/xMvuCQoDnKNmk64KtWtPU0KN92veY9kEtvr0DoFeRuEVy6f4Iui3x1DuLlq+gnWoUsrDar7WmaIzhOE7Ry3x9Oobuh7d09nOoN7ybolwncy9yHehXu5qQL3SH6/HCRgZ0vRmdwml1xDsmzGM1hTLXCRFGlJDFKSMkmU26w0lorxigj0lI6EYJhIbjlShgqLbGohRlKlbRWqg5lLKMSpriVgKKYG0UAIQm1qgUxwkhtZ6nSO5jklnDKrLUAI9hqqzWD5RSzvMNRzgmllBsudiSZoJoTphVRDVAxabQ0ikrKxA5JwRKWldp0SEVgLKggnDdElbbSSGOo0DscEcYwbTjf7U8AQ/hQoMEWZgVRkhNtBVUdUQojkM5oxXfLCcPAC+FGb8W0IDcox7hUwoodjnAhlJGK7jYoNUzo2n29HseECcmIIaAnU1CUh0J8+qoJrWeJkNb5qeGOTGHZi6lhLJnWAlLrKZVJvBjtJebkf+cQMTWnWiHZ0YessoQYDfIDe4VBf6sgLkaAte62DXHlTELQWCeXMhxSiBIJaVLnkcRG1HoqLpgmpgMyqSyHnNW0w+ltjkhQtYEpKYjQlHApJG1hpE5jbYhgXVSVpCA0qzPJbHkqVStOuLb2VyLHwovYxWJax3gqlKLTi5gk0+RSmkRbfulj+kjk++GXtlY8Otg+g9563h7vuiBGF11Fe9xCWkzdEQ5Ra4fvo/RiyHqdh6bb1TBcrtNQQduHHY2hFq6jaPt+aLF7F5/Tuqinrpogl1ZfwNcWtHM2AWcDtbDw1abInirM4PMqVJvEz9HaFaV/neauimB2PHkC4KoBe1c9ZQ9UH9vD5Higau+xf1Ta267limpbgBtNf0O/VoKu02zxwWV8225e+StoBGXjAe/0mLTqdvvtxt1+xr9H1ncJ1bvlNBkTDRBt2+P8qWgtgy9cES9v531/7xrUm+5l1Cj0VES63jtvLrG/7p77O2uvHt0tBrskiZp99i3vHjTQy7xAUeorFEAL8gL+HPTbaXvxgPnnz8fD5+1idzZ7uM/hyx65vaO8O8d9Zn1is1m7nR95vvqQR3ub6+P2bqErkBtfprcA2iOc+LIKmatvYQ8CdZ950VRAY2NWYAZNqO6FAm5qgnFmMbFQHAUjnE3QlFtoWcRiIxmT1BCr9sOaFwHItosN5M3SuwRqzhxJrFW9kJaUEg1XgIH8WIcqXs7RlAAva7QQUL2ZtoRCTx44V3kKWaQwM5xC22YMLjHC9svrUJNLNkXLlvRiMn4xmowWo63c3S9CB2V1m/qjzu7PsFrnRYU2RRphPKv8ag3n05ezi038Db7FxOUuYAezPvQgCdcoJIcD37RQnLqyhDeXcL19H374xejoYAb2j6BQumol3177InW3tdmSHp01kxjjgxkMh5FVnqcXrtjz/B8)

Browser: Firefox and Edge
Operating System: Windows 11

**Comment by ggetz** [comment] 2022-10-19 13:22
Thanks for the report @matvey-tk.

Your example works if [you change it slightly so that the last object in the picked list is selected](https://sandcastle.cesium.com/#c=nVdtT9tIEP4rq3yoHDXZ7PtLCtz1KFXRIbWi7fVDU1WLvZC9OnZkO1Ba8d9vHNvBBKNWZ0Fg1/PMPvvM7MxmkcV5Vlbo+O3Z23N0iI59GTYrfJyneYHPT17hm1AtX6brpYsIluMXi2zRIq6Dv/EFQDJ/08H+2c5Fi1G8HR/nWeVC5ovFaIJ+LjIET+WLAubeFfl1SHwx76Bx4V3lP+VFmnxoTKLxpIGUPvVxFfLsNEtC7KocUJcuLf0iu6sZNUxws+ankFz5Cpfgz2fv1y72J9c+q964LEnBqPCr/NqfZutN9XLrM2rXf78H+HC79vjs5PWHr6/efvzr7OTr8dnp8d99AXxtVoIA1TKU+Otu2NPj/TCLqGVcxj7zOHbZtStrz6h9Gle49FWfaOTH6PCo07F7wiWKPF7nZaiN0LNn6H6Ev4/3zetnNkMfy5BdoaQIaYoufOw2pUcQgHQK/0xjB6Mk9yXszKPSrTwC3mjpSlQzdkXIS3Sz9IVHVb5G3xGwhfXA3sFU5n3iE1Q4ABfgwWWI4sckGg3zi38htLVqDyTZEnsX4m+9rU2QmSAOP32l7n3lqcdpfhW1Hh8bdUvGJzXbW1iyNcWpz66qJTpCBP3RTX7eezlF9AsOCZqjbJOmA87rOLSuB0XfEmjew5bS2ysIzwoyvggu3T93l0W+OgfJ81X0E61CFlab1fYMzhEcwglaue8Pp9Dd0H7vHk71hncT9Mu07+X7QwELd3PSBfwQfX64yMDOF6MzqAGuOIeUW4zmMKZaYaKoUpIYJaRkkyk3WGmtFWOUEWkpnQjBsBDcciUMlZZY1MIMpUpaK1WHMpZRCVPcSkBRzI0igJCEWtWCGGGktrNU6R1Mcks4ZdZagBFstdWawXKKWd7hKOeEUsoNFzuSTFDNCdOKqAaomDRaGkUlZWKHpGAJy0ptOqQiMBZUEM4bokpbaaQxVOgdjghjmDac7/YngCF8KNBgC7OCKMmJtoKqjiiFEUhntOK75YRh4IVwo7diWpAblGNcKmHFDke4EMpIRXcblBomdO2+Xo9jwoRkxBDQkyko5UMhPn3VhNazREjr/NRwR6aw7MXUMJZMawGp9ZTKJF6M9hJz8r9ziJiaU62Q7OhDVllCjAb5gb3CoL9VEBcjwFp324a4ciYhaKyTSxkOKUSJhDSp80hiI2o9FRdME9MBmVSWQ85q2uH0NkckqNrAlBREaEq4FJK2MFKnsTZEsC6qSlIQmtWZZLY8laoVJ1xb+yuRY+FF7GIxrWM8FUrR6UVMkmlyKU2iLb/0MX0k8v3wS1srHh1sn0FHPm+Pd10ho4uuoj1uPC2m7iOHqLXD91F6MWS9zkPTI2sYLtdpqOCyADsaQy1cR9H2/dBi9y4+p3UrSF01QS6tvoCvLWjnbALOBmph4atNkT1VmMHnVag2iZ+jtStK/zrNXRXB7HjyBMBVA/auesoeqD62h8nxQNXeY/+otLdtzBXVtgA3mv6Gfq0EXafZ4oPL+LbdvPJX0AjKxgPe6TFp1e322427/Yx/j6zvEqp3N2oyJhog2rbH+VPRWgZfuCJe3s77/t41qDfdy6hR6KmIdL133lx9f90993fWXli6uw92SRI1++xb3j1ooJd5gaLUVyiAFuQF/Dnot9P2sgHzz5+Ph8/bxe5s9nCfw5c9cntHeXeO+8z6xGazdjs/8nz1IY/2NtfH7d1dVyA3vkxvAbRHOPFlFTJX390eBOo+86KpgMbGrMAMmlDdCwXc7wTjzGJioTgKRjiboCm30LKIxUYyJqkhVu2HNS8CkG0XG8ibpXcJ1Jw5klireiEtKSUargAD+bEOVbycoykBXtZoIaB6M20JhZ48cK7yFLJIYWY4hbbNGFxihO2X16Eml2yKli3pxWT8YjQZLUZbubtfhA7K6jb1R53dn2G1zosKbYo0wnhW+dUazqcvZxeb+Bt894nLXcAOZn3oQRKuUUgOB76foTh1ZQlvLuF6+z788IvR0cEM7B9BoXTVSr699kXqbmuzJT06ayYxxgczGA4jqzxPL1yx5/k/). This is because sometime a single object is returned, and sometimes both objects are.

I think this is a duplicate of https://github.com/CesiumGS/cesium/issues/9753. I'll close this issue to keep the discussion in one place.

**Closed by ggetz** 2022-10-19 13:22 UTC

**Comment by matvey-tk** [comment] 2022-10-20 04:05
@ggetz all fine if it's a duplicate, I'll be rooting for a fix!

To clarify. This was just an example and in real data there are lots of cases with multiple entity overlaps, I can't just grab the bottom of the drill result instead of the top. It'll end up selecting the wrong thing even more often!
