### ISSUE TITLE
Improve spacing around logo and attribution elements

### ISSUE THREAD

**Issue by LisaBosCesium** [CesiumGS/cesium#11912] opened 2024-03-29 21:35 UTC
Credits (logos) and the attribution/attribution link that appear in the lower left of the screen are a bit crowded and visually misaligned. Please adjust this to look cleaner. 

For example:
![image](https://github.com/CesiumGS/cesium/assets/66366602/8ebb34ce-0857-4aa1-bf8e-aa15b8598aea)
![image](https://github.com/CesiumGS/cesium/assets/66366602/5957f1c1-5998-4e1f-8791-adb38389952b)

**Comment by LisaBosCesium** [comment] 2024-06-04 18:42
Note the layout looks a little different but also not great in Cesium Stories. 
![image](https://github.com/CesiumGS/cesium/assets/66366602/2a6f0859-678a-449b-81bb-040a67817aef)

**Comment by ggetz** [comment] 2024-06-04 20:14
@jjspace Would you be able to fit this in sometime this month?

**Comment by jjspace** [comment] 2024-06-24 20:36
Just posting some thoughts I shared offline. One of the core issues here is that Google's logo (and potentially any other logo any attribution has) has a set defined height that may or may not nicely line up with the ion logo image and by extension, any text in that same block (like the "data attribution" link). We can add specific changes for google specifically (may need a change on ion's side) but the problem is universal for every image added and it's hard to align things.

![Slice 1 (2)](https://github.com/CesiumGS/cesium/assets/8007967/c3613ae6-4264-4055-b218-0db04d069f24)
![Slice 1 (3)](https://github.com/CesiumGS/cesium/assets/8007967/c4523191-5e6d-4de7-9648-96c253c25ab6)

(stretching height is not actually as easy as it sounds given how CSS treats width and height, hard to "stretch to biggest", easier but slightly restricting to "set all to same height")

I would _like_ to come up with a universal solution the "just works" for any logo but I think that may end up being too hard. I think it would be a lot easier to come up with guidelines to either (1) modify logo attribution images to be a set height and/or (2) define how image attributions are rendered and require changes to the logo/html on ion's side to always have them render predictably.

Something like adding vertical alignment to the attribution's html styling can achieve fairly nice results in the existing element's architecture:

![2024-06-24_16-35](https://github.com/CesiumGS/cesium/assets/8007967/75c58fb1-28d2-4f61-9cce-6dd66c8e45f1)
![2024-06-24_16-00](https://github.com/CesiumGS/cesium/assets/8007967/bfd07afe-12a2-40a2-b2de-66f395194e69)


@ggetz @LisaBosCesium I set up some time to quickly chat about this tomorrow.

**Comment by angrycat9000** [comment] 2024-06-25 18:27
The attributions do typically come from the data set in the asset in the ion UI. However Google is hard coded because we wanted it to show as non-collapsible (ie show on screen).  See https://github.com/CesiumGS/cesium-ion/issues/6537 .  That is why there is no attribution set on the Google asset in ion UI.

**Comment by angrycat9000** [comment] 2024-06-25 18:31
@jjspace @LisaBosCesium  was there any discussion of the horizontal spacing?  The Google logo is right next to the ion logo and could benefit from some space in between (this would apply to any attribution).  Looks like the _Data attribution_ link has 5px of space hard coded into it on the left

**Comment by jjspace** [comment] 2024-06-25 20:21
@angrycat9000 yes, horizontal spacing was also addressed in #12047

**Closed** 2024-06-27 21:21 UTC
Labels: type - enhancement, priority - next release, category - widgets
