### ISSUE TITLE
Clipping planes weird behavior on certain Android devices

### ISSUE THREAD

**Issue by dennisadams** [CesiumGS/cesium#9023] opened 2020-07-08 15:21 UTC
![Peek 2020-07-06 22-41](https://user-images.githubusercontent.com/29460712/86922694-aee6a500-c135-11ea-9564-7069c7f52dc7.gif)

I tried the clipping planes sandcastle on an Android device and got this bug where at the top part of the model, the clipping plane is clipping in the wrong direction. 
There already is an open issue - #8061 about clipping planes not working on certain Android devices, but in my case it does technically work and seems like a different issue. 

This device doesn't support float textures, and so it uses [getClippingPlaneUint8](https://github.com/CesiumGS/cesium/blob/952ad67d8899b8a8da161efb02ca0a88d20c616b/Source/Scene/getClippingFunction.js#L137). 
The glsl code from `getClippingPlaneUint8` calls `czm_unpackFloat` in which the problem occurs, right here: https://github.com/CesiumGS/cesium/blob/952ad67d8899b8a8da161efb02ca0a88d20c616b/Source/Shaders/Builtin/Functions/unpackFloat.glsl#L21
If I add a small epsilon value inside `floor`, e.g. `float exponent = floor(temp + 0.01);` everything works well. 
From my understanding, before the "flooring" `temp` should either be an integer or an integer + 0.5.  
My current guess is that because of precision issues on my device, `temp`'s value turns out to be slightly less than the integer it's supposed to be, and this messes up the exponent and consequently the sign of the float.

The only other place using `czm_unpackFloat` (if float textures are not supported) is `BatchTable.js`. I wonder if this can cause other issues on some devices.

**Comment by lilleyse** [comment] 2020-07-08 15:41
Thanks for the detailed write up @dennisadams

@likangning93 could you confirm that adding a small epsilon is an ok fix here?

**Comment by likangning93** [comment] 2020-07-24 00:37
Sorry for the slow response! The packing/unpacking technique didn't look familiar enough to me despite what `git blame` would suggest, so I took a dive through some of the relevant PRs and looks like it originated here: https://github.com/CesiumGS/cesium/commit/dacc45254559237ed68945c69a3b66a423dadc28#diff-a99111718fc832d03c79b3ec06c028a7R514

There's some reference to "discussions offline" but I wasn't able to find a link to anything explaining how this works.
I'm a little hesitant to change the implementation significantly without additional context around this technique, but @dennisadams's mention of device precision got me thinking about the `highp sampler2D` thing that was recently addressed in https://github.com/CesiumGS/cesium/pull/8805, so first I'm going to try out a branch that uses `highp` to see if that does anything. 

Fortunately I'm able to reproduce this combination (planes moving backwards + no float texture support) on an Acer Chromebook Tab 10, which uses a RK3399/Mali-T860 SoC. I'm also seeing weirdness on my Qualcomm 425/Adreno 308 Moto E4, which claims to support float textures, both when using float textures and when I override to force the `uint8` codepath. I'd love if all this weirdness just turned out to be different default precisions for samplers on different devices/webgl implementations.

@dennisadams out of curiosity, what device are you testing on?

**Comment by likangning93** [comment] 2020-07-24 00:53
I put together a smaller Sandcastle for testing this, it's [here on the current deployment](https://sandcastle.cesium.com/#c=dVRtT9swEP4rVj4FqTjpWmALBQ0VpiHB1gHbPizT5CbXxppjZ7YT6FD/+y6Jw5ICVVT73p67e852xTSpONyDJidEwj2Zg+FlTr81Oj/2kkaeK2kZl6Bjb0QeY0kIz9ka9GahVcVT0FE/+I4LuGbFLeiKJ3A59PSbcEJKLaIuYFlykV6rtBTwVQvMemYMWBPcwYMtNZjgE8OViQumbXZ5GXt7oxpk2y5LZuCKbUAvePK7LmXFhIHGtAaVqHSo0/CnBGNvQKIBk0JErC5r23bvOJaxdEXNBS8KLtcLwSTMlRCQWK4kLQ18EIpZVxzytiplY/L3yCPCo1a2+Y7JtkGskOWkD2eGbL+SqqOqaEIi8qMVyauhfucwdEHWcMfkxA9pOCLN3/6Yhi197e+Ahp3QqX+6FdI1fOepzSKCQY75pi9C6s4KZXhdLvb0LCNdaZWfw1oDGFfd/vjNhIZH0+nh+J3LMJ3S8CCcHIWHTjEJw7aeOk+bJQOWYp//k1wzm1GrblDNpPHHE2yh517snOiPbfyC2yS7QYp9B+j4CPvBSnPAAz9s6k5jmpXSuaHZDtaXklnQsh6Zm5ijxLWDxQybQXRuN4jd3j3ayBwMZWn6NHWHEe2i9aqL+oIz53ik8Wo9duMsNY9I7FEa4HfL8kLAObMsaPxM0HZ3xrXb/cItXYsl3vQOwSRM4C15+6TIueR5mS/4A4hb/hdt43pgT/bhWY92ZOe23TlJLRNWM7zE6UVHUMtU4+ONvJmxGwGnXZ73PC+UtvVb4mNzFrA5nIQJliWCWJoY03JOyCzoh85SXhGenrzwvmGxzBi0rErRNBd7p7MA/Z+F4iNQn4LPFWjBNrVbNj69apWU0lmA4suRVimxZHoH+R8) and [here on my branch's deployment](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/highpClippingPlaneTex/Apps/Sandcastle/index.html#c=dVRtT9swEP4rVj4FqTjpWmALBQ0VpiHB1gHbPizT5CbXxppjZ7YT6FD/+y6Jw5ICVVT73p67e852xTSpONyDJidEwj2Zg+FlTr81Oj/2kkaeK2kZl6Bjb0QeY0kIz9ka9GahVcVT0FE/+I4LuGbFLeiKJ3A59PSbcEJKLaIuYFlykV6rtBTwVQvMemYMWBPcwYMtNZjgE8OViQumbXZ5GXt7oxpk2y5LZuCKbUAvePK7LmXFhIHGtAaVqHSo0/CnBGNvQKIBk0JErC5r23bvOJaxdEXNBS8KLtcLwSTMlRCQWK4kLQ18EIpZVxzytiplY/L3yCPCo1a2+Y7JtkGskOWkD2eGbL+SqqOqaEIi8qMVyauhfucwdEHWcMfkxA9pOCLN3/6Yhi197e+Ahp3QqX+6FdI1fOepzSKCQY75pi9C6s4KZXhdLvb0LCNdaZWfw1oDGFfd/vjNhIZH0+nh+J3LMJ3S8CCcHIWHTjEJw7aeOk+bJQOWYp//k1wzm1GrblDNpPHHE2yh517snOiPbfyC2yS7QYp9B+j4CPvBSnPAAz9s6k5jmpXSuaHZDtaXklnQsh6Zm5ijxLWDxQybQXRuN4jd3j3ayBwMZWn6NHWHEe2i9aqL+oIz53ik8Wo9duMsNY9I7FEa4HfL8kLAObMsaPxM0HZ3xrXb/cItXYsl3vQOwSRM4C15+6TIueR5mS/4A4hb/hdt43pgT/bhWY92ZOe23TlJLRNWM7zE6UVHUMtU4+ONvJmxGwGnXZ73PC+UtvVb4mNzFrA5nIQJliWCWJoY03JOyCzoh85SXhGenrzwvmGxzBi0rErRNBd7p7MA/Z+F4iNQn4LPFWjBNrVbNj69apWU0lmA4suRVimxZHoH+R8):

On the `Acer Chromebook Tab 10 RK3399/Mali-T860` I'm seeing a significant improvement.

|1.71|branch|
|---|---|
|![Screenshot 2020-07-23 at 8 48 06 PM](https://user-images.githubusercontent.com/5395255/88351988-35020e80-cd26-11ea-82cb-25e108bf488e.png)|![Screenshot 2020-07-23 at 8 47 29 PM](https://user-images.githubusercontent.com/5395255/88351992-392e2c00-cd26-11ea-8c11-cbef288ee596.png)|

Sadly no dice on the `Qualcomm 425/Adreno 308 Moto E4`, although that was different weirdness with the model not showing at all unless I viewed it from below. That must be something else entirely, I'm gonna say it's separate from this issue.

@dennisadams can you confirm?

**Comment by dennisadams** [comment] 2020-07-24 13:07
> @dennisadams out of curiosity, what device are you testing on?

`Galaxy A20` with `ARM Mali-G71`.

In my case the two screenshots look pretty much the same:
1.71 | branch
-- | --
<img src="https://user-images.githubusercontent.com/29460712/88391854-a643cf00-cdc3-11ea-9946-150c684f9ad0.png" width="250">  |  <img src="https://user-images.githubusercontent.com/29460712/88391858-a774fc00-cdc3-11ea-9866-99ef1c81d5ae.png" width="250">


But that's because they are both good. Probably my problems were with the clipping plane in a different position. 
After applying your changes, I'm glad to confirm this solves the issues on my device. 
FWIW adding the `highp` only in `getClippingFunction.js` seems to be good enough, but I don't understand in glsl best practices.
Thanks @likangning93!

**Comment by lilleyse** [comment] 2020-07-24 14:11
Awesome, nice quick fix @likangning93. Could you open a PR?

**Closed** 2020-07-24 16:36 UTC
Labels: category - graphics, type - bug

**Comment by dennisadams** [comment] 2020-07-26 14:35
@likangning93 
I've tried your solution in a few other places and got some nice results:
1. Adding `highp` in https://github.com/CesiumGS/cesium/blob/67a36c7cf55e2219c9053ed278b1bbb0c4d1feb3/Source/Shaders/Builtin/Functions/shadowDepthCompare.glsl#L7
fixes #7176.
- In the [shadows sandcastle](https://sandcastle.cesium.com/?src=Shadows.html), if you check the `soft shadow` option and decrease the shadow map size from 2048 to 256 you still get some artifacts. But I get them also on my linux so I suspect that's another issue.
- There are more places needing a `highp`, such as the equivalent cubemap version `czm_samplesShadowMap`.
2. Adding `highp` in https://github.com/CesiumGS/cesium/blob/67a36c7cf55e2219c9053ed278b1bbb0c4d1feb3/Source/Shaders/PostProcessStages/PassThroughDepth.glsl#L1
fixes #6735, or at least some of the issues mentioned over there. `PassThroughDepth` is used for the globe depth texture.
3. Adding `highp` in https://github.com/CesiumGS/cesium/blob/67a36c7cf55e2219c9053ed278b1bbb0c4d1feb3/Source/Scene/PickDepth.js#L119
has some precision benefits. I haven't noticed any related open issue, but can elaborate if needed.
- Consider adding `highp` also in `executeDebugPickDepth`.
4. Other issues probably fixed by the above, although I haven't checked: #7273, #4752. 

This isn't the best place for this discussion, but I didn't want to split it across all issues.

A couple of general questions:
1. Will all these `highp`s hurt performance?
2. Do we need to check if `highp` is supported?


> I'd love if all this weirdness just turned out to be different default precisions for samplers on different devices/webgl implementations. 

It may be your lucky day.

**Comment by lilleyse** [comment] 2020-07-27 13:48
> 1. Will all these `highp`s hurt performance?

We should profile to see, but performance is a lesser concern if `highp` ends up fixing these artifacts.

> Do we need to check if `highp` is supported?

Yes, and that's something we're not checking everywhere. See https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#Be_precise_with_GLSL_variable_precision_annotations

**Comment by lilleyse** [comment] 2020-07-27 13:50
@dennisadams could you open a PR and copy your notes over there? I don't have a good device to test with but @likangning93 does.

Thanks for looking into this. I hope we can knock out as many mobile rendering bugs as possible.
