### ISSUE TITLE
Expose feature IDs in custom shaders

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9820] opened 2021-09-20 20:32 UTC
Feature IDs from implicit or explicit feature ID vertex attributes or from feature ID textures should be available in the custom shader.

**Comment by ptrgags** [comment] 2021-11-29 19:50
Closing as duplicate of https://github.com/CesiumGS/cesium/issues/9894

**Closed by ptrgags** 2021-11-29 19:50 UTC
