### ISSUE TITLE
Why can't I create a polyline with points (180,90), (180,-90) ?

### ISSUE THREAD

**Issue by shubhamMtree** [CesiumGS/cesium#9165] opened 2020-09-21 16:33 UTC
I am trying to create poly-line with points (180,90) and (180,-90) but Cesium is giving me the following error:

DeveloperError: Expected value to be greater than or equal to0.0125, actual value was 0.

What does this error actually mean and why is it coming up?

Also, points (90,0) ans (-90,0) are antipodals as well but no such error comes up for these.

**Comment by OmarShehata** [comment] 2020-09-24 14:00
Duplicate of https://github.com/CesiumGS/cesium/issues/9155. See discussion here: https://community.cesium.com/t/error-while-creating-a-polyline-in-cesium/10976/9

**Closed by OmarShehata** 2020-09-24 14:00 UTC
