### ISSUE TITLE
Missing buttons in animation widget in iOS 13.5.1

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8984] opened 2020-06-22 21:58 UTC
Reported on the forum: https://community.cesium.com/t/issues-with-new-ios-13-5-1/9972/3

The animation widget in the latest iOS, 13.5.1, seems to be missing the green buttons, although I can click on play/stop, or even the wheel itself to change the clock multiplier:

![image](https://user-images.githubusercontent.com/1711126/85339275-d3921a00-b4b1-11ea-869c-528a95005cb9.png)

I can reproduce with our office iPad Pro. No console errors, not sure what's causing this.

**Comment by mramato** [comment] 2020-06-22 23:30
Most likely related to these being SVGs, it could be a bug in Safari or it could be something wrong we have been getting away with for a long time.  There was a PR that changed code here a few releases ago, I wonder if versions like 1.65 have this problem.

I definitely think this is something that should be fixed before the next release, since it is a regression affecting millions of devices.

**Comment by sanjeetsuhag** [comment] 2020-06-30 21:47
Fixed in #8993

**Closed by sanjeetsuhag** 2020-06-30 21:47 UTC
Labels: priority - next release, type - bug
